openshift/cluster-network-operator

bindata/network/ovn-kubernetes/pre-puller.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/util/k8s/unstructured.go
Manual Cherry-pick of https://github.com/openshift/cluster-network-operator/pull/1141 
Fixed conflicts due to https://github.com/openshift/cluster-network-operator/pull/1145
cc @vrutkovs
=> Bug 1987046: Add pre-puller ds to reduce upgrade downtime

pkg/controller/statusmanager/pod_status.go, pkg/controller/statusmanager/status_manager.go
We specially handle the statuses of "non-critical" components (ie,
things that are not expected to become available until late in the
initial install), but we were ending that special handling as soon as
we reached "Available" for the first time... which intentionally
happens *before* the "non-critical" components finish deploying,
meaning that if the masters fully deploy but the workers don't, we
will erroneously report a status that makes it look like there is a
problem with the network components, rather than a problem with the
cluster.
=> Bug 1998508: Fix the install-time "waiting for other operators" statuses

pkg/network/bootstrap.go, pkg/network/render_test.go
Make sure `Bootstrap()` returns an empty struct instead of a nil, and the unit test matches reality. Breakage was introduced in 403c4ff06400be0879c81d310da4600b497159fb.
=> Bug 1997050: Fix panic with unknown networks

bindata/network-diagnostics/000-ns.yaml, bindata/network-diagnostics/001-rbac.yaml, bindata/network-diagnostics/network-check-source.yaml
CNO deploys a service monitor named "network-check-source" which is never picked up by prometheus.
This PR adds the `openshift.io/cluster-monitoring="true"` label to the `openshift-network-diagnostics` namespace and fixes some RBAC so the service is picked up for monitoring.
**How to verify:**
1. Spin up a cluster with this patch
2. Login to the cluster dashboard, go to Observe -> Metrics and query for one of the metrics of the `checkendpoints` pod, e.g. `pod_network_connectivity_check_count`
https://github.com/openshift/cluster-network-operator/blob/425a698d0459339878e34b2d580633c4eeba3ead/pkg/cmd/checkendpoints/controller/metrics.go#L22-L35
=> Bug 1986061: Monitor openshift-network-diagnostics namespace

Dockerfile, pkg/controller/proxyconfig/validation.go, pkg/util/validation/network.go, pkg/util/validation/network_test.go
ProxyConfig validation: check for valid IP addresses added.
Before:
```bash
$ oc -n openshift-network-operator logs network-operator-58d595444f-6rf4d | grep invalid
I0826 18:57:02.366450       1 log.go:184] Failed to validate proxy 'cluster': invalid noProxy: fd2e:6f44:5dd8::1
I0826 18:57:02.419354       1 log.go:184] Failed to validate proxy 'cluster': invalid noProxy: fd2e:6f44:5dd8::1
```
After, note `fd2e:6f44:5dd8::1` address:
```bash
$ oc version
Client Version: 4.8.4
Server Version: 4.8.4
Kubernetes Version: v1.21.1+38b3ecc
$ oc get proxy.config cluster --template '{{.status.noProxy}}' | tr ',' '\n' && echo
.cluster.local
.ocp-edge-cluster-0.qe.lab.redhat.com
.svc
10.0.0.0/16
10.128.0.0/14
127.0.0.1
169.254.169.254
172.30.0.0/16 …
```
=> Bug 1939435: proxyconfig - accept IPv6 address literals for noProxy

bindata/network/multus/002-rbac.yaml, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
Newer feature in Whereabouts uses leases for coordination of leaders as to not cause a race condition in ip allocations.
merged to master in #1174
=> Bug 1990928: [Backport 4.8] Whereabouts should have RBAC for leases

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
Currently OVN databases and ovn-northd are started with '-vconsole:${OVN_LOG_LEVEL} -vfile:off'.  This means that logs are going only to the console.  But console (unlike files) has no millisecond resolution by default.  This makes it hard to debug time-sensitive issues.
This PR adds the millisecond resolution to console logs of ovn components.
**How to verify:**
1. Start a cluster with this patch (e.g. via clusterbot: `launch openshift/cluster-network-operator#1196 ovn`)
2. Check the logs of ovn components, e.g. nbdb:
```
oc -n openshift-ovn-kubernetes logs ovnkube-master-n6gnc -c nbdb
...
+ exec /usr/share/ovn/scripts/ovn-ctl --db-nb-cluster-local-port=9643 --db-nb-cluster-local-addr=10.0.148.9 --no-monitor --db-nb-cluster-local-proto=ssl --ovn-nb-db-ssl-key=/ovn-cert/tls.key …
```
=> Bug 2002713: Add millisecond resolution to OVN logs

bindata/network/kuryr/003-config.yaml, bindata/network/kuryr/006-controller.yaml, go.mod, pkg/bootstrap/types.go, pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go, vendor/golang.org/x/net/http/httpproxy/proxy.go, vendor/modules.txt
When using Proxy and the installer is configured
on a restricted installation, Kuryr bootstrap
can't progress as the http client is not
configured to use Proxy. This commit ensures
proxy is used by relying on the cluster proxy
resource instead of relying on cvo to injecting
the proxy env vars.
=> Bug 1985486: Use proxy to connect to OSP cloud

bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
Add logic to OVN-Kubernetes to determine what platform we are running on 
drop icmp frag needed received from other nodes in the cluster
=> Bug 1988483: OVN drop icmp frag from other nodes on Azure cluster 

bindata/network/ovn-kubernetes/004-config.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
This PR is a backport to release-4.8 from release-4.9 for Bug 2008589  (a clone of Bug 1984049)
It combines 2 PRs: 
- https://github.com/openshift/cluster-network-operator/pull/1154 - Bug 1981055
- https://github.com/openshift/cluster-network-operator/pull/1159  - Bug 1984049. Depends on PR 1154
Bug 1981055 To handle kube-apiserver disruptions, the recommended defaults are LeaseDuration=137s, RenewDealine=107s, RetryPeriod=26s according to
https://github.com/openshift/enhancements/blame/84e894ead7b188a1013556e0ba6973b8463995f1/CONVENTIONS.md#L183
Signed-off-by: Christoph Stäbler <cstabler@redhat.com>
(cherry picked from commit 4126e3c3c254f8c899eb72b6d56864292abbedc7)
Conflicts:
pkg/network/ovn_kubernetes_test.go
---
Bug 1984049: Slow OVN Recovery on SNO
Keep default initialDelaySeconds …
=> Bug 2008589: [4.8z] Slow OVN Recovery on SNO

bindata/network/multus/002-rbac.yaml, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
Newer feature in Whereabouts uses leases for coordination of leaders as to not cause a race condition in ip allocations.
merged to master in #1174
=>  Bug 1990932: [Backport 4.7] Whereabouts should have RBAC for leases

bindata/kube-proxy/000-ns.yaml, bindata/network/kuryr/000-ns.yaml, bindata/network/multus/000-ns.yaml, bindata/network/openshift-sdn/000-ns.yaml, bindata/network/ovn-kubernetes/000-ns.yaml, manifests/0000_70_cluster-network-operator_00_namespace.yaml
Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-multus`/`openshift-network-operator`/`openshift-sdn` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz
=> podsecurity: enforce privileged for network namespaces

bindata/network/ovn-kubernetes/ovnkube-master.yaml, manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
The current logic checks the change of election timer in the postStart
hook, checking if the current node is the leader and in case applying
the desired change. When rolling out an upgrade, each ovnkube-master pod
is updated one at the time, with the result that when postStart
executes, the current node is never the leader. Here, we move the logic
to ovndbchecker (changed in https://github.com/ovn-org/ovn-kubernetes/pull/2356) to
reconcile the election timer asynchronously.
=> Bug 1976399: Raft election timer: move the logic to ovndbchecker

bindata/network/multus/003-dhcp-daemon.yaml
Set to 33% as it's not as critical as say, Multus (which uses 10%)
=> Bug 1962206: DHCP daemon should have maxunavailable for upgrade strategy

bindata/network/multus/003-dhcp-daemon.yaml
Sets a modest memory and CPU limit for DHCP daemon
=> Bug 1961509: DHCP Daemon should have memory and CPU limits set

bindata/network/openshift-sdn/alert-rules.yaml
Previous to this change, we are overloading the meaning of "SDN pod" to include SDN controller. This PR removes SDN controller and adds a separate alert for SDN controller.
~~Looking for a better metric than ```cluster:master_nodes``` to get the total number of control plane nodes. It comes from container ```kube-rbac-proxy-main```..~~
edit: Got advice from monitoring team to use kube_node_role metric.
=> Specific SDN controller alert

bindata/network/openshift-sdn/sdn.yaml
For some as yet undebugged reason, the theory is this mount setup seems to
not work with the CentOS 9 Stream kernel at least.
https://bugzilla.redhat.com/show_bug.cgi?id=1988520
Here we're avoiding "overmounting" on `/host` inside the container;
instead create `/host-cni-bin` which contains the in-container
view of the host's `/opt/cni/bin` (which is `/var/opt/cni/bin` on ostree
systems).
=> openshift-sdn/daemonset: Mount /host/opt/cni/bin at /host-cni-bin

bindata/kube-proxy/kube-proxy.yaml
All daemonsets in OCP must have a max unavailable value set to 10% or
33%. Fixed kube-proxy daemonset to be in accordance with this rule
Signed-off-by: Ben Pickard <bpickard@redhat.com>
=> Set upgrade strategy on kube-proxy

bindata/network/openshift-sdn/sdn.yaml
Change iptables chain names to not conflict with existing workaround(s)
(cherry picked from commit 32d72e5794ecd5e5f742c8708a2e4a6c183b0e4b)
=> Bug 1988427: Change to use mountPath: /host

bindata/network/multus/multus.yaml
When failures occur, a number of failed cronjobs pile up. Since another one will start in 5 minutes, we should just wait until the next instance in order to start another pod.
=> The ip-reconciler should not restart on failures.

bindata/network/openshift-sdn/cni-features.yaml, bindata/network/ovn-kubernetes/cni-features.yaml, bindata/network/public/000-roles.yaml, pkg/network/render.go, pkg/network/render_test.go
Related enhancement: [Expose Network features](https://github.com/openshift/enhancements/blob/master/enhancements/console/expose-network-features.md)
The console requires to know the network type capabilities to show/hide some Network Policy form fields.
As agreed in the linked enhancement document, the required network capabilities will be added to an `sdn-public` `ConfigMap`, created by the CNO, readable by any `system:authenticated` user.
This PR is also the placeholder to add future network capabilities, as long as our Console components require more knowledge about the underlying CNI.
We provide the known values to `OVNKubernetes` and `OpenShiftSDN` CNI types. If the CNI type is `Kuryr` or any other, we will take default actions (e.g. show the related form field with a warning …
=> NETOBSERV-31: Expose CNI type features as a config-map

bindata/kube-proxy/kube-proxy.yaml, bindata/network/ovn-kubernetes/error-cni.yaml, bindata/network/ovn-kubernetes/ipsec.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, hack/dpu-mode.yaml, pkg/bootstrap/types.go, pkg/network/kube_proxy.go, pkg/network/kube_proxy_test.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/network/render.go
In the Infra-Cluster (Cluster with DPUs), OVN-Kubernetes on DPU is managing the networking for the Tenant-Cluster (Cluster with x86-hosts). Currently, only host network based pods are supported on the DPU. This PR adds an Infra-DPU-CNI to the DPU, which is just a script that return an error to any CNI cmdAdd() calls. Multus requires a "readiness-indicator-file", which is a conf file with the CNI Plugin specifics. The presence of this file indicates to Multus that the CNI is ready. This PR also setups the "readiness-indicator-file".
Since OVN-Kubernetes running on the DPU is serving the Tenant-Cluster (x86 host), enable KubeProxy to run on the DPU to  enable networking on the DPUs in the Infra-Cluster.
=> Add CNI to DPU and enable Kube-Proxy on DPU

bindata/network/ovn-kubernetes/monitor.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
By enabling, we get:
* OVN DB cluster status,roles,connections metrics
* OpenFlow rules count, patch ports and geneve ports total on br-int
* Stopwatch and coverage metrics
.. and more.
Inspect OVN-Kubernetes RegisterOvnMetrics function to get a full set
of metrics enabled.
/cc
=> OVN-K: Enable OVN metrics to be consumed by ServiceMonitor

bindata/network-diagnostics/network-check-target.yaml, bindata/network/network-metrics/001-daemonset.yaml
On DPU Deployments:
* Tenant Cluster (Cluster with x86 hosts that contain Ethernet Controller
Cards with DPUs)  pods must either be host network backed or must request
a VF from the SR-IOV Device Plugin.
* Infra Cluster (ARM Cluster that contain the DPUs) pods must be host
network backed.
When OpenShift is deployed, some pods are deployed on all worker nodes.
Some of these pods are non-host network backed, so they need to handled
to meet the above criteria.
The following DaemonSets are marked as tolerating all taints, but are pod-networked:
* openshift-multus/network-metrics-daemon
* openshift-network-diagnostics/network-check-target
These DaemonSets are managed by CNO. This PR is setting affinity on
these DaemonSets so they won't be deployed on DPU or DPU-Host nodes.
Signed-off-by: Billy …
=> Pod networking on DPU host in Infra and Tenant clusters

bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
Fix incorrect metric name reference. 
As you can see upstream [1], we register with the default register, and this means the metric starts with "ovnkube_master".
[1] https://github.com/ovn-org/ovn-kubernetes/blob/b1b54eddff1490d6c93a5aceba6bd2029b6b31cf/go-controller/pkg/metrics/master.go#L201
=> OVN-K alerts: Fix incorrect metric name reference

bindata/network/ovn-kubernetes/ovnkube-master.yaml
This PR remove pidfile on postStart hook to avoid run_n/sb_ovsdb from an early return.
=> Bug 2022144: sbdb and nbdb containers leave pid around if they restarted or crashed

pkg/network/ovn_kubernetes.go
bootstrapOVN is repeatedly called in CNO's render loop.
However we should be calling bootstrapOVNGatewayConfig
only once right at the starup scenario of CNO where
the gatewayConfig is nil. Once that field is set, we
should not have to worry about checking the config map
and setting the default value.
Currently this makes CNO always change the gatewaymode
to shared because bootstrap is seemed to be called every
time in the loop. Let's add the check where this
function is called only if gatewayConfig==nil
=> Bug 2033422: bootstrapOVNGatewayConfig should only be called once

pkg/bootstrap/types.go, pkg/network/kuryr.go, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go, pkg/network/ovn_kubernetes.go, pkg/network/render.go, pkg/platform/openstack/kuryr_bootstrap.go, pkg/platform/platform.go, pkg/platform/platform_test.go
This supersedes #1260. 
This PR implements the following changes:
- Renames and refactors `bootstrapCloud` to `bootstrapInfrastructure` and moves that to the `platform` package 
- Moves `BootstrapResult.ExternalControlPlane` to `InfraBootstrapResult`
subsequently fixing the initialization issues for hypershift, when bootstrapping with openshift-sdn. 
/assign @abhat @trozet
=> Bug 2034322: Move infrastructure bootstrap to its own package

bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/bootstrap/types.go, pkg/controller/operconfig/operconfig_controller.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
As described in the [Related RFE](https://github.com/openshift/enhancements/blob/master/enhancements/network/ovs-flow-export-configuration.md), the CNO needs to listen for any change in the `ovs-flows-config` ConfigMap that is created after a `FlowCollector` object, so the CNO can properly configure and tune the OVN-Kubernetes' OpenVSwitch instance to export IPFIX flows.
This PR adds the following functionalities:
1. Adds a watcher for the `ovs-flows-config` configmap and retriggers the `operconfig_controller` reconciliation process on any change in that map.
2. On reconciliation, bootstraps the `ovs-flows-config` configmap information and renders it into the `ovnkube-node.yaml` to properly reconfigure`ovn-kubernetes`.
3. Defines the RBAC assets according to the [CNO<->NOO RBAC …
=> Bug 2034517: watch and apply changes of the ovs-flows-config configmap

bindata/network/additional-networks/crd/001-crd.yaml
This field is required for use in the IP reconciliation process for Whereabouts which uses the pod reference (podref) to calculate stranded IP addresses.
=> Bug 2034398: Whereabouts CRD should include a "podref" field.

bindata/cloud-network-config-controller/controller.yaml, pkg/network/render.go
Two changes are needed:
* Hypershift doesn't have master nodes, so the node selector must be absent
* Hypershift uses STS to auth with AWS, so a SA token with an `openshift` audience needs to be mounted. This also requires https://github.com/openshift/cloud-network-config-controller/pull/13 to work
/assign @alexanderConstantinescu
=> Bug 2035093: Cloud network config controller: Fix for Hypershift

bindata/network/openshift-sdn/004-multitenant.yaml, pkg/network/openshift_sdn_test.go
Since cluster-kube-apiserver-operator merged commit with number
77a0351146dbe38cba216b4a2036638524b27d41, that operator accesses all
service's webhook endpoints to verify if those are up. Therefore, open
all projects to/from namespace openshift-kube-apiserver-operator.
=> Bug 2036861: multitenant - Add openshift-kube-apiserver-operator to global namespaces

bindata/network/ovn-kubernetes/ovnkube-master.yaml
OpenShift and kube don't yet gracefully terminate pods in all cases,
especially when taking a node down for reboot. Attempt to handle that
better by asking northd to stop gracefully in the preStop hook and
the container script.
Co-Authored-By: Dan Williams <dcbw@redhat.com>
=> Bug 1943363: ovn: try to gracefully terminate ovn-northd

pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go, pkg/network/ovn_kubernetes.go
Previously the checks in `isOpenShiftSDNChangeSafe` were not run if there was no changes to `DefaultNetwork.OpenShiftSDNConfig`, which resulted in MTU migration not being verified.
With this commit `Migration` is also checked to make sure that the MTU migration changes are verified.
/cc @jcaamano @ricky-rav 
=> Bug 2034153: Fix MTU migration verification for OpenShiftSDN

bindata/cloud-network-config-controller/003-configmaps.yaml, bindata/cloud-network-config-controller/controller.yaml, pkg/apply/apply.go, pkg/bootstrap/types.go, pkg/names/names.go, pkg/network/cloud_network.go, pkg/network/render.go, pkg/platform/platform.go
It was noticed that there are cases that require special configuration
to authenticate to the AWS and Azure API endpoints:
- Azure has the notion of "Environments", which are named sets of API
URLs. Anyone connecting to Azure needs to be aware of them.
- Customers can override AWS and Azure endpoints via the Infrastructure object
- There is a magic ConfigMap that may contain a CA bundle only to be
used when connecting to AWS. This is needed for the AWS C2S platform
- We needed to include the proxy CA bundle.
So, add a lot of bootstrapping code to get all these configuration knobs.
Also, add a small commit that allows for create-only objects.
=> Bug 2034460: cncc: handle advanced AWS and Azure configurations 

bindata/network/ovn-kubernetes/ovnkube-node.yaml
Add ip6tables NOTRACK rules for udp/6081
Signed-off-by: Michael Cambria <mcambria@redhat.com> 
(cherry picked from commit 7d4d093844b0e614826c9d09ae34efb68ad9270c)
=> Bug 2023423: Add ip6tables NOTRACK rules for udp/6081

bindata/cloud-network-config-controller/002-rbac.yaml, bindata/cloud-network-config-controller/controller.yaml, manifests/01-cncc-namespace.yaml, manifests/02-cncc-credentials.yaml, pkg/controller/operconfig/operconfig_controller.go
It turns out, that thanks to https://github.com/openshift/enhancements/blob/master/enhancements/installer/credentials-management-outside-openshift-cluster.md, we need to be embedding all CredentialsRequests in `manifests` instead of dynamically in the CNO itself. So, do that. It's a bit awkward but doesn't actually break anything.
Also,
- tighten up RBAC for the CNCC. We accidentally added access to all Secrets, oops.
- don't blanket tolerate NotReady -- we're not critical to startup, and this keeps us from getting Pod creation errors
=> BUG 2034413: cncc: create Cloud CredentialsRequest in /manifests

go.mod, go.sum, vendor/github.com/gogo/protobuf/proto/text_parser.go, vendor/golang.org/x/sync/singleflight/singleflight.go, vendor/golang.org/x/tools/go/ast/astutil/util.go, vendor/golang.org/x/tools/imports/forward.go, vendor/golang.org/x/tools/internal/event/core/event.go, vendor/golang.org/x/tools/internal/gocommand/invoke.go, vendor/golang.org/x/tools/internal/gocommand/version.go, vendor/golang.org/x/tools/internal/imports/mod.go, vendor/golang.org/x/tools/internal/imports/mod_cache.go, vendor/modules.txt
This commit udpates the protobuf version used in CNO to 1.3.2
to address the CVE-2021-3121
=> Bug 1924839: [release-4.7] Update protobuf version to address CVE-2021-3121

bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/alert-rules.yaml
See "style guide" in alerting-consistency.md at repository
openshift/enhancements/monitoring.
/cc @npinaeva 
Waiting on clarification if I need to prefix metric name with component name.
=> Bug 2010663: OVN-K alerts: conform to monitoring team style guide

bindata/network/kuryr/003-config.yaml, bindata/network/kuryr/006-controller.yaml, go.mod, pkg/bootstrap/types.go, pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go, vendor/golang.org/x/net/http/httpproxy/proxy.go, vendor/modules.txt
When using Proxy and the installer is configured
on a restricted installation, Kuryr bootstrap
can't progress as the http client is not
configured to use Proxy. This commit ensures
proxy is used by relying on the cluster proxy
resource instead of relying on cvo to injecting
the proxy env vars.
=> Bug 2022747: Allow to use proxy to connect to OSP cloud

manifests/02-cncc-credentials.yaml
This is needed for more advanced cloud provider authentication scenarios
(e.g AWS STS).
=> Bug 2041329: cncc: add serviceAccountNames to CredentialsRequests

bindata/network/ovn-kubernetes/003-rbac-controller.yaml
With PR https://github.com/ovn-org/ovn-kubernetes/pull/2734 we will need to patch the `EgressIP` objects. This gives our ovnkube-master service account, that capability
/assign @trozet
=> Bug 2038732: Add egress* patch credentials for ovnkube-master

pkg/controller/operconfig/operconfig_controller.go
When nonexistent namespaces cause errors, provided users with additional logging to clarify possible next steps:
"Consider possible solutions:
(1) Edit config files to include existing namespace
(2) Create non-existent namespace
(3) Delete erroneous network-attachment-definition"
Based on [Bugzilla Bug #1896533](https://bugzilla.redhat.com/show_bug.cgi?id=1896533)
=> Bug 1896533: Nonexistent Namespaces Degradation logging message

bindata/network/openshift-sdn/cni-features.yaml
According to the recent comment of Dan Winship in a recently merged
PR: https://github.com/openshift/cluster-network-operator/pull/1204#issuecomment-990201372
> openshift-sdn also implements both egress rules and ipBlock exceptions.
This PR updates the reported capabilities for OpenshiftSDN so the Console
will accordingly show the proper sections in the Network Policy forms.
=> Bug 2035459: modify cluster-network-features for OpenshiftSDN

manifests/0000_70_cluster-network-operator_01_credentialsrequest.yaml, manifests/02-cncc-credentials.yaml
The ibm-cloud-managed profile doesn't use the cloud-credential-operator.
The CredentialsRequest CRs should not be installed in that environment.
Unmark the existing CredentialsRequests so they are no longer installed
in ibm-cloud-managed.
Create a list of previously-installed CredentialsRequests so that they
are cleaned up by the CVO only on the ibm-cloud-managed profile.
xref: https://issues.redhat.com/browse/CCO-177
=> Bug 2041989: no CredentialsRequests in ibm-cloud-managed

bindata/network/openshift-sdn/003-rbac-controller.yaml, bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/monitor.yaml
/cc
Depends on: https://github.com/openshift/sdn/pull/388
=> Bug 2039321: SDN: Expose controller metrics for collection

pkg/network/mtu.go, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Additionally added verification of migration MTU values.
/cc @ricky-rav @jcaamano 
=> Bug 2039345: Verify against mininimal IPv6 MTU value for clusters with IPv6 networks

bindata/network/multus/multus.yaml
The `backoffLimit` attribute - [0] - "specifies the number of retries
before marking this job failed. Defaults to 6."
The aforementioned attribute belongs to `jobTemplate.spec`, not to the
pod's spec template.
[0] - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/#lifecycle
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
=> Bug 2042796: whereabouts, reconciler: disable retries on failure

bindata/network/ovn-kubernetes/ovnkube-master.yaml
If supported by OVN, which was added in 21.12 and later.
=> Bug 2041546: ovn-kubernetes: set RAFT election timer at RAFT cluster creation time

bindata/network/multus/multus.yaml
The bond cni source directory path is incorrect. It is missing a trailing
directory separator. Without the separator the cnicopy.sh command will not
copy the contents of the directory.
BZ: [https://bugzilla.redhat.com/show_bug.cgi?id=2048413](https://bugzilla.redhat.com/2048413)
Verified using cluster bot (launch `openshift/cluster-network-operator#1205`)
=> Fix bond cni source directory path

bindata/network/openshift-sdn/sdn.yaml
SDN pods get restarted once `sdn-config` configmap changes, this caused transient issues with pods being deployed with wrong MTU during MTU migration.
Use a separate, optional config map that is used for mtu migration.
=> Bug 2049613: Use a separate configmap for mtu migration config to avoid pod restart

bindata/network/kuryr/003-config.yaml
A timeout during which kuryr-cni is waiting for the kuryr-controller to
create and populate KuryrPort for a Pod was set to 500 seconds, so
little over 8 minutes. The problem with that is that kubelet's timeout
to create PodSandbox is set to 4 minutes, after which kubelet will raise
mysterious "context deadline exceeded" error, effectively hiding the
real error from Kuryr.
This commit decreases the timeout in Kuryr to 200 seconds, so that we
will time out before kubelet and be able to raise real error.
=> Bug 2048793: Kuryr: Decrease vif_annotation_timeout

bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
Add logic to OVN-Kubernetes to determine what platform we are running on.
drop icmp frag needed received from other nodes in the cluster
(cherry picked from commit 7a05ada8774081d8a7f8be2b45d517bd02b54acb)
=> Bug  2038252: Backport 4.9  OVN drop icmp frag from other nodes on Azure cluster

bindata/network/additional-networks/crd/001-crd.yaml, bindata/network/multus/002-rbac.yaml, bindata/network/multus/multus.yaml, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
This implements the Whereabouts IP reconciliation cron job
NOTE: This pull request should be merged AFTER https://github.com/openshift/whereabouts-cni/pull/80
=> Bug 2034358: Whereabouts IP Reconciliaton [backport 4.6]

bindata/network/multus/multus.yaml
It should also use the internal load balancer.
This gives it connectivity during cluster lifecycle events where the SDN is in a transitioning state.
=> Bug 2048575: The Whereabouts ip-reconciler should use api-int load balancer

bindata/network/multus/multus.yaml
This gives it connectivity during cluster lifecycle events where the SDN is in a transitioning state.
backport of #1302
=> Bug 2051639: The Whereabouts ip-reconciler should use the internal load balancer and host network [backport 4.10]

bindata/network/ovn-kubernetes/004-config.yaml, pkg/network/ovn_kubernetes_test.go
By default the lflow cache is unlimited, but at scale this
makes ovn-controller consume large amounts of RSS and cause OOM
situations. Limit the cache size to prevent unbounded memory
usage while still providing enough for most setups.
The lflow cache is a tradeoff between CPU and memory, but we'd
rather use a bit more CPU than OOM a box.
Pick a 1GB limit based on data gathered from various scale runs,
which seems to be the upper-limit (for now) for 120-node
density runs.
(cherry picked from commit 4d1056a590678ddacd1a884242a0f606bbac93c2)
=> [release-4.8] Bug 2021221: ovnkube: set ovn-controller lflow cache limit to 1GB

pkg/controller/clusterconfig/clusterconfig_controller.go, pkg/controller/operconfig/cluster.go, pkg/controller/operconfig/operconfig_controller.go, pkg/network/cluster_config.go, pkg/network/cluster_config_test.go, pkg/network/previous_test.go, pkg/network/render.go, pkg/network/render_test.go
Only allow DualStack migration for BareMetal and None type clusters.
Additionally, update error messages for DualStack migrations.
Now that we are not hiding the existence of DualStack any more, give
clearer error messages for unsupported configurations.
=> Bug 2032559: Block DualStack migration for unsupported cluster types

bindata/network/ovn-kubernetes/ovnkube-node.yaml
Add ip6tables NOTRACK rules for udp/6081
(cherry picked from commit 7d4d093844b0e614826c9d09ae34efb68ad9270c)
=> [release-4.8] Bug 2023426: Add ip6tables NOTRACK rules for udp/6081

bindata/network/kuryr/005-daemon.yaml
In daemonset for kuryr-cni there was no upgrade strategy defined, which
means that during upgrade maxUnavailable field will have value of 1,
while it is expected of value of 10% or 33%. And since Kuryr daemon is
an entity which do have impact on other workloads in the cluster, the
appropriate value for maxUnavailable would be 10%.
=> Bug 2044227: Add rolling update strategy for Kuryr-CNI.

bindata/network/ovn-kubernetes/ovnkube-master.yaml
OpenShift and kube don't yet gracefully terminate pods in all cases,
especially when taking a node down for reboot. Attempt to handle that
better by asking northd to stop gracefully in the preStop hook and
the container script.
Co-Authored-By: Dan Williams <dcbw@redhat.com>
=> [release-4.9] Bug 2040530: ovn: try to gracefully terminate ovn-northd and ovsdb

bindata/network/ovn-kubernetes/ovnkube-master.yaml
"ovn-appctl exit" just tells the DB to exit, it doesn't wait. But
"ovn-ctl stop" actually waits for the DBs to exit.
We should do the same things in preStop as in the TERM hook since
there are cases in which neither preStop or TERM is executed so
having both increases the chances we'll terminate gracefully.
=> Bug 1944264: ovnkube: gracefully terminate databases from preStop

bindata/network/ovn-kubernetes/ovnkube-master.yaml
All normal operation has been converted over to libovsdb; we no longer
use ovn-nbctl for anything other than one-time checks and properties at
startup.
As such we no longer need the nbctl daemon keeping another whole copy
of the NB database in memory. Let's just use libovsdb.
=> ovn: stop spawning the ovn-nbctl daemon

bindata/network/ovn-kubernetes/ovnkube-master.yaml
This is to avoid the `PodDisruptionBudgetAtLimit` alert defined as:
```json
{
"alert": "PodDisruptionBudgetAtLimit",
"annotations": {
"description": "The pod disruption budget is at minimum disruptions allowed level. The number of current healthy pods is equal to desired healthy pods.",
"summary": "The pod disruption budget is preventing further disruption to pods."
},
"expr": "max by(namespace, poddisruptionbudget) (kube_poddisruptionbudget_status_current_healthy == kube_poddisruptionbudget_status_desired_healthy)\n",
"for": "60m",
"labels": {
"severity": "warning"
}
}
```
=> Bug 2037721: Do not apply OVN-Kubernetes `PodDisruptionBudget` on single-node clusters

bindata/network/multus/multus.yaml
This commit makes use of the `ttlSecondsAfterFinished` knob to auto clean
the failed jobs.
According to the Kubernetes API documentation - [0] - this property:
"""
limits the lifetime of a Job that has finished execution (either Complete or
Failed). If this field is set, ttlSecondsAfterFinished after the Job finishes,
it is eligible to be automatically deleted. When the Job is being deleted, its
lifecycle guarantees (e.g. finalizers) will be honored. If this field is unset,
the Job won't be automatically deleted. If this field is set to zero, the Job
becomes eligible to be deleted immediately after it finishes.
"""
We're leaving the failed job around for 15 minutes - which is the period
of the cron job.
[0] - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/#Jo …
=> Bug 2058671: ip reconciler: auto clean failed jobs

bindata/network/ovn-kubernetes/ovnkube-master.yaml
In order to avoid any potential bringup race conditions between dbchecker container
and sbdb/nbdb we move the memory trimming check and enable to start of each db.
upstream PR#[2830](https://github.com/ovn-org/ovn-kubernetes/pull/2830) will remove
enable memory trimming from dbchecker container
=> Bug 2058368: Move memory-trimming-on-compaction out of dbchecker to nbdb/sbdb

bindata/network/mtu-prober/02-job.yaml
Update of mtu prober job fails because spec.selector is immutable and this doesn't work with the recently introduced server side apply.
```
Could not apply mtu-prober object: failed to apply / update (batch/v1, Kind=Job) openshift-network-operator/mtu-prober: Job.batch "mtu-prober" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string(nil), MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
=> Remove empty selector from the mtu prober job.

cmd/cluster-network-operator/main.go, pkg/client/client.go, pkg/client/fake/fake_client.go, pkg/client/types.go, pkg/operator/operator.go
For usual deployments the in-cluster config is the one for the `default` clusterClient, in hypershift the in-cluster config will be for the `management` clusterClient instead.
This change allows us to define which client is tied to the in-cluster config.
I initially tried to create an additional kubeconfig from the ServiceAccount token but it seems that it is not the best idea since the token can expire: https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md#safe-rollout-of-time-bound-token.
Currently it is not a huge deal since the expiration is set to 1year, but we do get the following audit log in kube-apiserver:
```
{"kind":"Event",...,"annotations":{"authentication.k8s.io/stale-token":"subject: …
```
=> Add an option to define the client name for in-cluster config

bindata/network/multus/multus.yaml
This commit makes use of the `ttlSecondsAfterFinished` knob to auto clean
the failed jobs.
According to the Kubernetes API documentation - [0] - this property:
"""
limits the lifetime of a Job that has finished execution (either Complete or
Failed). If this field is set, ttlSecondsAfterFinished after the Job finishes,
it is eligible to be automatically deleted. When the Job is being deleted, its
lifecycle guarantees (e.g. finalizers) will be honored. If this field is unset,
the Job won't be automatically deleted. If this field is set to zero, the Job
becomes eligible to be deleted immediately after it finishes.
"""
We're leaving the failed job around for 15 minutes - which is the period
of the cron job.
[0] - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/#Jo …
=> Bug 2058672: ip-reconciler cronjob specification requires hostnetwork, api-int lb usage & proper backoff [backport 4.10]

bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
Adding initContainer in ovnkube-node pod to check sbdb avaliability before starting ovn-controller container
verified the changes on local cluster
```
+ [[ -f /env/ ]]
++ date -Iseconds
2022-03-29T12:57:57+00:00 - checking sbdb
+ echo '2022-03-29T12:57:57+00:00 - checking sbdb'
+ ovndb_ctl_ssl_opts='-p /ovn-cert/tls.key -c /ovn-cert/tls.crt -C /ovn-ca/ca-bundle.crt'
+ transport=ssl
+ db_port=9642
+ CLUSTER_INITIATOR_IP=10.0.0.3
+ retries=0
+ ovn-sbctl --no-leader-only --timeout=5 --db=ssl:10.0.0.3:9642 -p /ovn-cert/tls.key -c /ovn-cert/tls.crt -C /ovn-ca/ca-bundle.crt get-connection
read-write role="" pssl:9642
```
=> Add ovnkube-node initContainer to make sure sbdb is up before running other containers

bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
by the time nbdb and sbdb run the readiness prob the db ctl file should already be present
=> Bug 2058368: move enable memory trimming to readiness prob

bindata/network/multus/multus.yaml
The tuning cni currently allows to set any sysctl in the system, instead of just the sysctls for the specific interface on which it is run. In fact, until now it was not even possible to set the interface level sysctl, only global sysctls.
This poses security risks. It also makes the feature of limited pod level sysctls ([here](https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#enabling-unsafe-sysctls)) void, as it can be easily circumvented with an appropriate tuning-cni nad.
For this reason two new features were added to the tuning-cni:
- interface level sysctls - allowing to set a sysctl for the interface on which the cni is chained
- sysctl whitelist - allowing to limit the sysctls that can be set by the tuning-cni.
The sysctl whitelist requires a file …
=> Add tuning cni sysctl allowlist to nodes

manifests/02-cncc-credentials.yaml
Hypershift uses `ibm-cloud-managed` cluster profile.
Without this change CVO does not render credentials requests in 02-cncc-credentials.yaml
/cc @squeed @zshi-redhat 
=> Add ibm-cloud-managed annotations to 02-cncc-credentials.yaml, this is required in HyperShift

pkg/controller/statusmanager/status_manager.go
=> Don't return err with empty relatedClusterObject annotation

bindata/network/kuryr/alert-rules.yaml
With Kuryr the CNI requests can take a considerable
time given that it has to wait for a VIF from Neutron.
We've seen warnings being raised for KuryrCNISlow, so let's
increase it's max acceptable value to 60 which is the value
hit in most of the observations.
=> Bug 2070047: Bump max value of hist quantile for kuryr_cni_request_duration

bindata/network/ovn-kubernetes/managed/monitor-master.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
revert this change once ovnk metrics support tls
via: https://github.com/ovn-org/ovn-kubernetes/pull/2900
=> hypershift: disable TLS for ovnk master metrics

bindata/network/kuryr/002-crds.yaml
This is based on [1] and required by openshift/kuryr-kubernetes#645.
[1] https://opendev.org/openstack/kuryr-kubernetes/commit/d5f5db7005028f9ba88ed9dcc0b5d09d0bbd8bda
=> Bug 1983056: Kuryr: Update CRD from upstream

bindata/network/multus/multus.yaml
Fixes to include in this (and subsequent backports) include:
* auto clean failed jobs (https://github.com/openshift/cluster-network-operator/pull/1318)
* Use host network and api-int (https://github.com/openshift/cluster-network-operator/pull/1302)
* Disable retries on failure (https://github.com/openshift/cluster-network-operator/pull/1290)
=> Bug 2058673: ip-reconciler cronjob specification requires hostnetwork, api-int lb usage & proper backoff [backport 4.9]

bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
This was some legacy code that was used to pass the db address when
starting ovnkube binary. It's no longer needed.
=> OVN: remove detecing db_ip via kapi

manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
Cluster network operator is a host networked pod. Reserve port
TCP/9104 to make the kubernetes scheduler aware of that port
requirement.
=> Bug 2072766: Reserve port TCP/9104 for cluster-network-operator

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
Current probe interval for northd is set to 5 seconds.
The raft election timer is 16 seconds; which is the time
within which leader needs to hear from half its followers.
It doesn't make sense to have northd probe timeout set
less than half the raft election timer. Let's bump it to
10 seconds which is > than 8 seconds.
We had a bug where SBDB polls were 11 seconds and northd
was connecting with an old last-txn-id which was forcing
sbdb to reply with whole db causing the long loops and all
3 northd instances were dropping connection due to timeout
inactivity since sbdb was taking long to respond, as their
probes were set to 5 seconds.
=> Bug 2072710: Make northd probe interval default to 10 seconds

bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
Add logic to OVN-Kubernetes to determine what platform we are running on
drop icmp frag needed received from other nodes in the cluster
(cherry picked from commit 7a05ada8774081d8a7f8be2b45d517bd02b54acb)
=> Bug 2038295: Backport 4.8 OVN drop icmp frag from other nodes on Azure cluster

bindata/network/openshift-sdn/002-rbac.yaml
https://github.com/openshift/sdn/pull/417 makes openshift-sdn-node no longer make use of its Node modifying permissions, so this drops it from its service account.
/hold
=> Bug 2063123: Drop Node update permission for sdn-node

bindata/network/multus/multus.yaml
Fixes to include in this (and subsequent backports) include:
* auto clean failed jobs (https://github.com/openshift/cluster-network-operator/pull/1318)
* Use host network and api-int (https://github.com/openshift/cluster-network-operator/pull/1302)
* Disable retries on failure (https://github.com/openshift/cluster-network-operator/pull/1290)
=> Bug 2058674: ip-reconciler cronjob specification requires hostnetwork, api-int lb usage & proper backoff [backport 4.8]

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
The probe command fails with a non-zero exit code, causing the startup command to prematurely exit. Oops.
/cc @zshi-redhat
=> ovn-kube hypershift: fix pipefailure that prevents HA startup

bindata/network/multus/multus.yaml, pkg/network/multus.go, pkg/network/multus_ipam.go, pkg/network/multus_ipam_test.go, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
This refactors the dhcp_daemon.go to make the methods generic for use for other IPAM types.
It extends the same concept for DHCP daemon for use with Whereabouts in order to conditionally template the ip-reconciler cronjob.
=> Bug 2072215: Make the use of the ip-reconciler cronjob opt-in by detecting IPAM type usage

README.md, bindata/network/ovn-kubernetes/common/ipsec.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go
Re-add IPsec dynamic enablement/disablement functionality to CNO. This
feature was omitted from OCP because of some MTU dynamic change
limitations that were needed by this feature.
Now we have the ability to reconfigure MTU after cluster deployment this
feature can work as expected.
This reverts commit: 14cc1f86b5c2 (Revert "ipsec: Allow
enablement/disablement at runtime")
Signed-off-by: Mohammad Heib <mheib@redhat.com>
=> Revert "Revert ipsec: Allow enablement/disablement at runtime"

bindata/network/ovn-kubernetes/common/error-cni.yaml, bindata/network/ovn-kubernetes/common/ipsec.yaml, bindata/network/ovn-kubernetes/common/pre-puller.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
**- What this PR does and why is it needed**
This commit changes the spec.dnsPolicy to Default for OVN hostNetwork pods
so they use the hosts DNS. Even this is currently already the case for
pods having hostNetwork:true and spec.dnsPolicy DNSClusterFirst (which
is the default) this makes it more clear (https://github.com/kubernetes/kubernetes/blob/0424c7c74d926b4fe3193059e003e9056b429d28/pkg/kubelet/network/dns/dns.go#L303-L322)
**- How to verify it**
1. Deploy a cluster with this patch
2. Check that all of the ovn pods which use host network have the dnsPolicy `Default`:
```
$ oc -n openshift-ovn-kubernetes get po -ojsonpath='{.items[?(@.spec.hostNetwork)].spec.dnsPolicy}' 
Default Default Default Default Default Default Default Default Default%
```
**- Description for the changelog** …
=> Bug 2071859: Switch dnsPolicy to Default for OVN hostNetwork pods

manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
- PR addresses issue recently occurring in SNO upgrade jobs where upgrade fails because network-operator Deployment fails to rollout new  ReplicaSet because of already used `hostPort`.
- PR borrows from https://github.com/openshift/gcp-pd-csi-driver-operator/pull/30 which fixed similar issue for cluster-storage-operator
- How fix works
- `maxSurge: 0` results in first terminating old Pod, then starting new one (instead of both Pod existing at the same time, which cannot happen in SNO due to only one master and port being reserved)
- affinity settings causes to schedule new Pod on another master in regular clusters
- How the issue manifests
- network-operator Deployment fails to progress to a new ReplicaSet
```
{
"lastTransitionTime": "2022-04-21T19:27:37Z",
"lastUpdateTime": …
```
=> OCPVE-106 Customize rollout strategy to fix SNO upgrade

bindata/egress-router/001-deployment.yaml
Add default-route field to egress-router additional networks def so
that multus/ovn-k inject the correct routes into the pod towards
the cluster. Currently, the egress-router-cni relies on the gateway
field of the CNI definition to delete the default route and inject
its own, so in the future we will have to fix egress-router-cni, too.
For the moment, both the correct annotation and egress-router-cni's
incorrect behavior can coexist.
=> Bug 2075475: Add default-route field to egress-router k8s.v1.cni.cncf.io/networks

manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
The inactivity probe ensures that a client eventually disconnects
from a peer when no traffic has been received, even if the TCP
connection is supposedly still up. It attempts to detect hung
peers and uncleanly terminated TCP connections and allow quicker
recovery from these situations.
Node reboots do not cleanly terminate TCP connections and appear
to clients like the the peer has hung. The MCO reboot procedure
doesn't appear to allow the container scripts or preStop hooks
to run:
```
Apr 29 21:49:39.739350 ip-10-0-157-135 root[130737]: machine-config-daemon[121493]: Rebooting node
Apr 29 21:49:39.741203 ip-10-0-157-135 root[130738]: machine-config-daemon[121493]: initiating reboot: Node will reboot into config rendered-master-b296a1ff04aa28db1b1a172a2f8ff6da
Apr 29 21:49:39.749501 …
```
=> ovn: reduce SB<->ovn-controller inactivity probe to 30 seconds

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Allows the onvkube-master to be included in hypershift metrics recording rules
https://github.com/openshift/hypershift/blob/main/cmd/install/assets/recordingrules/hypershift.yaml
=> Add control-plane-component label to ovnkube-master for hypershift

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
Need to exec a shell so we can set the environment variable
we need that tells ovn-ctl not to touch the databases when
stopping northd.
@trozet
=> ovn: fix northd preStop command handling

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
These two are needed before we can use ovnkube as default in CI, we have verifications for these that currently fail.
Ref  https://github.com/openshift/hypershift/pull/1331
/assign @squeed
=> Hypershift: Fix ovnkube-master priority class and set resource requests on token-minter

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/managed/005-service.yaml, bindata/network/ovn-kubernetes/managed/007-certificate.yaml, bindata/network/ovn-kubernetes/managed/008-route.yaml, bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/managed/monitor-master.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, pkg/apply/apply.go, pkg/controller/operconfig/operconfig_controller.go, pkg/controller/statusmanager/pod_status.go, pkg/controller/statusmanager/status_manager.go, pkg/names/names.go
Instead of using the deprecated `ObjectMeta.ClusterName` field, use an annotation that serves the same purpose
https://github.com/kubernetes/kubernetes/pull/108717
/cc @squeed @zshi-redhat 
=> Remove ObjectMeta.ClusterName usage

bindata/cloud-network-config-controller/controller.yaml, bindata/network-diagnostics/network-check-source.yaml, bindata/network-diagnostics/network-check-target.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
  "objectRef": "openshift-network-diagnostics/daemonsets/network-check-target",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"network-check-target-container\" must set securityContext.allowPrivilegeEscalation=false), unrestri
cted capabilities (container \"network-check-target-container\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"network-check-target-container\" must set …
```
=> bindata/network-diagnostics, cloud-network-config-controller: comply to restricted pod security level

bindata/network/kuryr/001-rbac.yaml, bindata/network/kuryr/005-daemon.yaml, bindata/network/kuryr/006-controller.yaml, pkg/network/kuryr_test.go
This splits the Kuryr RBAC into separate ClusterRoles for controller nad
daemon and makes sure we don't keep unnecessary permissions. I also
dropped the ones related to sriov and dpdk support as we don't configure
them in OpenShift.
=> Bug 2082611: Limit Kuryr pods permissions

manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
This reverts commit ee7269e37286af8cdc4e0f6670036d4d32924e71.
While this makes sense for an isolated ovn-controller, it doesn't make
sense for some common cluster recovery cases where many controllers
connect to the SB around the same time:
1) If the OVN databases get wiped (sometimes done to reset clusters during
customer cases) then the database index resets to zero. ovn-controllers
stop intentionally ignore updates with old indexes to ensure cluster
consistency. When they are told to reset their index (because the wipe was
intentional) they will request the full DB from the SB.
2) if a large number of	nodes reboot, or part of the cluster was offline
and then came online again, a large number of controllers will attempt
to connect to the SB at the same time.
In these cases the …
=> Revert "ovn: reduce SB<->ovn-controller inactivity probe to 30 seconds"

bindata/network/ovn-kubernetes/managed/monitor-master.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
TLS support for ovnk-master was backported in https://github.com/openshift/ovn-kubernetes/pull/1064
=> Hypershift: enable TLS for ovnkube-master metrics

pkg/client/fake/fake_client.go, pkg/client/types.go, pkg/controller/configmap_ca_injector/controller.go, pkg/controller/operconfig/operconfig_controller.go, pkg/controller/proxyconfig/controller.go
This PR encompasses three separate changes that take the same shape:
1. Trigger a re-reconcile of the network when a Node is added or a ConfigMap changes in the CNO's namespace. This is because we saw HyperShift hang when no Nodes existed, and thus we couldn't run the MTU prober.
2. Switch the configmap-ca-injector to use a label-scoped watch, rather than watching all configmaps in the entire world.
3. Switch the ProxyConfig controller to use a namespace-scoped watch
=> Re-reconcile network on configmap, stop watching all configmaps in proxy controllers

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
v1beta1 will be removed in 1.25
=> Bug 2079422: Bump PodDisruptionBudget to v1

pkg/controller/operconfig/operconfig_controller.go, pkg/controller/statusmanager/status_manager.go
Remove NetworkPolicy, EgressFirewall, EgressIP and CloudPrivateIPConfig from CNO relatedObjects, since
1. it doesn't match relatedObjects definition ("Common uses are: 1. the detailed resource driving the operator 2. operator namespaces 3. operand namespaces")
2. it makes must-gather collect instances of these resource for all namespaces, and must-gather shouldn't collect resources from custom namespaces
egressips and cloudprivateipconfigs will be collected as cluster-scoped resources https://github.com/openshift/must-gather/pull/300 and egressfirewalls and networkpolicies will be collected as namespaced resources. https://github.com/openshift/oc/pull/1128
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
=> Bug 2023295: Cleanup CNO relatedObjects

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Since `k8s-token-file` parameter is provided there is no need to pass `k8s-token` as well.
Previously if the token was provided it could be logged as the script using it runs with `-x`.
Additionally add a wait loop for the token file to appear.
/cc @squeed @zshi-redhat 
=> Bug 2086544: Stop passing hosted cluster token as a parameter to ovnkube-master

bindata/network/ovn-kubernetes/managed/005-service.yaml, pkg/network/ovn_kubernetes.go
Bug 2087135: Fixing Hypershift nodeport flow:
1. In case of NodePort ClusterIp should not be set
2. Using the right client(management) to get NodePort service from
management cluster
3. Using right variable to set ovnsdb nodeport for ovnkube-node
=> Bug 2087135: Fixing Hypershift nodeport flow

pkg/controller/operconfig/mtu_probe.go, pkg/controller/operconfig/mtu_probe_test.go
Currently with Hypershift on AWS, we need to wait for a node to join the
cluster before we start setting up the controlplane components of the
networking stuck, because we need the MTU which we find out through
probing with a pod. This slows down cluster creation.
This change makes us short-circuit the pod deployment on AWS and use a
hardcoded value instead to avoid that.
=> Bug 2086461: AWS: Use hardcoded MTU to speed up cluster creation

pkg/controller/operconfig/mtu_probe.go, pkg/controller/operconfig/mtu_probe_test.go
This change adds a default for the Azure mtu to speed up cluster
creation, similiar like what already exists for AWS.
Ref:
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-tcpip-performance-tuning
/assign @squeed
=> Bug 2086461: Hypershift: Also add default for Azure mtu

bindata/network/multus/multus.yaml
Fixes to include in this (and subsequent backports) include:
* auto clean failed jobs (https://github.com/openshift/cluster-network-operator/pull/1318)
* Use host network and api-int (https://github.com/openshift/cluster-network-operator/pull/1302)
* Disable retries on failure (https://github.com/openshift/cluster-network-operator/pull/1290)
=> Bug 2058675: ip-reconciler cronjob specification requires hostnetwork, api-int lb usage & proper backoff [backport 4.7]

bindata/network/ovn-kubernetes/common/002-rbac.yaml
remove patch permission for ovnkube-node service for the following resources
- namespaces
- endpoints
- services
- configmaps
Kept same resource permissions for :-
- pods because its in use by `SetAnnotationsOnPod` used by ovn `addLogicalPort`
- nodes because its in use by `SetTaintOnNode` and `RemoveTaintFromNode`
=> Bug 2076776: remove patch permissions from ovnkube-node service account

bindata/network/multus/multus.yaml
It was previously copying directly to where the binaries are executed, which can cause for half-written binaries to be executed.
=> Bug 2073452: Copying CNI binaries should be an atomic operation.

bindata/network/openshift-sdn/002-rbac.yaml
Backport of #1350, incorporating #1409
depends on https://github.com/openshift/sdn/pull/422
/assign @andreaskaris
=> Bug 2078501: [release-4.10] Drop Node update permission for sdn-node

bindata/network/ovn-kubernetes/common/002-rbac.yaml
Bug 2076776 incorrectly changed role for certificatesigningrequests
resource from cluster scoped to namespace which isn't correct
=> Bug 2091167: incorrectly setting rbac role for certificatesigningrequests

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml, pkg/network/ovn_kubernetes.go
OVN 22.06 and later support the --n-threads northd option.
Less resource constrained clusters can use up to 4 northd
threads for better network operation latency at the cost
of a bit of extra CPU usage.
@trozet @jcaamano @tssurya @flavio-fernandes
=> Bug 2092495: ovn: use up to 4 northd threads in non-SNO clusters

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
This will enable the following bucket metrics:
ovnkube_master_network_programming_ovn_duration_seconds_*
ovnkube_master_network_programming_duration_seconds_*
We have carried out initial testing at scale with ~5k pods to show the perf 
regression is minimal.
/cc @npinaeva @bmeng
=> Bug 2089805: Enable config duration for OVN-Kubernetes

bindata/cloud-network-config-controller/002-rbac.yaml
Requirement for https://github.com/openshift/cloud-network-config-controller/pull/44
so it can rebase to use k8s.io/api v0.24.0
=> Bug 2092047: cncc: add RBAC coordination.k8s.io leases

bindata/network/multus/multus.yaml
Revert of PR used for debugging purposes.
=> Bug 2090336: Multus should log at a verbose log level (without a logfile)

pkg/client/client.go, pkg/client/fake/fake_client.go, pkg/operator/operator.go
Especially not later when leaderelection or other things might be accessing the global Scheme object that reads from registered types, which can cause concurrent map access and panic.
```
W0610 12:18:46.059490       1 cmd.go:213] Using insecure, self-signed certificates
I0610 12:18:46.770039       1 observer_polling.go:159] Starting file observer
W0610 12:18:46.793003       1 builder.go:230] unable to get owner reference (falling back to namespace): pods "cluster-network-operator-6b644ff8b9-zvxnq" not found
I0610 12:18:46.793128       1 builder.go:262] network-operator version v0.0.0-unknown-337cf37c
W0610 12:18:47.181014       1 secure_serving.go:69] Use of insecure cipher 'TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256' detected.
W0610 12:18:47.181132       1 secure_serving.go:69] Use of …
```
=> Bug 2095756: client: register types during init, not later

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Working with PerfScale on Hypershift, we observed a roughly 3x overprovision on memory requests for the containers within `ovnkube-master` pods. This equates to a memory request ~3Gi (1Gi per pod) over what is required for an HA control plane.
This PR brings memory requests in line with observe P90 usage as determined by PerfScale.
Big thanks to @mukrishn for getting the usage data!
fyi @derekwaynecarr @alvaroaleman @jeremyeder 
https://issues.redhat.com/browse/SDN-3132
=> Bug 2095772: bindata: managed: reduce memory requests to align with observed usage

pkg/controller/operconfig/operconfig_controller.go, pkg/controller/statusmanager/status_manager.go
Backport of https://github.com/openshift/cluster-network-operator/pull/1432
Related changes: https://github.com/openshift/oc/pull/1133, https://github.com/openshift/must-gather/pull/307
=> [release-4.10] Bug 2084591: Cleanup CNO relatedObjects

bindata/network/openshift-sdn/003-rbac-controller.yaml
needed for 1.24 rebase (https://github.com/openshift/sdn/pull/440)
=> Bug 2100079: Update sdn-controller perms for "configmapsleases" leaderelection

manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
Current probe interval for northd is set to 5 seconds.
The raft election timer is 16 seconds; which is the time
within which leader needs to hear from half its followers.
It doesn't make sense to have northd probe timeout set
less than half the raft election timer. Let's bump it to
10 seconds which is > than 8 seconds.
We had a bug where SBDB polls were 11 seconds and northd
was connecting with an old last-txn-id which was forcing
sbdb to reply with whole db causing the long loops and all
3 northd instances were dropping connection due to timeout
inactivity since sbdb was taking long to respond, as their
probes were set to 5 seconds.
NOTE: Seems like
https://github.com/openshift/cluster-network-operator/pull/1386 didn't
fix anything actually, so doing it correctly this time.
=> Bug 2084062: Make northd probe interval default to 10 seconds

bindata/network/ovn-kubernetes/ovnkube-master.yaml
OpenShift and kube don't yet gracefully terminate pods in all cases,
especially when taking a node down for reboot. Attempt to handle that
better by asking northd to stop gracefully in the preStop hook and
the container script.
Co-Authored-By: Dan Williams <dcbw@redhat.com>
=> Bug 2084366: ovn: try to gracefully terminate ovn-northd

pkg/controller/operconfig/operconfig_controller.go, pkg/controller/statusmanager/status_manager.go
Backport of https://github.com/openshift/cluster-network-operator/pull/1432
=> [release-4.9] Bug 2092265: Cleanup CNO relatedObjects

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Kubelet only sets a pod's Status.PodIP when all containers of the pod have started at least once (successfully or unsuccessfully)
or at least one of the initContainers finished.
Container start is blocked by postStart hooks. See https://github.com/kubernetes/kubernetes/issues/85966 for more details.
The NB and SB DB postStart hooks block until the DBs join the RAFT cluster or until a timeout is reached.
In a standalone cluster every pod is host networked and the DBs use host IP to communicate between the RAFT members.
In HyperShift OVN-Kubernetes master is run as a statefulset and the pods are not host networked, meaning we cannot rely on the podIP not changing.
To provide a stable network identity for each pod in the statefulset we use a headless service,
the downside of this approach is …
=> Bug 2103590: Add init container to ensure that Status.podIP is set before postStart hooks run

bindata/network/openshift-sdn/alert-rules.yaml
Before this patch, alert NodeProxyApplySlow calculates the 95th
percentile of the _total_ time series
kubeproxy_sync_proxy_rules_duration_seconds and alerts if it is
above 15 seconds.
Because it looks at the total time series, it lacks the ability
to be sensitive to periodic spikes in proxy rules sync latency.
This should merge after code freeze so I do not blow up alerting for 4.11 and it has sufficient soak test time.
/cc @danwinship
=> Bug 2060079: Enhance sensitivity of SDN alert NodeProxyApplySlow

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes_test.go
Reverts openshift/cluster-network-operator#1489 since this causes a performance regression.
=> Bug 2108232: Revert "Bug 2085089: Pass enable-udp-aggregation=true to ovn-kubernetes"

bindata/network/multus-admission-controller/admission-controller.yaml, pkg/network/multus_admission_controller_test.go
It's been running as a daemonset that will run on all masters, however, this isn't necessary, especially in large clusters. This causes some additional apiserver traffic when nodes are rebooted as well.
The intent here is to run two instances for redundancy.
=> The Multus admission controller should run as a deployment

bindata/cloud-network-config-controller/002-rbac.yaml
The OpenStack CNCC provider plugin requires a ConfigMap that provides
an additional CA certificate. The CNCC must monitor ConfigMaps in its
namespace for changes. Add list/watch rights to the CNCC ServiceAccount
for the CNCC namespace.
=> Add configmap list/watch rights to cloud-network-config-controller

bindata/network/multus-networkpolicy/multus-networkpolicy.yaml
Add `sriov` to the array of network plugins multus-networkpolicy-iptables should manage.
=> multi-networkpolicy: Enable on SR-IOV networks

bindata/network/kuryr/001-rbac.yaml, bindata/network/kuryr/005-daemon.yaml, bindata/network/kuryr/006-controller.yaml, bindata/network/kuryr/010-admission-controller.yaml, pkg/network/kuryr_test.go
This splits the Kuryr RBAC into separate ClusterRoles for controller nad
daemon and makes sure we don't keep unnecessary permissions. I also
dropped the ones related to sriov and dpdk support as we don't configure
them in OpenShift.
=> Bug 2083266: Limit Kuryr pods permissions

bindata/network/ovn-kubernetes/microshift/clusterrole.yaml, bindata/network/ovn-kubernetes/microshift/clusterrolebinding.yaml, bindata/network/ovn-kubernetes/microshift/configmap.yaml, bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml, bindata/network/ovn-kubernetes/microshift/master/serviceaccount.yaml, bindata/network/ovn-kubernetes/microshift/namespace.yaml, bindata/network/ovn-kubernetes/microshift/node/daemonset.yaml, bindata/network/ovn-kubernetes/microshift/node/serviceaccount.yaml, bindata/network/ovn-kubernetes/microshift/role.yaml, bindata/network/ovn-kubernetes/microshift/rolebinding.yaml
MicroShift updates embedded component manifests by gathering
them from various places in the staged repos and copying them
to its asset directory.
This commit adds MicroShift specific ovnk manifests in CNO
so that it can be gathered by MicroShift rebase automation.
Ovnk manifests under bindata/network/ovn-kubernetes/microshift
will not be populated by CNO for regular openshift deployment.
Closes [NP-536](https://issues.redhat.com/browse/NP-536)
=> Add microshift ovnk manifests

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Need to exec a shell so we can set the environment variable
we need that tells ovn-ctl not to touch the databases when
stopping northd.
(cherry picked from commit 599a9d5060e3e5bb79f93e2f321bc4592dfa7a22)
Backport of https://github.com/openshift/cluster-network-operator/pull/1414
=> [release-4.10] Bug 2095111: ovn: fix northd preStop command handling

pkg/apply/apply.go, pkg/apply/merge.go, pkg/apply/merge_test.go, pkg/client/fake/fake_client.go
Unfortunately disableNetworkDiagnostics is not setup as a pointer and is
overriden to the default value on the server-side apply when the cluster
config is reconciliated.
=> Bug 2103680: avoid overrriding disableNetworkDiagnostics on reconciliation

bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Several Ovn-kubernetes alerts were found to not have runbook links defined, despite the presence of those runbooks.
- (managed) NoRunningOvnMaster
- (managed) V4SubnetAllocationThresholdExceeded
- (self-hosted) NorthboundStale
This updates those alerts to have the correct runbook links.
=> Add missing runbook links for OVN-kubernetes alerts

bindata/network/kuryr/006-controller.yaml
By default livenessProbe times out after 1 second. We just saw that this
is sometimes too little for the Kuryr health server to respond, so this
commit bumps that time to 10s.
=> Bug OCPBUGS-216: Kuryr: Bump timeoutSeconds for livenessProbe

bindata/network/multus-admission-controller/001-service.yaml, bindata/network/multus-admission-controller/002-rbac.yaml, bindata/network/multus-admission-controller/003-webhook.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/multus-admission-controller/monitor.yaml, bindata/network/multus-admission-controller/rules.yaml, cmd/cluster-network-operator/main.go, pkg/client/client.go, pkg/client/fake/fake_client.go, pkg/controller/statusmanager/pod_watcher.go, pkg/controller/statusmanager/status_manager.go, pkg/names/names.go, pkg/network/cloud_network.go, pkg/network/multus_admission_controller.go, pkg/network/multus_admission_controller_test.go, pkg/network/ovn_kubernetes.go, pkg/network/render.go
The multus admission controller should run on the management cluster for hypershift
This applies the appropriate label for network.operator.openshift.io/cluster-name
Additionally, it also moves the default and hypershift cluster names to the names package, instead of as constants in the client package.
=> Multus admission controller changes for hypershift

bindata/network/ovn-kubernetes/managed/008-route.yaml, pkg/bootstrap/types.go, pkg/network/hypershift.go, pkg/network/ovn_kubernetes.go
This change makes it possible to configure the hostname and labels on
the Hypershift SBDB route through environment variables.
Configuring these is needed when the cluster is private, as in that case
a custom router is used to avoid sending the traffic over the internet.
In order to avoid duplicating the logic to determine if a cluster is
private and then needing to keep it in sync with the Hypershift
Controlplane operator, the simple environment variable approach was
chosen.
Ref https://issues.redhat.com/browse/HOSTEDCP-517
/assign @kyrtapz
=> Hypershift: Allow configuring hostname and labels on the route

bindata/network/multus-admission-controller/admission-controller.yaml
cc @alvaroaleman @csrwng 
Changed in https://github.com/openshift/cluster-network-operator/pull/1516
Fix failure in hypershift CI e.g.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_hypershift/1702/pull-ci-openshift-hypershift-main-e2e-aws-nested/1563067003344785408
=> hypershift: set multus controller priority appropriate for hosted clusters

pkg/controller/operconfig/migration.go
When migrating the configuration of Egress Firewall from SDN to
OVN, use a fixed name 'default' as the name of EgressFirewall CRs.
It also means when rolling back to SDN, all EgressNetworkPolicy CRs
created by CNO will use 'default' as name.
This is a hard requirement defined in EgressFirewall CRD.
=> Use fixed name for creating EgressFirewall CRs

bindata/network/multus-admission-controller/admission-controller.yaml
The token is created and rotated by a sidecar to the admission
controller, which means most of the time it won't be there yet when the
process tries to read it during startup. Wait until it is there before
starting.
/assign @dougbtv @kyrtapz 
We have a check in our CI that pods don't restart and this makes it fail regularly, e.G. here: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_hypershift/1689/pull-ci-openshift-hypershift-main-e2e-aws/1565002270200827904#1:build-log.txt%3A1927
=> Multus admission controller: Wait for token in Hypershift

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Some users need to be able to specify the v4 and v6 join subnets
to use for ovn-k. In particular, they may be already using the
ones that ovn-k uses as default, and they need a way to be able to
specify a different set of subnets as join subnets. This commit
creates the config option for the same. Eventually this will be
consumed by the CNO using rendered bootstrap data and passed to the
ovn-k daemonsets.
=> Bug 1894268: Allow users to specify ovnkube join subnet

bindata/network/multus/multus.yaml
This PR adds support for scos to the cnibincopy.sh script for multus.
Closes [OKD-49](https://issues.redhat.com//browse/OKD-49)
cc @LorbusChris
=> OKD-49: Adds support for scos to multus

pkg/bootstrap/types.go, pkg/controller/operconfig/operconfig_controller.go, pkg/controller/statusmanager/pod_status.go, pkg/controller/statusmanager/pod_watcher.go, pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go, pkg/names/names.go, pkg/operator/operator.go, pkg/platform/platform.go
CNO should only reconcile its status based on the resources it rendered.
In the management cluster there is the default CNO and one CNO per hosted clusters control namespace.
By using a label value set to the infrastructure name we can differentiate the resources rendered by different CNO instances.
In stand-alone environments the value is a non-empty constant so it doesn't overlap with older CNO versions.
Additionally start watching deployments in the hosted cluster control plane namespace sine we added CNCC and multus admission controller to it.
=> Bug SDN-3458: HyperShift: Differentiate resources deployed by different CNO instances in status manager

pkg/apply/apply.go, pkg/controller/add_networkconfig.go, pkg/controller/infrastructureconfig/OWNERS, pkg/controller/infrastructureconfig/infrastructureconfig_controller.go, pkg/controller/infrastructureconfig/predicates.go, pkg/controller/infrastructureconfig/sync_vips.go, pkg/controller/infrastructureconfig/sync_vips_test.go, pkg/controller/statusmanager/status_manager.go, pkg/names/names.go
For the dual stack API & Ingress VIP support, we have to add additional fields to onprem platform statuses (https://github.com/openshift/api/pull/1152). 
To have consistent APIs between versions and keep backwards compatible for components consuming the old VIP fields, we need to keep the new and old VIP fields in sync. This is addressed by this PR by adding a new controller to the CNO which keeps the old and new VIP fields in `Infrastructure.config.openshift.io/cluster` in sync.
**Special notes for reviewers:**
* we added an `OWNERS` file in the folder with adding the bare metal team as reviewers for this controller, as it could make sense to have one of the team members reviewing changes on this component.
=> Add controller to synchronize the API and Ingress VIP fields

bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml
The Egress Service controller requires these permissions as it updates annotations on services
=> OVN-K: add patch/update service permissions to controller

pkg/client/list_pager.go, pkg/controller/operconfig/migration.go, pkg/controller/operconfig/migration_test.go, pkg/controller/operconfig/mtu_probe_test.go, pkg/controller/operconfig/operconfig_controller.go, pkg/controller/operconfig/test_helpers.go
Patch that addresses blocker epic [OVN Migration Further Solution Enhancement](https://issues.redhat.com/browse/NP-20).
Multicast migration is simple, only annotations need to be updated.
=> Migrate Multicast configuration during SDN migration and rollback

manifests/image-references
Reference the ovn-kubernetes-microshift imagestream from an operator for it to be a part of the payload.
=> Add ovn-kubernetes-microshift to image-stream

bindata/network/ovn-kubernetes/microshift/configmap.yaml, bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml
1. enable MTU configuration
2. add K8S_NODE_IP env var in ovnk master daemon
K8S_NODE_IP in ovnk daemon triggers reconcilation
when node IP changes.
=> microshift: update ovnk manifests

pkg/controller/infrastructureconfig/sync_vips.go, pkg/controller/infrastructureconfig/sync_vips_test.go
VSphere UPI doesn't populate VSphere field. So with vSphere we should only handle the case, that `Status.Platform == configv1.VSpherePlatformType && Status.PlatformStatus.VSphere != nil`
=> Allow empty vSphere status field in VIP sync

pkg/client/list_pager.go, pkg/controller/operconfig/migration.go, pkg/controller/operconfig/migration_test.go, pkg/controller/operconfig/operconfig_controller.go
Patch that addresses blocker epic [OVN Migration Further Solution Enhancement](https://issues.redhat.com/browse/NP-20). 
With this patch, CNO will convert HostSubnets and Netnamespaces configured with egressIP to egressIP CR when migrating from Openshift SDN to OVN-Kubernetes. When rolling back, CNO will convert egressIP CR into configuration updates for HostSubnets and Netnamespaces. When said resources get recreated during rollback, the configuration updates will be applied, restoring egressIP config.
Of note: this feature only supports automatically configured egressIP migration for SDN to OVN migration. Manually configured SDN egressIPs are NOT supported and **the documentation should explicitly state this**.
Review comments are welcome and encouraged, as this feature is blocking the …
=> Migrate Egress IP configuration during SDN migration and rollback

pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
For IPv6, default int value is not large enough to store the number of IPs. In some case, it causes int overflow.
In golang, there is no built-in type for uint128. So create a custom uint128 type for calculating v6 IP number.
=> OCPBUGS-1515: Use custom uint128 type when validating v6InternalSubnet

pkg/bootstrap/types.go, pkg/controller/operconfig/operconfig_controller.go, pkg/controller/statusmanager/pod_status.go, pkg/controller/statusmanager/pod_watcher.go, pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go, pkg/names/names.go, pkg/operator/operator.go, pkg/platform/platform.go
Cherry pick of [d548cc66d883059cd22ab7fc176ebdef0d7c266bc](https://github.com/openshift/cluster-network-operator/pull/1541/commits/d548cc66d883059cd22ab7fc176ebdef0d7c266b)
/cc @jcaamano @zshi-redhat 
(cherry picked from commit d548cc66d883059cd22ab7fc176ebdef0d7c266b)
=> [release-11] Bug OCPBUGS-1075: HyperShift: Differentiate resources deployed by different CNO instances

manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
manifests/0000_70_cluster-network-operator_03_deployment.yaml does not need to explicitly specify OVN_EGRESSIP_HEALTHCHECK_PORT
This was a missing change in PR https://github.com/openshift/cluster-network-operator/pull/1539 that
happened afterwards in https://github.com/openshift/cluster-network-operator/pull/1520 and I forgot
to update. Mea culpa.
=> egress_ip: remove redundant config

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Re-push of #1489; that got reverted (#1510) because [QE had reported that it caused performance regressions](https://bugzilla.redhat.com/show_bug.cgi?id=2085089#c37). However
1. Most of the problem turned out to be because [un-labeled numbers in the perf results had been interpreted as being in milliseconds when they were actually microseconds](https://bugzilla.redhat.com/show_bug.cgi?id=2085089#c43); there _was_ an increase in latency, but it was tiny and expected, not large and problematic.
2. The rest of the problem is with a dubious test scenario which tests how fast the network is when using [a network protocol that is, essentially, maximally "optimized" for slowness](https://bugzilla.redhat.com/show_bug.cgi?id=2085089#c46) by doing fully-serialized request / response / request / …
=> Pass enable-udp-aggregation=true to ovn-kubernetes

bindata/network/ovn-kubernetes/common/alert-rules.yaml, bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
because of a test case [0] in CI that brings in a 4th master node temporarily, there is a period when ovn db raft does not have a consensus. These alerts will correctly fire during that window, but with the warn level they will trigger a failure in CI. With info, they will still fire but hopefully not trigger the failure. This bug [1] has more info.
[0] https://github.com/openshift/origin/blob/38f2bdd426b8cbb6ee9b0f6207add07ed69603cc/test/extended/etcd/vertical_scaling.go#L39 [1] https://issues.redhat.com/browse/OCPBUGS-1083
=> OCPBUGS-1083: Move OVNK alert level to info

bindata/allowlist/config/configmap.yaml, bindata/allowlist/daemonset/daemonset.yaml, bindata/network/multus/004-sysctl-configmap.yaml, bindata/network/multus/multus.yaml, pkg/controller/add_networkconfig.go, pkg/controller/allowlist/allowlist_controller.go, pkg/names/names.go, pkg/network/multus.go, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
A new controller which will watch for changes in the openshift-multus/allowlist config-map, and update the `/etc/cni/tuning/allowlist.conf `file on nodes to reflect changes in the config-map.
The  openshift-multus/allowlist config-map will be created by the multus-admission-controller (no change), as part of the multus installation, but the new controller will take on from there.
If the config-map is deleted, the controller will not delete the `/etc/cni/tuning/allowlist.conf` files on nodes. Should the user want to allow all sysctl's, an appropriate wildcard in the config-map must be added.
=> Add sysctl whitelist controller

bindata/network/multus-admission-controller/001-service.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/multus-admission-controller/monitor.yaml, pkg/network/multus_admission_controller.go
The usage of kube-rbac-proxy is not supported in hosted clusters control namespace as it required a clusterrole binding.
Follow the example of other components and expose encrypted metrics directly.
Additionally, replace metrics id for multus admission controller.
=> SDN-3515: HyperShift: multus admission controller: expose metrics over HTTPs

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Need to exec a shell so we can set the environment variable
we need that tells ovn-ctl not to touch the databases when
stopping northd.
(cherry picked from commit 599a9d5060e3e5bb79f93e2f321bc4592dfa7a22)
(cherry picked from commit e7beb6941f7d6157087f83d98968f8926105e6d7)
Backport of https://github.com/openshift/cluster-network-operator/pull/1414
=> [release-4.9] Bug 2095112: ovn: fix northd preStop command handling

bindata/network/ovn-kubernetes/ovnkube-master.yaml, manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
/cc @trozet 
brings in https://github.com/openshift/cluster-network-operator/pull/1386/commits/eebce7172b9fc236a454809dc1768fcf7b3703fd and https://github.com/openshift/cluster-network-operator/pull/1494/files (which is the right fix)
=> [release-4.10] OCPBUGS-1538: Make northd probe interval default to 10 seconds

pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
after the last downstream merge of ovn-kube we can enable and disable hybrid overlay post install
=> SDN-2591: allow hybrid overlay to be enabled post install

bindata/network/multus/004-sysctl-configmap.yaml
The allow_ra sysctl controlls router advertisment settings which are an ipv6 thing only. As such it should only be present for ipv6.
=> Remove the allow_ra sysctl for ipv4 from default systl whitelist

pkg/controller/operconfig/mtu_probe.go, pkg/network/cluster_config_test.go, pkg/network/multus.go, pkg/network/openshift_sdn.go, pkg/network/ovn_kubernetes.go, pkg/network/render_test.go, pkg/network/testutil_test.go, pkg/platform/platform.go
Most components such as OVNK, SDN, etc. require PROXY env variables only for hypershift. The CNCC on the other hand must talk to the underlying cloud platform and must respect PROXY settings.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-1736
=> Jira OCPBUGS-1736: Always set PROXY variables for CNCC

pkg/controller/operconfig/operconfig_controller.go
This is a follow up to #1128, for this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1896533
Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
=> Bug 1896533: moved SetDegraded call out of object loop to process all items first

bindata/network/ovn-kubernetes/microshift/clusterrole.yaml, bindata/network/ovn-kubernetes/microshift/configmap.yaml, bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml, bindata/network/ovn-kubernetes/microshift/node/daemonset.yaml, bindata/network/ovn-kubernetes/microshift/role.yaml
Fixes that went into microshift repo directly needs to be synced
back to CNO repo for consistency in 4.12.
For 4.13+, microshift ovnk manifests will be updated first in CNO
repo, then be picked up by microshift rebase automation.
Details about ovnk maintenance in microshift can be found:
https://docs.google.com/document/d/1xc-CJ8RlmC5dj3CguG5wQC1_rs5DBqKqkpADAeX9qwI/edit#heading=h.m9cxlcfppxur
=> NP-607: update microshift ovnk manifests

bindata/cloud-network-config-controller/managed/controller.yaml, pkg/network/cloud_network.go
In HyperShift CloudNetworkConfigController is deployed as a part of the hosted cluster controlplane
which means that the deployment is created in the management cluster.
CloudNetworkConfigController should use the proxy settings configured by hypershift controlplane operator
on CNO deployment.
=> SDN-3508: HyperShift: Render cncc with proxy settings of the management cluster

bindata/network/ovn-kubernetes/common/ipsec.yaml
ipsec: Run ovs-monitor-ipsec in the foreground and change probes
Up until now, we ran ovs-monitor-ipsec in the background and ran a sleep
infinity after that. We then used the following in our liveness and
readiness probes:
ovs-appctl -t ovs-monitor-ipsec ipsec/status && ipsec status
We never parsed the output of either of these commands thus the probes
failed only when ovs-monitor-ipsec was down or when pluto failed. Probes
also caused issues in environments with large numbers of IPsec endpoints
as they caused the ovn-ipsec pods to be killed on pod startup.
Optimize this by running ovs-monitor-ipsec in the foreground and by only
keeping `ipsec status` in the probes. Also shorten the
initialDelaySeconds.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-2598
Signed-off-by: Andreas …
=> OCPBUGS-2598: ipsec: Run ovs-monitor-ipsec in the foreground and change probes

bindata/network/multus/multus.yaml
I still am wholly unsure how the symlink gets created in the reported bug, but, this should make sure that the destination is unlinked before the copy.
=> OCPBUGS-3460: CNI binary copy should account for the possibility of symlinks

bindata/network/openshift-sdn/sdn.yaml
This PR reverts https://github.com/openshift/cluster-network-operator/pull/787 which no longer helps with the `unknown FS magic on "/var/run/netns/...": 1021994(TMPFS_MAGIC)`.
Additionally limit the `/var/run` mount to `/var/run/crio` as we no longer need to access the docker socket since: https://github.com/openshift/sdn/commit/153a756be0d73fac06db7b17fc023393633c6fb2.
/cc @andreaskaris 
/assign @danwinship
=> OCPBUGS-3744: SDN: /var/run mount cleanup

cmd/cluster-network-operator/main.go, hack/run-locally.sh, manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
Since https://github.com/openshift/cluster-network-operator/pull/976 we are no longer using the hosts kubeconfig.
Remove the references to the old approach.
This addresses https://bugzilla.redhat.com/show_bug.cgi?id=2083334, security bugs do not work with the bot:
> When the change merges, the Bugzilla associated with the CVE must be set to MODIFIED. Since the DPTP bugzilla bot is not permitted to scan bugs with the SECURITY group in Bugzilla, The REP will not be able to use the bot's public functionality of moving their bug to MODIFIED.
> https://docs.google.com/document/d/1KuenDafC3Ukw19jY55tkVeH8nNVVAi8TEAfqynoVfzY/edit#heading=h.ikdk6suc575k
=> Remove references to the hosts kubeconfig

bindata/network/ovn-kubernetes/common/ipsec.yaml
((counter++)) does not always work - the ovn-keys init container dies
when hitting that line under certain cicumstances.
I discovered upstream that changing this to counter=$[counter+1] will
fix this.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-3777
context, I implemented the ipsec pods in kind upstream and I had noticed that the expression was broken
So I already ported it this way upstream:
https://github.com/ovn-org/ovn-kubernetes/blob/master/dist/templates/ovn-ipsec.yaml.j2#L107
I think those loop counter increments likely never worked but that in most cases, the until always returned true so we never had to get into the loop.
Due to another fix for IPsec, Anurag started deploying and testing ovnk ipsec with dualstack all the …
=> Jira OCPBUGS-3777: IPsec: Fix broken counter++ expression

pkg/network/ovn_kubernetes.go
The golang ethtool library doesn't seem to work right on s390x, and this is blocking testing. Might be reverted later...
=> OCPBUGS-2532: Disable UDP aggregation on s390x

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Co-locate OVN-Kubernetes master with other hcp pods.
This tries to do the same that as: https://github.com/openshift/hypershift/blob/fa7bd17ab5f1bac31a06724cb0a5d53185260f11/support/config/deployment.go#L174
/cc @zshi-redhat @csrwng
To verify it works I created 6 HA hosted clusters and ovn-k is located in the same way as etcd now:
```
oc get po -A -lapp=etcd  --field-selector=metadata.namespace!=openshift-etcd  -o jsonpath='{range .items[*]}{.spec.nodeName}{"\n"}{end}'   | sort | uniq -c
2 ip-10-0-130-80.ec2.internal
3 ip-10-0-131-40.ec2.internal
4 ip-10-0-158-242.ec2.internal
3 ip-10-0-163-58.ec2.internal
3 ip-10-0-182-17.ec2.internal
3 ip-10-0-197-120.ec2.internal
```
```
oc get po -A -lapp=ovnkube-master  --field-selector=metadata.namespace!=openshift-ovn-kubernetes  -o …
```
=> OCPBUGS-3883: HyperShift: Co-locate OVN-Kubernetes master with other hcp pods

pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go
This commit fixes #1545 to make sure that Kuryr bootstrap honors the MTU set in KuryrConfig when creating the network for services. The MTU logic had to be moved from rendering to the bootstrap phase.
=> Bug OCPBUGS-736: Kuryr: If set use MTU from Config for svc net

bindata/network/openshift-sdn/alert-rules.yaml
`kube_pod_status_ready` metric has no label called `node`: https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md
Adding node name value from `kube_pod_info` metric, as it was done for kuryr in
- https://github.com/openshift/cluster-network-operator/pull/1176
Ref: https://issues.redhat.com/browse/OCPBUGS-3916
=> OCPBUGS-3916: SDN alerts: Add `$labels.node` to `SDNPodNotRady` metric

bindata/network/multus-admission-controller/monitor.yaml, bindata/network/ovn-kubernetes/managed/monitor-master.yaml, pkg/network/multus_admission_controller.go, pkg/network/ovn_kubernetes.go
When running in HyperShift mode and the RHOBS_MONITORING=1 environment variable is set, renders service monitors in the control plane namespace using the RHOBS group/version (monitoring.rhobs/v1) instead of the default monitoring.coreos.com/v1.
This is needed by the service delivery implementation of monitoring where the monitoring stack requires the use of the monitoring.rhobs/v1 group version in resources it discovers for scraping.
Fixes: #[HOSTEDCP-624](https://issues.redhat.com//browse/HOSTEDCP-624)
=> Support RHOBS monitoring for HyperShift

pkg/controller/statusmanager/pod_status.go, pkg/controller/statusmanager/status_manager_test.go, pkg/network/ovn_kubernetes.go, pkg/render/render.go
When a deployment or a statefulset is being updated `UpdatedReplicas` indicates how many replicas are on the latest version. When the field was not taken into account all statefulsets and deployments were considered ready prematurely during upgrades.
cc: @zshi-redhat 
/assign @jcaamano 
=> OCPBUGS-4350: Fix handling of deployment and statefulset updates

bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
- `oc describe` commands should be executed with the `--listen-addr=''` command line argument to keep the go profiling web server
=> OCPBUGS-2947: Disable the drop-icmp container 'oc' pprof webserver on Azure

cmd/cluster-network-operator/main.go, hack/run-locally.sh, manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
There are OpenShift environments that do not use MCO and rely on kubecfg being available on the host.
Revert the removal of the kubeconfig fallback to address that.
/assign @trozet @jcaamano 
This reverts commit a737ab6d1e523bcb9413f72dd0935bb078ff9019.
=> [release-4.12] OCPBUGS-4686: Revert "Remove references to the hosts kubeconfig"

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml, pkg/controller/operconfig/operconfig_controller.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
This cherry picks the improvements to ovn-k startup from https://github.com/openshift/cluster-network-operator/pull/1579
/cc @martinkennelly @dcbw
=> [release-4.11] OCPBUGS-3490: OVN-Kubernetes: Prefer oldest nodes

pkg/network/kuryr.go
2cb56d8176756e57dd95d4940c620e88cae02342 moved around code setting default value for MTU when Kuryr is configured. The problem is that it also stopped to set it, which made CNO unable to update the .status on Network CR and the kube-apiserver-operator from correctly populating API IP in the certs.
This commit makes sure we always populate KuryrConfig.MTU with a value.
=> Fix CNO crashing when Kuryr without MTU is set

Makefile
looks like the godownloader [0] wasn't updated for a while and no longer works, so install.goreleaser.com is no longer working.
new way to install was found here [1]
[0] https://goreleaser.com/deprecations/#godownloader [1] https://golangci-lint.run/usage/install/
=> update 'make install.tools' for golangci-lint

pkg/controller/operconfig/operconfig_controller.go, pkg/network/render.go
This PR aims to unblock checks that currently block Kuryr->OVNKubernetes migrations. Interestingly that worked just fine in 4.11, but feature migrations introduced in 4.12 started to block that. Also a validateMigration function is introduced that will
block Kuryr->OpenShiftSDN migrations that are considered not supported.
I also added error logging to feature migration code as these are not printed and I spent quite a while trying to figure out why the migration isn't progressing as it did in 4.11.
=> Allow SDN migration from Kuryr to OVNKubernetes

pkg/network/ovn_kubernetes.go
Master nodes are now sorted by creation timestamp so there is no need to sort the IP addresses to get a consistent result.
=> OCPBUGS-5306: OVN-Kubernetes: Stop sorting master node addresses

bindata/network/ovn-kubernetes/ovnkube-master.yaml
similar to https://github.com/openshift/cluster-network-operator/pull/1427
=> [release-4.10] Bug 2092193: Bump PodDisruptionBudget to v1

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
The DBs are running, so the readiness checks will just fail, which is pointless.
=> OCPBUGS-5306: ovn-kubernetes: ignore NB/SB readiness checks and dbchecker when not RAFT member

go.mod, go.sum, vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go, vendor/github.com/Masterminds/goutils/randomstringutils.go, vendor/github.com/Masterminds/goutils/stringutils.go, vendor/modules.txt
$ grep -i mastermin go.mod
github.com/Masterminds/goutils v1.1.0 // indirect
github.com/Masterminds/semver v1.5.0
github.com/Masterminds/sprig v2.22.0+incompatible
$ go mod why github.com/Masterminds/goutils
github.com/openshift/cluster-network-operator/pkg/render github.com/Masterminds/sprig
github.com/Masterminds/goutils
$ go get github.com/Masterminds/sprig/v3@v3.2.2
$ go mod vendor
$ go mod tidy
=> [release-4.10] OCPBUGS-5575: CVE-2021-4238 goutils: RandomAlphaNumeric and CryptoRandomAlphaNumeric are not as random as they should be

bindata/network/multus/multus.yaml, pkg/network/multus.go, pkg/network/multus_ipam.go, pkg/network/multus_ipam_test.go, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
…by detecting IPAM type usage.
This refactors the dhcp_daemon.go to make the methods generic for use for other IPAM types.
It extends the same concept for DHCP daemon for use with Whereabouts in order to conditionally template the ip-reconciler cronjob.
=> Bug 2101918: Make the use of the ip-reconciler cronjob opt-in [backport 4.8]

go.mod, go.sum, vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go, vendor/github.com/Masterminds/goutils/randomstringutils.go, vendor/github.com/Masterminds/goutils/stringutils.go, vendor/modules.txt
$ grep -i mastermin go.mod
github.com/Masterminds/goutils v1.1.0 // indirect
github.com/Masterminds/semver v1.5.0
github.com/Masterminds/sprig v2.22.0+incompatible
$ go mod why github.com/Masterminds/goutils
github.com/openshift/cluster-network-operator/pkg/render
github.com/Masterminds/sprig
github.com/Masterminds/goutils
$ go get github.com/Masterminds/sprig/v3@v3.2.2
$ go mod vendor
$ go mod tidy
=> [release-4.9] OCPBUGS-5574: CVE-2021-4238 goutils: RandomAlphaNumeric and CryptoRandomAlphaNumeric are not as random as they should be

bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
When a cluster is created, it typically takes ~2 minutes for  the databases to start up and form the Raft cluster. Before this occurs, there will be no DB endpointsm so the node containers that are waiting for them and failing readiness tests will cause alerts, which cause ci failures / flakes
We can avoid this problem by waiting 2 minutes to start the liveness probe, and reducing its polling rate
Signed-off-by: Ben Pickard <bpickard@redhat.com>
=> OCPBUGS-3272: Unhealthy Readiness Probe failing ci

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Problem: The ovn-nbctl logs were never rotated and are stored in a logfile that continually grows.
The nbctl daemon is run in detatched mode, which disables the file-descriptors, so we cannot just log to stdout
Solution: Simplest solution is to just remove the logs, especially since nbctl is not used in newer versions 
Signed-off-by: Ben Pickard <bpickard@redhat.com>
=> OCPBUGS-6736: Remove nbctl logfile

go.mod, go.sum, vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go, vendor/github.com/Masterminds/goutils/randomstringutils.go, vendor/github.com/Masterminds/goutils/stringutils.go, vendor/modules.txt
$ grep -i mastermin go.mod
github.com/Masterminds/goutils v1.1.0 // indirect
github.com/Masterminds/semver v1.5.0
github.com/Masterminds/sprig v2.22.0+incompatible
$ go mod why github.com/Masterminds/goutils
github.com/openshift/cluster-network-operator/pkg/render github.com/Masterminds/sprig
github.com/Masterminds/goutils
$ go get github.com/Masterminds/sprig/v3@v3.2.2
$ go mod vendor
$ go mod tidy
=> [release-4.8] OCPBUGS-5573: CVE-2021-4238 goutils: RandomAlphaNumericand CryptoRandomAlphaNumeric are not as random as they should be

bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
The node_mgmt_port_netdev_flags is a feature flag of ovn-kubernetes and shouldn't be restricted to any particular modes of operation.
Signed-off-by: William Zhao <wizhao@redhat.com>
=> ovn-kubernetes: Allow node_mgmt_port_netdev_flags for non-DPU modes

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml, pkg/network/ovn_kubernetes.go
Clean back-port of https://github.com/openshift/cluster-network-operator/pull/1675 and https://github.com/openshift/cluster-network-operator/pull/1673
=> [release-4.12] OCPBUGS-6494: OVN-Kubernetes: Stop sorting master node addresses, ignore readiness checks for redundant NB/SB

bindata/kube-proxy/kube-proxy.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/network-metrics/001-daemonset.yaml, bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
TLS_RSA_WITH_AES_128_CBC_SHA256 does not support Perfect Forward Secrecy (PFS) and can potentiall create compliance issues. Remove it.
JIRA: https://issues.redhat.com/browse/OCPBUGS-3267
=> remove TLS_RSA_WITH_AES_128_CBC_SHA256 cipher

pkg/network/hypershift.go, pkg/network/ovn_kubernetes.go
ovn-kube node should connect to the sbdb through a proxy only if the route is not an internal one.
=> OCPBUGS-6651: HyperShift: Do not use proxy for internal routes

pkg/util/proxyconfig/no_proxy.go
Currently in a PublicAndPrivate setup behind a proxy, nodes remain unready because ovn-node pods fail to talk to the control plane osdb and api endpoints. This is because the connection to .hypershift.local tries to go through the proxy.
This PR https://github.com/openshift/hypershift/pull/2081 should make hypershift.local to be set in NO_PROXY via
https://github.com/openshift/cluster-network-operator/blob/8db9a00429dd4a5e4123b1217da93419557645eb/pkg/util/proxyconfig/no_proxy.go#L76
and
https://github.com/openshift/hypershift/blob/117c87f271ad7dc7cab875afb17769795fb7d117/control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go#L248
Additionally we also want to let the CNO set .hypershift.local in NO_PROXY unconditionally as this is a design invariant …
=> OCPBUGS-6651: HyperShift: Add .hypershift.local to no proxy list

bindata/network/additional-networks/crd/001-crd.yaml
The OverlappingRangeIPReservation CRD was missing the podref field. Because of this, an issue occurs when the ip-reconciler code from whereabouts get executed, where the ip-reconciler will incorrectly view a pod as not alive, and consequently incorrectly delete the OverlappingRangeIPReservation object from kubernetes. 
I updated the CRD to include the podref field.
Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
=> OCPBUGS-4417: Added missing API field podref to OverlappingRangeIPReservation CRD

bindata/network/openshift-sdn/sdn.yaml
Reverts openshift/cluster-network-operator#1681 ; tracked by [TRT-848](https://issues.redhat.com//browse/TRT-848)
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
Example failing job: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-azure-sdn-upgrade/1625040515592359936
Since this merged, azure micro upgrades are failing with the drop-icmp container crashlooping with errors like this;
```
2023-02-13T11:33:43.533651259Z + touch /var/run/add_iptables.sh
2023-02-13T11:33:43.536071373Z + chmod 0755 /var/run/add_iptables.sh …
```
=> Revert "OCPBUGS-5842: Use pods oc vs host"

bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml, bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
The OVN-Kubernetes feature will be enabled whenever the `conf.DisableMultiNetwork` knob is disabled.
Manually testing deploying this PR w/ the following YAML gets us two pods interconnected via this cluster-wide logical switch on upcoming openshift-4.13:
```yaml
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
name: flatl2
spec:
config: '{                                                                           
"cniVersion": "0.4.0",
"name": "flatl2",
"netAttachDefName": "default/flatl2",
"topology": "layer2",
"type": "ovn-k8s-cni-overlay",                                          
"subnets": "192.168.100.0/24",                                                          
"logFile": "/var/log/ovn-kubernetes/ovn-k8s-cni-overlay.log",           
"logLevel": "5", …
```
=> ovn-k, multi-homing: enable the feature

hack/run-locally.sh
when working with run-locally.sh on new a new cluster, if that /tmp/env.sh file has not been removed, it will try to use it again and the script hangs waiting for something that will never show up. The 'oc' command to create it from scratch is not overly time consuming, so just run it every time.
=> always create env.sh when run_vs_existing_cluster

pkg/util/proxyconfig/no_proxy.go
The Azure VIP 168.63.129.16 is needed for communication to Azure platform resources [1].
In the case of StackCloud, we need to add `armEndpoint` so cluster nodes do not communicate with Stack Hub API through proxy.
[1] https://learn.microsoft.com/en-us/azure/virtual-network/what-is-ip-address-168-63-129-16
=> OCPBUGS-5559: add default noProxy config for Azure

bindata/network/additional-networks/crd/001-crd.yaml
The OverlappingRangeIPReservation CRD was missing the podref field. Because of this, an issue occurs when the ip-reconciler code from whereabouts get executed, where the ip-reconciler will incorrectly view a pod as not alive, and consequently incorrectly delete the OverlappingRangeIPReservation object from kubernetes.
I updated the CRD to include the podref field.
Signed-off-by: nicklesimba [simha.nikhil@gmail.com](mailto:simha.nikhil@gmail.com)
=> OCPBUGS-5953: Backport Added missing API field podref to OverlappingRangeIPReservation CRD [Backport 4.12]

pkg/network/additional_networks.go
Error message Failed to Unmarshal RawCNIConfig showed the raw byte output which is not very helpful in the status conditions of the network.operator (it's not human readable). Convert the output to its string representation.
=> Jira OCPBUGS-7774: Print RawCNIConfig in its string representation

manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/image-references
This PR flips ovn-kubernetes over to use RHEL9-based container images which include OVS 3.1. This brings us the following important fixes:
- Support for custom tunnel options (eg, NAT-T) for https://issues.redhat.com/browse/SDN-3221
- ovsdb-server writing snapshots in a separate thread for https://issues.redhat.com/browse/OCPBUGS-6730
=> OCPBUGS-6730, SDN-3221: ovn-kubernetes: use RHEL9-based images

bindata/network/ovn-kubernetes/common/alert-rules.yaml
This adds a prometheus alert rule for generating alert for ovnkube_resource_retry_failures_total counter when this keeps happening on cluster over 10 mins period.
Depends on https://github.com/ovn-org/ovn-kubernetes/pull/3314/
=> Add ovnk alert for resource retry failure

bindata/network/additional-networks/crd/001-crd.yaml
The OverlappingRangeIPReservation CRD was missing the podref field. Because of this, an issue occurs when the ip-reconciler code from whereabouts get executed, where the ip-reconciler will incorrectly view a pod as not alive, and consequently incorrectly delete the OverlappingRangeIPReservation object from kubernetes.
I updated the CRD to include the podref field.
Signed-off-by: nicklesimba [simha.nikhil@gmail.com](mailto:simha.nikhil@gmail.com)
=> OCPBUGS-5954: Backport Added missing API field podref to OverlappingRangeIPReservation CRD

pkg/names/names.go, pkg/network/ovn_kubernetes.go, pkg/network/render.go, pkg/network/render_test.go
- only the mask can change and must become smaller (allowing for more
ip addresses across the entire cluster)
- only supported for OVNKuberentes
=> Allow cidr expansion

bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Cluster manager now controls subnet allocation.
Migrate subnet alerts to use new cluster manager metrics. 
This PR depends on cluster manager being available downstream.
/cc
/hold
=> SDN-3730: OVN IC: migrate master alerts to cluster manager

bindata/network/ovn-kubernetes/common/alert-rules.yaml
OVS vswitchd and kernel module talk via a full duplex link comms using the netlink socket API. Reciever requires a buffer. Buffer overflow will cause packet loss.
Overflows can occur if node is under extreme load and numerous userspace flow lookups. It may also occur if OVS vswitchd is malfunctioning.
=> SDN-3597: OVN-K alerts: add OVS overflow alerts

pkg/names/names.go, pkg/network/ovn_kubernetes.go
the ability to toggle hybrid overlay has been added to ovn-kubernetes, make the cno automatically rollout changes using an annotation on the daemonsets
=> use annotation on the daemonset to update hybrid overlay

bindata/cloud-network-config-controller/managed/controller.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
This duplicates the following funcionality of HyperShift control-plane operator:
https://github.com/openshift/hypershift/blob/main/support/config/deployment.go#L264-L265
https://hypershift-docs.netlify.app/how-to/distribute-hosted-cluster-workloads/
I will work on [nodeSelector](https://github.com/openshift/hypershift/blob/main/support/config/deployment.go#L255) implementation in CNO as a follow up PR.
/cc @jcaamano @zshi-redhat @enxebre @csrwng
=> OCPBUGS-8692: HyperShift: Set affinity, tolerations and co-location for all hcp resources created by CNO

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml, pkg/network/ovn_kubernetes_test.go
- Set healthz-bind-address to 0.0.0.0:10256 for ovnk to match what we have in SDN
- Pass POD_NAME to ovnkube node for node healthz server checks (this goes hand in hand with https://github.com/ovn-org/ovn-kubernetes/pull/3469)
closes #OCPBUGS-9931
=> OCPBUGS-9931: Enable configuration of node healthz server on ovnkube

pkg/network/render_test.go
- use a smaller mask in TestDisallowShrinkingClusterNetworkCIDRMaskForSDN to actually reflect the name of the test case
- add new test case to verify hostPrefix cannot be changed for OVN
- rename existing test case to check hostPrefix cannot be changed to indicate it's done with SDN
=> add/update some UTs around clusternetwork change

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml, pkg/network/ovn_kubernetes_test.go
4.13 backport of https://github.com/openshift/cluster-network-operator/pull/1715:
- Set healthz-bind-address to 0.0.0.0:10256 for ovnk to match what we have in SDN
- Pass POD_NAME to ovnkube node for node healthz server checks (this goes hand in hand with https://github.com/ovn-org/ovn-kubernetes/pull/3469)
closes #OCPBUGS-9926
=> [release-4.13] OCPBUGS-9926: Enable configuration of node healthz server on ovnkube

bindata/network/ovn-kubernetes/common/ipsec.yaml
Point libreswan to proper nss location
OVS 3.1 / libreswan changed default location where nss db is.  The certificate for the node and CA are created, just not where OVNK looks for them.   
Fixes https://issues.redhat.com/browse/OCPBUGS-8707
=> OCPBUGS-8707: Point libreswan to proper nss location

bindata/network/additional-networks/crd/001-crd.yaml
The OverlappingRangeIPReservation CRD was missing the podref field. Because of this, an issue occurs when the ip-reconciler code from whereabouts get executed, where the ip-reconciler will incorrectly view a pod as not alive, and consequently incorrectly delete the OverlappingRangeIPReservation object from kubernetes.
I updated the CRD to include the podref field.
Signed-off-by: nicklesimba [simha.nikhil@gmail.com](mailto:simha.nikhil@gmail.com)
=> OCPBUGS-5955: Backport Added missing API field podref to OverlappingRangeIPReservation CRD

bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
The two alerts highlight connectivity problems
between OVN-K master and NB DB, NB DB and northd,
northd and SB DB and finally SB DB to OVN-K
master.
Networking is a critical component for a
functioning cluster, and without connectivity
between the aforementioned OVN components,
networking can be degraded. Critical
severity correctly highlights the severity
and allows SREs or cluster admins to
investigate.
/cc @npinaeva
=> Set OVN-K north/south bound stale alerts severity to critical

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml, pkg/network/ovn_kubernetes_test.go
4.11 backport for:
- Set healthz-bind-address to 0.0.0.0:10256 for ovnk to match what we have in SDN
- Pass POD_NAME to ovnkube node for node healthz server checks (this goes hand in hand with https://github.com/ovn-org/ovn-kubernetes/pull/3469)
closes #OCPBUGS-10487
=> [release-4.11] OCPBUGS-10487: Enable configuration of node healthz server on ovnkube

bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
This is a followup to https://github.com/openshift/cluster-network-operator/pull/1715
POD_NAME is now required for ovnkube-node, it was missing for managed deployments.
Without it ovnkube-node won't start in hypershift.
/cc @ricky-rav
=> OCPBUGS-10649: HyperShift: Add POD_NAME env to ovnkube-node

manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/image-references
Now that we're building the unsuffixed images with RHEL9 we can move back to them.
=> ovn-kube: move back to unsuffixed RHEL9 images

bindata/network/multus/002-rbac.yaml, bindata/network/multus/multus.yaml
Fix tier label - it's not needed to run the whereabouts-reconciler downstream
Remove privileged security Context - elevated privileges are not needed to run the whereabouts-reconciler downstream
Retrieve node name from the downward API - this is needed to accomodate a recent bugfix in the whereabouts-reconciler
Grant multus clusterrole the right to get nodes - this is needed to accomodate the same bugfix in the whereabouts-reconciler
=> Fix tier label, privileged, HOSTNAME/NODENAME in whereabouts reconciler 

bindata/network/openshift-sdn/sdn.yaml
The -a (--argument) flag is deprecated in favor of --template. It is currently causing a warning message. Fix that:
+ oc observe pods -n openshift-sdn --listen-addr= -l app=sdn -a '{ .status.hostIP }' -- /var/run/add_iptables.sh Flag --argument has been deprecated, and will be removed in a future release. Use --template instead.
=> OCPBUGS-7777: use --template instead of -a for 'oc observe'

bindata/network/ovn-kubernetes/common/alert-rules.yaml
Add the runbook url for OVNKubernetesControllerDisconnectedSouthboundDatabase alert
/hold
depends on: https://github.com/openshift/runbooks/pull/68 
=> SDN-3444: Add runbook url for SBDB connectivity alert

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
konnectivity certs were split out in hypershift: https://github.com/openshift/hypershift/pull/1891
Adapt the proxy to use the new cert.
Additionally make the files read-only.
=> OCPBUGS-9964: Split out konnectivity certs

bindata/network/multus/002-rbac.yaml, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
This adds a new clusterrolebinding for the cluster-readers group
=> OCPBUGS-9174: The cluster-readers group should be able to get net-attach-defs

bindata/network/multus-admission-controller/admission-controller.yaml, pkg/network/hypershift.go, pkg/network/multus_admission_controller.go
This PR changes pod security context of `multus-admission-controller` to run with a specific user ID when under Hypershift management.
Instead of duplicating code from Hypershift CPO to detect management cluster capabilities https://github.com/openshift/hypershift/blob/9d04882e2e6896d5f9e04551331ecd2129355ecd/support/capabilities/management_cluster_capabilities.go#L102-L109 (which possibly requires additional permissions assigned to CNO service account), user ID to run with is passed from Hypershift as an env variable.
=> OCPBUGS-10647: multus-admission-controller should not run as root under Hypershift

bindata/network/multus/002-rbac.yaml, bindata/network/multus/multus.yaml, pkg/network/multus_ipam_test.go
Backport changes to whereabouts reconciler
Clean cherry-picks:
~~~
[akaris@linux cluster-network-operator (OCPBUGS-11424)]$ git diff downstream/release-4.14 -- bindata/network/multus/multus.yaml
[akaris@linux cluster-network-operator (OCPBUGS-11424)]$ 
~~~
=> [release-4.13] OCPBUGS-11424: Backport changes to whereabouts reconciler

bindata/allowlist/daemonset/daemonset.yaml
This issue does not allow the allowlist controller to update the sysctl allowlist file of the nodes.
=> OCPBUGS-11046: Fix allowlist ds template

pkg/controller/connectivitycheck/connectivity_check_controller.go, pkg/controller/connectivitycheck/connectivity_check_template.go
This would make connectivitycheck controller to use new library-go api so that stale checks objects are removed automatically as part of controller sync.
=> OCPBUGS-1341: Enhance check controller to remove old check objects

bindata/allowlist/daemonset/daemonset.yaml, pkg/controller/allowlist/allowlist_controller.go
The allowlist controller was not updating the sysctl allowlist file on the nodes. The reconciliation mechanism didn't show any errors or retries. This PR addresses this by:
1. Improving the logging on the controller.
2. Do not return success if the list of pods of the daemonset is empty while checking its ready status.
3. Change the priority class name of the daemonset. The previous name does not exist.
=> OCPBUGS-11046: fix reconciliation process of the allowlist controller

bindata/network/ovn-kubernetes/common/007-rbac-cluster-reader.yaml
API group "k8s.ovn.org" should be included to cluster-reader role. That group has the following resources:
- EgressFirewall
- EgressIP
- EgressQoS
=> [release-4.14] OCPBUGS-11550: AUTH: update cluster-reader to include k8s.ovn.org

pkg/apply/apply.go, pkg/apply/fieldmanager.go, vendor/k8s.io/client-go/util/csaupgrade/OWNERS, vendor/k8s.io/client-go/util/csaupgrade/upgrade.go, vendor/modules.txt
Previous to 4.11, we used client side update operations with
a manager called 'cluster-network-operator', however
following 4.11, we changed the field manager name
and changed to SSA ("Apply" operation), without
considering the previous field manager we used to use.
This can cause duplicate field managers managing
different fields and we encountered a scenario
where our SSA field manager was unable to drop a
field because the depreciated field manager owned and
preserved the field.
This patch removes the depreciated field manager
regardless of the operation it used previously.
Best reviewed per commit.
=> OCPBUGS-8070: Depreciate legacy field manager

bindata/kube-proxy/kube-proxy.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/network-metrics/001-daemonset.yaml, bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
TLS_RSA_WITH_AES_128_CBC_SHA256 does not support Perfect Forward Secrecy (PFS) and can potentiall create compliance issues. Remove it.
JIRA: https://issues.redhat.com/browse/OCPBUGS-12795
=> [release-4.10] OCPBUGS-12795: remove TLS_RSA_WITH_AES_128_CBC_SHA256 cipher

pkg/controller/allowlist/allowlist_controller.go, pkg/controller/operconfig/operconfig_controller.go
The allowlist and operconfig reconcilers are running too often, which significantly drives up the cluster-network-operator kube-apiserver requests.
The allowlist controller creates a watcher that triggers the reconciler for any configmap change in any namespace. The first thing the reconciler does is a GET request for the 1 configmap it manages to check existence, creating it if it doesn't already exist. The second thing is to exit if the object being reconciled is not the configmap it manages. This results in the reconciler being run almost constantly, up to a few thousand times per hour, with a configmap GET request every time. By changing the controller to use a cmInformer to limit the watcher to a specific namespace, as is done with other controllers watching configmaps, the …
=> OCPBUGS-11565: High API requests due to allowlist and operconfig reconcilers running too often

bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml, hack/dpu-mode.yaml, hack/hardware-offload-config.yaml, pkg/bootstrap/types.go, pkg/controller/operconfig/operconfig_controller.go, pkg/network/kube_proxy.go, pkg/network/kube_proxy_test.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/network/render.go
Removed the NodeMode from the dpu-mode config map. This was done because the design has changed from using a cluster wide node mode to using node labels to identify Full, DPU Host, DPU, and Smart NIC nodes in the cluster.
The node labels can be overridden from the default values by using the config map. The resource-name is mandatory field of the config map and is needed for DPU Host and Smart NIC nodes to support the management port feature in OVN-K.
An additional daemonset is rendered if there is Smart NIC nodes in the cluster similarly with the DPU Host nodes.
=> OCPBUGS-12856: Support Device Plugin Resources For Smart NIC and DPU Hosts

go.mod, go.sum, pkg/controller/operconfig/cluster.go, pkg/controller/operconfig/operconfig_controller.go, pkg/controller/statusmanager/pod_status.go, pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go, pkg/operator/operator.go, vendor/modules.txt, vendor/sigs.k8s.io/controller-runtime/alias.go, vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go, vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/lazyrestmapper.go, vendor/sigs.k8s.io/controller-runtime/pkg/config/config.go, vendor/sigs.k8s.io/controller-runtime/pkg/config/doc.go, vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/doc.go, vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/register.go, vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/types.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go, vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go, vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go, vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go
This PR introduces two changes to:
- Make the Operator/ClusterOperator degraded on panic if any of the controllers crashes
- Do not set the Operator as available if the network config status is not set
I am not sure if this could be done better but I am open to suggestions, CNO sets the `Available` condition once it is done deploying all of the pods, I added an additional condition that it also has to wait for the config to get updated.
=> OCPBUGS-5027: Make the operator degraded on panic

bindata/network/ovn-kubernetes/common/pre-puller.yaml, pkg/network/ovn_kubernetes_test.go
Currently the `ovnkube-upgrades-prepuller` daemon set uses the `Always` image pull policy. As a result this pod requires the presence of working image registry server. That is not really needed, and complicates upgrades in environments where the registry is not available at the time this pod runs. To avoid that this patch chages the image pull policy to `IfNotPresent`.
Related: https://issues.redhat.com/browse/OCPBUGS-13219
Related: https://issues.redhat.com/browse/MGMT-13733
=> OCPBUGS-13219: Use `IfNotPresent` instead of `Always` in OVNK upgrades pre-puller

bindata/network/multus-admission-controller/admission-controller.yaml, pkg/apis/network/v1/operatorpki_types.go, pkg/client/client.go, pkg/controller/operconfig/operconfig_controller.go, pkg/network/multus_admission_controller.go, pkg/network/multus_admission_controller_test.go, pkg/network/render.go, pkg/network/render_test.go
This change introduces -ignore-namespace option to multus-admission-controller.
=> [release-4.10] OCPBUGS-343: Configure ignored namespaces into multus-admission-controller

bindata/network/multus/multus.yaml, pkg/network/multus_ipam_test.go
This adds yaml to start a controller in replacement of the cronjob.
Required for backporting dual stack functionality for Whereabouts
=> OCPBUGS-13067: Whereabouts should implement the reconciliation controller [backport 4.12]

bindata/allowlist/daemonset/daemonset.yaml, pkg/controller/allowlist/allowlist_controller.go
The allowlist controller was not updating the sysctl allowlist file on the nodes. The reconciliation mechanism didn't show any errors or retries. This PR addresses this by:
1. Improving the logging on the controller.
2. Do not return success if the list of pods of the daemonset is empty while checking its ready status.
3. Change the priority class name of the daemonset. The previous name does not exist.
cherry-pick of #1792
=> [release-4.13] OCPBUGS-11750: fix reconciliation process of the allowlist controller

bindata/network/multus-admission-controller/admission-controller.yaml
CNO managed component (multus-admission-controller) to conform to hypershift control plane expectations that All secrets should be mounted to not have global read. change from 420(0644) to 416(0640)
=> OCPBUGS-10937: multus-admission-controller mounts secret with mode 0640

bindata/network/multus/002-rbac.yaml, bindata/network/multus/multus.yaml
Fix tier label.
Remove privileged security Context.
Retrieve node name from the downward API.
Grant multus clusterrole the right to get nodes.
=> OCPBUGS-13067: Fix tier label, privileged, HOSTNAME/NODENAME in whereabouts reconciler [backport 4.12]

bindata/network/multus/multus.yaml
This change removes nodeSelector for architecture in whereabouts daemonset yaml becuase it is no longer for specific architecture, not only for amd64, also arm64.
=> OCPBUGS-14384: Remove nodeSelector for architecture in whereabouts daemonset

pkg/controller/proxyconfig/controller.go, pkg/controller/signer/signer-controller.go
This was preventing us from bumping to golangci-lint 1.53.1 in CI.
=> OCPBUGS-14833: Fixes lint issues

bindata/cloud-network-config-controller/managed/controller.yaml
This PR fixes part of this bug: https://issues.redhat.com/browse/OCPBUGS-11882.
Basically adding this annotation to the pods which contains volumes or emptyDirs will allow the ClusterAutoscaler to drain the pods properly.
=> OCPBUGS-11882: Added another volume to safe-to-evict-local-volume annotation

bindata/network/multus-admission-controller/admission-controller.yaml, pkg/controller/operconfig/mtu_probe.go, pkg/controller/operconfig/mtu_probe_test.go
When the `ControlPlaneTopology` is set to `External` it does not always mean that HyperShift is also enabled. Instead of relying on `ControlPlaneTopology` value, always check if HyperShift is directly enabled.
It looks like in IBM ROKS  `ControlPlaneTopology` is always set to `External` triggering the bug in CNO: https://github.com/openshift/ibm-roks-toolkit/blob/master/assets/cluster-bootstrap/cluster-infrastructure-02-config.yaml#L16
/cc @jcaamano
=> OCPBUGS-14714: Do not rely on ControlPlaneTopology do determine if running in HyperShift

bindata/network/multus/multus.yaml
This change adds nodeSelector to wherebouts reconciler to make consistency among multus related daemonset.
=> OCPBUGS-15138: Add kubernetes.io/os nodeSelector to wherebouts reconciler DS

bindata/network/ovn-kubernetes/common/001-crd.yaml, bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml
Adds the AdminPolicyBasedExternalRoute CRDs and includes the RBAC verbs for controllers.
Requires this [PR](https://github.com/ovn-org/ovn-kubernetes/pull/3462) to be merged before this one goes ahead.
FYI @trozet
=> [SDN-2484] Add support for AdminPolicyBasedExternalRoute CRD and controller's RBAC

bindata/cloud-network-config-controller/common/002-rbac.yaml
Necessary for https://github.com/openshift/cloud-network-config-controller/pull/102 to access the cluster infrastructure object
/assign @kyrtapz 
/cc @jcaamano
=> CCO-356: Add Infrastructures permission to CNCC cluster role

bindata/network/multus/multus.yaml
CNO uses it to track whether updates to the daemonset have been done or
not. If not set, CNO won't set the overall operator version to the
target upgrade and the upgrade won't complete.
=> OCPBUGS-15282: Add release version annotation to whereabouts-reconciler

bindata/network/multus/multus.yaml
Now that the binary is being dynamically compiled downstream, the binary must match the RHEL version of RHCOS because it is copied to the host.
=> Change rhel7/8 to rhel8/9

bindata/network/ovn-kubernetes/common/002-rbac.yaml, bindata/network/ovn-kubernetes/common/007-rbac-cluster-reader.yaml
It shouldn't change the object, therefore get, list, watch should be enough.
Initally added here https://github.com/openshift/cluster-network-operator/pull/1765
Without this change non-OVN-IC deployments have errors like
```
current.log:2023-06-30T13:10:51.027146349Z E0630 13:10:51.027130    2903 reflector.go:148] github.com/openshift/ovn-kubernetes/go-controller/pkg/crd/adminpolicybasedroute/v1/apis/informers/externalversions/factory.go:116: Failed to watch *v1.AdminPolicyBasedExternalRoute: failed to list *v1.AdminPolicyBasedExternalRoute: adminpolicybasedexternalroutes.k8s.ovn.org is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-node" cannot list resource "adminpolicybasedexternalroutes" in API group "k8s.ovn.org" at the cluster scope
```
=> OCPBUGS-15544: Add adminpolicybasedexternalroutes rights for ovnkube-node.

bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Add logic to pick the ovn-k8s-cni-overlay binary from the right source directory.
=> OCPBUGS-15962: Add logic to pick the ovn-k8s-cni-overlay binary from the right dir

bindata/allowlist/daemonset/daemonset.yaml
To support the workload partitioning we need to add this required annotations
(https://github.com/openshift/enhancements/pull/703).
=> OCPBUGS-15794: fix: add missing annotation for workload partitioning

bindata/network/ovn-kubernetes/common/001-crd.yaml, bindata/network/ovn-kubernetes/common/002-rbac.yaml, bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml, bindata/network/ovn-kubernetes/common/007-rbac-cluster-reader.yaml, bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/microshift/clusterrole.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes_test.go
This PR cherry-picks changes from https://github.com/openshift/cluster-network-operator/pull/1844 since Ori is out and there were conflicts. 
I resolved conflicts in:
- `bindata/network/ovn-kubernetes/common/001-crd.yaml`
- `bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml`
Since https://github.com/ovn-org/ovn-kubernetes/pull/3567 got downstream [here](https://github.com/openshift/ovn-kubernetes/pull/1718) this PR should be ready to go in as well.
=> Enable EgressService controller

bindata/network/openshift-sdn/sdn.yaml
Add logic to pick the sdn shim binaries from the correct source directories based on host os release. This change is required so that we pick the right binary based on the base OS version to not fail glibc linkage for FIPS.
=> OCPBUGS-15977: Add logic to pick the openshift-sdn shims from right directories

pkg/util/proxyconfig/no_proxy.go, pkg/util/proxyconfig/no_proxy_test.go
The CNO uses machineCIDR and machineNetwork CIDR parameters in install config of the cluster config map object to render proxy/cluster status. In some cases, machineCIDR contains 0.0.0.0/0 which makes CNO to render noProxy with 0.0.0.0/0 in proxy/cluster status. This is invalid config and leads to installation fails at times. This PR ensures 0.0.0.0/0 is not rendered into proxy/cluster status.
=> OCPBUGS-15918: Skip rendering 0.0.0.0/0 for cluster proxy status

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Add --enable-multi-external-gateway flag, since we disabled this feature on ovn-k by default. Don't enable this feature for microshift.
=> OCPBUGS-15544: Enable multi-external-gateway feature by default for managed and hosted clusters

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes_test.go
For the live-migration ovn-kuberntes features [1] CNO need to pass the namespace and name of the dns resolver service.
[1] https://github.com/ovn-org/ovn-kubernetes/pull/3478
=> ovn-k: Configure dns service namespace and name

pkg/names/names.go, pkg/network/ovn_kubernetes.go
This is a backport of https://github.com/openshift/cluster-network-operator/pull/1709 
the 4.12 cherry-pick did not apply cleanly because of https://github.com/openshift/cluster-network-operator/commit/9d1ccf753f6b62460a73a663a042d168dcbccec6 in names.go but the rest of the cherry-pick applied without issue 
the ability to toggle hybrid overlay has been added to ovn-kubernetes, make the cno automatically rollout changes using an annotation on the daemonsets
=> [release-4.12 ] OCPBUGS-11217:use annotation daemonset to update hybrid overlay

bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Add logic to pick the ovn-k8s-cni-overlay and openshift-sdn binaries from the right source directories.
=> [release-4.9] OCPBUGS-16312: pick the ovn-k8s-cni-overlay and openshift-sdn shims from right directories 

pkg/controller/allowlist/allowlist_controller.go
The allowlist controller was not updating the sysctl allowlist file on the nodes. The reconciliation mechanism didn't show any errors or retries. This PR addresses this by:
Improving the logging on the controller.
Do not return success if the list of pods of the daemonset is empty while checking its ready status.
Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/1793
=> OCPBUGS-16142: fix reconciliation process of the allowlist controller

bindata/network/multus-admission-controller/001-service.yaml
We are preventing/deleting any webhook that runs in a hosted cluster and targets a service running in the management cluster here: https://github.com/openshift/hypershift/pull/2775
This PR adds a label to the `multus-admission-controller` service to ensure `multus.openshift.io` webhook doesn't get deleted.
Fixes #[HOSTEDCP-1063](https://issues.redhat.com/browse/HOSTEDCP-1063)
=> HOSTEDCP-1063: allow webhooks in hosted clusters to reach multus-admission-controller service

bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Add logic to pick the ovn-k8s-cni-overlay and openshift-sdn binaries from the right source directories.
=> [release-4.8] OCPBUGS-16685: pick the ovn-k8s-cni-overlay and openshift-sdn shims from right directories

bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Add logic to pick the ovn-k8s-cni-overlay and openshift-sdn binaries from the right source directories.
=> [release-4.7] OCPBUGS-16686: pick the ovn-k8s-cni-overlay and openshift-sdn shims from right directories

bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Add logic to pick the ovn-k8s-cni-overlay and openshift-sdn binaries from the right source directories.
=> [release-4.6] OCPBUGS-16687: pick the ovn-k8s-cni-overlay and openshift-sdn shims from right directories

pkg/controller/allowlist/allowlist_controller.go, pkg/controller/clusterconfig/clusterconfig_controller.go, pkg/controller/configmap_ca_injector/controller.go, pkg/controller/egress_router/egress_router_controller.go, pkg/controller/infrastructureconfig/infrastructureconfig_controller.go, pkg/controller/ingressconfig/ingressconfig_controller.go, pkg/controller/operconfig/operconfig_controller.go, pkg/controller/pki/pki_controller.go, pkg/controller/proxyconfig/controller.go, pkg/controller/signer/signer-controller.go, pkg/controller/statusmanager/pod_watcher.go, pkg/controller/statusmanager/status_manager.go, pkg/operator/operator.go
`utilruntime.PanicHandlers` is a global slice of fuctions that can be ran when a panic occurs. One of the places this happens is:
https://github.com/openshift/cluster-network-operator/blob/db57a477b10f517bc4ae501d95cc7b8398a8755c/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go#L157 If the panic handlers are ran in a http handler any panics that happen will get supressed: https://github.com/golang/go/blob/49d42128fd8594c172162961ead19ac95e247d24/src/net/http/server.go#L1865-L1870
This means CNO cannot just add a `panic()` to a handler in utilruntime.PanicHandlers because it can result in it setting the degraded status without exiting the process.
Use `utilruntime.HandleCrash` with an additional handler for each reconciler to avoid affecting other components and …
=> OCPBUGS-15945: Stop using utilruntime.PanicHandlers to handle reconciliation panics

bindata/network/multus/multus.yaml
It changes to invoke entrypoint.sh instead of ip-control-loop directly to run corresponding container base OS version binary.
=> Bug 16136: change whereabouts ip reconciler exec

manifests/02-cncc-credentials.yaml
xref: [CCO-294](https://issues.redhat.com//browse/CCO-294)
This PR switches from using a blanket role binding to the more granular individual permissions.  A full list can be found here: https://learn.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations
=> CCO-294: Switch azure credentials request to use explicit permissions

bindata/network/ovn-kubernetes/common/002-rbac.yaml, bindata/network/ovn-kubernetes/common/ipsec.yaml
CertificateSigningRequest is a cluster scoped resource and it is not great to have the permission to delete it.
CSRs are garbage collected so instead of removing the previous one, always create it with a randomized name.
=> OVN-Kubernetes ipsec: create the CSR with a random name

pkg/controller/allowlist/allowlist_controller.go
The daemonset has a BestEffort QoS which  means that in some cases, the pods won't ever be scheduled.
This also prevents unwanted retries when one or more pods are not ready due to issues with the cluster.
https://issues.redhat.com/browse/OCPBUGS-15818 (BestEffort Daemonset cni-sysctl-allowlist-ds)
When there are issues with the cluster such as in https://issues.redhat.com/browse/OCPBUGS-15284, some pods are stuck in the terminating state which affects subsequent reconciliations of the allowlist controller.
=> OCPBUGS-16019: prevent creation of multiple cni-sysctl-allowlist-ds pods

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
ovnkube-node creates and reads `certificatesigningrequests`, there is no need for it to have the update permission.
Upstream docs: https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#authorization
/cc @jcaamano
=> Remove certificatesigningrequests/update permission from ovnkubenode

bindata/network/ovn-kubernetes/managed/common/004-config.yaml
At ovn-k managed config template both control plane and workers should have the same join subnet configuration.
Closes: https://issues.redhat.com/browse/OCPBUGS-17964
=> OCPBUGS-17964: ovn-k, managed: Align join subnet configuration

pkg/controller/connectivitycheck/connectivity_check_controller.go, pkg/controller/connectivitycheck/connectivity_check_template.go
Backport of relevant 4.14 commits 0d78f7c8b33728435a96cfc27e2dad477887fb58 and 09086a70c51cebba3db454e26cd23238697a7883.
No Conflicts.
=> [release-4.13] OCPBUGS-17721: Enhance check controller to remove old check objects

bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml, pkg/controller/operconfig/operconfig_controller.go, pkg/network/ovn_kubernetes.go
CNO will detect an upgrade scenario from 4.13->4.14. In this case, IP Forwarding is set in the API to Global mode. This is desired to not break users during upgrade who have features enabled that rely on this behavior (like Metal LB). In 4.13 IP Forwarding is set via MCO. During upgrade, CNO upgrades first and will detect the upgrade, and enable global IP forwarding. Upon node reboot during upgrade, MCO will remove the forwarding files, but the ovnkube-node container will re-enable forwarding at start up.
For non 4.13->4.14 upgrade scenarios, whatever the setting in the API is will be used (by default this is restricted forwarding).
=> OCPBUGS-16051, OCPBUGS-3176: Enables IP Forwarding config in CNO

bindata/cloud-network-config-controller/managed/controller.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, pkg/bootstrap/types.go, pkg/network/cloud_network.go, pkg/network/multus_admission_controller.go, pkg/network/ovn_kubernetes.go, pkg/platform/hypershift.go
This PR is to back-port change https://github.com/openshift/cluster-network-operator/pull/1770 to release-4.13 branch.
=> [release-4.13] OCPBUGS-13920: add Hypershift release-image annotation to multus

manifests/02-cncc-credentials.yaml
Adds additional missing permission `Microsoft.Network/loadBalancers/backendAddressPools/join/action`.
OCPBUGS-17677
/cc @huiran0826
=> OCPBUGS-17677: [Azure]CNCC failed to assign egressIP to NIC for Azure Workload Identity Cluster

pkg/controller/statusmanager/pod_status.go, pkg/controller/statusmanager/pod_watcher.go, pkg/controller/statusmanager/status_manager.go, pkg/network/ovn_kubernetes.go
During an upgrade from non-IC to IC, the CNO status logic looks up a well-known configmap that indicates whether the an upgrade to IC is ongoing in order not to report the new operator version (4.14) until the second and final phase of the IC upgrade is done.
The following corrections are needed:
- CNO shouldn't report a new version if IC configmap can't be retrieved for whatever reason, as suggested in a review to the CNO PR that enabled IC support: https://github.com/openshift/cluster-network-operator/pull/1874#pullrequestreview-1560616992
- looking up the key "ongoing-upgrade" inside the IC configmap is enough; checking for its value to be "true" is not correct, since after code reviews it was decided not to set the value to "true", but to set it to an empty string;
- (optimization) …
=> OCPBUGS-17916: Fix IC configmap lookup in pod_status.go

pkg/network/kuryr.go, pkg/network/kuryr_test.go, pkg/platform/openstack/kuryr_bootstrap.go
Since #1952 `network.Render` is no longer supplied with operConfig used later, but a copy of it. This means that MTU set by Kuryr's render phase won't be used for setting the Network.Status and will lead to panic.
We have this issue because for Kuryr default MTU is detected on bootstrap phase and there's no fixed value.
This commit solves this by making "0" a default value for Kuryr's MTU. Having 0 means that Kuryr will attempt to autodetect the MTU. Moreover the MTU on KuryrConfig will now be set on bootstrap phase, so update of the OperConfig done after the bootstrap phase will make sure to update it too.
=> OCPBUGS-18517: Kuryr: Set MTU on Bootstrap, not Render phase

bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-master.yaml, pkg/network/ovn_kubernetes.go
northd has an option to sleep for a short amount of time after processing changes from NB/SB that allows it to trade off a bit of latency for a lot of CPU savings. Since events from NB come frequently during scale tests northd doesn't have a lot of time to sleep. Until we have more incremental processing, most of that CPU time is burned just recalculating things that haven't changed, so it's mostly wasted.
Letting northd sleep has been shown in density-light and density-cni 120 node scale tests to have almost no adverse effect on P99 PodReady times, but a huge improvement in CPU utilization.
Upstream equivalent is https://github.com/ovn-org/ovn-kubernetes/pull/3877
=> OCPBUGS-18676: ovnkube: set northd backoff-interval and use a single thread to save CPU

bindata/kube-proxy/kube-proxy.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/network-metrics/001-daemonset.yaml, bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml
During an internal audit conducted by one of our customers in OCP, it was discovered that the openshift-sdn component, specifically on port 9101, has exposed certain cipher suites that are considered weak. We have identified the following weak ciphers that are currently being accepted:
[TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256](https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256/)
[TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256](https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256/)
Reported-at: https://issues.redhat.com/browse/OCPBUGS-15201
=> OCPBUGS-15201: Disable weak SSH cipher suites

bindata/network/ovn-kubernetes/managed/common/004-config.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/common/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml, pkg/network/ovn_kubernetes_test.go
The intent of this PR is to split out the logs for libovsdb client out of the ovnkube-node logs,
so must-gather collection has a lot less data to deal with.
Modifications to must-gather gather-netwotk-logs, as well as sos-report must be in place in
order to ensure these new log files are not left behind.
**TODO**:
~~- make sure we are happy with the name of the logs chosen~~
~~- consider using non defaults (i.e. make explicit) values for aging, number of backups and max-size. Their defaults are kept here:   https://github.com/openshift/ovn-kubernetes/blob/f05d79a6080efe659ad6445ccd2a5636cfabf172/go-controller/pkg/config/config.go#L78-L80~~
~~- what if pod/container restart? Maybe logs need to be in a volume-mount? Maybe co-locate it with the dbs?~~
=> separate libovsdblogs from main ovnkube-master logs

bindata/network/ovn-kubernetes/managed/common/004-config.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/common/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml, pkg/network/ovn_kubernetes_test.go
The intent of this PR is to split out the logs for libovsdb client out of the ovnkube-node logs,
so must-gather collection has a lot less data to deal with.
Modifications to must-gather gather-netwotk-logs, as well as sos-report must be in place in
order to ensure these new log files are not left behind.
=> [release-4.14] OCPBUGS-19481: separate libovsdblogs from main ovnkube-master

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml, bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml, bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml, pkg/controller/statusmanager/status_manager.go, pkg/network/ovn_kubernetes_test.go
OVN-Kubernetes no longer requires nodes and pods permissions with: https://github.com/ovn-org/ovn-kubernetes/pull/3773
Removed the endpoints creation permission as it was never used downstream.
Removed pod deletion permission from control plane.
Modified status manager garbage collector to avoid removing stale objects from "rbac.authorization.k8s.io" during upgrade. This means that if there is an RBAC file no longer rendered in CNO it will only be removed once the upgrade completes. Using the new names keeps both RBACs during upgrade.
=> Limit OVN-Kubernetes permissions

bindata/network-diagnostics/network-check-source.yaml, bindata/network-diagnostics/network-check-target.yaml, bindata/network/openshift-sdn/controller.yaml, bindata/network/ovn-kubernetes/common/ipsec-containerized.yaml, bindata/network/ovn-kubernetes/common/ipsec-host.yaml, bindata/network/ovn-kubernetes/common/pre-puller.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml
- Replace deprecated `beta.kubernetes.io/os` node selector with `kubernetes.io/os`
https://kubernetes.io/docs/reference/labels-annotations-taints/#beta-kubernetes-io-os-deprecated
- Add linux node selector to openshift-sdn/sdn-controller daemonset
=> OCPBUGS-18114: Update node selector in various YAMLs

bindata/network/ovn-kubernetes/common/ipsec-host.yaml
now that we depend on systemd
we should not kill pluto
this fixes OCPBUGS-19494
=> OCPBUGS-19494: ipsec: remove preStop from host

bindata/network/multus/multus.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml
RHEL_VERSION isn't present in scos
=> OCPBUGS-19018: use $CPE_NAME to find the OS major version

bindata/network/multus/multus.yaml
This allows multus to set an apiserver filter to only watch pods on its own node. Should reduce memory usage as multus doesn't care about pods on other nodes.
Clusters with ~60,000 pods show multus using around 1.8G of RSS which seems fairly unnecessary.
QE: can be verified by looking at the top of `kube-multus` container logs in multus pods:
```
$ oc logs -n openshift-multus -c kube-multus multus-llgcj | grep "Filtering pod"
2023-09-21T12:44:11Z [verbose] Filtering pod watch for node "ci-op-fvc0qy12-b3a20-dkw5b-worker-b-m7qmq"
```
=> OCPBUGS-19550: multus: set MULTUS_NODE_NAME to filter pods to local node

bindata/network/node-identity/common/node-identity-namespace.yaml, bindata/network/node-identity/common/node-identity-rbac.yaml, bindata/network/node-identity/managed/node-identity-service.yaml, bindata/network/node-identity/managed/node-identity-webhook.yaml, bindata/network/node-identity/managed/node-identity.yaml, bindata/network/node-identity/self-hosted/node-identity-pki.yaml, bindata/network/node-identity/self-hosted/node-identity-webhook.yaml, bindata/network/node-identity/self-hosted/node-identity.yaml, bindata/network/ovn-kubernetes/common/002-rbac-node.yaml, bindata/network/ovn-kubernetes/common/ipsec-containerized.yaml, bindata/network/ovn-kubernetes/common/ipsec-host.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml, pkg/bootstrap/types.go, pkg/controller/configmap_ca_injector/controller.go, pkg/controller/proxyconfig/validation.go, pkg/controller/statusmanager/status_manager.go, pkg/network/node_identity.go, pkg/network/ovn_kubernetes.go, pkg/network/render.go, pkg/platform/platform.go, pkg/util/validation/trustbundle.go
This PR enables the network-identity webhook introduced in ovn-kubernetes.
It is not ovn-kubernetes specific as it is going to be required for multus with different CNIs.
=> OCPBUGS-19648: Network identity: node-specific certificate in ovnkube-node, admission webhook

pkg/network/kuryr.go
PR https://github.com/openshift/cluster-network-operator/pull/1988 introduced a bug causing upgrades to fail, because even when Kuryr MTU was detected from the previous version of the KuryrConfig, CNO would override it to 0. This commit fixes that.
=> OCPBUGS-19377: Kuryr: Fix deriving MTU from previous config

bindata/network/node-identity/common/node-identity-namespace.yaml, bindata/network/node-identity/common/node-identity-rbac.yaml, bindata/network/node-identity/managed/node-identity-service.yaml, bindata/network/node-identity/managed/node-identity-webhook.yaml, bindata/network/node-identity/managed/node-identity.yaml, bindata/network/node-identity/self-hosted/node-identity-pki.yaml, bindata/network/node-identity/self-hosted/node-identity-webhook.yaml, bindata/network/node-identity/self-hosted/node-identity.yaml, bindata/network/ovn-kubernetes/common/002-rbac-node.yaml, bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml, bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml, bindata/network/ovn-kubernetes/common/ipsec-containerized.yaml, bindata/network/ovn-kubernetes/common/ipsec-host.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml, pkg/bootstrap/types.go, pkg/controller/configmap_ca_injector/controller.go, pkg/controller/proxyconfig/validation.go, pkg/controller/statusmanager/status_manager.go, pkg/network/node_identity.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/network/render.go, pkg/platform/platform.go, pkg/util/validation/trustbundle.go
Clean cherry-pick of https://github.com/openshift/cluster-network-operator/pull/1983 and https://github.com/openshift/cluster-network-operator/pull/1982
=> [release-4.14] OCPBUGS-19649: Network node identity: node-specific certificate in ovnkube-node, admission webhook

bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-master.yaml, bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-master.yaml
JIRA: https://issues.redhat.com/browse/OCPBUGS-17391
when the prestop hook executes the ovn-ctl stop... command this causes the containers main script to exit which also propagates to the main container (PID 1) process which exits causing the container to exit. This is not neccessarily a problem except that with recent changes in CRI-O [0] there is some problem with how kubelet views this case. the containers are Exited for crio but seen as Ready from kubelet's perspective. Because of this, the pod gets stuck in Terminating state until it times out (~3m) and then containers will restart.
removing the prestop hook let's the SIGTERM reach the configured trap (example [1]) run which effectively does the same thing as what the prestop hook would have done. This prevents the pod from being …
=> OCPBUGS-17391: remove prestop hooks for northd, sbdbd and nbdb

bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/monitor-control-plane.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/monitor-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-control-plane.yaml
In order to avoid possible issues with SDN during migration from SDN to OVNK, do not use port 9106 for ovnkube-control-plane metrics, since it's already used by SDN. Use a port that is not used by SDN, such as 9108.
This was a point raised while reviewing the IC upgrade enhancement: https://github.com/openshift/enhancements/pull/1409/files#r1335850394
=> OCPBUGS-19705: Use port 9108 for ovnkube-control-plane metrics

pkg/controller/operconfig/operconfig_controller.go
Render has side effects in the passed in operConfig that are reflected later on in the status when it is being updated. This stopped working when the the passed in operConfig was changed to a copy that was not then used when applying the status.
It makes sense to use the updated operConfig for everything that comes after, not just Render, so change that to fix the issue.
Fixes: https://github.com/openshift/cluster-network-operator/pull/1952
=> OCPBUGS-18396: Fix config status MTU migration not being updated

pkg/network/ovn_kubernetes.go
We've seen cases in which an upgrade to 4.14 was being performed on a 4.13 cluster where one node was in a Ready,SchedulingDisabled state. The ovnkube-node instance on that node had been removed and CNO considered ovnkube-node DaemonSet as progressing (5 out 6 instances were available). This completely bypassed the IC upgrade path and no IC configmap was created. 
Let's relax the conditions on when CNO adds the IC configmap, so we can get IC upgrade started in this case too.
=> OCPBUGS-19418: Relax conditions to get IC upgrade started

bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/monitor-control-plane.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/monitor-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-control-plane.yaml
In order to avoid possible issues with SDN during migration from SDN to OVNK, do not use port 9106 for ovnkube-control-plane metrics, since it's already used by SDN. Use a port that is not used by SDN, such as 9108.
Signed-off-by: Riccardo Ravaioli <rravaiol@redhat.com>
(cherry picked from commit 6aee20c73bb94b7b89c15ec6f4b6638d3a18d7c8)
=> OCPBUGS-19747: [release-4.14] Use port 9108 for ovnkube-control-plane metrics

bindata/network/multus/multus.yaml
Also uses `/etc/cni/multus/certs` for certificate storage on host
=> OCPBUGS-19861: Multus per-node certificates should have 24h duration

go.sum, pkg/controller/proxyconfig/validation.go, pkg/platform/hypershift.go, vendor/golang.org/x/net/internal/socks/client.go, vendor/golang.org/x/net/internal/socks/socks.go, vendor/golang.org/x/net/proxy/dial.go, vendor/golang.org/x/net/proxy/direct.go, vendor/golang.org/x/net/proxy/per_host.go, vendor/golang.org/x/net/proxy/proxy.go, vendor/golang.org/x/net/proxy/socks5.go, vendor/modules.txt
When CNO checks proxy readiness it should send the requests through the hosted cluster.
Depends on HyperShift changes here: https://github.com/openshift/hypershift/pull/2974, which merged already.
=> OCPBUGS-14819: HyperShift: Use the local konnectivity proxy when checking proxy readiness

bindata/network/multus/multus.yaml
Also uses `/etc/cni/multus/certs` for certificate storage on host
=> OCPBUGS-19862: Multus per-node certificates should have 24h duration [backport 4.14]

bindata/network/network-metrics/001-daemonset.yaml
I noticed during CI tests that sometimes this component will attempt to start at the same time the CNI is attemting to start.
This can cause multus to return an error during CNI ADD and cause test failures.
Metrics are user facing.
See openshift docs on priority class definitions: https://docs.openshift.com/container-platform/4.13/nodes/pods/nodes-pods-priority.html
=> Network metrics daemon: change priority class to openshift-user-critical

pkg/network/ovn_kubernetes.go
ds name changed and since both ipsec-host and ipsec-containerized are
paired, we can get by getting either
=> OCPBUGS-19918: get ipsecStatus from host daemonset

bindata/network/multus/multus.yaml, pkg/network/multus.go
Otherwise, we have a report of a file not found due to a symlink issue
=> OCPBUGS-20076: Multus should determine kubeconfig path

bindata/network/multus/multus.yaml, pkg/network/multus.go
Otherwise, we have a report of a file not found due to a symlink issue
=> OCPBUGS-20064: Multus should determine kubeconfig path [backport 4.14]

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml, bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
when the prestop hook executes the ovn-ctl stop... command this causes the containers main script to exit which also propagates to the main container (PID 1) process which exits causing the container to exit. This is not neccessarily a problem except that with recent changes in CRI-O [0] there is some problem with how kubelet views this case. the containers are Exited for crio but seen as Ready from kubelet's perspective. Because of this, the pod gets stuck in Terminating state until it times out (~3m) and then containers will restart.
removing the prestop hook let's the SIGTERM reach the configured trap (example [1]) run which effectively does the same thing as what the prestop hook would have done. This prevents the pod from being stuck in Terminating state.
[0] cri-o/cri-o#7168
[1] …
=> [release-4.13] OCPBUGS-19894: remove prestop hooks for northd, sbdbd and nbdb

bindata/network/ovn-kubernetes/common/008-script-lib.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml, pkg/network/ovn_kubernetes_test.go
Clean up a bunch of things that are done for us by other things, or just aren't necessary.
Then move all the common functionality to a bash script library shared between all the containers so we can use the same code from multiple daemonsets. Tip of the hat to Tomo for the ConfigMap trick.
=> OCPBUGS-18089,OCPBUGS-18088: ovnkube: container scripts cleanup

bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
OVK-Kubernetes `ovspinning.go` monitors `/etc/openvswitch/enable_dynamic_cpu_affinity`
cluster-node-tuning-operator enables the feature, so we have to notify that component when the path changs on the host.
=> OCPBUGS-18392: notify when /etc/openvswitch path changes

bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-master.yaml, bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml
Add missing volume mount to ovnkube-node pods while in the single zone phase
=> OCPBUGS-20519: hosted cluster upgrade failure from 4.13 stable to 4.14

bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-master.yaml, bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml
Add missing volume mount to ovnkube-node pods while in the single zone phase
=> [release-4.14] OCPBUGS-20472: hosted cluster upgrade failure from 4.13 stable to 4.14

bindata/network/ovn-kubernetes/common/001-crd.yaml
Depends on this [PR](https://github.com/ovn-org/ovn-kubernetes/pull/3811) from the ovn-kubernetes repository.
@trozet @jcaamano @danwinship PTAL.
=> [ovn-kubernetes] Make APB External Route namespace selector mandatory for a dynamic hop

bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml
Like GENEVE we don't need to conntrack the hybrid overlay VXLAN traffic.
Resolves: https://issues.redhat.com/browse/OCPBUGS-10652
=> OCPBUGS-10652: ovnkube: disable conntrack on hybrid overlay VXLAN ports

bindata/network/multus-networkpolicy/custom-iptables-rules.yaml, bindata/network/multus-networkpolicy/multus-networkpolicy.yaml, pkg/network/multi_network_policy_test.go
MultusNetworkPolicy iptables implementation denies all traffic that is not specified by policy rules. This can bring to some unexpected scenario, especially when working with IPv6.
Unlike ARP in IPv4, Neighbor Discovery Protocol (NDP) uses IP packets to exchange information between peers, so they are affected by iptables rules. In a scenario where a server is the subject of a MultiNetworkPolicy and a client is the only one who can send traffic to the server, the latter should be able to send the neighbor advertisements, otherwise the client will never know the link-layer address of the server.
multus-networkpolicy doc: https://github.com/openshift/multus-networkpolicy/blob/master/docs/configurations.md#add-custom-iptablesip6tables-rules
=> multinetworkpolicy: allow Neighbor Discovery Protocol traffic

bindata/cloud-network-config-controller/managed/controller.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/node-identity/managed/node-identity.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-control-plane.yaml, bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-master.yaml
Added 2 missing labels in the CNO pods on Hypershift context:
- hypershift.openshift.io/hosted-control-plane
- hypershift.openshift.io/control-plane
The `hypershift.openshift.io/hosted-control-plane` label needs to be present to signal the Management Cluster router to fulfil the route.
The `hypershift.openshift.io/control-plane` is needed to mark those pods as part of the ControlPlane avoiding to fall into the serving-component-nodes.
Signed-off-by: Juan Manuel Parrilla Madrid <jparrill@redhat.com>
=> OCPBUGS-19370: Added HCP label to CNO pods

bindata/egress-router/001-deployment.yaml
Before this change, Egress CNI Pod has a QOS
of BestEffort. This means it will utilise CPU
cores that arent Guaranteed to any other pods.
The kubelet prefers to evit pods with this QOS.
If no resource requests a specified, the kubelet
will allocate the default CPU share of 2.
For the worse case scenario, if a node had 1 core, this could end up being ~0.19% CPU time (2/1024*100).
Egress router will consume some CPU to route packets, therefore it seems sensible to give it minimum CPU share and give it QOS class of BURSTABLE.
Tested by replacing CNO and creating a `EgressRouter` CR:
```yaml
apiVersion: network.operator.openshift.io/v1
kind: EgressRouter
metadata:
name: egress-router-test
spec:
addresses: [
{
ip: "192.168.3.10/24",
gateway: "192.168.3.1",
},
]
mode: Redirect
redirect: { …
```
=> OCPBUGS-15817: Egress router: request at least 100 milliCPU

manifests/0000_70_cluster-network-operator_02_rbac.yaml, manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
To be compliant with CIS benchmark rule, network operator should run with separate service account instead of using default
=> OCPBUGS-11179: change CNO to use custom ServiceAccount

bindata/network/node-identity/managed/node-identity.yaml
Set `automountServiceAccountToken` to `false` for hypershift managed `network-node-identity` deployment
From our initial investigation, it seems like this component does not need management cluster access. We were looking at:
https://github.com/openshift/cluster-network-operator/blob/release-4.14/bindata/network/node-identity/managed/node-identity.yaml
For the webhook and approver container: https://github.com/openshift/ovn-kubernetes/blob/release-4.14/go-controller/cmd/ovnkube-identity/ovnkubeidentity.go
For the token minter container: https://github.com/openshift/hypershift/blob/release-4.14/token-minter/tokenminter.go
Addresses https://issues.redhat.com/browse/OCPBUGS-23082
=> OCPBUGS-23082: set automountServiceAccountToken to false for hypershift managed network-node-identity deploy

bindata/network/ovn-kubernetes/common/002-rbac.yaml, bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml, bindata/network/ovn-kubernetes/common/ipsec.yaml
this is the CNO portion of https://github.com/openshift/ovn-kubernetes/pull/1950 and limit the RBAC permissions of ovn-kubernetes
the changes are from 
https://github.com/openshift/cluster-network-operator/pull/1896 
https://github.com/openshift/cluster-network-operator/pull/1928 
https://github.com/openshift/cluster-network-operator/pull/1934
the first two commits applied cleanly leaving the third to have a small conflict because master branch had additional security constraints added  
was able to cleanly bring in https://github.com/openshift/cluster-network-operator/commit/8b5cd5fa892e737287b6bf78ad1091618899668e and https://github.com/openshift/cluster-network-operator/commit/2e3fc8e7a01fc47cb213e77a033564d7babedc8b to address …
=> [release-4.13]SDN-4184: Limit OVN-Kubernetes RBAC permissions

bindata/network/ovn-kubernetes/managed/common/004-config.yaml
On HyperShift hosted cluster we were not enabling the multi-net (or multi-net policy) features; as such, the network attachment definition informers were not started, which caused multi-homed pods from being started in the hosted cluster.
Also enabled the multi-net policy feature depending on the operator configuration, since it was also missing from the configuration.
=> OCPBUGS-22869: hypershift, hosted clusters: enable multi-homing and multi-net features

pkg/controller/configmap_ca_injector/controller.go, pkg/controller/proxyconfig/controller.go, pkg/names/names.go
Mark ownership of the proxy-ca configmaps managed and injected by this operator.  This is later harvested by generated documentation.
/cc @vrutkovs
=> NO ISSUE: add ownership of the proxy-ca

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
Looks like we have 0 tests for APBRoute in CNO, but if you deploy a 4.14 cluster and create APBRoute, you will find its status is empty and logs like
`
W1130 14:58:55.081710 5185 master_controller.go:227] Failed to update AdminPolicyBasedExternalRoutes default status: failed to update AdminPolicyBasedExternalRoutes default status: adminpolicybasedexternalroutes.k8s.ovn.org "default" is forbidden: User "system:ovn-node:ci-ln-f2400f2-72292-sgnts-master-2" cannot update resource "adminpolicybasedexternalroutes/status" in API group "k8s.ovn.org" at the cluster scope
`
Randomly found here https://github.com/openshift/cluster-network-operator/pull/2132/files#r1410561628
Must be related to https://issues.redhat.com/browse/OCPBUGS-22710
=> OCPBUGS-22710: Add apbroute/status patch rights for ovnkube-node to update status

bindata/network/ovn-kubernetes/common/001-crd.yaml, bindata/network/ovn-kubernetes/common/002-rbac-node.yaml, bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
Update APBRoute IP validation.
Depends on https://github.com/ovn-org/ovn-kubernetes/pull/3750
=> SDN-4308: Update status merge for APBRoute and EgressFirewall.

pkg/operator/operator.go
Call SetLogger before adding controller-runtime client to prevent controller-runtime complaining about it after 30 seconds of binaries lifetime. 
https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/log/log.go#L54
JIRA: https://issues.redhat.com/browse/OCPBUGS-23161
=> OCPBUGS-23161:  Set logging for controller-runtime

bindata/network/ovn-kubernetes/common/80-ipsec-master-extensions.yaml, bindata/network/ovn-kubernetes/common/80-ipsec-worker-extensions.yaml, bindata/network/ovn-kubernetes/common/ipsec-host.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml, pkg/bootstrap/types.go, pkg/client/client.go, pkg/names/names.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/platform/platform.go, pkg/util/util.go
This PR ensures IPsec daemonset pod uses IPsec packages installed on the host and it can be used to configure IPsec for both east-west and north-south traffic. It also seamlessly handles both fresh install and upgrade scenario so that network operator bring up only one IPsec pod on every node.
=> OCPBUGS-19817, SDN-4162: Upgrade IPsec with single daemonset pod

bindata/network/ovn-kubernetes/common/ipsec-host.yaml
we need to restart pluto after flushing xfrm state&policy or else it loses all the previous state.
and we do want to flush, to get a "clean slate"
(cherry picked from commit 2f5879349699b8477a2fcef9bc6d725e741c59c8)
=> OCPBUGS-24633: ipsec add pluto restart

bindata/network/ovn-kubernetes/common/008-script-lib.yaml, bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes_test.go
to pass to both ovnkube-node and control-plane pods. There is no feature gate, so it is set unconditionally.
=> SDN-4308,OCPBUGS-24650: Set enable-multi-external-gateway flag in ovnkube.conf

bindata/network/multus/multus.yaml
WHEREABOUTS_NAMESPACE env var is used by whereabouts-reconciler to garbage collect the Pod IPs. When unset, it defaults to kube-system namespace, while ippool.whereabouts.cni.cncf.io custom resource only exist in openshift-multus namespace on openshift. Setting WHEREABOUTS_NAMESPACE env var will tell whereabouts-reconciler where to get the ippool customer resource
=> OCPBUGS-23199: add env var in whereabouts-reconciler daemonset

pkg/apply/apply.go
the old manager "cluster-network-operator" was changed to "cluster-network-operator/operconfig" in 4.11 when server-side-apply was migrated to from client-side-apply. However, the old operator still had it's own managed fields and some interaction between those and the change to remove preStop hooks in ovnkube-master's daemonset containers was causing upgrades to stick in the network operator.
this will just remove the old manager (and it's managed fields) entirely. it's done before the update to apply the object instead of after.
JIRA: https://issues.redhat.com/browse/OCPBUGS-22293
deal w/ deprecated field manager before apply
=> OCPBUGS-24036: remove all managed fields used by old manager

pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
It's not reliable to check on ready machine count as it won't work in case of node reboot. Moreover it's enough to check for ipsec machine config extension in machine config pool status to confirm whether ipsec extension is completely rolled out or not. Hence this commit removes additional checks on ready machine count.
=> OCPBUGS-25337: Avoid removal of ipsec-host daemonset when node is NotReady

pkg/controller/proxyconfig/validation.go, pkg/util/validation/trustbundle.go
Copy of https://github.com/openshift/cluster-network-operator/pull/2141 as I was unable to make the the tide happy...
@trozet please approve again.
Previously, the CertificateData function would error out when unable to decode the next PEM block, causing issues with files containing empty lines at the end.
This causes problems for HyperShift clusters with a management cluster that uses the legacyVulnerableCABundle:
https://github.com/openshift/service-ca-operator/blob/fe887613d031435fb0c76eb397764ba68fe09014/pkg/controller/cabundleinjector/starter.go#L30C5-L35
https://github.com/openshift/service-ca-operator/blob/fe887613d031435fb0c76eb397764ba68fe09014/pkg/controller/cabundleinjector/starter.go#L72
This change addresses the problem by using crypto.CertsFromPEM from library-go, which …
=> OCPBUGS-24176: Ignore invalid PEM blocks

bindata/network/node-identity/managed/node-identity.yaml, pkg/network/node_identity.go
In HyperShift the network-node-identity deployment is located in the management cluster. Use the appropriate client to retrieve it.
=> OCPBUGS-24693: HyperShift, network-node-identity: Check the deployment in the management cluster

manifests/02-cncc-credentials.yaml
Instead of using the roles/compute.admin role use specific permissions required by CNCC:
-    [Instances.UpdateNetworkInterface](https://github.com/openshift/cloud-network-config-controller/blob/90bf88ab7abfd2920c36a493103c4e610a9b110b/pkg/cloudprovider/gcp.go#L80) - compute.instances.updateNetworkInterface, compute.subnetworks.use ([GCP doc](https://cloud.google.com/compute/docs/reference/rest/beta/instances/updateNetworkInterface#iam-permissions))
-    [ZoneOperations.Wait](https://github.com/openshift/cloud-network-config-controller/blob/90bf88ab7abfd2920c36a493103c4e610a9b110b/pkg/cloudprovider/gcp.go#L173) - compute.zoneOperations.get ([GCP doc](https://cloud.google.com/compute/docs/reference/rest/v1/zoneOperations/wait#iam-permissions))
- …
=> SDN-4227: Use specific permissions for CNCC in GCP

bindata/kube-proxy/kube-proxy.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/network-metrics/001-daemonset.yaml, bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
cherry pick from https://github.com/openshift/cluster-network-operator/pull/2090/commits/f91a102386fd2bec25cf941839793cfcff7d2c75
During an internal audit conducted by one of our customers in OCP, it was discovered that the openshift-sdn component, specifically on port 9101, has exposed certain cipher suites that are considered weak. We have identified the following weak ciphers that are currently being accepted:
[TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256](https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256/)
[TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256](https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256/)
=> [release-4.13] OCPBUGS-24570: Disable weak SSH cipher suitesRm weak ciphers 4.13

bindata/kube-proxy/kube-proxy.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/network-metrics/001-daemonset.yaml, bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
During an internal audit conducted by one of our customers in OCP, it was discovered that the openshift-sdn component, specifically on port 9101, has exposed certain cipher suites that are considered weak. We have identified the following weak ciphers that are currently being accepted:
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 - See [1]
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 - See [2]
[1] https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256/
[2] https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256/
=> [release-4.12] OCPBUGS-24571: Disable weak SSH cipher suites

pkg/apply/apply.go
the old manager "cluster-network-operator" was changed to "cluster-network-operator/operconfig" in 4.11 when server-side-apply was migrated to from client-side-apply. However, the old operator still had it's own managed fields and some interaction between those and the change to remove preStop hooks in ovnkube-master's daemonset containers was causing upgrades to stick in the network operator.
this will just remove the old manager (and it's managed fields) entirely. it's done before the update to apply the object instead of after.
JIRA: https://issues.redhat.com/browse/OCPBUGS-22293
deal w/ deprecated field manager before apply
=> [release-4.14] OCPBUGS-24037: remove all managed fields used by old manager

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes_test.go
OVNKube-controller, formerly known as OVNKube-master, no longer uses HA if the the deployment mode is SNO. OVNKube-cluster-manger however does use HA via a lease even though there is only expected to be one instance in this HA set.
For now, fix the lease config override mechanism via config file.
Depends on ovn-kubernetes#3967
=> OCPBUGS-19635: OVN-K in SNO deployment mode: fix Lease override for CM

pkg/apply/apply.go, pkg/apply/fieldmanager.go, vendor/k8s.io/client-go/util/csaupgrade/OWNERS, vendor/k8s.io/client-go/util/csaupgrade/upgrade.go, vendor/modules.txt
Previous to 4.11, we used client side update operations with a manager called 'cluster-network-operator', however following 4.11, we changed the field manager name
and changed to SSA ("Apply" operation), without
considering the previous field manager we used to use.
This can cause duplicate field managers managing
different fields and we encountered a scenario
where our SSA field manager was unable to drop a
field because the depreciated field manager owned and preserved the field.
This patch removes the depreciated field manager
regardless of the operation it used previously.
=> [release-4.13] OCPBUGS-22293: remove all managed fields used by old manager

pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/platform/platform.go
The Machine Config Operator doesn't understand how to process IPsec MachineConfig as it's rolled out by network operator and that wasn't present in install manifest. This makes cluster operator "machine-config" to degraded state. Hence this commit waits for both master and worker machine config pool to be in ready state and then renders IPsec MachineConfig.
=> OCPBUGS-25207: Render IPsec MachineConfig after cluster settles with MachineConfigs

bindata/network/node-identity/self-hosted/node-identity.yaml
The network node identity in self-hosted clusters should tolerate all taints, not only the common ones. 
This mimics the behavior of the API server pods: https://github.com/openshift/cluster-kube-apiserver-operator/blob/03c5a03d1bd0a952655aa180bd2708802e8cc1a4/bindata/assets/kube-apiserver/pod.yaml#L268-L269
=> OCPBUGS-24635: network node identity: tolarate all taints

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
ovn-kubernetes-node does not write anything to egressip and doesn't interact with cloudprivateipconfigs at all. This commit removes the unnecessary permissions.
This PR specifically handles the egressip resource, other features will be handled separately.
=> OCPBUGS-24379: Remove egressip write permissions from ovn-kubernetes-node

OWNERS
At some point someone added a `cluster-network-operator` subcomponent in jira, but never updated the OWNERS file here to reference it
=> NO-JIRA: Fix jira component info

pkg/controller/operconfig/operconfig_controller.go
`e2e-aws-ovn-shared-to-local-gateway-mode-migration` and its opposite flake about 50% of the time with
```
+ oc patch Network.operator.openshift.io cluster --type=merge --patch '{"spec":{"defaultNetwork":{"ovnKubernetesConfig":{"gatewayConfig":{"routingViaHost":false}}}}}'
network.operator.openshift.io/cluster patched
+ oc wait co network --for=condition=PROGRESSING=True --timeout=60s
error: timed out waiting for the condition on clusteroperators/network 
```
This is because #1721 changed CNO to re-reconcile any time any Node object changes, but Nodes change *a lot* (specifically, their Conditions), so now we do a ton of unnecessary reconciling, causing CNO to be super busy and lag behind in processing events. This PR fixes it to only reconcile when node labels change.
(I don't know …
=> OCPBUGS-27264: Only reconcile on Node updates with Label changes

pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/platform/platform.go
The CNO does not roll out its own IPsec Machine Config when user already installed Machine Config for IPsec. This leads to IPsec gets disabled temporarily in the data plane when user deletes their own Machine Config. IPsec would be in disabled state until operator rolls out its own IPsec machine config in the subsequent reconcile loop followed by nodes reboot. To avoid this situation, this commit always rolls out its own IPsec Machine Config at the time of IPsec fresh install or upgrade irrespective of user's Machine Config exists or not.
=> OCPBUGS-26952: Deploy CNO IPsec MC even if user already have one

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Adds the necessary knobs in the cno to consume the api change (https://github.com/openshift/api/pull/1410) exposing the internal masquerade subnet in ovn-k where we reserve addresses for ip masquerading
=> SDN-3708: Support configurable masquerade subnet in ovn-k 

bindata/network/multus/multus.yaml
Modify the whereabouts-reconciler DaemonSet to mount the whereabouts-config ConfigMap into /cron-schedule/config. This will be consumed by Whereabouts, which monitors this path to update its cron schedule for cleaning up unused IPs.
Please note that we set the ConfigMap volume as optional to reduce complexity and avoid requiring the cluster-network-operator to deploy the whereabouts ConfigMap.
Users will be able to create the whereabouts ConfigMap later, and it will update automatically in the whereabouts container. For example: `oc create configmap whereabouts-config -n openshift-multus \ --from-literal=reconciler_cron_expression="*/15 * * * *"`
To update the value use:
`oc patch configmap whereabouts-config -n openshift-multus --type merge \ -p …
=> OCPBUGS-26986: Add ConfigMap mount to the whereabouts-reconciler

bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml, pkg/network/ovn_kubernetes_test.go
backport of https://github.com/openshift/cluster-network-operator/pull/2169 first commit
=> OCPBUGS-27198: [release-4.15] Update ovn-k managed control-plane RBAC

bindata/network/multus/multus.yaml
Cherry-pick of #2209 
Related to: https://github.com/openshift/whereabouts-cni/pull/239
Modify the whereabouts-reconciler DaemonSet to mount the whereabouts-config ConfigMap into /cron-schedule/config. This will be consumed by Whereabouts, which monitors this path to update its cron schedule for cleaning up unused IPs.
Please note that we set the ConfigMap volume as optional to reduce complexity and avoid requiring the cluster-network-operator to deploy the whereabouts ConfigMap.
Users will be able to create the whereabouts ConfigMap later, and it will update automatically in the whereabouts container. For example: oc create configmap whereabouts-config -n openshift-multus \ --from-literal=reconciler_cron_expression="*/15 * * * *"
To update the value use:
oc patch configmap …
=> OCPBUGS-27748: [release-4.15] Add ConfigMap mount to the whereabouts-reconciler

bindata/network/multus/multus.yaml
Cherry-pick of #2214 
Related to: [openshift/whereabouts-cni#240](https://github.com/openshift/whereabouts-cni/pull/240)
Modify the whereabouts-reconciler DaemonSet to mount the whereabouts-config ConfigMap into /cron-schedule/config. This will be consumed by Whereabouts, which monitors this path to update its cron schedule for cleaning up unused IPs.
Please note that we set the ConfigMap volume as optional to reduce complexity and avoid requiring the cluster-network-operator to deploy the whereabouts ConfigMap.
Users will be able to create the whereabouts ConfigMap later, and it will update automatically in the whereabouts container. For example: `oc create configmap whereabouts-config -n openshift-multus \ --from-literal=reconciler_cron_expression="*/15 * * * *"`
To update the value …
=> OCPBUGS-27858: [release-4.14] Add ConfigMap mount to the whereabouts-reconciler DaemonSet

pkg/controller/clusterconfig/migration.go, pkg/controller/operconfig/migration.go, pkg/controller/operconfig/migration_test.go, pkg/names/names.go
This issue always happens when doing live migration in a large (it was initially reported on a cluster with 26 workers) cluster. The CNO will enter an infinity loop of step3->step2->step3 during live migration.
The reason is that in a smaller cluster, the MCP master normally takes more time to finish updating. And the master pool is always the first item of `pools.Items`. So the reason for the condition `NetworkTypeMigrationMTUReady` will not be set to `MachineConfigNotApplied` before the master pool finishes updating and the condition `NetworkTypeMigrationTargetCNIInUse` becomes `True`. This patch will ensure the reason for the condition `NetworkTypeMigrationMTUReady` is always set to `MachineConfigPoolsUpdating`, if any of the pools is updating.
=> OCPBUGS-27823: Not update migration conditions when any MCP is updating

bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
Prevent NoRunningOvnControlPlane alert getting fired continuously for managed cluster
In managed cluster kube-rbac-proxy is not there to scrape metrics from ovnkube-cluster-manager. Instead metrics endpoint of ovnkube-cluster-manager gets exposed directly. This PR takes care of following aspects:
- Makes 9108 port listen on all IPv4 interfaces instead of localhost only.
- Change expression used with NoRunningOvnControlPlane alert to correct namespace to HostedClusterNamespace.
=> OCPBUGS-25079: Prevent NoRunningOvnControlPlane alert getting fired continuously

pkg/network/ovn_kubernetes.go
It's all single thread now, plus we don't need an if/else block for SNO anymore since it's just a single boolean now.
=> OCPBUGS-19551: ovnkube: simplify northd threading and SNO templating

pkg/bootstrap/types.go, pkg/controller/clusterconfig/clusterconfig_controller.go, pkg/controller/operconfig/cluster.go, pkg/network/cluster_config.go, pkg/network/cluster_config_test.go, pkg/network/render.go, pkg/network/render_test.go, pkg/platform/platform.go, pkg/util/util.go
In all the managed clusters excl hypershift aka standalone managed clusters, the namespace "dedicated-admin" shall exist. We use this to figure out if CNO is running in a managed cluster.
=> NP-903: Only allows live migration on standalone managed clusters

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml, bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
Based on https://github.com/openshift/cluster-network-operator/pull/2170
ovn-kubernetes-node should only be allowed to read the egressservices resources. Additionally ovn-kubernetes-control-plane should only be allowed to update egressservices/status.
This PR specifically handles the egressservices resource, other features will be handled separately.
The only place we modify the egresservices resource is a status update here: https://github.com/ovn-org/ovn-kubernetes/blob/7447607048cf6fca57b0a51dd3361e694fea851d/go-controller/pkg/kube/kube.go#L456
Other than that both the ovn-kubernetes-node and ovn-kubernetes-control-plane read the egresservices from the API.
=> OCPBUGS-24383: Limit write permissions for egressservices

pkg/bootstrap/types.go, pkg/controller/clusterconfig/clusterconfig_controller.go, pkg/controller/operconfig/cluster.go, pkg/network/cluster_config.go, pkg/network/cluster_config_test.go, pkg/network/render.go, pkg/network/render_test.go, pkg/platform/platform.go, pkg/util/util.go
BP of https://github.com/openshift/cluster-network-operator/pull/2236
For the set of managed clusters excluding hypershift, the namespace "dedicated-admin" shall exist.
Use this info to only enable live migration within that set.
/hold
=> OCPBUGS-28904: [release-4.15] Restrict live migration to standalone managed clusters

bindata/cloud-network-config-controller/001-crd.yaml, go.mod, go.sum, manifests/0000_70_cluster-network-operator_01-Default.crd.yaml, vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml, vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml-patch, vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml, vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml, vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml-patch, vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-Default.yaml, vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml-patch, vendor/github.com/openshift/api/config/v1/custom.authentication.testsuite.yaml, vendor/github.com/openshift/api/config/v1/stable.authentication.testsuite.yaml, vendor/github.com/openshift/api/config/v1/stable.hypershift.authentication.testsuite.yaml, vendor/github.com/openshift/api/config/v1/techpreview.authentication.testsuite.yaml, vendor/github.com/openshift/api/config/v1/types_authentication.go, vendor/github.com/openshift/api/config/v1/types_feature.go, vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml, vendor/github.com/openshift/api/operator/v1/stable.network.testsuite.yaml, vendor/github.com/openshift/api/operator/v1/types_network.go, vendor/modules.txt
Includes moving the live migration to default.
Additionally it pulls the CNCC change, cc: @dulek, @martinkennelly 
Commands ran:
```
go get github.com/openshift/api@release-4.15
go mod tidy && go mod vendor
./hack/update-codegen.sh
```
=> [release-4.15] NP-905,OCPBUGS-28902: Bump openshift API

bindata/network/node-identity/managed/node-identity.yaml
CNO managed component (network-node-identity) to conform to hypershift control plane expectations that all secrets should be mounted to not have global read. change from 420(0644) to 416(0640)
=> OCPBUGS-24299: network-node-identity mounts secrets with mode 0640

bindata/network/node-identity/managed/node-identity.yaml
The node-network-identity deployment should contain liveness and readiness probes where applicable.
=> OCPBUGS-24436: Add probes to node-network-identity

bindata/network/multus/multus.yaml
(cherry picked from commit 5045f12323487d76b40c49ba4e7b873552e40535)
fixed the following merge conflict by keeping the serviceAccountName to be multus since the security hardening work hasn't been backported to 4.13:
```
++<<<<<<< HEAD
+      serviceAccountName: multus
++=======
+       nodeSelector:
+         kubernetes.io/os: linux
+       serviceAccountName: multus-ancillary-tools
+       priorityClassName: "system-node-critical"
++>>>>>>> 5045f1232 (OCPBUGS-19830: fix whereabouts conformance test failures)
```
=> OCPBUGS-28777: fix whereabouts conformance test failures

bindata/allowlist/daemonset/daemonset.yaml
This code changes cni-sysctl-allowlist ds without container network interface because this ds does not require any network.
=> OCPBUGS-29099: Add hostNetwork:true to cni-sysctl-allowlist ds

bindata/network/multus/multus.yaml
Modify the whereabouts-reconciler DaemonSet to mount the whereabouts-config ConfigMap into /cron-schedule/config. This will be consumed by Whereabouts, which monitors this path to update its cron schedule for cleaning up unused IPs.
Please note that we set the ConfigMap volume as optional to reduce complexity and avoid requiring the cluster-network-operator to deploy the whereabouts ConfigMap.
Users will be able to create the whereabouts ConfigMap later, and it will update automatically in the whereabouts container. For example: `oc create configmap whereabouts-config -n openshift-multus \ --from-literal=reconciler_cron_expression="*/15 * * * *"`
To update the value use:
`oc patch configmap whereabouts-config -n openshift-multus --type merge \ -p …
=> OCPBUGS-28801: [release-4.12] Add ConfigMap mount to the whereabouts-reconciler DaemonSet

bindata/network/ovn-kubernetes/common/ipsec-containerized.yaml, bindata/network/ovn-kubernetes/common/ipsec-host.yaml
There is no need for libreswan rpm existence checks anymore in ipsec daemonset pod because libreswan is always expected to be present, otherwise it should be an error. Hence this commit is removing those checks. This also inherently fixes rpm db directory mount issue because rhel and rhcos use different directories for it.
=> OCPBUGS-28676: Remove libreswan rpm existence checks

pkg/controller/ingressconfig/ingressconfig_controller.go
Update ingressconfig_controller to use subcontroller "ingress_controller"
for field management on Patch calls. It used to apply changes with
deprecated cluster-network-operator field manager, that was overridden
and removed by ApplyObject. Thus, labels applied to
openshift-host-network namespace were periodically removed.
On upgrade, ingress-owned labels will be merged with "cluster-network-operator/operconfig" Apply call here https://github.com/openshift/cluster-network-operator/blob/master/pkg/apply/apply.go#L139-L150 and removed as the new owner didn't specify them. On the next reconcile loop, ingress controller will re-apply the labels with the new fieldManager and everything should work fine ever after.
For some reason, ingress controller was last this that doesn't use apply logic, …
=> OCPBUGS-28920: Update ingressconfig_controller to use field Manager

bindata/network/node-identity/managed/node-identity.yaml
The node-network-identity deployment should be set to assist in a controlled rollout of the microservice pods.
=> OCPBUGS-24601: Add minReadySeconds to network-node-identity

pkg/controller/ingressconfig/ingressconfig_controller.go
clean backport of https://github.com/openshift/cluster-network-operator/pull/2259
=> [release-4.15] OCPBUGS-29299: Update ingressconfig_controller to use field Manager

pkg/controller/ingressconfig/ingressconfig_controller.go
cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2265
=> [release-4.14] OCPBUGS-29300: Update ingressconfig_controller to use field Manager

pkg/controller/clusterconfig/clusterconfig_controller.go, pkg/controller/operconfig/cluster.go, pkg/controller/operconfig/operconfig_controller.go
In CNO, the network.operator CR can be updated by both operconfig and clusterconfig controllers. There is a chance that these two controllers may encounter a racing condition, resulting in conflict error.
Normally, this type of error can be automatically recovered by retrying the operation. Therefore, we don't set CNO to degrade when encountering this error.
=> OCPBUGS-26492: Not set CNO to degraded if API server returns conflict error

pkg/controller/ingressconfig/ingressconfig_controller.go
cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2267
=> [release-4.12] OCPBUGS-29302: Update ingressconfig_controller to use field Manager

bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-control-plane.yaml, pkg/network/ovn_kubernetes.go
in 4.14 we switched to OVN-IC and no longer require 3 nodes for RAFT consensus
backport of: https://github.com/openshift/cluster-network-operator/pull/2052
This needs to be a manual backport because the filenames of the yamls changed
=> [release-4.14] OCPBUGS-18281: only 2 master nodes are required for ovn-kubernetes

pkg/controller/statusmanager/pod_status.go, pkg/network/ovn_kubernetes.go
If ever a cluster is not making progress during phase 1 or phase 2 of the upgrade to OVN IC, a cluster admin can now edit the interconnect configmap and add a new key (`fast-forward-to-multizone`) to bypass the two-phase upgrade and let CNO apply directly the multizone YAMLs.
The current code only allows the cluster to move forward when it's in phase 1 by setting `zone-mode=multizone` and `temporary=false`:
Let's improve that by allowing to jump to multizone in either phase of the upgrade. At the same time, remove the `temporary` field from the configmap, since the `ongoing-upgrade` field already tracks that CNO is going through an upgrade:
=> [release-4.14] OCPBUGS-26573: Improve troubleshooting IC upgrades

bindata/network/multus/003-dhcp-daemon.yaml
With system-node-critical priority, dhcp-daemon pods will not get evicted before workloads.
=> OCPBUGS-29341: Run dhcp-daemon pods as system-node-critical priority

bindata/network/ovn-kubernetes/common/008-script-lib.yaml
Openvswitch version 3.0.0 onward memory-trim-on-compaction is enabled by default. This PR is to stop redoing it while starting both nbdb and sbdb.
Jira: https://issues.redhat.com/browse/OCPBUGS-237
https://issues.redhat.com/browse/OCPBUGS-25764
=> OCPBUGS-25764: memory-trim-on-compaction is enabled by default

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml, bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
The ovnkube-node pod only listens to CRUD events of APBExternalRoutes and updates its status, So this PR adjusts its cluster role accordingly.
=> OCPBUGS-24380,OCPBUGS-24381,OCPBUGS-24382: Update APBExternalRoute, EgressFirewall, EgressQoS permissions for ovnkube pods

pkg/controller/infrastructureconfig/infrastructureconfig_controller.go, pkg/controller/infrastructureconfig/sync_specstatus.go, pkg/controller/infrastructureconfig/sync_specstatus_test.go, pkg/controller/infrastructureconfig/sync_vips.go, pkg/controller/infrastructureconfig/sync_vips_test.go, pkg/controller/infrastructureconfig/validations.go, pkg/util/ip/addr.go, pkg/util/ip/addr_test.go
Recently we have introduced VIPs to the PlatformSpec in the
Infrastructure CR. Previously they only existed in PlatformStatus and
now we will have them in both Spec and Status.
In order to properly handle clusters created before the change was
introduced, during the upgrade of such a cluster we will detect case
when PlatformSpec is empty and PlatformStatus is filled with VIPs. For
those, we will copy content from Status to Spec.
We are adding validation logic to the Infrastructure Controller that is
responsible for checking if requested changes to the VIPs or Machine
Networks are valid. Those validations are in principle the same as
validations performed by the o/installer but those here happen when
Infrastructure CR is updated by the end user (as opposed to the
o/installer ones which …
=> OPNET-358, OPNET-360: Allow VIP mutation in Infra CR

pkg/platform/platform.go, pkg/util/util.go
In ARO the dedicated-admin namespace does not exit. Detect `openshift-azure-operator` instead.
/cc @martinkennelly @pliurh
=> OCPBUGS-30299: Fix managed cluster detection on ARO

pkg/network/multus_admission_controller.go, pkg/network/node_identity.go, pkg/network/render.go, pkg/network/render_test.go
Cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2278.
There were conflicts in the second commit.
=> OCPBUGS-30021:  [release-4.14] Disable network-node-identity on ROKS

bindata/network/multus/multus.yaml
According to CIS benchmark guidance, all files according to networking configuration should only be read/writeable to the owner (600).
This commit updates the installation script that lays down the whereabouts.conf file to use permissions 600 instead of 644.
=> OCPBUGS-22995: Tighten the permissions on whereabouts.conf

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
Backport of https://github.com/openshift/cluster-network-operator/pull/2203
CONFLICT (content): Merge conflict in bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
(cherry picked from commit 4019afea4c61c3349fa8be5543ceec9e80a9b0d8)
=> [release-4.14] OCPBUGS-31360: Remove egressip write permissions from ovn-kubernetes-node

bindata/network/multus-admission-controller/001-service.yaml, bindata/network/multus-admission-controller/monitor.yaml, bindata/network/node-identity/managed/node-identity-service.yaml, bindata/network/ovn-kubernetes/managed/monitor-control-plane.yaml, pkg/bootstrap/types.go, pkg/hypershift/hypershift.go, pkg/network/multus_admission_controller.go, pkg/network/multus_admission_controller_test.go, pkg/network/node_identity.go, pkg/network/ovn_kubernetes.go, pkg/network/render.go, pkg/network/testutil_test.go
This PR allows HyperShift the ability to set the CA ConfigMap and key through an environment variable. The PR also removes the service-sa annotation from services used by HyperShift since we will pass through a CA ConfigMap for the services we are using.
Fixes [SDN-4607](https://issues.redhat.com//browse/SDN-4607)
=> SDN-4607: Allow HyperShift ability to set ConfigMap through env var

bindata/network/ovn-kubernetes/common/001-crd.yaml
This PR updates the ANP/BANP CRDs to reflect the latest changes, i.e egress support and this reflects the release v0.1.3 upstream: https://github.com/kubernetes-sigs/network-policy-api/releases/tag/v0.1.3 (had to change bundle version manually since release is not cut yet but this is just aesthetics) + adds support for `isCIDR()` in the networks peer which is OCP carry only HACK because it hits k/k only in 1.31 release but we have support for this in OCP thanks to https://github.com/openshift/kubernetes/pull/1828
The manual changes are a second commit on top with OCPHACKs title, we should hopefully sync with upstream once we cut a release + we become 1.31 so that network-policy-api repo can also leverage isCIDR()
source-code: https://github.com/tssurya/network-policy-api/tree/final-ocp-crd …
=> SDN-4596: Update (B)ANP CRDs; prepare for GA

pkg/network/node_identity.go, pkg/platform/platform.go
Clean cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2313. 
I hope we can wait till 4.16 is fully verified on ROKS before merging this. 
/cc @dougbtv
=> [release-4.15] OCPBUGS-29654: Fully disable network-node-identity on ROKS

bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
without this, configuring 'automountServiceAccountToken: false' cause ovnkube-control-plane pods to CrashLoop with:
"unable to create kubernetes rest config, err: TLS-secured apiservers require token/cert and CA certificate."
=> OCPBUGS-26408: automountServiceAccountToken:false hosted CP pods

pkg/network/node_identity.go, pkg/platform/platform.go
Clean cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2314.
/cc @dougbtv
=> [release-4.14] OCPBUGS-30021: Fully disable network-node-identity on ROKS

bindata/network-diagnostics/network-check-target.yaml
missed one last time.  this adds the debugging info to the API on container crash.
=> OCPBUGS-28230: enforce termination message policy on all platform pods

bindata/cluster-network-operator/prometheus.yaml, pkg/controller/operconfig/operconfig_controller.go, pkg/network/ovn_kubernetes.go, pkg/network/render.go, pkg/util/ipsec/metrics.go
This PR adds a metric for the ipsec mode. The metric created is a Gauge named `cluster_network_ipsec_state` with a constant value of 1 and 2 labels:
1. "mode" which lists the ipsec mode, one of `Disabled` `External` or `Full`
2. "is_legacy_api" which states the flavor of the API used - either `true`
for legacy API (up to OCP V4.14) or `false` for the new API (OCP 4.15+)
-- If the cluster uses non ovn-k network (a network that does not
support ipsec) the value of this label is "N/A - ipsec not supported (non-OVN network)"
Then a Prometheus rule  is created to remove other labels and this rule `openshift:cluster_network_ipsec_state:sum` will be collected in the telemetry
Jira ticket https://issues.redhat.com/browse/MON-3707
=> SDN-4163: Add ipsec state to telemetry

pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Currently CNO checks only machineConfigStatus.Configuration.Source for IPsec Machine Config are rolled out completely on cluster nodes, but from CI test with 24 nodes, it's found that source is populated even before UpdatedMachineCount reaches to MachineCount. So CNO proceeds with rendering IPsec DaemonSet which makes its pods into crashlooping on those node because ipsec service are not running yet. Hence this commit also checks MachineCount with UpdatedMachineCount to ensure IPsec machine config is available on all nodes.
=> OCPBUGS-32347: Improve IPsec MachineConfig readiness check

bindata/network/ovn-kubernetes/common/ipsec-containerized.yaml, bindata/network/ovn-kubernetes/common/ipsec-host.yaml
The condition used in until loop is buggy which always resulted to true though certificate present in the csr object status or not. Hence this commit fixes it so that ovs get configured with non empty certificate and avoids ovs-monitor-ipsec script failing with No cert error.
=> OCPBUGS-32402: Fix wait logic for IPsec certificate signing request

bindata/cluster-network-operator/prometheus.yaml
A minor change to the Prometheus rule query and name as requested by the monitoring team
=> SDN-4163: Improved prometheus rule for ipsec metric

pkg/controller/infrastructureconfig/sync_specstatus.go, pkg/controller/infrastructureconfig/sync_specstatus_test.go
vSphere UPI is a special platform which uses `platform: vsphere` but its PlatformStatus is `nil`. Because of this, whenever we need to differentiate the migration scenario for vSphere IPI and UPI
* IPI starts upgrade with `nil` PlatformSpec and ends with values copied from PlatformStatus
* UPI starts upgrade with `nil` PlatformSpec and ends with `nil`
Important to note that serialization of `nil` is different than serialization of an empty struct.
Important to note that having Platform defined and empty/nil PlatformStatus is a good enough indicator that we use UPI.
Fixes: OCPBUGS-31528
=> OCPBUGS-31528: infraconfig: handle vSphere UPI by not updating any fields

bindata/network/iptables-alerter/001-rbac.yaml, bindata/network/iptables-alerter/002-script.yaml, bindata/network/iptables-alerter/003-daemonset.yaml, manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/image-references, pkg/bootstrap/types.go, pkg/network/bootstrap.go, pkg/network/render.go
This adds a daemonset that runs a script that periodically:
- lists all local non-`hostNetwork` pods
- checks if iptables rules have been created in that pod's network namespace (other than the rules created by ovn-kubernetes/openshift-sdn)
- logs an Event if so
There was an enhancement for this which never went anywhere, but you can see some discussion of ideas in https://github.com/openshift/enhancements/pull/1509/files.
I actually originally implemented this in MCO via a systemd timer that ran a locally-installed script. But this ran into problems because it had to use kubelet's serviceAccount, and kubelet doesn't have permission to list/create events in all namespaces. So I would have had to create a separate service account and get the credentials installed onto the node but I don't …
=> SDN-4114: Add iptables-alerter daemonset

pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go
This PR updates network cluster operator status condition with Upgradable to False when networking plugin is with openshift-sdn. This would help CVO to block cluster upgrade into 4.17 when it sees Upgradable=False from Cluster Operator.
=> SDN-4726: Block upgrade for openshift-sdn

pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go
Reverts #2330 ; tracked by https://issues.redhat.com/browse/TRT-1618
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
All SDN jobs failing due to upgradeable false
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload 4.16 nightly blocking
```
CC: @pperiyasamy
<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>
=> Revert #2330 "SDN-4726: Block upgrade for openshift-sdn"

pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/platform/platform.go
While testing IPsec upgrade on 24 node cluster in CI, it's noticed there are more than two (master, worker) machine config pools present. For example infra and workload pools were present which belong worker role. Hence this PR queries all machine config pools based on master and worker roles and check ipsec plugin existence on every pool.
=> OCPBUGS-32525: Check every MachineConfigPool for IPsec plugin existence

bindata/allowlist/config/configmap.yaml
I've left out `forwarding` for now
still want to understand why they want it and what it relates to
it is safe, but might make our support life .. complicated
=> OCPBUGS-29403: add more safe sysctls

pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
This PR updates network operator progressing condition for rolling out IPsec daemonset for cluster. It reflects appropriate status for network cluster operator which would make openshift-install to exit gracefully after installing all of IPsec components for the cluster.
=> OCPBUGS-32979: Update network operator status for IPsec

bindata/network/ovn-kubernetes/common/001-crd.yaml, bindata/network/ovn-kubernetes/common/002-rbac-node.yaml, bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml, bindata/network/ovn-kubernetes/common/007-rbac-cluster-reader.yaml, bindata/network/ovn-kubernetes/common/008-script-lib.yaml, bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Enable `DNSNameResolver` feature-gate for ovn-kubernetes 
Related to EP : https://github.com/openshift/enhancements/pull/1335
=> CFE-888: Enable DNSNameResolver feature-gate 

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes_test.go
CNO is writing custom masquerade subnet into ovnkube-config CM but against key v4-internal-masquerade-subnet and v6-internal-masquerade-subnet. However ovnkube is expecting custom masquerade subnet from v4-masquerade-subnet and v6-masquerade-subnet keys.
Additionally custom masquerade subnet needs to be added for managed hub cluster as well. This PR also takes care of that part.
=> OCPBUGS-33728: Add custom masquerade subnet against right key at ovnkube-config CM

pkg/client/list_pager.go, pkg/network/cluster_config.go, pkg/network/cluster_config_test.go, pkg/network/ovn_kubernetes.go
Adds the following validations for OpenShiftSDN to OVNKubernetes live migration:
- Do not allow migrating from OpenShiftSDN in multitenant mode.
- Check whether any of the `ClusterNetwork` and `ServiceNetwork` CIDRs conflict with the internal OVNKubernetes subnets: `v[4|6]InternalSubnet`, `v[4|6]InternalTransitSwithSubnet` and `v[4|6]InternalMasquerateSubnet`.
- Do not allow migrating from OpenShiftSDN if there are any pods
with pod.network.openshift.io/assign-macvlan annotation present in the cluster.
=> NP-974: Validation for live migration from OpenShiftSDN to OVNKubernetes 

pkg/network/multus_admission_controller.go, pkg/network/multus_admission_controller_test.go
This code changes to introduce additional condition check for ignored-namespaces, whether the ns is openshift component or not
=> OCPBUGS-32991: Add conditions for ignored-namespaces

bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
During live migration, we run ovn-k and sdn in parallel. When new nodes are added to the cluster, ovn-k and sdn may assign different subnets to the nodes. This patch lets ovn-k subject to sdn for the node subnet allocation when both CNIs are deployed.
=> NP-975: Align new node subnet allocation between OVN-K and SDN during live migration

bindata/network/node-identity/self-hosted/node-identity-pki.yaml, bindata/network/node-identity/self-hosted/node-identity-webhook.yaml, bindata/network/node-identity/self-hosted/node-identity.yaml, pkg/network/node_identity.go
For clusters with IPv6 as the primary network the `network-node-identity.openshift.io` admission webhook should have the IP address in brackets.
The only actual change is that we include brackets in the webhook address when using ipv6 (`url: https://::1:9743/node` changes to `url: https://[::1]:9743/node`)
The issue was observed during testing of the k8s 1.30 rebase in which the webhook client started using http2 for loopback IPs: https://github.com/kubernetes/kubernetes/pull/122558.
It looks like the issue is caused by how a http2 client handles this invalid address, I verified this change by setting up a cluster with https://github.com/openshift/kubernetes/pull/1953 and this pr.
=> OCPBUGS-34359: Ensure that the node-identity webhook address contains colons for IPv6

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes_test.go
CNO is writing custom masquerade subnet into ovnkube-config CM but against key v4-internal-masquerade-subnet and v6-internal-masquerade-subnet. However ovnkube is expecting custom masquerade subnet from v4-masquerade-subnet and v6-masquerade-subnet keys.
Additionally custom masquerade subnet needs to be added for managed hub cluster as well. This PR also takes care of that part.
Signed-off-by: Arnab Ghosh <arnabghosh89@gmail.com>
(cherry picked from commit aeb0b1cb239d24798a06ca66b95a008adc7fd4c9)
=> [release-4.16] OCPBUGS-34013: Add custom masquerade subnet against right key at ovnkube-config CM

pkg/network/ovn_kubernetes.go
A few misc fixes for the IC upgrade logic:
- When evaluating whether phase 2 is ongoing, don't rely on ovnkube-node being "progressing", since that might happen also due to transient node conditions _after_ a complete roll out of ovnkube-node (found in https://issues.redhat.com//browse/OCPBUGS-30579)
- Tighten the progression to phase 2 to the presence of the configmap: since CNO removes the configmap as soon as the upgrade is completed, checking for the configmap prevents us from mistakenly going back to the multi-zone-interconnect-tmp folder when some transient conditions on ovnkube-xyz pods could make us flag them as "progressing". (found in https://issues.redhat.com//browse/OCPBUGS-30579)
- Remove all code related to the migration from multizone to single zone, since we've decided not …
=> OCPBUGS-27925,OCPBUGS-30579:[release-4.14] tighten conditions for the state transitions in IC upgrade

bindata/network/iptables-alerter/002-script.yaml
We get the list of running pods once and then process all of them; it's possible some pods will have exited by the time we reach the end of the loop. Previously that would cause `crictl inspectp` to return an error, which (due to `set -x`) would make the script error out. Just ignore it instead.
(Also fixes an indentation bug at the end of the script that had no effect other than looking wrong.)
=> OCPBUGS-33497: Handle pod exiting race conditions in iptables-alerter

pkg/network/multus_admission_controller.go, pkg/network/multus_admission_controller_test.go
This code changes to introduce additional condition check for ignored-namespaces, whether the ns is openshift component or not
=> OCPBUGS-34214: Add conditions for ignored-namespaces

bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-control-plane.yaml
Put feature-gate flag to the control-plane pod spec to make sure control-plane pods are restarted on feature gate enablement. ovnkube-node is fine, as this flag is enabled via script-lib.
=> OCPBUGS-34524: Fix DNSResolver feature gate enablement

pkg/controller/operconfig/cluster.go, pkg/controller/operconfig/operconfig_controller.go, pkg/network/cluster_config.go
The NetworkTypeMigrationInProgress is set in operconfig controller and not in the clusterconfig controller.
Ensure that the live migration is valid before initializing the condition.
/cc @martinkennelly @pliurh
=> OCPBUGS-34858, OCPBUGS-34916: Validate live migration before setting the progressing condition

manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/image-references, pkg/network/openshift_sdn_test.go, pkg/network/previous_test.go, pkg/network/render.go
It's time...
~I removed live migration and offline migration in two separate pieces because I realized belatedly I had to be somewhat careful about it because we still need _some_ of the migration code in place to support "MTU migration"...~
UPDATED: this now leaves most of the sdn code there, it just removes support for actually _deploying_ sdn (and in particular, removes the references to the SDN image, which is needed so we can start the process of removing the image from the release). We can do followups to clean up the dead code.
=> SDN-4896: Drop openshift-sdn support

bindata/network/iptables-alerter/003-daemonset.yaml
It's supposed to be a background process, but it's not acting that way right now
=> OCPBUGS-33497: Limit iptables-alerter's cpu

bindata/allowlist/daemonset/daemonset.yaml, bindata/kube-proxy/kube-proxy.yaml, bindata/network/iptables-alerter/003-daemonset.yaml, bindata/network/multus-networkpolicy/multus-networkpolicy.yaml, bindata/network/multus/multus.yaml, bindata/network/network-metrics/001-daemonset.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/common/ipsec-containerized.yaml, bindata/network/ovn-kubernetes/common/ipsec-host.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
This change updates the daemonsets of:
- iptables-alerter
- multus
- network-metrics
- ovnkube-node
- kube-proxy
- sdn/openshift-sdn
- [ovn-ipsec-containerized|ovn-ipsec-host]/openshift-ovn-kubernetes
- multus-networkpolicy
- whereabouts-reconciler
- cni-sysctl-allowlist-ds
with an annotation that prevents the cluster-autoscaler from evicting them during a scaling event.
This is to ensure that scaling can happen without stopping workloads from being evicted, due to critical components not being present on the node.
=> OCPBUGS-23000: Adds cluster-autoscaler annotation to prevent eviction

.golangci.yaml
This commit removes the linters deprecated from 0.53.0 to 0.59.0. 
It is required for a follow-up PR which will update CNO to use golang 1.22 (which requires golangci-lint >= 0.56.0).
=> SDN-5029: linter: removed deprecated linters

pkg/controller/operconfig/mtu_probe.go, pkg/controller/operconfig/operconfig_controller.go
The configmap mtu is required by SDN live migration. It should be created by the mtu-prober job at the installation time since 4.11. But if the cluster was upgrade from a very early releases, it may be absent.
=> OCPBUGS-35316: Create the configmap mtu if not found

bindata/network/multus-admission-controller/admission-controller.yaml, pkg/hypershift/hypershift.go, pkg/network/multus_admission_controller.go, pkg/network/ovn_kubernetes_test.go
**What this PR does / why we need it**:
The multus-admission-controller component currently does not honor the hypershift custom priority class overrides specified on the hostedcluster.  The custom priority class override feature was first introduced to all other hypershift hosted control plane components in https://github.com/openshift/hypershift/pull/2661.  Multus was left out at the time due to it not being directly managed by the CPO.  These changes extend the hypershift custom priority class override feature to the multus-admission-controller to ensure that this component honors the custom class if it is set.  These changes also extend the hypershift control plane component resource preservation support to the multus container as well, where the expected behavior is that any …
=> OCPBUGS-31878: Propogate hypershift control plane priority class override to multus and preserve container resource requests

pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/util/util.go
Ipsec is currently not functional all throughout the 4.13->4.14 upgrade, until the new ovnkube-node pods are deployed on each node.  
4.13 deploys `ovn-ipsec` daemonset, while 4.14 deploys `ovn-ipsec-host` and `ovn-ipsec-containerized` daemonsets, which require the certificates issued by ovnkube-node-identity, otherwise they are in crashloopbackoff
until the new ovnkube-node pods are running.
The idea is that, during 4.13->4.14 upgrades,we should run the 4.13 ovn-ipsec daemonset until phase 2 of the upgrade to IC is done, that is until all multizone ovnkube-node pods are deployed, at which point the new 4.14 daemonsets can be created and the 4.13 one is removed.
```                    
│ 4.13          │   4.14              │  4.14                  │ 4.14 …
```
=> OCPBUGS-34885:[release-4.14] Fix 4.13->4.14 upgrade with ipsec enabled

bindata/network/ovn-kubernetes/common/008-script-lib.yaml
This PR is to set IPv4 and IPv6 IP forwarding sysctl parameter when ipForwarding mode is set to Restricted.
If ipForwarding is set to 'Restricted':
sysctl -w net.ipv4.ip_forward=0
sysctl -w net.ipv6.conf.all.forwarding=0
=> OCPBUGS-23758: Set global IP forwarding sysctl parameters while starting ovnkube-node

pkg/network/multus_admission_controller.go, pkg/network/multus_admission_controller_test.go
This code changes to introduce additional condition check for ignored-namespaces, whether the ns is openshift component or not
=> OCPBUGS-32989: Add conditions for ignored-namespaces

bindata/network/multus/multus.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
This PR is to change mountPropagation for /var/lib/kubelet mount from None to HostToContainer. This is to allow clean unmount of CSI Volumes.
Jira: https://issues.redhat.com/browse/OCPBUGS-30950
=> OCPBUGS-30950: Set mount propagation to HostToContainer for /var/lib/kubelet

bindata/network/ovn-kubernetes/common/alert-rules.yaml, bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
* Moved distributed control plane alerts from master-rules to alert-rules.
* Tweaked the wording of the alerts to either reflect the enw component names or the distributed nature of them.
* Added OVNKubernetesNorthdInactive alert back with adjusted severity and duration.
=> OCPBUGS-33758: Fix IC distributed control plane alerts

bindata/network/ovn-kubernetes/common/008-script-lib.yaml, bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-control-plane.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/network/render.go
Enables TechPreview feature gate for NetworkSegmentation
Builds on top of https://github.com/openshift/cluster-network-operator/pull/2428
We will GA in the last sprint but we don't have to do anything given
we just need to bump it to default ON in API repo.
The new network CRD can also use this gate to be installed if the flag is ON
=> SDN-4934: Enable TechPreview FeatureGate for NetworkSegmentation

bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
Add RBAC permissions for the new EndpointSlice mirror controller. 
The services/finalizer update is required because the controller copies the ownerReference that might block serivce deletion.
=> SDN-4919: OVN-Kubernetes UDN: EndpointSlice mirror controller RBAC permissions

pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/platform/platform.go
While testing IPsec upgrade on 24 node cluster in CI, it's noticed
there are more than two (master, worker) machine config pools present.
For example infra and workload pools were present which belong worker
role. Hence this commit queries all machine config pools based on master
and worker roles and check ipsec plugin existence on every pool.
=> OCPBUGS-37205: Check every MachineConfigPool for IPsec plugin existence

bindata/cloud-network-config-controller/managed/controller.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/node-identity/managed/node-identity.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml, pkg/bootstrap/types.go, pkg/hypershift/hypershift.go, pkg/network/cloud_network.go, pkg/network/multus_admission_controller.go, pkg/network/node_identity.go, pkg/network/ovn_kubernetes.go
The HostedCluster object for hypershift recently got a [new feature](https://github.com/openshift/hypershift/pull/4339) that allows users creating HCP clusters to set custom tolerations on their HCP pods. The CNO needs to integrate this feature in the same way it integrated the NodeSelector feature for HCP.
=> CNV-43973: HCP custom tolerations integration 

bindata/network/iptables-alerter/002-script.yaml
Apparently under heavy node load, crictl may (sporadically) return errors like "timed out". In the linked bug, it is apparently failing on the "newtork namespace type" check and getting back `""`, which is not `"NODE"`, so it keeps going, and then apparently succeeds on the following crictl calls, and ends up doing an iptables rule check in the host network namespace and logging messages because it seems the host-network ovn-kubernetes iptables rules there.
=> OCPBUGS-37713: Handle random crictl errors in iptables-alerter

pkg/network/multus_admission_controller.go, pkg/network/multus_admission_controller_test.go
This code changes to introduce additional condition check for ignored-namespaces, whether the ns is openshift component or not
=> OCPBUGS-32706: Add conditions for ignored-namespaces

bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
Fix the use case for Public clusters that require a proxy to access the kube apiserver.
=> OCPBUGS-37786: Add proxy env vars to onvkube-node

bindata/cluster-network-operator/prometheus.yaml, pkg/controller/operconfig/operconfig_controller.go, pkg/network/render.go, pkg/util/ipsec/metrics.go
This is a backport of PR #[2270](https://github.com/openshift/cluster-network-operator/pull/2270) which added ipsec state metric to OCP V4.16, and PR #[2389](https://github.com/openshift/cluster-network-operator/pull/2389) which backported this to V4.15. Both these PRs are based on API change that was added to V4.15 - therefore this PR is a manual backport and not a cherry-pick since the API does not exist in V4.14 and will not be ported to this version due to compatibiilty reasons.
=> [release-4.14] OCPBUGS-37468: Backport ipsec state metric

bindata/network/ovn-kubernetes/common/008-script-lib.yaml, bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
This PR is to rollout ovnkube-node when there is a change in either ipv4 or ipv6 internalMasqueradeSubnet and done after cluster installation.
This PR also stops updating ovnkube-config configmap with ipv4 or ipv6 internalMasqueradeSubnet and instead updates ovnkube-script-lib configmap in openshift-ovn-kubernetes namespace so that CNO inbuilt logic can trigger ovnkube-node rollout.
=> SDN-5070: Allow day 2 customization of masquerade subnet

README.md, docs/architecture.md, docs/operands.md, hack/run-locally.sh, pkg/network/bootstrap.go, pkg/network/cluster_config.go, pkg/network/cluster_config_test.go, pkg/network/multi_network_policy_test.go, pkg/network/multus_admission_controller_test.go, pkg/network/multus_ipam_test.go, pkg/network/multus_test.go, pkg/network/network_metrics_test.go, sample-cluster-network-config.yaml, sample-config.yaml
#2384 dropped support for deploying openshift-sdn, but (to make it easier to review and merge) it didn't actually fully get rid of it. This PR does a little more:
1. In unit tests that are testing something non-plugin-specific, fix them to use ovn-k rather than openshift-sdn in the configuration.
2. Fix a bunch of docs, sample configs, comments, etc.
It would be nice to merge this for 1.17 but it's not necessary.
=> NO-JIRA: more openshift-sdn cleanup

bindata/cloud-network-config-controller/managed/controller.yaml, pkg/network/cloud_network.go
For ARO HCP, we need to be able to override the authentication type to be MSI. For more information please see openshift/enhancements#1659.
=> SDN-4773: Add Azure MSI Env Var for ARO HCP

bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml, pkg/bootstrap/types.go, pkg/names/names.go, pkg/network/ovn_kubernetes.go
Set the following default masquerade CIDRs in OVNKubernetes for new clusters:
IPv4: `169.254.0.0/17`
IPv6: `fd69::/112`
If the masquerade subnet is provided through the API it takes precedence over
the defaults.
There is no change for upgraded clusters. If not specified through the API the
default masquerade CIDRs are decided by OVNKubernetes and currently are:
IPv4: `169.254.169.0/29`
IPv6: `fd69::/125`
We went with  `169.254.0.0/17` instead of  `169.254.0.0/16` to avoid catching 169.254.169.254(cloud metadata IP).
Introduced the `networkoperator.openshift.io/default-masquerade-network-cidrs` annotation on the ovnkube-node daemonset that stores the new default CIDRs. This is needed to ensure that the values set during cluster creation are retained. The value of this annotation can differ …
=> SDN-4919: Change the masquerade subnet default value for new clusters 

bindata/network/multus/multus.yaml
For kubevirt passt binding to work a global nad is needed to be configured, this change allow nads being created at openshift-cnv namespace to be read from pods at different namespace kubevirt VMs can use passt with the nad at openshift-cnv
=> OCPBUGS-38176: multus, Add openshift-cnv to globalNamespace

bindata/network/ovn-kubernetes/common/alert-rules.yaml, bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/alert-rules-control-plane.yaml
* Moved distributed control plane alerts from master-rules to alert-rules.
* Tweaked the wording of the alerts to either reflect the enw component names or the distributed nature of them.
* Added OVNKubernetesNorthdInactive alert back with adjusted severity and duration.
(cherry picked from commit 53804c56a6a88950a59565f637d6bb4c31dccec7)
=> [release-4.14] OCPBUGS-38073: Fix IC distributed control plane alerts

bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml, pkg/client/list_pager.go, pkg/controller/operconfig/cluster.go, pkg/controller/operconfig/migration.go, pkg/controller/operconfig/operconfig_controller.go, pkg/network/cluster_config.go, pkg/network/cluster_config_test.go, pkg/network/ovn_kubernetes.go
Depends on https://github.com/openshift/cluster-network-operator/pull/2392
Metrics docs: https://docs.google.com/document/d/1QQJDtipDqSyLnOYkoEJ12QnV-g61d6BwDLY-aOpdZVw/edit
Cherry-picks was clean except 7d31ad2a3aea0bd6467dc760e98a0cdc752ecf8f
I needed to modify it to remove the config for masq and transit switch subnets.
=> OCPBUGS-34613,OCPBUGS-34726,OCPBUGS-34727: Live migration backports

bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml, pkg/network/ovn_kubernetes_test.go
The UDN CRD controller fails to create NAD objects due to the following error:
```
failed to create NetworkAttachmentDefinition: network-attachment-definitions.k8s.cni.cncf.io
"test-net1" is forbidden: cannot set blockOwnerDeletion if an ownerReference
refers to a resource you can''t set finalizers on: , <nil>
```
On OCP, the `OwnerReferencesPermissionEnforcement` [1] plugin is enabled.
It enforces the controller managed CRD object which is referred to as owner of another CRD
object has permissions to the managed CRD finalizers sub-resource [2].
The UDN CRD controller create NAD objects with owner-reference to the request UDN CR.
It fails to create NAD because it creates the NAD object with owner-reference to the
request UDN CR object, but the controller has no permissions to the referred …
=> OCPBUGS-38326: OVN-K, UDN CRD: Add missing permissions to control-plane

manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/image-references
This is required so hypershift's control-plane-operator will be able to deploy CNO with this image, extracted from the release payload.
This PR is a prerequisite for #2322
=> CONSOLE-3952: Add networking-console-plugin image to release payload

bindata/network/iptables-alerter/002-script.yaml
I'm not really sure why iptables-alerter is using a lot of CPU (or at least, why some people _think_ it's using a lot of CPU), but looking at what it does, the most likely CPU suck is `jq`. (Especially maybe if `crictl` returns A LOT of JSON for certain pods for some reason?)
So this fixes it to use golang template support instead, and also fixes it to make only a single call to `crictl` per pod. Also, while I was tracing the pod to try to figure out what was being slow, I realized there's really no point in checking if we already logged an event before even deciding if we want to log an event. (Running `iptables-save` is more work on the node itself, but running `kubectl` is probably more work for the cluster as a whole.)
=> NO-JIRA: iptables-alerter streamlining

bindata/networking-console-plugin/000-namespace.yaml, bindata/networking-console-plugin/001-config-map.yaml, bindata/networking-console-plugin/002-deployment.yaml, bindata/networking-console-plugin/003-service.yaml, bindata/networking-console-plugin/004-console-plugin.yaml, pkg/bootstrap/types.go, pkg/client/client.go, pkg/client/fake/fake_client.go, pkg/network/render.go, pkg/platform/platform.go
Use the CNO operator config controller to deploy and reconcile the resources required to enable the new Networking console plugin:
* Deployment (hosts the plugin pages contents via an nginx web server)
* Service (exposes the webserver to the console)
* ConfigMap (for nginx config)
* ConsolePlugin (binds the console with the dynamic plugin)
Also, enables the console plugin by adding it to the cluster Console plugins list.
Jira ticket: https://issues.redhat.com/browse/CONSOLE-3952
=> CONSOLE-3952: Deploy networking-console-plugin by CNO

pkg/network/cluster_config.go
=> OCPBUGS-39096: Live migration: report network overlap via live_migration_blocked metric

bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/node-identity/managed/node-identity.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
The combination of PDBs and antiaffinity rules prevent a rolling update with a surge of pods that have antiaffinity rules when a control plane lives in a single zone. This change ensures antiaffinity rules only apply when running HA in multiple zones.
=> OCPBUGS-29497: HyperShift: do not use antiaffinity on single replica control planes

pkg/bootstrap/types.go, pkg/network/cluster_config.go, pkg/network/cluster_config_test.go, pkg/network/render.go, pkg/network/render_test.go, pkg/platform/platform.go, pkg/util/util.go
In 4.15, we want to support SDN live migration for unmanaged clusters.
This's a manual cherrypick of #2321
=> [release-4.15] NP-1064, OCPBUGS-39336: Remove managed cluster checking for live migration

bindata/network/ovn-kubernetes/common/ipsec-host.yaml
Though IPsec mesh configuration is established for all the cluster nodes, IPsec session is not established at times on a certain pair of nodes and pod traffic is no longer works between those nodes. We can not find out the reason why that
happens. After the discussion with libreswan team (@ueno), `narrowing=yes` connection parameter helps to recover from the issue. Hence this PR rolls out this config for all IPsec connections.
/cc @huiran0826
=> OCPBUGS-35417: Configure narrowing=yes for IPsec connections

bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
This commit is to append configurable subnets while running hybrid-overlay-node binary in the process of live migration.
This change will prevent subnet overlap check to emmit an error when clusterNetwork CIDR overlps with either join or transit switch or masquerade default subnets even after those subnets have been customized by patching network.operator CR.
Cherry picked from https://github.com/openshift/cluster-network-operator/pull/2497/commits/2c15a6996d3115fc107a53d193790aa9150971f7
Note for reviewer : 4.16 does not support day 2 masquerade subnet modification and hence refraining from passing v4 and v6 masquerade subnet to hybrid-overlay-node binary.
=> [release-4.16] OCPBUGS-41840: Add configurable subnets while running hybrid-overlay-node binary

bindata/network/multus/multus.yaml
Necessary integration for https://github.com/openshift/multus-cni/pull/252 for graceful termination of the multus daemon.
=> OCPBUGS-42238: Updates terminationGracePeriodSeconds to 30 seconds for Multus daemonset

pkg/network/cloud_network.go, pkg/network/multus_admission_controller.go, pkg/network/node_identity.go
Add CLI_CONTROL_PLANE_IMAGE enavr to
cloud-network, multus-admission-controller and node-identity to avoid
registryOverrides propagating to data plane components
=> HOSTEDCP-1981: Add controlplane cli image envar for use with hypershift

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
Allow ovnkube-node to watch CSRs to avoid unecessary warnings in the API audit logs.
=> OCPBUGS-42472: Add certificatesigningrequests/watch RBAC to ovnkube-node

bindata/network/ovn-kubernetes/common/ipsec-host.yaml
The `ovn-ipsec-host` DaemonSet manifest file hardcoded `host-cni-netd` mount point with `/var/run/multus/cni/net.d `directory, but this won't work when multi network is disabled via `disableMultiNetwork` parameter as ovn-k uses `/etc/kubernetes/cni/net.d` directory to write cni config file for this case. So this PR fixes host path to use `CNIConfDir` tag.
=> OCPBUGS-42449: Use CNIConfDir for mounting directory to ovn-ipsec-host pod

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
This is a follow up to https://github.com/openshift/cluster-network-operator/pull/2524.
Allow to read userdefinednetworks only when the featuregate is enabled.
/cc @tssurya @trozet
=> NO-JIRA: OVN-Kubernetes node RBAC tightening

bindata/network/multus-networkpolicy/multus-networkpolicy.yaml
Make the multus-networkpolicies iptables implementation work with `ipvlan` and `bond` network types.
=> CNF-14257, CNF-14251: multi-networkpolicy: Enable for `ipvlan` and `bond` networkds

bindata/network/frr-k8s/frr-k8s.yaml, bindata/network/frr-k8s/monitor.yaml, pkg/network/render_test.go
Few adjustments required to make the frr-k8s metrics to appear under prometheus.
Tested locally, will be tested under CI.
=> CNF-13671: Adjust frr-k8s metrics

bindata/network/frr-k8s/frr-k8s.yaml
We set an optional env variable from the configmap in order to drive the loglevel of the daemonset.
=> CNF-14971: frr-k8s: allow setting the loglevel from env-overrides

bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
By checking the environment varialbe NODE_CNI, the CNI processes can know if it shall run in the live migration mode.
=> OCPBUGS-42605: OCPBUGS-42244: Exporting environment varialbe NODE_CNI for live migration

bindata/cloud-network-config-controller/managed/controller.yaml, pkg/network/cloud_network.go
Passes the appropriate env var in order to authenticate with Azure with certs for ARO HCP
=> HOSTEDCP-2035: Set up Azure authentication with cert for ARO HCP

bindata/networking-console-plugin/002-deployment.yaml
The annotation should not be added to the deployment but should be added to the pod.
=> OCPBUGS-39189: fix annotation from deployment to pod

manifests/02-cncc-credentials.yaml
GCP recently [added new permissions to roles/compute.admin][1]:
> h2. Upcoming IAM changes for the week of 2024-10-21
> ...
> Compute Engine
> The following permissions have been added to the Compute Admin role (roles/compute.admin):
>
> * `backupdr.backupPlanAssociations.create`
> * `backupdr.backupPlanAssociations.createForComputeInstance`
> ...
The network operator doesn't need those permissions, but it confuses the cloud credential operator, resulting in failures issues [like][2]:
```console
level=error msg=Cluster operator cloud-credential Degraded is True with CredentialsFailing: 2 of 7 credentials requests are failing to sync.
level=info msg=Cluster operator cloud-credential Progressing is True with Reconciling: 5 of 7 credentials requests provisioned, 2 reporting errors.
... …
```
=> OCPBUGS-43821: manifests/02-cncc-credentials: Set skipServiceCheck for GCP

bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, pkg/network/ovn_kubernetes_test.go
This has to wait for https://github.com/openshift/ovn-kubernetes/pull/2314
=> SDN-4930: UDN: Allow access to default/kubernetes and openshift-dns/dns-default

bindata/network/ovn-kubernetes/common/008-script-lib.yaml
In OVN-K, we use function CheckForOverlaps() to check if there is any overlapping among the subnet CIDRs in the configuration. If we don't pass the transit_switch_subnet options, ovnkube will use the default transit_switch_subnet in this check instead of the real one. So we pass this options to in ovnkube-node pod, although it's not actually used there.
=> OCPBUGS-43740: Pass transit_switch_subnet options in ovnkube-node pod

pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/platform/platform.go
There was a regression issue found with libreswan 4.9 which breaks pod-to-pod traffic over ipsec tunnels. The libreswan and its dependent packages are installed by ipsec machine config extension which is rolled out by network operator.   So we must rollback to libreswan 4.5 to fix the problem, but this is not directly possible with ipsec machine config extension.
As an immediate workaround (until it gets fixed properly in next libreswan release), we must skip network operator from rendering its own machine config and allow users to install their own machine config and it can install previous version of libreswan (say 4.5) which is working fine now with OCP. 
This PR adds required changes to allow for user owned ipsec machine configs to be present with a condition that it must have …
=> SDN-5436: Provide support for user owned IPsec machine configs

bindata/network/ovn-kubernetes/common/ipsec-host.yaml
The ovn-ipsec container for the ovn-ipsec-host pod has libreswan installed and uses its ipsec command to configure ipsec service running on the host. But there is a chance versions of libreswan installed on the host and container may be different. This causes coredump on the ipsec service while running ipsec whack command from the container. 
This PR mounts ipsec binary and its dependent libraries from the host to avoid incompatibility behavior.
=> SDN-5436: Use host ipsec binary inside ovn-ipsec container 

bindata/network/ovn-kubernetes/common/001-crd.yaml, bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml, pkg/network/ovn_kubernetes_test.go
Add the `ClusterUserDefinedNetwork` CRD definition and the backing controller required RBAC, introduced by https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4612.
=> SDN-5472: bindata, ovn-k: Add ClusterUserDefinedNetwork CRD and RBAC

bindata/allowlist/daemonset/daemonset.yaml
Otherwise, sometimes this fails intermittently in CI. Borrowed request amount pattern from other CNI plugin installations.
=> OCPBUGS-44344: The sysctl allowlist daemonset should set requests for memory and cpu

bindata/network/ovn-kubernetes/common/ipsec-host.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/platform/platform.go
Manual cherry-pick of 94a09504ef0c08c760fad9d525577755e9dcc79c and 125851f45840ff9355de482c2c276ea321ed7c92.
Resolved conflicts:
`pkg/network/ovn_kubernetes_test.go` (in `import` section and setting `featureGatesCNO`)
=> [release-4.17] OCPBUGS-44779, SDN-5436: Provide support for user owned IPsec machine configs

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
Allow to read userdefinednetworks only when the featuregate is enabled
=> [release-4.17] OCPBUGS-44807, SDN-4930, SDN-5297: OVN-Kubernetes node RBAC tightening

bindata/network/ovn-kubernetes/common/ipsec-host.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/platform/platform.go
Manual cherry-pick of 4.17 commits 2fc56fc006d3312c8231d5c676e2746e38cf7792 and b8a074a9c85f282727a677f4a188bc78834edcff.
Resolved conflicts:
`pkg/network/ovn_kubernetes.go` (import section)
`pkg/network/ovn_kubernetes_test.go` (with featureGatesCNO variable)
`pkg/platform/platform.go` (needed to remove unnecessary function that came from 4.17)
=> [release-4.16] OCPBUGS-44846, SDN-5436: Provide support for user owned IPsec machine configs

bindata/cloud-network-config-controller/managed/controller.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/node-identity/managed/node-identity.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml, pkg/bootstrap/types.go, pkg/hypershift/hypershift.go, pkg/network/cloud_network.go, pkg/network/multus_admission_controller.go, pkg/network/node_identity.go, pkg/network/ovn_kubernetes.go
HCP is adding a new API field to allow users creating HCP clusters to set custom labels on all HCP pods https://github.com/openshift/hypershift/pull/5114. The CNO needs to integrate this feature in the same way it integrated the NodeSelector feature for HCP.
=> OCPBUGS-44950: Propagate HCP pods labels to 2nd level operands

pkg/operator/operator.go
The metrics server was incorectly enabled in acd67b432be4ef2efb470710aebba2e3551bc00d.
Revert this behavior by specifying the metrics port in the options.
Kudos to @pperiyasamy for finding the rootcause.
=> OCPBUGS-42189: Re-disable metrics server

bindata/network/ovn-kubernetes/common/008-script-lib.yaml
In OVN-K, we use function CheckForOverlaps() to check if there is any overlapping among the subnet CIDRs in the configuration. If we don't pass the transit_switch_subnet options, ovnkube will use the default transit_switch_subnet in this check instead of the real one. So we pass this options to in ovnkube-node pod, although it's not actually used there.
(cherry picked from commit 82c53dcfcc990ec449a217c47625bd8dccca8a87)
Conflict: Fixed a merge conflict and it was due to masquerade subnet not being added as a flag to ovnkube running in ovnkube-controller in release-4.16.
=> [release-4.16] OCPBUGS-45593: Pass transit_switch_subnet options in ovnkube-node pod

bindata/network/ovn-kubernetes/common/ipsec-host.yaml
The ovs-monitor-ipsec doesn't set authby, so when it calls ipsec auto --start the default ones defined at Libreswan's compile time will be used. On restart, Libreswan will use authby from libreswan.config. If libreswan.config is incompatible with the Libreswan's compiled-in defaults, then we'll have an authentication problem. But OTOH, ovs-monitor-ipsec does set ike and esp algorithms, so those may be incompatible with libreswan.config as well. Hence commenting out the "include" from libreswan.conf to avoid such conflicts.
@igsilya proposed [fixes](https://patchwork.ozlabs.org/project/openvswitch/list/?series=436137&state=*) in ovs to solve this problem in a proper way, When these changes are consumed, the current workaround should be replaced with `--root-ipsec-conf` and …
=> OCPBUGS-46065: Skip including default crypto policies to avoid authby issue

bindata/network/ovn-kubernetes/common/ipsec-host.yaml
Resolved conflict on the file `bindata/network/ovn-kubernetes/common/ipsec-host.yaml` (introduced by 4.19 PR https://github.com/openshift/cluster-network-operator/pull/2372 which gets cherry-pick into 4.18 with https://github.com/openshift/cluster-network-operator/pull/2592).
=> [release-4.18] OCPBUGS-43713: Skip including default crypto policies to avoid authby issue

pkg/controller/operconfig/operconfig_controller.go
The first step in an offline migration is settingspec.migration.networkType, which triggers the cluster to update the MachineConfigPools. It also triggers feature migration, the egress IP previously assigned by the SDN will be released. At this stage, however, OVN-K is not yet deployed; the SDN continues to manage networking, allowing the egress IP functionality to remain operational. Therefore, we postpone the feature migration until after spec.default.type has been
modified. It can help to reduce the downtime for egressIP during SDN migration. The impact for live migration is similar.
=> [release-4.16] OCPBUGS-43803: Start feature migration when the cluster CNI is changed to the target type

bindata/network/ovn-kubernetes/common/udn-admission-policy.yaml, pkg/network/ovn_kubernetes_test.go
UDN namespace label will be required when namespaces are created in order to use a primary UDN in that namespace.
Upstream PR: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4912
=> OCPBUGS-42609: Disable adding/removing the UDN namespace label

bindata/network/ovn-kubernetes/common/80-ipsec-master-extensions.yaml, bindata/network/ovn-kubernetes/common/80-ipsec-worker-extensions.yaml, bindata/network/ovn-kubernetes/common/ipsec-host.yaml
This PR does the following to fixes to prevent unnecessary ipsec service restart, ip xfrm state policy cleanups while bringing up ipsec-host pod. This would potentially avoid reestablishment of IKE SAs during ipsec pod restarts and let OVN networking pods traffic go on without any packet drops.
1. There is an incorrect check in ipsec pod clean up logic which removes `/etc/ipsec.d/openshift.conf` file, ip xfrm state and policy entries in all cases, but these must be removed only when ipsec mode is changed from full to external or disabled.
2. We don't need narrowing=yes option to be set explicitly anymore because system default crypto policies are commented out now, otherwise `TS_UNACCEPTABLE` error is seen temporarily at the time of ipsec service restart.
3. The IPsec service restart is …
=> SDN-4168: Cleanup ipsec state only when ipsec is not full mode

bindata/network/ovn-kubernetes/managed/common/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/common/004-config.yaml, pkg/network/ovn_kubernetes_test.go
The single-zone mode is a phase in the multi-step upgrade process for IC. To ensure the subnet overlapping check uses the customized value, it is necessary to pass the transit_switch_subnet parameter to ovn-k when configuring this mode.
=> OCPBUGS-48323: Pass transit_switch_subnet options in ovnkube-node pod for single-zone

pkg/network/ovn_kubernetes.go
The following change on the machine pool:
`status.MachineCount == status.UpdatedMachineCount && hasSourceInMachineConfigStatus(status, machineConfigs)` 
is introduced with PR https://github.com/openshift/cluster-network-operator/pull/2349 which ensures IPsec machine config is always installed on all the nodes in the cluster,
So this is deleting the IPsec daemonset as per the CNO state machine for IPsec when the condition is not met. But this is also accidentally disabling IPsec in OVN which is not an expected behavior. This causes ovs-monitor-ipsec to refresh existing ipsec connections unnecessarily when IPsec pod comes up as it is not able to find remote_name from the tunnel. This may also trigger deleting IPsec connection entries from openshift.conf file if ovs-monitor-ipsec is not …
=> SDN-5330: Keep IPsec in OVN enabled during the upgrade

bindata/network/ovn-kubernetes/common/001-crd.yaml
This PR updates the egressfirewall CRD with the latest CRD from the ovk-kubernetes repo. This fixes the issue of mismatch of regex validation of the DNS name field between the two CRDs.
=> OCPBUGS-46564: Update egressfirewall CRD to be consistent with ovn-kubernetes repo

bindata/network/ovn-kubernetes/common/007-rbac-cluster-reader.yaml, bindata/network/ovn-kubernetes/common/009-rbac-udn-editor.yaml, bindata/network/ovn-kubernetes/common/010-rbac-udn-viewer.yaml, pkg/network/ovn_kubernetes_test.go
Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2619 
The last commit add unit tests from [[1]](https://github.com/openshift/cluster-network-operator/pull/2442), except for the RA unit test because its not reach relase-4.18 branch yet.
Adding the those changes should help preventing cheery-pick conflicts with future PR that depends on those tests.
[1] https://github.com/openshift/cluster-network-operator/pull/2442
=> [release-4.18] OCPBUGS-48443: ovn-k, rbac: Enable users read & modify UserDefinedNetwork CRs

bindata/network/ovn-kubernetes/common/001-crd.yaml
In the previous validation rule, valid IPv6 subnets would mistakenly invalidate the CustomResource.
Reflecting the changes happening upstream in https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5018
=> OCPBUGS-49621:Fix UDN and CUDN hostSubnet validation

bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml, pkg/network/ovn_kubernetes_test.go
(cherry picked from commit ce522688ae00349fc0aa438de4d99835ed80f6c8)
=> OCPBUGS-49670: OVNK should be able to annotate network ID on NADs

bindata/network/frr-k8s/001-crd.yaml, bindata/network/frr-k8s/frr-k8s.yaml, bindata/network/frr-k8s/webhook.yaml
specifically, we bring the healthcheck change and unnumbered support.
=> OCPBUGS-48312: frr-k8s: align manifests with operator

pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
The commit https://github.com/openshift/cluster-network-operator/commit/4e57dcd195992dd6d19b2d1a731d6673c9ee2e4b is not complete because `OVNIPsecStatus` is still not set when none of the IPsec daemonset exists on the cluster at the time of machine config pools are updating
(or) node is rebooted. Hence fixing it by `OVNIPsecStatus` is always set to reflect ipsec deployment state of the cluster
and update the render pipeline to render ovn ipsec for the above mentioned scenarios.
It renders ovn ipsec even before ipsec daemonsets are deployed when IPsec is freshly enabled on the cluster. That's ok	because It will be effective only when the `ovs-monitor-ipsec `script is started and that's going to be done only when the ipsec pod is running. so we are safe to ignore it now.
When IPsec is …
=> SDN-5330: Keep rendering OVN IPsec when its daemonset not available

bindata/network/multus/multus.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/common/008-script-lib.yaml
As we move to using pure centos bootimages for OKD, support the "centos" ID as the ID will not be "scos" anymore.
=> NO-JIRA: Add "centos" to supported OS ids

bindata/network/multus/002-rbac.yaml, bindata/network/multus/multus.yaml, pkg/network/multus.go, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
cc @dougbtv 
Add whereabouts controller and necessary RBAC to enable fast ranges in openshift
Currently pointing to personal image, but when dockerfile change merges in o/wherabouts i will correct the image ref and remove the hold
=> NP-1100: Enable fast ranges

bindata/network/frr-k8s/webhook.yaml
We change the webhook name so  that the operator and CNO do not attempt to modify eachother's resources, e.g the operator deleting the webhook created by CNO.
=> OCPBUGS-52361: frr-k8s: rename validatingwebhook name

bindata/network/frr-k8s/frr-k8s.yaml, bindata/network/frr-k8s/webhook.yaml
cherry-pick from 4.19 https://github.com/openshift/cluster-network-operator/pull/2615, without the unnumbered api changes that are not supported in 4.18
=> OCPBUGS-48305: frr-k8s: align manifests with operator

bindata/network/ovn-kubernetes/common/007-rbac-cluster-reader.yaml, bindata/network/ovn-kubernetes/common/009-rbac-udn-editor.yaml, bindata/network/ovn-kubernetes/common/010-rbac-udn-viewer.yaml, pkg/network/ovn_kubernetes_test.go
This PR is manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2627 
The automated cherry-pick wont pass CI because it require manual changes https://github.com/openshift/cluster-network-operator/pull/2640
=> [release-4.17] OCPBUGS-49816: ovn-k, rbac: Enable users read & modify UserDefinedNetwork CRs

bindata/cloud-network-config-controller/managed/controller.yaml, pkg/network/cloud_network.go
This PR updates the parameters needed for authentication with Azure on managed Azure HCP for the new managed Azure HCP authentication type, UserAssignedIdentityCredentials.
See [Persisting MSI Credentials](https://docs.google.com/document/d/1tX2avo8ORyjqL4GJNwxq-wQTM3-LC7zBTP5V9EgwU74/edit?tab=t.0#heading=h.12bfa2iapy8v) for more info.
=> CNTRLPLANE-112: Update managed Azure HCP cloud network config

pkg/controller/clusterconfig/migration.go, pkg/network/cluster_config.go, pkg/network/cluster_config_test.go
If spec.migration.features of the network.operator CR, CNO will update the status.migration of the network.config CR to an empty value '{}'. It prevents CNO from proceeding with live migration. This shall be fixed in CNO.
Only update status.migration.network of the network.config CR when the spec.migration.network of network.operator CR is set.
=> [Release 4.16] OCPBUGS-50712: Not update status.migration of the network.config CR to empty

bindata/network/ovn-kubernetes/common/ipsec-containerized.yaml, bindata/network/ovn-kubernetes/common/ipsec-host.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/platform/platform.go, pkg/version/semver.go, pkg/version/semver_test.go
When a machine config pool is in a paused state, then it doesn't process any machine config. so during legacy IPsec upgrade (`4.14->4.15`), IPsec machine configs may not be installed on the nodes when its pool is in paused state.
In those cases the network operator continues to render older IPsec daemonsets which blocks network components from not getting upgraded to newer versions.
Hence this PR renders newer IPsec daemonsets immediately, with new `IPsecCheckForLibreswan` check ensures one of the pods serves IPsec for the node. When MCPs are fully rolled out with ipsec machine config, then it goes ahead with rendering only host flavored IPsec daemonset.
It brings in new behavior on IPsec daemonset rendering during IPsec deployment, upgrade and node reboot scenarios.
1. Users would notice …
=> OCPBUGS-52280: Move to use newer IPsec DaemonSets irrespective of MCP state

bindata/network/frr-k8s/webhook.yaml
clean cherry-pick from https://github.com/openshift/cluster-network-operator/pull/2659
=> OCPBUGS-52837: frr-k8s: rename validatingwebhook name

bindata/network/multus/multus.yaml, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
Using the shim to deploy the controller causes the controller to error out, auto-deploy works
=> OCPBUGS-5241: Auto opt in for whereabouts-controller

bindata/network/frr-k8s/frr-k8s.yaml
Just as ovnkube-node, frr-k8s daemon set is an infrastructure component and should be deployed regardless of taints. This solves frr-k8s pods not being deployed on nodes labeled with node-role.kubernetes.io/infra and tainted with NoSchedule.
=> OCPBUGS-54159: frr-k8s: tolerate all taints

bindata/networking-console-plugin/001-config-map.yaml
Add an additional listen directive that will catch IPv6-originated requests towards the nginx server that serves the networking-console-plugin manifests.
=> OCPBUGS-53180: Add IPv6 NGINX configuration

pkg/controller/signer/signer-controller.go, pkg/controller/signer/signer_test.go
In CNO we have an approver that signs certs automatically, without checking any identity information, so this PR enhances  the signer to check on CSR's user name that is populated by API server upon receiving CSR request from the nodes.  So it's sufficient to verify the user name before signing the CSR.
It also adds required unit  tests to test signer controller, it needed to change from using `kubernetes.Clientset` to `cnoclient.Client` for accessing CSR's UpdateApproval API. This needs to be tested on OCP cluster.
cc @kyrtapz @trozet @jcaamano
=> SDN-5342: Signer username validation

manifests/02-cncc-credentials.yaml
Although the issue was found while testing on AKS it is not specific to it.
This also affects standalone Azure deployments.
=> OCPBUGS-54837: Add missing backendAddressPools read permission on azure

bindata/network/frr-k8s/frr-k8s.yaml
Now that the changes are merged in the code, we
can update the manifests to include the frr-status exporter in charge of creating the actual resources.
=> CNF-16707: frr-k8s: wire the frr-status sidecar container

pkg/controller/signer/signer-controller.go, pkg/controller/signer/signer_test.go
When CSR signing reattempt happens, signer controller is not updating existing `CertificateFailed` condition type, instead it tries to add another `CertificateFailed` condition and leads to Duplicate value: "Failed" error in the network co status,
```
% oc get co network
NAME      VERSION                                                   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
network   4.19.0-0.ci.test-2025-03-26-015315-ci-ln-g8dqch2-latest   True        False         True       4h      Unable to update csr: CertificateSigningRequest.certificates.k8s.io "ipsec-csr-test-80237" is invalid: status.conditions[1].type: Duplicate value: "Failed"
```
Fixing it just by updating existing `CertificateFailed` condition so that network status don't get updated unnecessarily for this …
=> OCPBUGS-54238: Update CSR status condition appropriately

bindata/network/multus/multus.yaml
Using the `auxiliaryCNIChainName` feature which isolates executions to an independent CNI chain.
See also [this gist](https://gist.github.com/dougbtv/52ecdc17a7601d26312f7fd3fa49dc5d) with a demo about how to operate it.
=> OCPBUGS-55090: Configures subdirectory based CNI chain loading

bindata/network/ovn-kubernetes/common/008-script-lib.yaml, pkg/network/ovn_kubernetes.go
There is a requirement to encapsulate IPsec east west traffic in UDP via NAT-T so that those packets are compatible with intermediate NAT device(s) if present. This PR consumes new API to enable or disable encap option and applies to
OVN to configure east west ipsec tunnel connections accordingly.
API PRs:
https://github.com/openshift/api/pull/1472
https://github.com/openshift/api/pull/2199
=> OCPBUGS-40906: Implement IPsec NAT-Traversal encapsulation option

bindata/network/ovn-kubernetes/common/001-crd.yaml
Add CEL validation on OVN-K CUDN CRD for localnet to topology,  to ensure the specified `excludeSubnetes` match the specified `subnets`.
**Note to reviewer:**
This change make the CRD diverge from the CRD on U/S due to a bug [[1]](https://issues.redhat.com/browse/OCPBUGS-54426) that its fix is available on D/S [[2]](https://github.com/openshift/kubernetes/pull/2263) [[3]](https://github.com/openshift/kubernetes/pull/2267) but not available on U/S yet.
Once the fix is available on U/S, the CRD definition in OVN-Kubentes repo should have the same CEL validation this PR adds, tracked by [[4]](https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5195).
[1] https://issues.redhat.com/browse/OCPBUGS-54426
[2] https://github.com/openshift/kubernetes/pull/2263
[3] …
=> OCPBUGS-55285: bindata,ovn-k,cudn: Validate loclanet topology's excludeSubnet match specified subnets

bindata/cloud-network-config-controller/managed/controller.yaml, pkg/network/cloud_network.go
This commit removes the environment variables related to ARO HCP managed identity version 2. These environment variables are no longer needed for ARO HCP managed identity version 3.
=> OCPBUGS-55488: Remove environment variables related to ARO HCP MIv2 for CNO

bindata/cloud-network-config-controller/managed/controller.yaml, bindata/network/node-identity/managed/node-identity.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
Not all containers deployed in HyperShift had the terminationMessagePolicy set.
@martinkennelly ptal
=> OCPBUGS-56051: Configure the terminationMessagePolicy for all containers deployed in HyperShift

pkg/controller/allowlist/allowlist_controller.go, pkg/controller/clusterconfig/clusterconfig_controller.go, pkg/controller/configmap_ca_injector/controller.go, pkg/controller/controller.go, pkg/controller/dashboards/dashboard_controller.go, pkg/controller/egress_router/egress_router_controller.go, pkg/controller/infrastructureconfig/infrastructureconfig_controller.go, pkg/controller/ingressconfig/ingressconfig_controller.go, pkg/controller/operconfig/operconfig_controller.go, pkg/controller/pki/pki_controller.go, pkg/controller/proxyconfig/controller.go, pkg/controller/signer/signer-controller.go, pkg/controller/signer/signer.go, pkg/operator/operator.go
Implements https://github.com/openshift/enhancements/pull/1670
Short Cert Rotation [job](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-gcp-modern/1928000959246503936)
=> CNTRLPLANE-341: Issue shorter certificates when ShortRotation featuregate is enabled

pkg/network/render.go, pkg/network/render_test.go
The function isMigrationChangeSafe reports error when feature migration configured explicitly. It prevent the live migration from being completed at the last step, when the clusterconfig controller remove the flags spec.migration.networkType and spec.migration.mode.
Manual cherry-pick, resolve the conflicts in pkg/network/render_test.go by removing the func `Test_renderNetworkDiagnostics`.
=> [release-4.15] OCPBUGS-56649: Fix live migration with feature migration configured explicitly

bindata/network/multus/multus.yaml
In changing to using the flatfile configuration for usage as a configmap, we clobbered the name that we use for allowing overriding the reconciler schedule.
See also: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/networking/multiple-networks#nw-multus-configuring-whereabouts-ip-reconciler-schedule_configuring-additional-network
=> OCPBUGS-56878: whereabouts-config is a reserved name for user interaction.

bindata/network/multus-admission-controller/003-webhook.yaml
This should save up calls to the webhook and reduce latency when a NAD is updated to add labels or annotations.
The root cause of the change is the OVNK BGP feature: when BGP is enabled for the cluster default network, reconfiguration might cause temporary disruptions. As part of this reconfiguration and necessary to complete it, OVNK depends on annotating an internal NAD. We want to avoid having to reach the webhook for this annotation because the temporary disruption might prevent it and in that case the reconfiguration won't complete.
Another possibility would be to filter out from validation the specific internal NAD but this current approach might be more beneficial overall.
/cc @kyrtapz @dougbtv
=> OCPBUGS-56086: Validate NAD name and spec only in multus admission controller

bindata/network/frr-k8s/webhook.yaml
Instead of relying on the metrics port to understand when the webhook is ready, we try to hit the endpoint of the webhook itself, so the webhook pod is going to be ready only when it is effectively able to serve.
This is aligned with the frr-k8s binary change where we add a new endpoint "healtz" to the webhook server.
This is also required for https://github.com/openshift/frr/pull/93 where we disable the metrics endpoint as part of making the webhook hostnetworked.
=> CNF-18236: FRRK8s webhook: webhook liveness / readiness from metrics to webhook

bindata/network/multus/002-rbac.yaml, bindata/network/multus/multus.yaml, pkg/network/multus.go, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
update install-cni script to match whereabouts bin so that we get cert rotatation in openshift
we have to break the tokenwatcher section of the whereabouts script out because it was running in an init container, so it would never "complete", hanging the rollout
to accomplish this I created a new whereabouts watcher ds to house this section of the script
IMPORTANT: to enable the token watcher to run you must have the the whereabouts shim in your network object
https://docs.openshift.com/container-platform/4.12/networking/multiple_networks/configuring-additional-network.html#nw-multus-creating-whereabouts-reconciler-daemon-set_configuring-additional-network 
(cherry picked from commit 6e82842306a2722188b7af48d3a73b4bdd36c0e4)
=> OCPBUGS-58047: Add cert-rotation script into cno

bindata/network/frr-k8s/001-crd.yaml, bindata/network/frr-k8s/webhook.yaml
Align to upstream:
- FRRK8s webhook becomes hostnetworked and we change the port to one in the allowed range in https://github.com/openshift/enhancements/blob/master/dev-guide/host-port-registry.md (still need to be registered)
- The DisableMP is deprecated, the default behavior is single stack ipfamily, a dualstackIPFamily flag is added for backward compatibility.
=> CNF-18237: Align frrk8s manifests to upstream

pkg/controller/ingressconfig/ingressconfig_controller.go, pkg/controller/ingressconfig/ingressconfig_controller_test.go, pkg/controller/ingressconfig/mocks_test.go
This PR updates the CNO to conditionally watch the IngressController resource only when the Ingress capability is enabled. When Ingress is disabled in HyperShift, the IngressController CRD is not available. Without this change, CNO attempts to watch a non-existent resource and repeatedly restarts. This update prevents that by skipping the watch when the capability is disabled.
**Assisted-by:** Cursor
=> OCPBUGS-58155: CNO must skip watching IngressController if Ingress capability is disabled in HyperShift

bindata/network/ovn-kubernetes/common/008-script-lib.yaml
This is necessary to enable asymmetric traffic for advertised Layer2 networks running in local gateway mode.
=> CORENET-5881: Reconfigure NBDB for route advertisements in LGW

bindata/network/multus/multus.yaml
Add target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}' annotation to whereabouts-controller deployment to satisfy
_sig-node__apigroup_config.openshift.io__CPU_Partitioning_cluster_platform_workloads_should_be_annotated_correctly_for_Deployments__Suite_openshift/conformance/parallel_ job
Remove resource limits on whereabouts controller to satisfy ShiftOnStack
conformence test `Pods in platform namespaces are not following resource
request/limit rules or do not have an exception granted`
=> OCPBUGS-59135,OCPBUGS-59134: Annotate whereabouts-controller

bindata/network/ovn-kubernetes/common/008-script-lib.yaml, bindata/network/ovn-kubernetes/managed/004-config.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/004-config.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-control-plane.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Following https://github.com/openshift/enhancements/pull/1793, https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5238 and https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5332
This PR makes CNO enable OVN-K feature (EnableCustomNetworkConfig) when PreconfiguredUDNAddresses is enabled
=> CORENET-6127: ovn-k: Enable OVN-K feature when PreconfiguredUDNAddresses is enabled

pkg/network/ovn_kubernetes_test.go
This PR is to quickly remove FeatureGatePersistentIPsForVirtualization due to [openshift/cluster-network-operator#2737](https://github.com/openshift/cluster-network-operator/pull/2737)
=> NO-JIRA: remove PersistentIPsForVirt FG

OWNERS_ALIASES
Removing trozet as he left the company. Adding tssurya as team lead replacement.
Adding pliurh as approver replacing dougbtv who will be eventually removed after some soak period as he moved on to other unrelated projects. pliurh has demonstrated extensive experience working on this repository througout his work on sdn->ovnk different migration modes.
Added bpickard22 to help as a reviewer for multus related changes as a replacement for dougbtv.
=> NO-JIRA: Update CNO reviewers/approvers

bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go
Now that IBM ROKS is working on OVN support for Hypershift cluster, we need to run the ovnkube-control-plane pods as a non-root user if at all possible.  This change will run the ovnkube-control-plane pods as the RUN_AS_USER from the cluster-network-operator the same way that multus-admission-controller pods currently do.
=> CORENET-6247: Set runAsUser for ovnkube-control-plane

bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml, pkg/network/ovn_kubernetes_dpu_host_test.go
- Add conditional logic to both ovnkube-node.yaml templates to exclude OVN database and control plane containers (ovn-controller, ovn-acl-logging, kube-rbac-proxy-ovn-metrics, northd, nbdb, sbdb) when OVN_NODE_MODE=dpu-host
- Ensure only essential containers (ovnkube-controller, kube-rbac-proxy-node) run in dpu-host mode for both managed and self-hosted deployments
- Add comprehensive unified tests covering both template types across all OVN_NODE_MODE values (full, smart-nic, dpu-host) with container validation, YAML validity checks, and Azure platform compatibility
This enables DPU host nodes to run minimal OVN components while maintaining full functionality for other deployment modes.
=> MGMT-20706: fix DPU host mode support for  OVN templates

bindata/network/ovn-kubernetes/common/008-script-lib.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
This change introduces a mechanism to provide hidden or experimental configuration to OVN-Kubernetes through a ConfigMap. This provides a flexible way to enable advanced or experimental OVN-Kubernetes features without modifying the CNO API.
A new ConfigMap 'ovn-kubernetes-config-overrides', is now read by the operator during the bootstrap process. The key-value data from this ConfigMap is passed down to the OVN-K components.
As an initial implementation, this is used to support the flag 'udn-isolation-mode' which is to enable user to select the UDN isolation mode between 'loose' and 'strict'. If unset, the default mode is 'strict'.
=> OCPBUGS-55962: Allow overriding OVN-Kubernetes configuration

bindata/cloud-network-config-controller/managed/controller.yaml, bindata/network/node-identity/managed/node-identity.yaml, bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml, pkg/bootstrap/types.go, pkg/network/cloud_network.go, pkg/network/node_identity.go, pkg/network/ovn_kubernetes.go
priorityClass can be specified in the HostedControlPlane for hypershift managed clusters.  When it is specified, it should be used by the control plane components.  Currently the cluster-network-operator deployment and the multus-admission-controller deployment do use the priority class that is specified, but the ovnkube-control-plane and network-node-identity deployments do not, they use a hardcoded value.
This change updates the ovnkube-control-plane and network-node-identity deployments to use teh priorityClass from the HostedControlPlane if it is specified
=> CORENET-6276: Use priorityClass from HostedControlPlane for OVN and NNI

bindata/network/multus-admission-controller/003-webhook.yaml, bindata/network/ovn-kubernetes/common/001-crd.yaml, bindata/network/ovn-kubernetes/common/default-net-annotation-policy.yaml, pkg/network/multus_admission_controller.go, pkg/network/multus_admission_controller_test.go, pkg/network/ovn_kubernetes_test.go, pkg/network/render.go, pkg/network/render_test.go
Introduce the following changes behind the featuregate:
- Layer2 (Cluster) UDN API update: Add new API fields to both CUDN and UDN CRDs behind the PreconfiguredUDNAddresses featuregate
- Add ValidatingAdmissionPolicy blocking v1.multus-cni.io/default-network updates: Prevent modification of v1.multus-cni.io/default-network once a pod is created, applies to environments with PreconfiguredUDNAddresses featuregate enabled
-  Avoid multus-admission webhook race with ovn-kubernetes: Add CEL expression to ignore default/openshift-ovn-kubernetes NAD to prevent circular dependency where ovn-k fails to start because multus webhook blocks NAD creation, while webhook uses cluster-networked pods which require ovn-k to be running
=> CORENET-6130, CORENET-6261, CORENET-6092: Implement PreconfiguredUDNAddresses API changes

bindata/network/node-identity/managed/node-identity.yaml, pkg/network/node_identity.go
We should be running the network-node-identity pods as the user specified in the cluster-network-operator container's RUN_AS_USER environment variable if it is specified).   We already do this for the multus-admissions-controller:
- https://github.com/openshift/cluster-network-operator/blob/f41e188873b952c6dd0d41d89fdc7c63da51fc7f/pkg/network/multus_admission_controller.go#L96
- https://github.com/openshift/cluster-network-operator/blob/f41e188873b952c6dd0d41d89fdc7c63da51fc7f/bindata/network/multus-admission-controller/admission-controller.yaml#L264-L267
and recently in PR https://github.com/openshift/cluster-network-operator/pull/2757/files I added this for ovnkube-controll-plane. This PR does the same thing for network-node-identity.
I tested this in a ROKS cluster that I had running …
=> CORENET-6306: Set RunAsUser for network-node-identity

bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml, bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml, hack/hardware-offload-config.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_dpu_host_test.go, pkg/network/ovn_kubernetes_label_validation_test.go
- The code prior to this commit only allowed an label with  an empty value.
- However some labels could come from Node Feature Discovery operator which can assign labels with values (not empty).
We need to allow labels that could equal to empty or equal to a specific value. This will allow NFD operator labels to be used to find matching nodes.
Meaning we need the following label="specific value" for ovn-k daemonset to deploy on that node.
label="invalid value" for ovn-k daemonset to NOT deploy on that node.
=> OCPBUGS-61561: Relax label req. of DPU/DPU Host/Smart NIC

bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
(The metric is designed to have only the things we want for telemetry anyway, but the rules for telemetry metrics say we need an explicit recording rule anyway, so that if more info gets added to the metric later it doesn't get automatically sucked in to telemetry.)
/cc
=> OCPBUGS-54806: Add recording rules for UDN telemetry
