Dockerfile
pkg/operator/openshift_sdn_test.go

Use official build and base images

---

hack/build-go.sh
hack/init.sh

@squeed @danwinship finally got tired of docker container compiles

hack: use local GOPATH if GOPATH isn't set

---

hack/test-go.sh

@squeed @danwinship mostly cribbed from ovn-kubernetes but significantly cleaned up since we don't need sudo.

hack: add a test script

---

bindata/network/openshift-sdn/controller.yaml
bindata/network/openshift-sdn/sdn-ovs.yaml
manifests/0000_07_cluster-network-operator_03_daemonset.yaml

@smarterclayton @derekwaynecarr

set cpu request and remove limits for pods and operator

---

bindata/network/multus/000-ns.yaml
bindata/network/multus/002-rbac.yaml
bindata/network/multus/multus.yaml
pkg/network/multus_test.go

To make it clearer that it's infrastructural.

Multus: move to "openshift-multus" namespace

---

manifests/0000_07_cluster-network-operator_04_clusteroperator.yaml
pkg/controller/controller.go

Re http://post-office.corp.redhat.com/archives/aos-devel/2019-February/msg00065.html and https://coreos.slack.com/archives/C3VS0LV41/p1549234605180400

Add ClusterOperator to manifest, fix name

---

pkg/util/clusteroperator/status_manager.go

1. status_manager.go was using a mix of plain go `"log"` and logrus (copied from cluster-dns-operator), and was the only place in the operator where we were using logrus, so fix that
2. logging the entire ClusterOperator object as a golang object is not super helpful:
```
time="2019-02-12T09:30:23-05:00" level=info msg="updated clusteroperator: &v1.Cl
usterOperator{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, ObjectMeta:v1.Ob
jectMeta{Name:\"testing\", GenerateName:\"\", Namespace:\"\", SelfLink:\"\", UID
:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.T
ime{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(n
il), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), An
notations:map[string]string(nil), …
```

Improve StatusManager logging, drop isolated use of logrus

---

README.md

fix broken link and typos in README.md

---

INSTALLER-HACKING.md
hack/overrides-minimize-patch.yaml
hack/run-locally.sh

This is an awful hack, but it is fast(er).
Also, wait for the network operator namespace to come in to existence before continuing.

hack: add HACK_MINIMIZE command to make running on libvirt possible.

---

bindata/network/openshift-sdn/004-multitenant.yaml

openshift-sdn: Add kube-service-catalog to apiserver netnamespace.

---

bindata/network/additional-networks/sriov/sriov-cni.yaml
bindata/network/additional-networks/sriov/sriov-device-plugin.yaml
pkg/network/sriov.go

sriov: report release version number of daemonsets

---

bindata/network/openshift-sdn/sdn-ovs.yaml
bindata/network/openshift-sdn/sdn.yaml

Reverts openshift/cluster-network-operator#161

Revert "openshift-sdn: log ovs and sdn to the system journal"

---

hack/run-locally.sh

#158 renamed the manifest files but run-locally.sh was still using the old names

Update run-locally.sh for manifest renumbering

---

pkg/controller/operconfig/cluster.go
pkg/network/cluster_config.go
pkg/network/cluster_config_test.go

We were stomping on third-party network operators.

Don't set a network status at all if we're not managing networking.

---

bindata/network/multus/multus.yaml

in service to https://github.com/openshift/origin/pull/22787

bindata: add resource requests to multus DS pods

---

hack/open-ovn-ports.sh

From Dan Winship
@danwinship @squeed

hack: ensure 'aws' command output is JSON

---

bindata/network/additional-networks/sriov/sriov-cni.yaml
bindata/network/additional-networks/sriov/sriov-device-plugin.yaml
bindata/network/multus/003-dhcp-daemon.yaml
bindata/network/multus/multus.yaml
bindata/network/openshift-sdn/sdn-ovs.yaml
bindata/network/openshift-sdn/sdn.yaml
bindata/network/ovn-kubernetes/000-ns.yaml
bindata/network/ovn-kubernetes/ovnkube-master.yaml
bindata/network/ovn-kubernetes/ovnkube-node.yaml

ref: https://jira.coreos.com/browse/POD-114

update kubelet label to use upstream GA label

---

bindata/network/openshift-sdn/sdn.yaml
pkg/network/openshift_sdn.go
pkg/network/openshift_sdn_test.go

https://github.com/openshift/origin/pull/23205 is failing because while we generate a proxy config now, we forgot to actually tell openshift-sdn to use it...

Actually pass --proxy-config to openshift-sdn

---

bindata/network/kuryr/002-crds.yaml

This commit adds validations and additional printer columns
to KuryrNet and KuryrNetPolicy CRDs.

Add validations and additional printer columns to Kuryr CRDs

---

hack/run-locally.sh

1) only open AWS ports when using AWS
2) print help text on errors rather than referring to HACKING.md
3) back up the install-config.yaml so it can be cached by the user
@danwinship @squeed @pecameron @JacobTanenbaum @rcarrillocruz

hack/run-locally.sh: misc fixes (AWS ovn-kube ports, help text, etc)

---

Gopkg.lock
bindata/network/multus-admission-controller/001-service.yaml
bindata/network/multus-admission-controller/002-rbac.yaml
bindata/network/multus-admission-controller/003-webhook.yaml
bindata/network/multus-admission-controller/004-configmap.yaml
bindata/network/multus-admission-controller/admission-controller.yaml
manifests/0000_70_cluster-network-operator_03_daemonset.yaml
manifests/image-references
pkg/controller/add_networkconfig.go
pkg/controller/operconfig/configmap_controller.go
pkg/names/names.go
pkg/network/multus_admission_controller.go
pkg/network/multus_admission_controller_test.go
pkg/network/render.go

Talk with @dougbtv we decide not to bring isolation feature at this time. So the PR only contains /validation for net-attach-def.

Multus admission controller support

---

pkg/platform/openstack/kuryr_bootstrap.go

Since Rocky Octavia supports setting timeouts for periods without data
passing through connections. This patch makes use of that we use that to
increase the timeouts to 1 hour for the OpenShift API LB. The default of
50 seconds is unacceptable for an LB used for watching the OpenShift
API.

Kuryr: Set large data timeouts on the API LB

---

pkg/controller/operconfig/configmap_controller.go

EnqueueRequestForOwner{} will enqueue the owner of the target,
hence it enqueue configmap owner, network CR. This change fixes
reconciler function to match it.

Fix Watch arguments in configmap operator

---

README.md
bindata/network/additional-networks/simplemacvlan/simplemacvlan.yaml
pkg/network/additional_networks_test.go

This change contains the following fix:
+ updating README.md with this new configuration.
+ fix macvlan config "cniVersion" to 0.3.1 and its namespace

Followup #255 comments

---

bindata/kube-proxy/kube-proxy.yaml

After this merges: https://github.com/openshift/sdn/pull/14 the kube-proxy cmd will be standalone rather than embedded in hyperkube, so need to update the DaemonSet.  
/cc @danwinship

update kube-proxy cmd

---

pkg/controller/proxyconfig/validation.go

This PR fixes a formatting error in the proxy controller that was added in https://github.com/openshift/cluster-network-operator/pull/245.
/assign @squeed @bparees

Fixes proxy validation error formatting

---

bindata/network/multus/multus.yaml

A backport of PR [291](https://github.com/openshift/cluster-network-operator/pull/291)

Bug 1743587: Adding cni-version to multus daemonset yaml

---

pkg/util/proxyconfig/no_proxy.go

Previously, machineCIDR was only being added to the default noProxy list for clusters installed in cloud provider environments. According to https://bugzilla.redhat.com/show_bug.cgi?id=1744532, machineCIDR is used for vSphere and bare metal installations too. This PR adds machineCIDR to the default noProxy list for all installation types, provides consistency with PR https://github.com/openshift/installer/pull/2286

Bug 1744532: Adds machineCIDR noProxy support for all platforms

---

pkg/controller/statusmanager/status_manager.go

Hi
Following PR [279](https://github.com/openshift/cluster-network-operator/pull/279) the status manager is now thread safe. However, we still face issues concerning stale objects being retrieved from the API server when performing `status.client.Get(context.TODO(), types.NamespacedName{Name: status.name}, co)`. This means that in between two updates the API server does not have enough time to update its cache, so the second update is done on a stale object leading to logs such as: `Failed to update ClusterOperator "network": Operation cannot be fulfilled on clusteroperators.config.openshift.io "network": the object has been modified; please apply your changes to the latest version and try again` which can throw us off. 
This PR introduces the retry mechanism from `client-go`, which …

Bug 1737026: Use retry mechanism for fixing updates on stale objects in cache

---

bindata/network/kuryr/004-daemon.yaml
bindata/network/multus/multus.yaml
bindata/network/openshift-sdn/sdn.yaml
bindata/network/ovn-kubernetes/ovnkube-node.yaml
pkg/network/kuryr.go
pkg/network/kuryr_test.go
pkg/network/multus.go
pkg/network/openshift_sdn.go
pkg/network/ovn_kubernetes.go
pkg/network/render.go

This reverts commit e4d19971badf69cc427763e1b64ff86801fa6c2c, reversing
changes made to 4845741090a6ae4a5cdab7defb4a72e7a02daef7.

Bug 1749446: Revert "Merge pull request #299 from dougbtv/alternate-config-dir"

---

pkg/controller/proxyconfig/validation.go

Previously, a readiness endpoint with a https url scheme would be considered invalid if `httpsProxy` used a http scheme. It's common for clients to be configured with https proxies that contain an http url scheme. This PR updates `readinessEndpoint` validation to allow for this use case and also simplified the name of the http/https scheme constants.

Bug 1750991: Fixes http readinessEndpoint validation for httpsProxy

---

bindata/network/ovn-kubernetes/005-service.yaml
bindata/network/ovn-kubernetes/ovnkube-master.yaml
bindata/network/ovn-kubernetes/ovnkube-node.yaml

nb db port changed to 9641, sb db port changed to 9642
jira sdn-353
https://jira.coreos.com/browse/SDN-353

Bug 1748162: Shift ovn db ports to 9000-9999 range

---

bindata/network/multus/003-dhcp-daemon.yaml

Was incorrectly using a file outside of the host bind mount.

Bug 1754682: The DHCP daemon should mount the directory for the socketfile

---

bindata/network/multus-admission-controller/003-webhook.yaml

This adds the UPDATE operation to the list of operations on which to perform validation.

Bug 1758702: The Multus admission controller should validate & gate on UPDATE events

---

pkg/controller/controller.go
pkg/controller/statusmanager/status_manager.go
pkg/controller/statusmanager/status_manager_test.go

As that means they are from an older version, thus no longer needed.

Delete current related objects not been rendered by controller

---

bindata/network/ovn-kubernetes/003-rbac-controller.yaml

ovn-kubernetes: new permissions required for HA leader election

---

bindata/network/ovn-kubernetes/000-ns.yaml
bindata/network/ovn-kubernetes/monitor.yaml
bindata/network/ovn-kubernetes/ovnkube-master.yaml
bindata/network/ovn-kubernetes/ovnkube-node.yaml

along with ovn-kubernetes PR https://github.com/ovn-org/ovn-kubernetes/pull/837
this will allow prometheus to collect metrics from ovn-kubernetes

expose prometheus endpoints in ovn-kubernetes to prometheus server

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml

@danwinship @knobunc @JacobTanenbaum @pecameron @squeed

ovn/master: enable unidling

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml

On azure the hostnames do not get resolved correctly, change db creation
to use the ip address instead

change to use IP address instead of hostname for nb and sb db creation

---

pkg/util/proxyconfig/no_proxy.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1773870

Bug 1773870: Check if infra.Status.PlatformStatus exists before accessing it

---

bindata/network/ovn-kubernetes/003-rbac-controller.yaml

OVN - fix cluster role binding

---

bindata/network/openshift-sdn/004-multitenant.yaml

Bug 1779133: sdn: Make openshift-user-workload-monitoring global on multitenant

---

pkg/network/cluster_config.go
pkg/network/ovn_kubernetes.go

split out from #400; this should be uncontroversial and can merge right away

ipv6 stuff part 1

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml
bindata/network/ovn-kubernetes/ovnkube-node.yaml
pkg/bootstrap/types.go
pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go

This is a reworking of the rest of #400 that wasn't in #417 
In addition to updating for some of the review comments there, I also reworked it to do more work in the CNO itself and less in the daemonset shell scripts.
@russellb

ipv6 stuff part 2

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml
bindata/network/ovn-kubernetes/ovnkube-node.yaml
pkg/bootstrap/types.go
pkg/network/cluster_config.go
pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go

Bug 1792309: IPv6 backports for 4.3

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml

backport of #459 
/assign @dcbw @rcarrillocruz

Bug 1801802: [4.3] Put brackets around IPv6 addresses passed to ovn-ctl

---

pkg/platform/openstack/kuryr_bootstrap.go

This commit ensures the security group are limiting access
to the minimum required.

bug 1803193: Tighten security groups

---

pkg/util/proxyconfig/no_proxy.go

Bug 1797894: Add MachineNetworks to proxy.status.noPoxy

---

pkg/util/proxyconfig/no_proxy.go

Manual cherry-pick of #490 and #503 
There are no conflicts, but I wanted both to be on the same PR

[release-4.3] Bug 1805726: Add MachineNetworks to proxy.status.noProxy

---

bindata/network/additional-networks/crd/001-crd.yaml
bindata/network/multus/002-rbac.yaml
bindata/network/multus/multus.yaml
manifests/0000_70_cluster-network-operator_03_deployment.yaml
manifests/image-references
pkg/network/additional_networks_test.go
pkg/network/multus.go
pkg/network/multus_test.go

Bug 1807067: [Backport 4.4] Adds route-override-cni and whereabouts for secondary network routing and IPAM

---

pkg/platform/openstack/kuryr_bootstrap.go

When upgrading Octavia from OSP13 to OSP16 the CNO checks if
tagging is supported and look for an API load balancer with tag.
However, the existent LB was created with OSP13, which does not
support tagging and so the tagging was added on description.
The CNO then tries to create a new LB API and fails due to
address already in use.
This commit fixes the issue by ensuring no LB exists with tags
and description, when tagging is supported, prior to creating
a new one.

Bug 1808797: Ensure no API LB recreation happens upon Octavia upgrade

---

bindata/network/additional-networks/crd/001-crd.yaml
bindata/network/multus/002-rbac.yaml
bindata/network/multus/multus.yaml
manifests/0000_70_cluster-network-operator_03_deployment.yaml
manifests/image-references
pkg/network/additional_networks_test.go
pkg/network/multus.go
pkg/network/multus_test.go

Bug 1807062: [Backport 4.3.z] Adds route-override-cni and whereabouts for secondary network routing and IPAM

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml

PR 500 has a quote problem. This fixes it.

Fix quotes in hybrid ovn

---

hack/run-locally.sh

#441 changed run-locally.sh so that if `$KUBECONFIG` was set, it would take precedence over everything else. I very frequenly have an old out-of-date `KUBECONFIG` value set in most of my shells, so this is annoying.
This makes it so that if you use `-c` or set `CLUSTER_DIR` then it either creates a new cluster or connects to an existing cluster, depending on the contents of the directory, like before.
/assign @alexanderConstantinescu

run-locally.sh: make CLUSTER_DIR override KUBECONFIG

---

bindata/network/kuryr/001-rbac.yaml
bindata/network/kuryr/002-crds.yaml
bindata/network/kuryr/003-config.yaml

Kuryrnet CRDs are handled differently on Kuryr now, and this PR
is adapting the CRD to the new format

Add support for new Kuryrnetwork CRD format

---

bindata/network/multus-admission-controller/002-rbac.yaml
bindata/network/multus-admission-controller/admission-controller.yaml
bindata/network/multus-admission-controller/monitor.yaml
manifests/0000_70_cluster-network-operator_03_deployment.yaml
manifests/image-references
pkg/network/multus_admission_controller.go

Secure metrics endpoint for multus

---

pkg/controller/statusmanager/pod_status.go
pkg/controller/statusmanager/status_manager_test.go

Backport of #474 and #510
/cc @dcbw

Bug 1815613: [4.4] Update Progressing message for non-critical components

---

bindata/network/multus-admission-controller/001-service.yaml
bindata/network/multus-admission-controller/002-rbac.yaml
bindata/network/multus-admission-controller/admission-controller.yaml
bindata/network/multus-admission-controller/monitor.yaml
manifests/0000_70_cluster-network-operator_03_deployment.yaml
manifests/image-references
pkg/network/multus_admission_controller.go
pkg/network/multus_admission_controller_test.go

Securing multus scrape endpoint with kube-rbac-proxy

Bug 1817562: Configure tls for multus metrics endpoint

---

pkg/platform/openstack/kuryr_bootstrap.go

In case of LB which is in error state, don't wait for it, but return
immediately.
(cherry picked from commit 96c737edbdc4efa6d964c6f509ff0be413ff3319)

Bug 1821128: Stop waiting for failed loadbalancer.

---

pkg/platform/openstack/kuryr_bootstrap.go
pkg/platform/openstack/networking.go

In order to support updates in the SG rules added on Kuryr bootstrap we
need to make sure the security groups that got replaced by others are
removed. This commit, by maintaing list of "decommissioned" SG rules,
will make sure we delete them on upgrade.

Bug 1832305: Kuryr: Remove old SG rules on upgrade

---

pkg/platform/openstack/kuryr_bootstrap.go

In order to support updates in the SG rules added on Kuryr bootstrap we
need to make sure the security groups that got replaced by others are
removed. This commit, by maintaing list of "decommissioned" SG rules,
will make sure we delete them on upgrade.

Bug 1832899: Kuryr: Remove old SG rules on upgrade

---

OWNERS

This PR adds abhat to the OWNERS file as reviewer and approver.

OWNERS: add abhat

---

pkg/platform/openstack/kuryr_bootstrap.go

This PR ensures the security group are limiting access
to the minimum required.

Bug 1832311: Kuryr: Tighten security groups

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml
bindata/network/ovn-kubernetes/ovnkube-node.yaml

Updated CPU requests according to CI run results

Bug 1839733: bindata/network/ovn-kubernetes/ovnkube-: update resource requests

---

bindata/network/openshift-sdn/004-multitenant.yaml

Bug 1837575: Allow connection between authentication net namespaces

---

bindata/network/kuryr/000-ns.yaml
bindata/network/kuryr/003-config.yaml
bindata/network/kuryr/005-daemon.yaml
bindata/network/kuryr/006-controller.yaml
bindata/network/kuryr/monitor.yaml

This commit expose the Prometheus endpoints in Kuryr
to the Prometheus server.

Expose Kuryr metrics endpoints to Prometheus server

---

pkg/controller/proxyconfig/validation.go

Previously, a TLS transport that includes a trusted CA bundle would only be created if the readiness endpoint had an https scheme. This PR updates `proxy.spec.readinessEndpoints` validation to use `proxy.spec.httpsProxy` if the `readinessEndpoints[x]` has an https scheme and `proxy.spec.httpsProxy` exists. Otherwise, `proxy.spec.httpProxy` will be used for all other `readinessEndpoints[]` validation.

Bug 1798887: Fixes Proxy ReadinessEndpoints Validation

---

bindata/network/ovn-kubernetes/ovnkube-node.yaml

Disabling conntrack for GENEVE

Disable conntrack for GENEVE

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml

Reverts openshift/cluster-network-operator#693

Bug 1858712: Revert "[release-4.5] Bug 1854072: Check if the db file has been correctly initialized with raft.

---

bindata/network/openshift-sdn/sdn-ovs.yaml

Back-port of https://github.com/openshift/cluster-network-operator/pull/712
/assign @abhat @juanluisvaladas

Bug 1857742: [release-4.4] Set timeoutSeconds to reflect expected timeout for OVS commands

---

bindata/network/ovn-kubernetes/ovnkube-node.yaml

Disable conntrack for GENEVE 
Bug 1859374

Bug 1859374: Disable conntrack for GENEVE

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml
bindata/network/ovn-kubernetes/ovnkube-node.yaml
manifests/0000_70_cluster-network-operator_01_crd.yaml
pkg/network/ovn_kubernetes.go

pipe the new HybridOverlayVXLANPort configuration option to ovn-kubernetes

pipe vxlan port from configuration files into ovn-kubernetes

---

bindata/network/openshift-sdn/sdn-ovs.yaml

Back-port of #712
/assign @abhat @juanluisvaladas

Bug 1857744: [release-4.3] Set timeoutSeconds to reflect expected timeout for OVS commands

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml

4.4 back-port of #755
/assign @knobunc

Bug 1875438: [release-4.4] OVN: Handle OVN db upgrades

---

pkg/controller/operconfig/operconfig_controller.go

Fixes [SDN-1344](https://issues.redhat.com/browse/SDN-1344)

Add operator.openshift.io/v1/network to relatedObjects for must-gather

---

Dockerfile
Dockerfile.rhel7

Forgot to add this on previous PR

Build check-endpoints in Dockerfile

---

hack/run-locally.sh

Need to remove the URL_ONLY_KUBECONFIG from the environment list.

hack: fix run-locally

---

bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml

Bug 1777038: Add alerting rules for subnet allocations

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml

This PR is in response to the feedback from QA on https://bugzilla.redhat.com/show_bug.cgi?id=1874638

Bug 1874638: Add -F flag for ovn-nbctl logging

---

bindata/network/openshift-sdn/006-flowschema.yaml
bindata/network/ovn-kubernetes/007-flowschema.yaml

Based on comment https://github.com/openshift/cluster-network-operator/pull/920#discussion_r552553510
/assign @sttts

: Bug 1913399: Bump flow control apiVersion to beta

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml

Bug 1939752: ovnkube: add missing resource requests for SBDB

---

pkg/network/cluster_config.go
pkg/network/cluster_config_test.go
pkg/network/render.go
pkg/network/render_test.go

Bug 1937829: Cherry-pick dual stack migration

---

bindata/network/multus-networkpolicy/001-scheme.yaml
bindata/network/multus-networkpolicy/002-rbac.yaml
bindata/network/multus-networkpolicy/multus-networkpolicy.yaml
manifests/0000_70_cluster-network-operator_01_crd.yaml
manifests/0000_70_cluster-network-operator_03_deployment.yaml
manifests/image-references
pkg/network/multi_network_policy.go
pkg/network/multi_network_policy_test.go
pkg/network/render.go

Add MultiNetworkPolicy support
Depends on: openshift/api/pull/808

MultiNetworkPolicy integration

---

OWNERS_ALIASES

Commit updates kuryr-reviewers and adds backup kuryr-approvers.

Kuryr: Update OWNERS

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml

Bug 1944160: ovn: log more info about nbctl daemon database reconnections

---

pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go

- log formatting error
- is not good to swallow errors on the tests, it can give false positives

Minor cleanups 

---

bindata/network/network-metrics/001-daemonset.yaml

Bug 1936719: OSD-6600 network-metrics missing priorityClass

---

manifests/0000_70_cluster-network-operator_01_crd.yaml
manifests/0000_70_cluster-network-operator_01_egr_crd.yaml
manifests/0000_70_cluster-network-operator_01_pki_crd.yaml

Update the manifests by running hack/update-codegen.sh

Bug 1937594: Update the codegen with the latest API

---

pkg/apply/merge.go
pkg/apply/merge_test.go
pkg/bootstrap/types.go
pkg/controller/operconfig/operconfig_controller.go
pkg/controller/statusmanager/pod_status.go
pkg/controller/statusmanager/status_manager_test.go
pkg/names/names.go
pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go
pkg/network/semver.go
pkg/network/semver_test.go
pkg/network/testutil_test.go
pkg/util/k8s/unstructured.go
pkg/util/k8s/unstructured_test.go

This is the manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/961 and https://github.com/openshift/cluster-network-operator/pull/1027

Bug 1950094: Upgrade nodes before masters

---

bindata/network/network-metrics/001-daemonset.yaml

Bug 1936710: OSD-6600 network-metrics missing priorityClass

---

bindata/network/multus-admission-controller/003-webhook.yaml

Bug 1954187: The multus admission controller admissionReviewVersions should be v1

---

bindata/network/openshift-sdn/sdn.yaml
pkg/bootstrap/types.go
pkg/network/bootstrap.go
pkg/network/openshift_sdn.go
pkg/network/openshift_sdn_test.go
pkg/network/render.go

drop icmp frag needed received from other nodes in the cluster

Bug 1825219: drop icmp frag needed received from other nodes in the cluster

---

bindata/network/multus/multus.yaml

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

Bug 1965834: add management annotation to multus-additional-cni-plugins pods

---

bindata/network/kuryr/003-config.yaml
pkg/bootstrap/types.go
pkg/network/kuryr.go
pkg/platform/openstack/kuryr_bootstrap.go
pkg/platform/openstack/networking.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/results.go
vendor/modules.txt

This commit adds the support to detect the Nodes
Network MTU so that the Namespace Networks use the
same MTU as the host.

Bug 1932114: Detect Nodes Network MTU

---

pkg/platform/openstack/kuryr_bootstrap.go
pkg/platform/openstack/networking.go

When creating a Services subnet, in order to accommodate additional VRRP
ports of Octavia Amphora VMs, Kuryr was creating a subnet for services
in OpenStack of twice the size requested by user in ServiceNetwork. To
make sure a VRRP port will never land in the ServiceNetwork range,
allocation ranges were used to point to the _other_ half of the subnet.
This is no longer required when using OVN-Octavia, so this commit gets
rid of it, making sure that the change will only affect existing
installations (as we cannot change the CIDR of the existing subnet in
OpenStack).
The services subnet requires a gateway IP to be put somewhere in the
range and we normally put it somewhere on the range reserved from VRRP
so K8s would never choose it for a Service. As there's no way to inform
K8s about a …

Bug 1955548: Kuryr: Do not expand services subnet with OVN

---

OWNERS

adding JacobTanenbaum to approvers
primarily so that I can approve CI testing changes

Add JacobTanenbaum to list of approvers

---

pkg/util/proxyconfig/no_proxy.go
pkg/util/proxyconfig/no_proxy_test.go

This addresses the BZ https://bugzilla.redhat.com/show_bug.cgi?id=1981975
As mentioned in the BZ, if this fix is approved we will need to evaluate to backport the fix

Bug 1981975: Update service network status to reflect dual stack entries

---

bindata/network/openshift-sdn/sdn.yaml

Change to use mountPath: /host

Bug 1984449: Change to use mountPath: /host

---

bindata/network/openshift-sdn/sdn.yaml

Change iptables chain names to not conflict with existing workaround(s)
(cherry picked from commit 32d72e5794ecd5e5f742c8708a2e4a6c183b0e4b)

Bug 1988426: Change to use mountPath: /host

---

bindata/network/multus-admission-controller/admission-controller.yaml
bindata/network/network-metrics/001-daemonset.yaml

Changed pod user to non-root based on [Bug 1914398](https://bugzilla.redhat.com/show_bug.cgi?id=1914398)

Bug 1914398: Changed pod user to non-root

---

pkg/bootstrap/types.go
pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go

(It's spelled correctly in the bindata templates)

fix a typo in a field name

---

bindata/network/multus/002-rbac.yaml
bindata/network/multus/multus.yaml
pkg/network/multus_test.go
pkg/network/network_metrics_test.go

Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>

Bug 1914053: whereabouts: add ip-reconciler cronjob

---

bindata/network/ovn-kubernetes/ovnkube-node.yaml

Add ip6tables NOTRACK rules for udp/6081

Add ip6tables NOTRACK rules for udp/6081

---

bindata/network/multus/multus.yaml
manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
manifests/0000_70_cluster-network-operator_03_deployment.yaml
manifests/image-references
pkg/network/multus.go

This PR will add the bond-cni to the multus installation.
Bond cni repo: [https://github.com/openshift/bond-cni](https://github.com/openshift/bond-cni)
Upstream repo: [https://github.com/intel/bond-cni](https://github.com/intel/bond-cni)

Add bond-cni

---

bindata/network/multus/000-ns.yaml
bindata/network/openshift-sdn/000-ns.yaml

bindata/network: specify pod-security levels via labels not annotations

---

bindata/network/openshift-sdn/controller.yaml

SDN: Do not tolerate a controller failure during upgrade

---

go.mod
go.sum
vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
vendor/modules.txt

Bump openshift/build-machinery-go
Includes a fix for https://github.com/openshift/build-machinery-go/issues/56

Bump openshift/build-machinery-go

---

bindata/network/openshift-sdn/sdn.yaml
bindata/network/ovn-kubernetes/004-config.yaml
pkg/network/cluster_config.go
pkg/network/openshift_sdn.go
pkg/network/openshift_sdn_test.go
pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go
pkg/network/render.go

Add MTU migration support for OVNKubernetes and OpenshiftSDN
Enhancement: https://github.com/openshift/enhancements/blob/master/enhancements/network/allow-mtu-changes.md
Depends on https://github.com/openshift/sdn/pull/381, should be merged after that

Add MTU migration support for OVNKubernetes and OpenshiftSDN

---

go.mod
go.sum
vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/OWNERS
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/admissionregistration.go
vendor/modules.txt

Bumps openshift/build-machinery-go to fix
openshift/build-machinery-go#56.

Bug 2037500: Bump openshift/build-machinery-go

---

OWNERS

remove people who are no longer on the team

clean up OWNERS

---

bindata/network/additional-networks/crd/001-crd.yaml
bindata/network/multus/002-rbac.yaml
bindata/network/multus/multus.yaml
pkg/network/multus_test.go
pkg/network/network_metrics_test.go

This implements the Whereabouts IP reconciliation cron job.
NOTE: This pull request should be merged AFTER 
https://github.com/openshift/whereabouts-cni/pull/77

Bug 2034351: Whereabouts IP Reconciliaton [backport 4.9]

---

bindata/network/ovn-kubernetes/ovnkube-master.yaml
bindata/network/ovn-kubernetes/ovnkube-node.yaml

This was accidentally removed in:
0f38cc7f233e09c795540be43bab291c8b857fe8

Bug 2034155: Adds back --disable-snat-multiple-gws

---

bindata/network/additional-networks/crd/001-crd.yaml
bindata/network/multus/002-rbac.yaml
bindata/network/multus/multus.yaml
pkg/network/multus_test.go
pkg/network/network_metrics_test.go

This implements the Whereabouts IP reconciliation cron job
NOTE: This pull request should be merged AFTER 
https://github.com/openshift/whereabouts-cni/pull/78

Bug 2034352: Whereabouts IP Reconciliaton [backport 4.8]

---

bindata/network/additional-networks/crd/001-crd.yaml
bindata/network/multus/002-rbac.yaml
bindata/network/multus/multus.yaml
pkg/network/multus_test.go
pkg/network/network_metrics_test.go

This implements the Whereabouts IP reconciliation cron job
NOTE: This pull request should be merged AFTER https://github.com/openshift/whereabouts-cni/pull/79

Bug 2034355: Whereabouts IP Reconciliaton [backport 4.7]

---

OWNERS

Changes-Include:
- Add Jaime as reviewer/approver
- Remove Alex
- Alphabetical Order

Update project owners

---

bindata/network/openshift-sdn/alert-rules.yaml

See "style guide" in alerting-consistency.md at repository
openshift/enhancements/monitoring.

Bug 2010361: SDN alerts: conform to monitoring team style guide

---

OWNERS

Adds Jaime, removes stale contributors.

[release 4.9] Updates owners

---

OWNERS

Adds Jaime, removes stale contributors.

[release 4.8] Updates owners

---

Dockerfile

Fix golang image version in Dockerfile

---

pkg/network/mtu.go

Multi path routes do not have a link index attribute set on the route, instead each path has it's own link index.

Fix MTU detection for multi path default routes

---

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml

Run ovnkube-master statefulset pods in parallel

---

pkg/controller/connectivitycheck/connectivity_check_controller.go

Exclude openshift-kube-apiserver and openshift-apiserver service/endpoints from connectivity checks in hypershift

---

pkg/controller/statusmanager/pod_status.go

Use (un)setProgressing for pod status update

---

pkg/util/proxyconfig/no_proxy.go
pkg/util/proxyconfig/no_proxy_test.go

Hypershift clusters do in many cases not actually have an internal
apiserver adress, which is why it puts the external one into the
infrastructure status. This entails that this address has to be proxied.
Unfortunately, sometimes this address is actually internal and doesn't
need proxying and we can not differentiate these two cases from the
cluster alone. Thus, this adds a knob that allows configuring if the
internal apiserver address should be proxied or not.
Ref https://issues.redhat.com/browse/HOSTEDCP-333
/assign @squeed

Proxyconfig: Add a knob for Hypershift to enable proxying internal apiserver address

---

bindata/network/multus-admission-controller/002-rbac.yaml
bindata/network/multus/002-rbac.yaml

Takin' a look to see what it looks like d/s

Multus: split pod/status rbac

---

pkg/bootstrap/types.go
pkg/network/ovn_kubernetes.go

hypershift: get control plane replicas from hcp

---

bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml

raise the severity level for the alert and add the runbook
should be merged after this https://github.com/openshift/runbooks/pull/41

raise the alert NoOvnMasterLeader to critical and add the runbook url

---

bindata/network/ovn-kubernetes/common/alert-rules.yaml
bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml

Introduced by PR #1328 and #1366.

Bug 2078910: Correct runbook_url field location within schema

---

bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml

Lets us finally get host OVS metrics with ovnkube.

ovnkube: export OVS metrics along with OVN metrics

---

bindata/network/openshift-sdn/002-rbac.yaml

Bug 2080255: SDN: Re-add list/watch/get permissions for nodes needed for EgressIP

---

pkg/controller/statusmanager/pod_status.go
pkg/controller/statusmanager/status_manager.go
pkg/network/hypershift.go

This PR additionally fixes a bug where we created an empty condition:
```
conditions:                                                                                                                                                                                                                                                                                                                                                                          
- lastTransitionTime: "2022-05-02T17:00:26Z" …
```

Hypershift: Copy all CNO conditions to HostedControlPlane status 

---

bindata/network/multus/multus.yaml

- Extend the tuning cni sysctl allowlist
- add rules on cni safe sysctls list

add more sysctls to the multus allowlist

---

bindata/network/openshift-sdn/006-flowschema.yaml
bindata/network/ovn-kubernetes/self-hosted/007-flowschema.yaml

v1beta1 will be removed in 1.26

Bug 2076877: Bump FlowScema apiVersion to v1beta2

---

bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml

Add gm metric record to use for telemetry exposure

---

bindata/network/ovn-kubernetes/common/001-crd.yaml
bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml
bindata/network/ovn-kubernetes/managed/004-config.yaml
bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
pkg/network/ovn_kubernetes_test.go

since https://github.com/ovn-org/ovn-kubernetes/pull/2876 is merged d/s,
we can enable it here.

Bug 2086437: Enable EgressQoS controller

---

pkg/bootstrap/types.go
pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go

Bug 2086506: hypershift: respect statefulset when upgrading ovnk

---

pkg/network/ovn_kubernetes.go

Bug 2087556: Fix rendering DPU manifests

---

bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml

Bug 2094071: Add southboundStale alert runbook

---

OWNERS

remove @squeed from owners

---

bindata/network/ovn-kubernetes/managed/004-config.yaml
bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
pkg/network/ovn_kubernetes_test.go

(cherry picked from commit 5ae9febfab8257deb23842dfe3f8999e3b2524c3)

Bug 2108236: Revert "Bug 2085089: Pass enable-udp-aggregation=true to ovn-kubernetes"

---

pkg/controller/operconfig/operconfig_controller.go
pkg/controller/statusmanager/status_manager.go

Backport of https://github.com/openshift/cluster-network-operator/pull/1468

[release-4.8] Bug 2092264: Cleanup CNO relatedObjects

---

pkg/network/render.go

During SDN migration, we need to support custom resource translation
for features like egressIP and egressFirewall. So we need the CRDs
of both CNIs to be rendered.

Render CRDs for both OSDN and OVNK during migration

---

bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml

Closes #[NP-542](https://issues.redhat.com//browse/NP-542)

microshift: compact ovn databases periodically

---

bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml

Bug 2094068: Add northboundstale alert runbook

---

bindata/network/ovn-kubernetes/common/001-crd.yaml

Bug OCPBUGS-917: Add EgressQoS DstCIDR format validation

---

pkg/network/cluster_config.go
pkg/network/cluster_config_test.go
pkg/network/render.go
pkg/network/render_test.go

Add vSphere platform to allow dual-stack cluster

---

bindata/network/ovn-kubernetes/common/alert-rules.yaml

/assign @martinkennelly : WDYT? PTAL; the expr looks too simple to be true. :D
/cc @npinaeva

SDN-3432: Add alert for OVNKubernetesControllerDisconnectedSouthboundDatabase

---

bindata/network/ovn-kubernetes/common/alert-rules.yaml
bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml

OVN-K alerts: first tranche

---

pkg/platform/openstack/kuryr_bootstrap.go
pkg/platform/openstack/networking.go

We configure Kuryr to create Neutron networks with MTU that CNO gets
from the machines network. We however still create network for services
with the default MTU. This commit fixes that and also uses machines
network MTU when creating the services network.

Bug: OCPBUGS-736: Kuryr: Use machine net MTU to create service net

---

pkg/network/multus_ipam.go
pkg/network/multus_ipam_test.go

This updates the detection method to parse for conflists as well as non-conflist configurations

OCPBUGS-1038: Multus IPAM detection should honor conflists

---

pkg/controller/connectivitycheck/connectivity_check_controller.go

This would set node object which is hosting network-check-source pod as owner reference for PodNetworkConnectivityCheck objects so that these are automatically garbage collected when node is actually removed from cluster.

OCPBUGS-1341: Set owner reference for pod network connectivity check

---

bindata/network/multus/multus.yaml

Signed-off-by: nicklesimba <simha.nikhil@gmail.com>

fixed typo in comment

---

bindata/network/ovn-kubernetes/ovnkube-node.yaml

Bug 2111588: Enable OVS metrics for ovnk

---

bindata/network/ovn-kubernetes/common/alert-rules.yaml
bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
pkg/controller/operconfig/operconfig_controller.go
pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go

All credit to nadia / dan w.
waiting on #1560 to merge and CI is consistently green after 10 retries including the ovn serial job.

OCPBUGS-2362: Prefer oldest nodes, harden new alerts and revert setting new OVN-K alerts to info

---

bindata/network/ovn-kubernetes/microshift/clusterrole.yaml
bindata/network/ovn-kubernetes/microshift/configmap.yaml
bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml
bindata/network/ovn-kubernetes/microshift/node/daemonset.yaml
bindata/network/ovn-kubernetes/microshift/role.yaml

(cherry picked from commit c04d33c2a4f1420e2a61c6faf5c9ce0df33ead74)

OCPBUGS-3184: update microshift ovnk manifests

---

bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml

/cc @csrwng 
All credits to @zshi-redhat for spotting that!

HyperShift: Fix typo in control-plane-component label value

---

pkg/operator/operator.go

During CNO startup there is a small chance that it will read the infrastructure object before its `Status.InfrastructureName` is updated by hosted cluster config operator. 
To address such scenario do not accept empty InfrastructureName. 
Additionally add a retry to avoid unnecessary restarts.

OCPBUGS-3114: HyperShift: Do not accept empty infrastructure name

---

pkg/controller/egress_router/egress_router_controller.go
pkg/operator/operator.go

Fix info log formatting

---

pkg/network/ovn_kubernetes.go

We were bailing out early and returning false ("don't disable it") if the config file didn't exist, well before the check of "return true by default on s390x"...
(As with the previous PR, this is untested, because I don't have a mainframe lying around, so please double-check my logic...)

OCPBUGS-2532: Fix default disable-udp-aggregation value on s390x

---

bindata/network/openshift-sdn/sdn.yaml

OCPBUGS-5842: Use pods oc vs host

---

bindata/network/openshift-sdn/sdn.yaml

Reverts openshift/cluster-network-operator#1713

OCPBUGS-7354: Revert "Revert "OCPBUGS-5842: Use pods oc vs host""

---

bindata/network/ovn-kubernetes/common/002-rbac.yaml
bindata/network/ovn-kubernetes/microshift/clusterrole.yaml

https://issues.redhat.com/browse/NHE-443
https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/cni/cni_dpu.go#L70

Allow updates to pods

---

bindata/network/ovn-kubernetes/common/001-crd.yaml

Follows the upstream implementation here:
https://github.com/ovn-org/ovn-kubernetes/pull/3002

Enables nodeSelector to be used in egress firewall rule

---

bindata/network/multus/multus.yaml
pkg/network/multus_ipam_test.go

This adds yaml to start a controller in replacement of the cronjob

Whereabouts should implement the reconciliation controller

---

bindata/network/multus/multus.yaml

This also includes the fix for the atomic move during CNI binary copy.

OCPBUGS-64: CNI binary copy should account for the possibility of symlinks [backport 4.10]

---

pkg/network/kuryr.go
pkg/platform/openstack/kuryr_bootstrap.go

Cherry pick of #1586 adding fix from #1669.

[release-4.12] Bug OCPBUGS-4896: Kuryr: If set use MTU from Config for svc net

---

bindata/cloud-network-config-controller/common/002-rbac.yaml
bindata/cloud-network-config-controller/managed/controller.yaml
bindata/cloud-network-config-controller/self-hosted/controller.yaml

xref: [CCO-358](https://issues.redhat.com//browse/CCO-358)
xref: [CCO-294](https://issues.redhat.com//browse/CCO-294)
* Enhancement proposal: https://github.com/openshift/enhancements/pull/1301
* Corresponding change for `cloud-network-config-controller`: https://github.com/openshift/cloud-network-config-controller/pull/102

CCO-358: Manifest changes necessary to support Azure Workload Identity

---

bindata/network/openshift-sdn/sdn.yaml
bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml

Add logic to pick CNI shim binaries for ovn-k and sdn based on the host os version.

OCPBUGS-15961: FIPS related CNO changes

---

bindata/network/openshift-sdn/sdn.yaml

(cherry picked from commit b681d7b1a93f236c5eae1c6e0d9cf1bcf2336dff)

[release-4.9] OCPBUGS-16894: Use pods oc vs host

---

bindata/network/openshift-sdn/sdn.yaml

(cherry picked from commit b681d7b1a93f236c5eae1c6e0d9cf1bcf2336dff) (cherry picked from commit f3c550ec81536f84338a597baf258ff360b2fd5c)

[release-4.8] OCPBUGS-16872: Use pods oc vs host

---

bindata/network/openshift-sdn/sdn.yaml

(cherry picked from commit b681d7b1a93f236c5eae1c6e0d9cf1bcf2336dff) (cherry picked from commit f3c550ec81536f84338a597baf258ff360b2fd5c) (cherry picked from commit 51e582caa22a949fa345571f95b0aa9fe97cf9ee) (cherry picked from commit f449c1ede4518725555a42cc02d43b0495c4c9ce)

[release-4.6] OCPBUGS-16893: Use pods oc vs host

---

bindata/network/openshift-sdn/sdn.yaml

(cherry picked from commit b681d7b1a93f236c5eae1c6e0d9cf1bcf2336dff) (cherry picked from commit f3c550ec81536f84338a597baf258ff360b2fd5c) (cherry picked from commit 51e582caa22a949fa345571f95b0aa9fe97cf9ee)

[release-4.7] OCPBUGS-16891: Use pods oc vs host

---

pkg/network/render.go

Partially implements: https://github.com/openshift/enhancements/pull/1365

Add OpenStack platform to list of allowed dual-stack clusters

---

bindata/network/multus/multus.yaml
pkg/network/multus.go
pkg/network/multus_test.go
pkg/network/network_metrics_test.go

This makes multus changes to thick plugin. It changes multus to server/client model as ovn-kubernetes/openshift-sdn.

Multus thick plugin support

---

pkg/controller/allowlist/allowlist_controller.go

Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/1904

OCPBUGS-17457: prevent creation of multiple cni-sysctl-allowlist-ds pods

---

bindata/network/ovn-kubernetes/common/monitor-node.yaml
bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go
pkg/util/util.go

Copied from https://github.com/openshift/cluster-network-operator/pull/1930 and removed hack commit for quicker CI signal

OCPBUGS-17782, SDN-3664: Join ovnkube-controller and ovnkube-node container for multizone setup

---

pkg/controller/allowlist/allowlist_controller.go

Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/1904

OCPBUGS-17656: prevent creation of multiple cni-sysctl-allowlist-ds pods

---

bindata/network/ovn-kubernetes/common/ipsec-host.yaml
docs/enabling_ns_ipsec.md

so pluto will run on the host by systemd only without the duality of
possibly running it via systemd or from the e-w container

OCPBUGS-18892: make ipsec.service required

---

pkg/network/kuryr.go
pkg/network/kuryr_test.go
pkg/platform/openstack/kuryr_bootstrap.go

The fixes are no longer required as #2021 is in.

Revert Kuryr MTU fixes

---

bindata/network/node-identity/common/001-node-identity-namespace.yaml
bindata/network/node-identity/self-hosted/003-node-identity-scc-rbac.yaml
bindata/network/node-identity/self-hosted/node-identity.yaml

(cherry picked from commit 792116688be44225809b66597a8455dc3c4cb21f)

OCPBUGS-20184: [release-4.14]: Don't run network node identity as root

---

pkg/operator/operator.go

cc @kyrtapz 
We are seeing flakes on CNO restarts in the hypershift control plane
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_hypershift/2967/pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn/1699008879737704448/artifacts/e2e-kubevirt-aws-ovn/run-e2e-local/artifacts/TestCreateCluster/namespaces/e2e-clusters-pvhd5-example-s6skm/core/pods/logs/cluster-network-operator-78fd774c97-7w7dg-cluster-network-operator-previous.log
```
W0905 11:42:53.359515       1 builder.go:106] graceful termination failed, controllers failed with error: failed to get infrastructure name: infrastructureName not set in infrastructure 'cluster'
```
The current backoff is set to `retry.DefaultBackoff` which is appropriate for 409 conflicts and only retries for < …

OCPBUGS-18569: hypershift: adjust backoff on infrastructure name retry

---

bindata/network/openshift-sdn/controller.yaml

/hold 
Depends on https://github.com/openshift/sdn/pull/578

OCPBUGS-18785: SDN controller manifest: add node name from downward kapi to sdn controller

---

bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-control-plane.yaml
bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-control-plane.yaml
pkg/network/ovn_kubernetes.go

https://issues.redhat.com/browse/SDN-4071

[SDN-4071] two replicas for CM instead of 3 

---

bindata/network/ovn-kubernetes/common/008-script-lib.yaml
bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go

Put common scripts into a bash script library and source that library from the ovnkube-node containers.

 OCPBUGS-18089,OCPBUGS-18088: ovnkube: container scripts cleanup [v2]

---

pkg/controller/statusmanager/status_manager.go
pkg/controller/statusmanager/status_manager_test.go

Kuryr is not supported on 4.15. This commit makes sure that for clusters with Kuryr configured in `.spec.defaultNetwork.type`, the upgrade to 4.15 will be blocked.

OCPBUGS-23011: Block upgrades to 4.15 with Kuryr

---

manifests/0000_70_cluster-network-operator_01_credentialsrequest.yaml
manifests/02-cncc-credentials.yaml

Add capability annotations to cloud credentials requests

OCPVE-779: Annotate credentials request manifests

---

bindata/kube-proxy/kube-proxy.yaml
bindata/network/multus-admission-controller/admission-controller.yaml
bindata/network/network-metrics/001-daemonset.yaml
bindata/network/openshift-sdn/controller.yaml
bindata/network/openshift-sdn/sdn.yaml
bindata/network/ovn-kubernetes/common/008-script-lib.yaml
bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml
bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-control-plane.yaml
bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-master.yaml
bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml
pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go

Put common scripts into a bash script library and source that library from the ovnkube-node containers.

[release-4.14] OCPBUGS-22787,OCPBUGS-22788,OCPBUGS-22789: ovnkube: container scripts cleanup

---

pkg/controller/clusterconfig/migration_test.go
pkg/names/names.go

https://github.com/openshift/enhancements/blob/master/enhancements/network/sdn-live-migration.md#workflow-description

OCPBUGS-25760: Keep the live migration annotation consistant with the enhancement doc

---

bindata/network/ovn-kubernetes/common/ipsec.yaml

OCPBUGS-28208: ipsec: fix oopsy from 2e3fc8e (cherry-pick of 980c08318e)

---

bindata/cloud-network-config-controller/managed/controller.yaml
bindata/cloud-network-config-controller/self-hosted/controller.yaml

CNCC is a cluster networked pod. Remove references to cloud provider internal LB.

NO-JIRA: Remove ILB from CNCC

---

bindata/network/ovn-kubernetes/common/ipsec-containerized.yaml
bindata/network/ovn-kubernetes/common/ipsec-host.yaml

OCPBUGS-29305: ipsec: fix openssl typo

---

pkg/controller/ingressconfig/ingressconfig_controller.go

cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2266

[release-4.13] OCPBUGS-29301: Update ingressconfig_controller to use field Manager 

---

bindata/network/ovn-kubernetes/common/ipsec.yaml

OCPBUGS-30150: ipsec: fix openssl typo

---

pkg/controller/statusmanager/status_manager.go
pkg/controller/statusmanager/status_manager_test.go

This reverts commit 996fd663d5df72b450674356baa178c157c35e75.
/assign @pperiyasamy

SDN-4726: Reapply "Merge pull request #2330 from pperiyasamy/block-sdn-upgrade"

---

bindata/network/ovn-kubernetes/common/001-crd.yaml

Bring in the changes from https://github.com/ovn-org/ovn-kubernetes/pull/4158 for 4.16
cc @pperiyasamy

OCPBUGS-33080: Update EQoS CRD to latest

---

bindata/network/multus-networkpolicy/multus-networkpolicy.yaml

OCPBUGS-28230: enforce termination message policy on all platform pods

---

bindata/network/ovn-kubernetes/common/001-crd.yaml
bindata/network/ovn-kubernetes/managed/004-config.yaml
bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml

/cc @simonpasquier / @martinkennelly / @npinaeva 
I am unsure if "max" is correct here, I presume it is; even if I have labels for this metric?
original change: https://github.com/ovn-org/ovn-kubernetes/pull/4254#issuecomment-2059847242 for metrics details.

SDN-3817,MON-3795: Add ANP metric rule expressions for telemetry exposure

---

bindata/network/openshift-sdn/sdn.yaml
bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
pkg/client/list_pager.go
pkg/controller/operconfig/cluster.go
pkg/controller/operconfig/migration.go
pkg/controller/operconfig/operconfig_controller.go
pkg/network/cluster_config.go
pkg/network/cluster_config_test.go
pkg/network/ovn_kubernetes.go

Main metrics PR: https://github.com/openshift/cluster-network-operator/pull/2388
Main validation PR: https://github.com/openshift/cluster-network-operator/pull/2344
Main align subnet PR: https://github.com/openshift/cluster-network-operator/pull/2367
All commits are clean cherry-picks.

OCPBUGS-34612,OCPBUGS-34660,OCPBUGS-34663: Live migration backports

---

bindata/network/additional-networks/crd/001-crd.yaml

Manual cherry-pick https://github.com/openshift/cluster-network-operator/pull/2414

[release-4.16] OCPBUGS-35923: update whereabouts crd

---

bindata/network/additional-networks/crd/001-crd.yaml

Manual cherry-pick https://github.com/openshift/cluster-network-operator/pull/2419

[release-4.15] OCPBUGS-36367: update whereabouts crd

---

bindata/network/ovn-kubernetes/common/001-crd.yaml
bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
bindata/network/ovn-kubernetes/self-hosted/ovnkube-control-plane.yaml
manifests/0000_70_cluster-network-operator_01_pki_crd.yaml
manifests/0000_70_network_01_networks.crd.yaml
pkg/network/ovn_kubernetes.go
pkg/network/ovn_kubernetes_test.go

Also install the IPAMClaims CRD; a follow-up PR will make the installation depend on a feature gate defined on the openshift API.
Introducing the feature gate in PR: 
- https://github.com/openshift/api/pull/1913
Cherry-pick PR from:
- https://github.com/openshift/cluster-network-operator/pull/2357

SDN-5029: ipam, virt: enable the persistent ips feature

---

bindata/network/additional-networks/crd/001-crd.yaml

Manual cherry-pick https://github.com/openshift/cluster-network-operator/pull/2427

[release-4.14] OCPBUGS-36722: update whereabouts crd

---

bindata/network/multus-admission-controller/admission-controller.yaml
pkg/hypershift/hypershift.go
pkg/network/multus_admission_controller.go
pkg/network/ovn_kubernetes_test.go

Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2335 to release-4.15.

[release-4.15] OCPBUGS-35837: Propogate hypershift control plane priority class override to multus and preserve container resource requests

---

bindata/network/additional-networks/crd/001-crd.yaml

This is a manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2458

OCPBUGS-37942: [release-4.12] update whereabouts crd

---

bindata/network/ovn-kubernetes/common/001-crd.yaml
bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
pkg/network/ovn_kubernetes_test.go

Add the `UserDefinedNetwork` CRD definition and the backing controller required RBAC.

SDN-5144: Add UserDefinedNetwork CRD and RBAC

---

bindata/networking-console-plugin/004-console-plugin.yaml

OCPBUGS-39398: Preload networking plugin locales

---

OWNERS
OWNERS_ALIASES
bindata/network/frr-k8s/001-crd.yaml
bindata/network/frr-k8s/OWNERS

Here we align the CRDs to the content of openshift/frr and we propose @fedepaol and @oribon as additional approvers for the frr-k8s subfolder.

CNF-14199: Align FRR-K8s CRDs

---

bindata/network/ovn-kubernetes/common/001-crd.yaml

- localnet support is removed as its not supported yet
- Add missing markers to status conditions

NO-JIRA: onv-k, udn: Update UserDefinedNetwork CRD

---

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
bindata/network/ovn-kubernetes/common/ipsec-host.yaml

Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2592. No conflicts.

[release-4.17] OCPBUGS-46146: Remove ip xfrm state when IPsec is disabled

---

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
bindata/network/ovn-kubernetes/common/ipsec-host.yaml

Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2594. No conflicts.

[release-4.16] OCPBUGS-46148: Remove ip xfrm state when IPsec is disabled

---

pkg/controller/clusterconfig/migration.go
pkg/controller/clusterconfig/migration_test.go

When a MCP is paused, the NetworkTypeMigrationTargetCNIInUse condition cannot become true. However NetworkTypeMigrationMTUReady will be false in that case, as the mtu-migration.service has been removed from unpaused MCPs. The migration will be flapping between step-2 and step-3. Checking the spec.defaultNetwork.Type before entering step-2 to ensure we don't go back from step-3.

[release-4.16] OCPBUGS-44338: Prevent live migration process from flapping between step-2 and step-3

---

bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
bindata/network/ovn-kubernetes/common/ipsec-host.yaml

Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2595. No conflicts.

[release-4.15] OCPBUGS-46149: Remove ip xfrm state when IPsec is disabled

---

bindata/network/ovn-kubernetes/common/ipsec-host.yaml

Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2593, No conflicts.

[release-4.17] OCPBUGS-43714: Skip including default crypto policies to avoid authby issue

---

bindata/network/ovn-kubernetes/common/ipsec-host.yaml

Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2597, No conflicts.

[release-4.16] OCPBUGS-43715: Skip including default crypto policies to avoid authby issue

---

bindata/network/ovn-kubernetes/common/ipsec-host.yaml

Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2598, No conflicts.

[release-4.15] OCPBUGS-43716: Skip including default crypto policies to avoid authby issue

---

bindata/network/ovn-kubernetes/common/udn-admission-policy.yaml

SDN-4930: Fix user-defined-networks-namespace-label binding

---

bindata/network/ovn-kubernetes/common/udn-admission-policy.yaml

[release-4.18] OCPBUGS-48710, SDN-4930: Disable adding/removing the UDN namespace label

---

bindata/network/ovn-kubernetes/common/001-crd.yaml

Changes from https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4933

SDN-5426: (C)UDN CRD: add IPAM section and IPAM.Mode field.

---

bindata/network/ovn-kubernetes/common/001-crd.yaml

Update CUDN CRD according to [1]: add API validation to ensure CUDN CR spec.topology match the spesifed topology-configuration.
[1] https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5016

OCPBUGS-49746: ovn-k,cudn crd: Ensure matching toplogy and topology-config

---

bindata/network/ovn-kubernetes/common/001-crd.yaml

Specifically, this brings the host additionalPrinterColumn.

NO-JIRA: ovn-k: sync EgressService with upstream

---

bindata/network/multus/multus.yaml
pkg/network/multus_test.go
pkg/network/network_metrics_test.go

update install-cni script to match whereabouts bin so that we get cert rotatation in openshift

CORENET-4481: update install-cni script

---

bindata/network/multus-networkpolicy/001-scheme.yaml

This version adds endPort support.

SDN-5701: [multus-networkpolicy] Update CRD to the latest v1beta1

---

pkg/controller/operconfig/migration.go
pkg/controller/operconfig/migration_test.go

1. In the migration case from SDN to OVN, set egress-assignable node
annotation if 'egressCIDRs' is configured in the hostsubnet. The
user may configure more hostsubnet with 'egressCIDRs' then the
egress IPs.
2. In the rollback case, verify the existence of the node annotation
`cloud.network.openshift.io/egress-ipconfig` before using it. In
non-cloud platforms, use the node annotation 'node-primary-ifaddr'
to derive the 'egressCIDRs'.

[release-4.16] OCPBUGS-53317: Fix feature migration for EgressIP

---

bindata/network/ovn-kubernetes/self-hosted/ovnkube-control-plane.yaml

Some code (EgressSVC and BGP) in cluster-manager needs to know the gateway mode.

OCPBUGS-51093, OCPBUGS-55157: Pass '--gateway-mode' flag for ovnkube-cluster-manager

---

pkg/platform/platform.go

Now that IBM ROKS is working on OVN support, we need to be able to enable or disable network node identity using the openshift-network-operator/network-node-identity configmap. So we need to revert the changes that were made in the following PRs that disabled network node identity for all clusters running on IBMCloud:
- https://github.com/openshift/cluster-network-operator/pull/2197
- https://github.com/openshift/cluster-network-operator/pull/2313

CORENET-6228: Allow network-node-identity to be enabled for IBMCloud PlatformType
