openshift/cluster-network-operator

Dockerfile, cmd/openshift-network-renderer/main.go, hack/build-go.sh, pkg/operator/handler.go
This adds a separate mode that works entirely offline - it consumes configuration from disk, and writes a single yaml file with all desired objects.
=> Add render-to-disk binary

pkg/apis/networkoperator/v1/register.go
To be kind to downstream programs. This change is a noop
=> pkg/apis: make api vendorable without operator-framework

pkg/operator/openshift_sdn_test.go, pkg/operator/reconcile.go, pkg/operator/reconcile_test.go, pkg/operator/testutil_test.go
ServiceAccounts have a token that is automatically generated, but we were deleting it every time we reconciled. Let the auto-generated one win.
Also, test that all objects from openshift-sdn reconcile to themselves.
=> pkg/reconcile: ServiceAccount-specific logic

manifests/0000_07_cluster-network-operator_03_daemonset.yaml
We override `KUBERNETES_SERVICE_HOST|PORT` since we can't use the service IP. We previously used 127.0.0.1, but that doesn't work during bootstrap since the apiserver is still running on the bootstrap node. Switch to a new configmap created by the installer.
=> manifests: change to using installer-created apiserver environment.

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/openshift-sdn/sdn.yaml
As discovered in openshift/installer#600, there is some murky race within crio with regards to SELinux relabeling. Unfortunately, the SDN is one of the first containers to run, so it loses the race.
=> openshift-sdn: Add stupid loop to wait out crio SELinux relabeling.

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/openshift-sdn/sdn.yaml
It turns out we're not racing with a relabel, and waiting doesn't fix it. Instead, we're non-deterministically being started with a different selinux context. It's probably a crio bug. Removing runAsUser: 0 to see if that fixes it.
=> openshift-sdn: remove sdn relabel wait, remove runAsUser

bindata/network/openshift-sdn/sdn-ovs.yaml
* Bring over the fix for bz1572797
* Tail openvswitch logs to the console
* Exit if any of the underlying processes have quit
=> openshift-sdn: ovs daemonset improvements:

pkg/network/openshift_sdn.go
We query the CRI endpoint directly. The code defaults to the dockershim, but now we're using crio.
=> openshift-sdn: use the crio CRI socket

bindata/network/openshift-sdn/sdn.yaml, cmd/cluster-network-operator/main.go, sample-config.yaml
This addresses @danwinship's review comments in #28.
The sysctl was moved to openshift/machine-config-operator#178.
The default network blocks are being changed in openshift/installer#658
some extra apostrophe's we're added.
=> Remove ip_forward sysctl

cmd/cluster-network-renderer/main.go, pkg/apis/networkoperator/v1/networkconfig_types.go, pkg/controller/networkconfig/networkconfig_controller.go, pkg/controller/networkconfig/previous.go, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go, pkg/network/render.go, pkg/network/render_test.go
This saves the applied configuration as a config map, then retrieves it and compares against the newly-requested configuration.
It also makes the step of applying defaults explicit, so we can reason more clearly about proposed changes. In other words, changing a field from null to it's default should not be blocked. Likewise, a code bug that changes a default dangerously should also not propagate.
=> Block unsafe changes

bindata/network/openshift-sdn/sdn.yaml, pkg/network/openshift_sdn.go
now that https://github.com/openshift/origin/pull/21551 is merged, remove kubelet certs from the sdn pod
needed for https://github.com/openshift/machine-config-operator/pull/187
@smarterclayton @squeed
=> remove kubelet pki from sdn pod

bindata/network/openshift-sdn/sdn.yaml, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go
- use url-only-kubeconfig instead of patching the kubeconfig
- pass nodename directly instead of sed'ing
This enables restart-on-config-change.
=> openshift-sdn: minor daemonset cleanups:

bindata/network/openshift-sdn/controller.yaml
Even though daemonset does allow `replicas`,
`bindata/network/openshift-sdn/controller.yaml` set the value.
This patch removes `replicas: 1` from `openshift-sdn/controller.yaml`.
Fixes https://github.com/openshift/cluster-network-operator/issues/61
=> Remove invalid replicas 1 in daemonset in openshift-sdn/controller.yaml

bindata/network/openshift-sdn/sdn-ovs.yaml
When running ovs-vsctl when ovs-vswitchd isn't running, you have to pass `--no-wait` to tell it to not wait for ovs-vswitchd to read in the new config, for obvious reasons.
(The current version of the code doesn't correspond to any version that was ever in openshift-ansible... I guess Casey must have gotten an early version of the fix from Ben or something and then didn't realize that it wasn't what actually got committed.)
=> Fix the ovs-vswitchd too-many-threads fix

cmd/cluster-network-renderer/main.go
This patch calls f.Close() after opening file in readConfigObject().
=> Close file after open in readConfigObject

bindata/network/openshift-sdn/001-crd.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1661983
=> openshift-sdn: EgressNetworkPolicy is namespaced

bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/openshift-sdn/sdn.yaml, manifests/0000_07_cluster-network-operator_03_daemonset.yaml
This can be useful when we have the Pod but not its logs.
Thanks @deads2k for the suggestion.
=> openshift-sdn, manifests: capture last few log lines as our TerminationMessage

OWNERS
So I had noticed that for some reason, the bot *always* assigns @JacobTanenbaum and @pecameron to review cluster-network-operator PRs, and apparently this is because they're the only people listed as reviewers in the OWNERS file... ("approvers" aren't automatically assumed to be "reviewers" too)
also, alphabetization!
=> fix OWNERS

manifests/0000_07_cluster-network-operator_01_crd.yaml
The controller-runtime code gets very angry if one of the objects it's watching can't be deserialized into the expected golang type.
For the cluster config, we can fix this using the new CRD validation hack in origin, but for the network config that's not the greatest idea, since then origin would have to vendor cluster-network-operator to get the type, and then we'd have to coordinate changes between the two repos whenever we changed anything.
Instead, we can use OpenAPI validation to ensure that objects will only be accepted by the apiserver if they are at least close-enough-to-valid that we'll be able to deserialize them. (Eg, you don't have a string where an integer is supposed to be.)
This is based on the current definition of the struct but maybe we should remove the unsupported …
=> Add openAPIV3Schema to operator config type

manifests/0000_07_cluster-network-operator_03_daemonset.yaml
https://github.com/openshift/cluster-version-operator/pull/38#issuecomment-438465640
@deads2k suggests that a deployment should be able to schedule even when node is not-ready.
=> manifests: switch network operator to deployment

README.md
=> Update instructions for running operator locally

pkg/controller/clusterconfig/clusterconfig_controller.go
The offending line was added in a spree of new logging, oops.
=> cluster config controller: fix nil dereference

README.md, pkg/network/render.go, pkg/network/render_test.go
The intention is for users of third-party network plugins to still be able to set their network type.
=> Allow DefaultNetwork.Type to have arbitrary values.

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/openshift-sdn/sdn.yaml
This in combination with https://github.com/openshift/origin/pull/21978 should help avoid OOM of sdn and ovs pods
xref https://github.com/openshift/cluster-network-operator/pull/80
@derekwaynecarr @danwinship @dcbw @squeed
=> bindata: use system-node-critical priority

bindata/network/openshift-sdn/sdn-ovs.yaml
Changes from 3.9 to 3.10 now has OVS running in a pod. There must be
sufficient memory or the OOM killer will be invoked. This change adds a
liveness probe that checks the process is running. Also, resource limits
are relaxed a little.
bug 1671822
https://bugzilla.redhat.com/show_bug.cgi?id=1671822
clone of bug 1669311
https://bugzilla.redhat.com/show_bug.cgi?id=1669311
=> A ovs process gets killed when oom-killer is invoked

cmd/cluster-network-operator/main.go, pkg/util/k8s/dynamicrestmapper.go
controller-manager assumes that all resource Kinds will have been created before it starts up, so it can't deal with the case of creating a CRD and then creating an instance of that CRD (or waiting for another operator to create a CRD, and then creating an instance of that CRD). This is maybe not the bestest fix, but it works and we can discuss it further upstream.
Note that this code would be especially bad/inefficient if we thought that the controller was going to be repeatedly asked about objects of non-existent types, but there's no reason that would happen in CNO, so the reload path should only get hit in the creating-an-instance-of-a-previously-created-CRD case.
=> Replace the controller manager's RESTMapper with a dynamic one

INSTALLER-HACKING.md, README.md, hack/null-kubeconfig, hack/overrides-patch.yaml, hack/run-locally.sh
This is a stupid way to tell the installer not to run the network operator, and let us run it manually as part of the install process.
=> hack: add a development way to run the operator as part of the installer

hack/test-go.sh
also "go list" appears to ignore vendor by default these days, and the "xargs echo" was totally redundant
=> Only run "go test" in dirs with tests

bindata/network/openshift-sdn/000-ns.yaml, bindata/network/openshift-sdn/monitor.yaml, pkg/controller/networkconfig/networkconfig_controller.go, pkg/names/names.go, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go
Add the required service, serviceMonitor, role, and rolebinding to allow Prometheus
to scrape the metrics that the sdn provides
=> configure endpoints to expose openshift-sdn metrics to Prometheus

bindata/network/openshift-sdn/004-multitenant.yaml, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go
This groups control-plane namespaces in to three groups:
- VNID 0 (default, can access and be accessed by all)
- openshift-kube-apiserver
- openshift-dns
- openshift-ingress
- openshift-monitoring
- openshift-operator-lifecycle-manager
- openshift-image-registry
- VNID 1 (control plane)
- openshift-apiserver
- kube-system (etcd)
And all others will have their own isolated network.
Fixes SDN-284 / BZ 1659376
=> openshift-sdn: join control plane namespaces so multitenant works in 4+

bindata/network/openshift-sdn/004-multitenant.yaml
This adds 3 more namespaces to the control-plane namespace:
- openshift-template-service-broker
- openshift-ansible-service-broker
- kube-service-catalog-controller-manager
Fixes BZ1680214
/cc @jboyd01
=> openshift-sdn: more service-catalog netnamespace fixes

hack/verify-style.sh, pkg/network/cluster_config.go, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go, pkg/util/clusteroperator/status_manager.go, pkg/util/clusteroperator/status_manager_test.go, sample-config.yaml
- Actually verify style in hack/verify-stule.sh
- Fix rare nil pointer exception
- Fix name in sample-config.yaml
- Don't set network status when we haven't installed a network
=> Some small operator fixes

bindata/network/multus/multus.yaml, bindata/network/openshift-sdn/controller.yaml, manifests/0000_07_cluster-network-operator_03_daemonset.yaml
blocks passing smoke tests for ensuring control plane pods always schedule.
see: openshift/origin#22217
=> manifests: ensure system priorities

pkg/network/mtu.go, pkg/network/mtu_unsupported.go
Split out of #110 (and with the default fixed from 1400 to 1500) since the rest of #110 is going to get absorbed into another PR.
(See also #113, but this fix is still needed to make it easier for non-Linux-users to send us bugfixes.)
=> Fix build on non-Linux by not trying to guess the default MTU

bindata/network/multus/multus.yaml, bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/openshift-sdn/sdn.yaml, manifests/0000_07_cluster-network-operator_03_daemonset.yaml, manifests/0000_07_cluster-network-operator_04_clusteroperator.yaml, pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go, pkg/network/multus.go, pkg/network/openshift_sdn.go
As part of closing out cluster operators they must report when they
reach "level" - have rolled out the code in the update. For the network
operator that involves ensuring all the daemonsets and deployments
have the latest code deployed, and then reporting the current
controller release version via cluster operator status.
Related to https://github.com/openshift/cluster-image-registry-operator/pull/219
Needs a bump to vendor and updates to the cluster operator conditions
coming from @danwinship
=> Report version number from payload "when we hit level"

bindata/network/openshift-sdn/004-multitenant.yaml
A recent requirement hit Service Catalog to set the priorityClassName to "system-cluster-critical" which in turn required changing the namespaces for Service Catalog.  See associated Service Catalog updates:  
https://github.com/openshift/cluster-svcat-apiserver-operator/pull/37
https://github.com/openshift/cluster-svcat-controller-manager-operator/pull/24
This PR updates the namespaces in the multi tenant netid mappings.
=> New namespaces for Service Catalog

pkg/network/render.go
We don't currently support it, and it's not tested.
"Fixes" 1688212.
=> network: don't allow changing DisableMultiNetwork

manifests/0000_07_cluster-network-operator_01_crd.yaml
Namely this is the place https://github.com/openshift/cluster-config-operator/blob/master/manifests/0000_05_config-operator_01_network.crd.yaml and that is guaranteed to be instantiated before you run your operator.
=> Remove networks.config.openshift.io which is already instantiated by cluster-config-operator

pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go
Don't explicitly mark the operator as Available=False when marking it Progressing=True... However, if we mark it Progressing=True and there is no Available status at all, then mark it Available=False in that case.
The net effect of this is that we should still be Available=False at startup, but we will be Available=True Progressing=True during upgrades.
=> Bug 1687973: Fix operator status during upgrade

bindata/network/openshift-sdn/sdn.yaml
In order to get access to the hosts iptables binary mount all of the hosts / dir in the sdn image as /host
=> mount hosts / in sdn image

bindata/network/openshift-sdn/sdn.yaml
RHEL7 unifies /usr/bin and /bin but we should refer to the location of the openshift-sdn binary as the same place even though the two are functionally equivalent
=> specify the same location for the openshift-sdn binary

bindata/network/multus/multus.yaml
This requires that this pull request is merged first: https://github.com/openshift/multus-cni/pull/7/files
If this gets merged before that pull request -- Multus may fail to come up due to the fact that previous versions did not support unknown parameters (that will be mitigated in the future by changes within the referenced PR)
=> Adds parameter to set multus log level to verbose in multus.yaml

Dockerfile.rhel7
Remove hardcoded 'amd64' from Dockerfile to support multi-arch builds.
=> Remove hardcoded 'amd64' from Dockerfile to support multi-arch builds.

bindata/network/multus/003-dhcp-daemon.yaml, pkg/network/dhcp_daemon.go, pkg/network/dhcp_daemon_test.go, pkg/network/multus.go, pkg/network/render.go
Adds rendering, bindata & unit tests for the containernetworking/plugins DHCP CNI plugin running as a daemon.
Currently has no dependency on the macvlan functionality, however, it anticipates it with a commented-out `TODO` block.
=> DHCP Daemon

README.md, bindata/network/ovn-kubernetes/000-ns.yaml, bindata/network/ovn-kubernetes/002-rbac.yaml, bindata/network/ovn-kubernetes/003-rbac-controller.yaml, bindata/network/ovn-kubernetes/004-config.yaml, bindata/network/ovn-kubernetes/005-service.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, manifests/0000_07_cluster-network-operator_03_daemonset.yaml, manifests/image-references, pkg/network/cluster_config.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/network/render.go
This sets up the structural support for ovn-kubernetes overlay networks.
This is very early, lots more changes in the works.
It supplies pkg/network/{ovn_kubernetes.go,}
And modifies pkg/network/{cluster_config.go,render.go} to reference ovn
It supplies the needed bindata/network/ovn-kubernetes/ files.
The operator comes up and creates the ovn environment
=> Initial support for ovn-kubernetes

bindata/network/additional-networks/sriov/sriov-device-plugin.yaml
Kubernetes 1.13 supports(GA) a new plugin registration
path {kubelet_root_dir}/plugins_registry, but it also
maintains backward compat for old registration path at
{kubelet_root_dir}/device-plugins; This change allows
both pathes be mounted to sriov device plugin daemonset.
=> fix mount path for sriov device plugin socket

bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
The node is ready when the cni plugin creates its .conf file
in /etc/cni/net.d/ This change deletes thefile when the cni
plugin terminates.
bug: 1654044
https://bugzilla.redhat.com/show_bug.cgi?id=1654044
SDN 352 - 4.0 Keep node NotReady until sdn is up.
https://jira.coreos.com/browse/SDN-352
=> Remove /etc/cni/net.d/ file when plugin is down

bindata/network/multus/multus.yaml, pkg/network/multus.go
That way multus will use that to look up pod info during setup/teardown, and not depend on the service IP working.
Fixes for https://bugzilla.redhat.com/show_bug.cgi?id=1695554. (Either https://github.com/openshift/origin/pull/22471 or this should fix the bug. Both are independently worthwhile fixes though.)
=> Pass the "real" apiserver info to the multus setup script

pkg/controller/statusmanager/status_manager.go
We should also need to call syncFailing in case level is nil.
Signed-off-by: Ricardo Carrillo Cruz <ricardo.carrillo.cruz@gmail.com>
=> Call syncFailing on SetNotFailing method

bindata/network/openshift-sdn/sdn.yaml
This avoids getting spurious "No such file or directory" failures
on sdn pod log during startup
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1581584
=> Pipe socat stdout and stderr to dev null

pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go
The easiest way to tell that a daemonset is progressing is that UpdatedNumberScheduled is less than Desired.
Also, catch the case where the daemonset update hasn't yet been observed by the controller.
=> status: catch a few more Progressing cases

pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go
Reverts #26 because origin bumped its copy of openshift/api a long time ago
=> Bug 1666223 - Remove temporary hack around vxlanPort serialization

pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go
At startup we report Failing/Degraded status because we know the operator is planning to create a DaemonSet but it hasn't done it yet. We don't really need to be that pessimistic. We can just assume that the operconfig controller actually will create the DaemonSet it said it was going to create, and if it doesn't, that it will set a Degraded status itself.
=> Be less pessimistic about operator status at startup

pkg/controller/statusmanager/status_manager.go
Apparently the "Progressing" condition on a Deployment does not get cleared when the Deployment becomes "Available".
(Casey added this as part of #143 but it wasn't tested there since openshift-sdn doesn't use any Deployments, just DaemonSets.)
=> Fix handling of Deployment Progressing status

bindata/network/openshift-sdn/sdn.yaml
By checking to see that the sdn configuration file gets written out, we ensure the daemonset doesn't roll out a completely broken change.
It also slows down sdn rollouts slightly.
=> openshift-sdn: configure sdn readiness probe

hack/open-ovn-ports.sh
While waiting to figure out https://github.com/openshift/installer/issues/1218, here's a helper to open the ports for you in a cluster. It can be run almost immediately after `openshift-install create cluster` starts (and if you run it too soon, it will error out and you can try again later).
I didn't bother making `run-locally.sh` run it automatically yet, although we could... but it's hopefully temporary?
Requires the `awscli` and `jq` packages (and requires that `awscli` has been set up with the correct defaults, which I believe is explained somewhere in the openshift docs...)
=> Add helper script to open OVN ports on AWS

bindata/network/openshift-sdn/003-rbac-controller.yaml, manifests/0000_07_cluster-network-operator_00_namespace.yaml
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …
=> Add node-selector annotation to namespace

bindata/network/openshift-sdn/sdn.yaml
When we try and mount `/etc/sysconfig/openshift-sdn`, but it doesn't exist, runc creates it as a directory. This is annoying when we want users to be able to enable logging - it needs to be a file.
So, just mount /etc/sysconfig.
=> openshift-sdn: mount full sysconfig directory

pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go
`W0418 15:38:05.687451    2233 util_unix.go:77] Using "/var/run/crio/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/crio/crio.sock".`
=> Use non-deprecated crio URL format

bindata/network/openshift-sdn/sdn.yaml
The kube-proxy code exposes a liveness endpoint. Configure the pod to use that.
=> openshift-sdn: add kube-proxy liveness probe

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/openshift-sdn/sdn.yaml
For SDN, use a bash hack to redirect all stderr and stdout to the system journal, so that logs are preserved via journald. For OVS, use the native syslog support.
Philosophically, this is because the sdn processes, although distributed via a daemonset, really are "node" components.
=> openshift-sdn: log ovs and sdn to the system journal

hack/run-locally.sh
Two unrelated fixes:
- Get `RELEASE_VERSION` from the cluster rather than the local tree. There was discussion about this in #146 and I was arguing that we have to get the image variables from the local tree, and Casey was arguing that we have to get the version from the cluster, and we were both right. #146 was getting the version from the `DaemonSet` when taking over an existing cluster, but you need to get the right version even when starting a new cluster if you want it to come up fully and error-free, so this changes the script to parse it out of the `ClusterVersion` resource.
- Use `kubectl patch` rather than `kubectl convert` as our hacky "run a JSONPath expression on a YAML file" command, since the latter is now deprecated and prints a warning
=> run-locally.sh fixes

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/cluster_config.go, pkg/network/ovn_kubernetes.go
This does not get CNO+OVN into a fully-working state. But all of these fixes are correct as-is and don't depend on any as-yet-unmerged upstream stuff.
=> OVN Kubernetes fixes

bindata/network/additional-networks/sriov/sriov-device-plugin.yaml
As discussed in #165, the sriov-device-plugin pod needs the same tolerations as sriov-cni
=> Make srio-device-plugin tolerations match sriov-cni

cmd/cluster-network-operator/main.go
No sense in generating spurious error messages.
=> cmd: exit 0 on graceful shutdown

pkg/apply/merge.go
This was resulting in pointless object churn as we deleted the pull secrets, then the controller immediately re-added them.
=> pkg/apply: copy over auto-generated imagePullSecrets for ServiceAccounts

bindata/network/ovn-kubernetes/003-rbac-controller.yaml, bindata/network/ovn-kubernetes/005-service.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
1. At some point the `ovnkube-master` service got renamed to `ovnkube-db`, and `ovnkube.sh` changed to manually create its Endpoints after the sbdb comes up, rather than having them be created automatically by kubernetes. So update the Service and our RBAC permissions for that.
2. `ovnkube.sh` no longer hardcodes the namespace, so update to pass in the correct namespace in the pods
(Note that these changes only touch files that are ovn-kubernetes-only, so this PR has no effect on 4.1.)
=> More ovn-kubernetes fixes

pkg/apply/apply.go, pkg/apply/merge.go
=> Only run update logic if objects are actually different

bindata/network/openshift-sdn/002-rbac.yaml
This is needed for SDN-260, which is about tainting
nodes with a too small MTU, thus the need for update permission.
=> Give the ability to patch nodes to openshift-sdn

bindata/network/openshift-sdn/sdn.yaml
Should be no need for this to be writable.
=> openshift-sdn: make host mount read-only

bindata/network/openshift-sdn/sdn-ovs.yaml
When looking in to other bugs, I saw a lot of errors from kubelet:
Pod "ovs-XXX" is terminated, but some containers are still running.
It looks like the SIGTERM isn't being respected. Let's fix this two ways: Stop running tail in an infinite loop (which might cause the signal to be ignored), and tell the kubelet to stop OVS explicitly.
=> openshift-sdn: ovs shutdown ordering.

bindata/network/openshift-sdn/sdn-ovs.yaml
This reverts commit 6a3ff5cf3d1130318b640c806a958bf736db6fc7, #181.
I'm not clear on the connection, but this change seems to have [increased the likelihood of fatal upgrade timouts][1], and that's blocking org-wide master progress.  Ideally we'd fix [the underlying issue][2], but this reversion should help unblock master CI while we work on that.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1715515
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1714699
=> Revert "openshift-sdn: ovs shutdown ordering."

bindata/network/openshift-sdn/005-clusternetwork.yaml, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go, pkg/network/testutil_test.go
Currently CNO writes out a controller-config.yaml for sdn-controller, which the sdn-controller then turns into the default ClusterNetwork object. But this is just historical baggage, and there's no reason the CNO couldn't just create the ClusterNetwork itself.
Currently sdn-controller requires that it receives a controller-config on startup, and it will get annoyed if it finds a pre-existing ClusterNetwork object that doesn't match the controller-config. So we still have to create the controller-config as well. But once this has merged, we can change sdn-controller to read its config from the ClusterNetwork object instead and not need a config file.
=> Render the default ClusterNetwork

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Our ovn-northd pod was reserving the same (host) port for health checking as we use for kube-controller-manager, causing kube-controller-manager to not be able to start up. Since the OVN pods were just reserving the ports without actually doing any health checking with them, let's just remove them.
(Not submitting this upstream because removing the TODO is wrong.)
=> Remove (unused) ovn-kube health check ports, which conflict with kube-controller-manager

manifests/0000_70_cluster-network-operator_03_daemonset.yaml, manifests/image-references
This has no real effect - since the release tooling *always* replaces these with references to builds, but it helps for attach.sh and for documentation.
=> manifests: change image references to 4.2

bindata/network/openshift-sdn/003-rbac-controller.yaml
Because the sdn-controller was based on the openshift-controller-manager code, it used to ignore the ServiceAccount we set up for it and instead used the one set up by origin, which we then also redundantly set up here because in 4.x the sdn-controller starts up for the first time before the origin bootstrappolicy stuff runs.
Anyway, with https://github.com/openshift/origin/pull/22947 merged, sdn-controller now uses the roles we set up, which means that we can get rid of the redundant-origin-role-setting-up stuff, but also that we need to fix our role to actually be correct. (In particular, sdn-controller needs to be able to delete NetNamespaces when the corresponding Namespaces are deleted.)
=> Update sdn-controller RBAC

bindata/network/ovn-kubernetes/ovnkube-node.yaml
Copied the readinessProbe from OpenShiftSDN and modified for ovn
SDN-447 - OVN: exec-based readiness probe
https://jira.coreos.com/browse/SDN-447
=> Add readinessProbe to ovn-kubernetes

bindata/network/openshift-sdn/sdn-ovs.yaml
This reverts commit 5de6391d372a856d553e676fe3c2c5169a143c35, reversing changes made to 72a73a47d07284cfba697d6bbb61a5bc58cdf498.
It restores proper OVS shutdown.
=> Revert "Merge pull request #183 from wking/revert-OVS-shutdown-change"

bindata/network/openshift-sdn/sdn.yaml
The 'loglevel' flag is getting removed from internal binaries to
eliminate some shared packages that are not necessary.
blocks https://github.com/openshift/origin/pull/23113
=> Use the go-native flag for verbosity

bindata/network/ovn-kubernetes/ovnkube-node.yaml
ovnkube creates iptables rules for nodeport ports, so it needs to use the right iptables binaries
See also https://github.com/openshift/ovn-kubernetes/pull/10
=> Mount host / into ovnkube-node container, for iptables binaries

HACKING.md, hack/run-locally.sh
```
hack/run-locally.sh new -n ovn -i /path/to/openshift/installer -c /tmp/ovntest -m "quay.io/openshift/origin-ovn-kubernetes:latest"
hack/run-locally.sh override -c /tmp/ovntest
```
@squeed @rcarrillocruz @danwinship @pecameron @JacobTanenbaum
=> run-locally.sh: add from-scratch cluster up capability

pkg/controller/statusmanager/status_manager.go
Before, during an upgrade, the status would go:
DaemonSet %q update is rolling out (0 out of 3 updated)
...
DaemonSet %q is not available (awaiting 1 nodes)
...
DaemonSet %q update is rolling out (1 out of 3 updated)
...
DaemonSet %q is not available (awaiting 1 nodes)
...
DaemonSet %q update is rolling out (2 out of 3 updated)
...
DaemonSet %q is not available (awaiting 1 nodes)
...
Fix it to make the "update is rolling out" status take precedence over
the "not available" status.
=> Slightly improve Progressing statuses

hack/open-ovn-ports.sh
The `aws ec2 authorize-security-group-ingress` call will error out if the ports already exist. Since this is just a temporary hack, I just made it ignore the error rather than checking first, because that was easier.
=> Allow running open-ovn-ports.sh multiple times

bindata/network/openshift-sdn/alert-rules.yaml
adding 2 initial alerts to openshift-sdn
1. Adding alert to check if any containers in the openshift-sdn are in crashloopbackoff
2. Adding alert if there is a mismatch between the number of nodes and the number of ovs containers
=> adding alerts for sdn in prometheus

bindata/kube-proxy/000-ns.yaml, bindata/kube-proxy/001-rbac.yaml, bindata/kube-proxy/kube-proxy.yaml, bindata/kube-proxy/monitor.yaml, manifests/0000_70_cluster-network-operator_03_daemonset.yaml, manifests/image-references, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go, pkg/network/proxy.go, pkg/network/proxy_test.go, pkg/network/render.go
This installs a standalone kube-proxy when needed. This is whenever we're not installing a network that is known to include it itself. This means that kube-proxy will be installed for third-party network plugins.
=> Install standalone kube-proxy.

bindata/network/openshift-sdn/alert-rules.yaml
After talking with the monitoring team 'critical' was too high a severity level for rule NetworkPodsCrashLooping, 'warning' is more appropriate.
=> change the serverity level for alert NetworkPodsCrashLooping

bindata/network/kuryr/004-daemon.yaml, bindata/network/kuryr/005-controller.yaml
Commit changes the labels of Kuryr pods to make sure we distinguish
kuryr-cni and kuryr-controller. Also selector field is added as it seems
to be required.
=> Make Kuryr pods labels unambiguous

bindata/network/openshift-sdn/sdn-ovs.yaml
The two chowns are to set the ownership from the host mounted
volumes, since they may be incorrectly mapped.
sdn-33
ref: https://jira.coreos.com/browse/SDN-33
Signed-off-by: Aaron Conole <aconole@redhat.com>
=> sdn-ovs: allow ovs daemons to run as non-root

bindata/network/ovn-kubernetes/ovnkube-node.yaml
Needed to sync with https://github.com/ovn-org/ovn-kubernetes/commit/f3b2e19c and https://github.com/ovn-org/ovn-kubernetes/pull/741. Blocks https://github.com/openshift/ovn-kubernetes/pull/12
=> Specify OVN_GATEWAY_MODE in ovnkube-node

bindata/network/openshift-sdn/004-multitenant.yaml
Currently multitenant is broken since apiserver cannot connect
to etcd
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1719653
=> Put openshift-etcd netnamespace on netid 1

bindata/network/multus/multus.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
This PR is created with respect to Bugzilla ID: [1726069](https://bugzilla.redhat.com/show_bug.cgi?id=1726069)
I'm paraphrasing the bug report: "Now that multus pods already use .spec.priorityClassName, they should not keep the experimental 'critical-pod' annotation"
=> removing experimental annotation on multus ds config. 

bindata/network/kuryr/003-config.yaml
Turns out that in .ini-like files you don't use "[]" to mark a list, you
just add options separated by a comma. This commit removes "[]"
mistakendly used on resource_tags option, so the tags will have a
correct form of just `openshiftClusterID=<cluster-id>`.
=> Kuryr: Fix [neutron_defaults]resource_tags setting

bindata/network/openshift-sdn/alert-rules.yaml
IPTableSyncSDNPod - fires when it takes an sdn pod more then 15s to sync 95% of the iptables rules
IPTableSyncCluster - fires when it takes the whole cluster on average more then 10s to refresh iptables rules
iptables taking a long time to sync would be a useful in debugging network issues, could be symptomatic of a number of network issues
NodeIPTablesStale - fires when an individual sdn pod has not synced iptables for 120s
ClusterIPTablesStale - fires when the average refresh rate of the cluster if 90s
NOTE: 90s and 120s are not really the time for refresh, there are a few offsets including a scrape delay that could not be fully tracked down but these values should be sufficiently high
not syncing iptables rules reflects that the sdn pods are starved for resources and could be the cause …
=> adding additional sdn alerts to prometheus

bindata/network/kuryr/003-config.yaml
Seems like RHCOS VM's use ens3 as the name of the Neutron interface they
get. In order for Kuryr to correctly attach subports to that interface
this commit sets [binding]link_iface=ens3 in kuryr.conf.
=> Kuryr: Use ens3 as link_iface in kuryr.conf

pkg/network/proxy.go, pkg/network/proxy_test.go
Kuryr handles services on its own, so it doesn't need kube-proxy. This
commit disables its deployment when Kuryr is configured.
=> Kuryr: Disable kube-proxy

pkg/network/cluster_config.go
Looks like due to an overlook we haven't enabled setting status on
Network CRD when running with Kuryr. This made the certificates
presented by openshfit-apiserver lack the IP as Common Name, causing SSL
validation to fail when trying to call API using the IP.
This commit fixes that by making sure StatusFromOperatorConfig() is not
returning nil when Kuryr is configured.
=> Kuryr: Fix setting status on Network CRD

bindata/network/kuryr/003-config.yaml
OpenShift with new installer has an enourmous amount of namespaces
created initially. As Kuryr needs to prepare a new subnet for each
namespace and prepopulate it with ports, we get high rate of requests to
OpenStack Neutron, which affects performance even to the point of
killing the neutron API server.
To counteract that this commit lowers the default numbers of ports being
created for each pool.
=> Fine-tune Kuryr port pools defaults

pkg/platform/openstack/kuryr_bootstrap.go
This PR solves two issues with the Octavia LB we create to cover `kubernetes.default` access to OpenShift API. One is allowing the traffic from service subnet (where Octavia LB VM sits) to masters subnet (where OpenShift API sits).
Second one makes sure LB members are added into service subnet, not the worker subnet, basically because the latter doesn't make any sense and puts Octavia into L2 mode which isn't supported.
I'm just editing this as GitHub doesn't seem to display this when listing PR's, so let's see if that triggers anything.
=> Kuryr: Fix OpenShift API loadbalancer

bindata/network/kuryr/004-daemon.yaml, bindata/network/kuryr/005-controller.yaml, pkg/network/kuryr.go
Turns out we should use api-int loadbalancer to make Kuryr connect to
the OpenShift API. This commit implements that.
=> Make Kuryr connect to API through api-int LB

pkg/controller/operconfig/operconfig_controller.go, pkg/controller/statusmanager/status_manager.go
This allows must-gather tool to give information about CNO objects
for free.
=> Add namespaces managed by CNO to related objects field

bindata/network/openshift-sdn/003-rbac-controller.yaml
We need this to remove the NetworkUnavailable status that the GCP cloud-provider always sets. This is because it requires routes to be programmed, but we have it configured to not actually program routes.
=> openshift-sdn: give sdn-controller the ability to patch nodes.

manifests/0000_70_cluster-network-operator_03_daemonset.yaml
For GCP, all nodes start with `node.kubernetes.io/network-unavailable` due to upstream behavior.
we need the network-operator to schedule on masters and start sdn pods so that node is made available.
/cc @squeed @dcbw
=> manifests: allow network-operator to be schedulable when network-unavailable

bindata/network/openshift-sdn/001-crd.yaml
This addresses bug [1707749](https://bugzilla.redhat.com/show_bug.cgi?id=1707749)
Please let me know if the description should be modified.
/Alex
=> Adding egress IP addresses to the CRD output

pkg/platform/openstack/kuryr_bootstrap.go
The API LB members should match the default/kubernetes endpoints.
This commit adds support to sync the members with the endpoints
when a reconciliation occurs.
=> Kuryr: Sync LB members with Kubernetes endpoints

bindata/network/openshift-sdn/controller.yaml, manifests/0000_70_cluster-network-operator_03_daemonset.yaml, manifests/image-references, pkg/network/openshift_sdn.go, pkg/network/ovn_kubernetes.go
Necessary to split sdn from origin.
=> Move from hypershift to sdn-controller image

bindata/network/ovn-kubernetes/ovnkube-node.yaml
#223 mistakenly added the `OVN_GATEWAY_MODE` variable to the ovn-controller container rather the ovnkube node container. (Alas, fixing this does not fix the dns-not-ready problem.)
Also, for no apparent reason, we were running ovnkube node with debug-level logging, while everything else was at "info" level.
=> ovn-kubernetes: fix gateway mode, log level

bindata/network/ovn-kubernetes/003-rbac-controller.yaml
Currently you can't create a privileged-ish pod when using ovn-kubernetes, because when the ovnkube master tries to patch the Pod with an annotation, it fails:
time="2019-07-17T15:20:15Z" level=info msg="Setting annotations ovn={\\\"ip_address\\\":\\\"10.129.2.9/23\\\", \\\"mac_address\\\":\\\"0e:3a:8f:81:02:0a\\\", \\\"gateway_ip\\\": \\\"10.129.2.1\\\"} on pod lemon"
time="2019-07-17T15:20:15Z" level=error msg="Error in setting annotation on pod lemon/foo: pods \"lemon\" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 8888: Host ports are not allowed to be used]"
It seems that you can only add an annotation to a security-context-constrained pod if you have access to an SCC that would …
=> Allow openshift-ovn-kubernetes-controller to use privileged SCC

Dockerfile
This modifies the Dockerfile to add the build support for archs other than amd64, based on the commit: https://github.com/openshift/cluster-network-operator/commit/1c9828fdcacec9240aff3a402429df4c3e1dd2ef
=> Adding build support for archs other than amd64

hack/run-locally.sh
on a bad argument, run-locally would report, eg:
danw@p50:cluster-network-operator (run-locally-usage)> ./hack/run-locally.sh -x
./hack/run-locally.sh: illegal option -- x
./hack/run-locally.sh: line 220: OPTARG: unbound variable
This is because (a) bash getopt reports its own errors on bad arguments, and (b) run-locally's own error reporting was using the wrong variable name (`OPTARG` instead of `opt`)
This drops run-locally's error reporting, which then also makes it print the help on any unrecognized argument.
=> run-locally.sh: fix output on usage error

pkg/controller/operconfig/operconfig_controller.go, pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go
This PR sets the "Upgradeable" condition to always be true. Fixes [Bugzilla report 1727026](https://bugzilla.redhat.com/show_bug.cgi?id=1727026)
Some requested feedback on this PR: I am not sure if the best way of doing this is by using the setter (as I have done). This will mean that we just reset the upgradeable status to true everytime any condition status is set of course. I didn't find any more straightforward way of doing this however, i.e: clearer way and without code duplication. Please let me know if anyone has any ideas.
=> Adding upgradeable status and setting it to always "true" for now.

pkg/network/openshift_sdn.go
I didn't want to do another round of back and forth on Friday evening when we were trying to get stuff in before the deadline and wrestling with e2e-aws flakes, but this was annoying me. The override correctly handles all cases without needing to modify the defaults. (Also, the comment about having already validated proxy-mode should be inside the `if`, not outside it, since the comment is only true if the `if` condition is true.)
=> Slightly simplify unidling config code

pkg/platform/openstack/kuryr_bootstrap.go
By default pods under the same subnet should be able to
talk with each other, this commit adds a new security group
rule allowing this traffic.
=> Add sg rule allowing traffic between pods

pkg/controller/statusmanager/status_manager.go
When we update the ClusterOperator.Status we log the YAML of it. But this is mostly because it's interesting to see the conditions; we don't want to see the list of related objects every time, since it never changes (and just forces the part that you do care about to scroll off the screen). So just log `co.Status.Conditions` instead.
Then while trying to figure out why we still logged the status even when nothing changed, I discovered that we were dumb. A `ClusterOperator` will never be equal to a `*ClusterOperator`...
=> Stop unnecessary status updates, make necessary ones less verbose

cmd/cluster-network-renderer/main.go, hack/test-sec.sh
gosec does static code analysis and checks for common security issues in golang codebases.
This PR introduces the tool, and sets it up as a test target in the Makefile; it also fixes a couple of warnings that were found.
=> Introduce gosec for security checks

bindata/network/multus/003-dhcp-daemon.yaml, bindata/network/multus/multus.yaml, manifests/0000_70_cluster-network-operator_03_daemonset.yaml, manifests/image-references, pkg/network/multus.go
This condenses the images for the container networking CNI reference plugins into a single image instead of having them in two images (with -supported & -unsupported suffixes).
I had ART update their build instructions, and their changes are available here @ https://gitlab.cee.redhat.com/openshift-art/ocp-build-data/merge_requests/172/diffs
Additionally, I have a pending PR for updating image mirroring in openshift/release here @ https://github.com/openshift/release/pull/4334
I believe this PR should be in a hold state until the openshift/release PR gets merged.
Also, quite happy to take any input on other changes should I have missed any, I tried to grep through and find any references to the -supported/-unsupported images to have them updated, but, any eyeballs are appreciated for sure.
=> Condense CNI reference plugins images into a single image

bindata/network/kuryr/004-daemon.yaml, pkg/network/kuryr.go
With the merge of #237 kuryr can now get the CNI plugins it needs from the official image rather than stealing them from the SDN image.
I'm not sure how to test this, but someone should before merging it.
=> kuryr: get CNI loopback plugin from CNIPluginsImage

hack/overrides-patch.yaml
When attempting to use `hack/run-locally.sh` to attach to a running cluster you get a failure
patching the clusterversion
...validation failure list:
spec.overrides.group in body is required
adding the api group to the overrides-patch.yaml
=> add the api group to the override spec

manifests/0000_70_cluster-network-operator_01_crd.yaml
Currently if you follow [our documentation on configuring multitenant, etc](https://docs.openshift.com/container-platform/4.1/installing/installing_aws/installing-aws-network-customizations.html#modifying-nwoperator-config-startup_installing-aws-network-customizations) it doesn't actually work because we claim you can write out a partial operator config, but we install a CRD that won't accept the partial config. Or maybe it worked somehow in 4.1 but doesn't in 4.2? Anyway, easy fix...
=> Don't require clusterNetwork and serviceNetwork to be set in operator type

pkg/controller/proxyconfig/status.go, pkg/util/proxyconfig/merge.go
Moves noProxy merge function to a separate pkg. Also supercedes https://github.com/openshift/cluster-network-operator/pull/283/files to fix noProxy status sync.
/assign @bparees @squeed @wking
=> Moves noProxy merge func to a separate pkg

pkg/util/proxyconfig/merge.go
Previously, values of dependent resources (i.e. network) were assumed to be present. This PR checks the presence of the value before using it in the noProxy merge function.
/assign @squeed @bparees
=> Fixes Bug 1740027: Checks length of values in noProxy merge

pkg/controller/proxyconfig/controller.go, pkg/controller/proxyconfig/validation.go
Requires https://github.com/openshift/cluster-network-operator/pull/245.
__Note:__ `readinessEndpoints` with a https URI scheme requires https://github.com/openshift/cluster-network-operator/pull/271.
Jira: [SDN-492](https://jira.coreos.com/browse/SDN-492) 
PTAL @squeed @bparees @JacobTanenbaum
=> Adds readinessEndpoint validation for Proxy API type.

bindata/network/kuryr/004-daemon.yaml, bindata/network/kuryr/005-controller.yaml
Default failureThreshold for healtchecks is 3. This PR increases
that default value for the kuryr-controller and kuryr-cni pods
to reduce the number of unneeded restarts during the installation
=> modify default failureThreshold for kuryr components

bindata/network/openshift-sdn/sdn.yaml, pkg/network/openshift_sdn.go
Sets us up to stop building those plugins in the openshift-sdn image
=> openshift-sdn: get CNI loopback and host-local plugins from CNIPluginsImage

bindata/network/multus/multus.yaml
This is a PR addressing bug [1735538](https://bugzilla.redhat.com/show_bug.cgi?id=1735538). 
Problem:
Multus is writing a CNI config file on the host, which today, is missing the `cniVersion` and leading to errors when attempting to delete pod networks.
Solution:
The multus `entrypoint.sh` parses the `--cni-version` passed, I thus assume the intention from the multus team is to pass the CNI version through the daemonset deployment spec like this.
The problem that remains is of course a hard-coded CNI version in multus (which will need to be updated manually). I could also just read the `cniVersion` from the SDN config file, but I am not sure that's better...........
=> Bug 1735538: Adding cni-version to multus daemonset yaml

manifests/0000_70_cluster-network-operator_01_crd.yaml
This makes it impossible to change the network configuration from what's in the cluster.
@weliang1 this should fix the issue you saw.
=> manifests: the openshift-sdn type isn't actually required

hack/run-locally.sh
"`-m IMAGE`" only worked if you also specified "`-n PLUGIN`", even though the plugin would otherwise correctly default to `OpenShiftSDN`.
=> run-locally.sh: fix -m without -n

pkg/util/proxyconfig/merge.go
Fixes Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1743507
Previously, only the service cidr was added to the default noProxy list. This does not help when pods communicate with a service using a DNS name. This PR adds `.svc` and `svc.cluster.local` to the default noProxt list.
/assign @knobunc @bparees
=> Adds .svc and .svc.cluster.local to default noProxy

bindata/network/kuryr/003-config.yaml, bindata/network/kuryr/005-controller.yaml, pkg/network/kuryr.go, pkg/network/kuryr_test.go
This PR updates some default configuration for kuryr, such as:
- Port to be used for the kuryr-controller healthcheck if not stated
- Kuryr-controller healthcheck tuning to avoid unneeded restarts
- Default waiting time for ports to become active (increasing default
value to limit kuryr-cni restarts)
=> OpenStack: Adjust kuryr default configuration

bindata/network/kuryr/006-service.yaml, bindata/network/kuryr/007-admission.secret.yaml, bindata/network/kuryr/008-webhook.secret.yaml, bindata/network/kuryr/009-admission-controller.yaml, bindata/network/kuryr/010-webhook.yaml, pkg/bootstrap/types.go, pkg/names/names.go, pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go, pkg/platform/openstack/util/cert/cert.go
Due to Octavia not supporting UDP listeners in Queens version,
coredns deployments that uses UDP are not supported as well.
This PR creates a mutating webhook to inject a dnsConfig option,
"use-vc", to pods deployments, so TCP is used instead of UDP
for dns resolution.
=> Add Kuryr DNS modifications webhook

pkg/controller/operconfig/operconfig_controller.go, pkg/controller/proxyconfig/controller.go, pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go
This addresses bug: [1737026](https://bugzilla.redhat.com/show_bug.cgi?id=1737026)
I am not sure if this addresses the concerns you mentioned in the bug @danwinship , but in this case I made set internal and I added a mutex inside `set`. 
I inspired myself on `runningPodsLock` in pod.go from openshift/sdn.
=> Bug 1737026: Making set internal to the statusManager and adding mutex for thread safety

bindata/network/kuryr/004-daemon.yaml, bindata/network/kuryr/005-controller.yaml, bindata/network/kuryr/009-admission-controller.yaml, pkg/network/kuryr.go
This PR ensures the VERSION field is set on the network cluster
operator config object by adding it to the different kuryr
components, i.e., the kuryr-controller and admission-controller
deployments, and kuryr-cni daemon set.
=> Set version on network cluster operator with kuryr SDN

pkg/network/openshift_sdn.go
We can fill a sensible default anyways. So this is just confusing and user-unfriendly.
=> Bug 1746360: openshift-sdn: allow empty mode

pkg/util/proxyconfig/no_proxy.go, pkg/util/proxyconfig/no_proxy_test.go
The node subdomain must be added to the default proxy noProxy list to allow functionality such as the api server fetching container logs. `TestMergeUserSystemNoProxy` was added to exercise the `MergeUserSystemNoProxy` function.
/assign @squeed @bparees
/cc @knobunc @JacobTanenbaum
=> Adds mergeProxy() tests and node subdomain to default noProxy list

pkg/controller/configmap_ca_injector/controller.go, pkg/controller/statusmanager/status_manager.go
To help debug potential issues with the configmap ca injector add statusmanager and more clearly log some errors
=> Adding status to configmap ca injector controller

bindata/network/kuryr/003-config.yaml, pkg/bootstrap/types.go, pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go
Seems like setting `external_svc_net` was ommitted in initial
implementation of preparing kuryr.conf. This breaks Kuryr's support for
LoadBalancer services. This commit fixes it by fetching the external
network ID from the external-router created by the installer and passing
it to kuryr.conf.
=> Bug 1748354: Kuryr: Add external_svc_net to kuryr.conf

pkg/platform/openstack/kuryr_bootstrap.go
Seems like openshift/installer#2304 updates the SG opening traffic to
master to just open port 6443 instead of 6443-6445 range. I was
suspecting it's just a typo, but did the same on CNO just to be safe.
This commit mimics what the openshift/installer commit does.
=> Kuryr: Open just 6443 on masters SG

bindata/network/kuryr/004-daemon.yaml, bindata/network/multus/multus.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/kuryr.go, pkg/network/kuryr_test.go, pkg/network/multus.go, pkg/network/openshift_sdn.go, pkg/network/ovn_kubernetes.go, pkg/network/render.go
This is a continuation of #218 and includes @squeed 's commit therein.
In order to address the race condition where openshift-sdn CNI config is loaded by crio/ocicni first and then does not read the `00-multus.conf` file as generated by the entrypoint.
This implements a parameters to enter a loop to detect the presence/absence of the openshift-sdn CNI configuration and a flag to restart CRIO on generation of the `00-multus.conf`. This does **not** override the `"name":` field (e.g. using `--override-network-name=true` which would copy that from source CNI config to generated `00-multus.conf`)
*NOTE*: This may not be necessary if we have the intended changes to ocicni. So I intend to put this on a hold.
In reference to [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1732598).
=> Alternate configuration directory + 00-multus.conf regeneration

bindata/network/kuryr/003-config.yaml
With recent change to kuryr-lib it is possible to specify OpenStack
cloud region name that should be used by Kuryr. This commit implements
that by setting that option in kuryr.conf.
=> Kuryr: Set region_name in kuryr.conf

pkg/network/additional_networks.go, pkg/network/additional_networks_test.go
SimpleMacvlan should respect the desired namespace in the additionalNetworks struct.
Updates SimpleMacvlan to set the namespace before it's rendered, alters test to specify a namespace instead of using default.
=> Bug 1751070: Updates SimpleMacvlan to add AdditionalNetworkNamespace to template data

pkg/platform/openstack/kuryr_bootstrap.go
With a recent change that tightens the security groups of masters, we need to ensure etcd ports are accessible from svc subnet to masters, and not only from the remote_group as is defined on the master ingress etcd rule by the installer.
=> Bug 1752371: Kuryr: Open etcd traffic from svc subnet to master nodes

bindata/network/kuryr/001-rbac.yaml
Kuryr ClusterRole was missing "use" verb for SecurityContextConstraints,
making us unable to edit pods outside of `openshift.io/run-level: "0"`
namespaces. This commit adds that permission.
=> Bug 1752905: Kuryr: Allow usage of SCC's to allow pod update

pkg/platform/openstack/kuryr_bootstrap.go
In case the API lbaas gets to a provisiong status with ERROR, the
reconciliation is triggered and the same lbaas with ERROR status
is used on the creation of the next lbaas resources, e.g. pools,
listeners and members. The operator will never finish Kuryr
bootstraping phase.
This commit fixes the issue by deleting the lbaas in case it's
with ERROR status and creating a new one.
=> Bug 1753014: Kuryr: Fix kuryr bootstrap when lbaas API has ERROR status

bindata/network/kuryr/004-daemon.yaml, bindata/network/multus/multus.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/kuryr.go, pkg/network/kuryr_test.go, pkg/network/multus.go, pkg/network/openshift_sdn.go, pkg/network/ovn_kubernetes.go, pkg/network/render.go
#299 has been used to work around the CRIO + Multus CNI configuration issues. However, this caused collateral damage to Kuryr and OpenShift upgrades. #299 was reverted with #310 -- this PR adds the commit for the alternate CNI configuration direct from #299 back, as well as a commit for updating the Multus entrypoint parameters.
**UPDATE**: Notably different from #299 is that this *no longer performs a CRIO restart*.
----
It's been observed that with #299 in place, openshift-sdn and Kuryr were having trouble with write operations to the directories within `/run` -- notably #299 uses `/var/run/multus/cni/net.d` as an alternate configuration directory.
Additionally, some selinux logs were gathered both with the denials, and also with an experiment where selinux permissive mode was enabled, …
=> Bug 1732598: Alternate CNI config dir

Gopkg.lock, pkg/platform/openstack/kuryr_bootstrap.go
Kuryr bootstrap process creates an Octavia loadbalancer that serves as
OpenShift API endpoint for the pods (i.e. kubernetes.default service on
the first IP of service subnet). It turns out during beginning of the
installation phase, the master nodes will not yet provide API access,
only bootstrap node will.
In order to support such situation this commit adds the bootstrap node
to the loadbalancer pool. Also to make sure the LB will point to correct
addresses, a health monitor is added to the pool. This ensures that the
master nodes will only get added to the LB when they're up.
Besides that it sets weight for load balancer members to prioritize genuine master nodes in favor of bootstrap node.
=> Bug 1751756: Kuryr: Add health monitor to Octavia load balancer

pkg/controller/proxyconfig/validation.go, pkg/util/proxyconfig/no_proxy.go, pkg/util/proxyconfig/no_proxy_test.go
Adds GCP metadata hostnames to default noProxy based on GCP [doc recommendations](https://cloud.google.com/vpc/docs/special-configurations).
=> Fixes Bug 1754049: Adds GCP metadata hostnames to default noProxy

bindata/network/openshift-sdn/alert-rules.yaml
Change `kube_pod_info_node_count` to `sum(kube_pod_info{namespace="openshift-sdn",  pod=~"ovs.*"})` 
this more accuratly computes the alert by returning the number of nodes that have an ovs pod running
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1754592
=> Correct the way nodes are computed for alert ClusterIPTablesStale

README.md, bindata/network/ovn-kubernetes/005-service.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
While we're in the process of adding HA and TLS, let's just execute the binaries directly.
=> ovn-kubernetes: run binaries directly

bindata/network/openshift-sdn/sdn-ovs.yaml
This changes the liveness/readiness probe for OVS to (hopefully) a more rigorous end-to-end check. The challenge is to find one that doesn't rely on br0 being present, which won't happen until openshift-sdn is up and running.
So, we do ovs-ctl status, which checks that the pidfiles have pids that are up and running. It also adds an ovs-appctl command to verify that the vswitchd is running, and a ovs-vsctl check to see that the DB is running.
/cc @orgcandman
=> Bug 1751246: openshift-sdn: add better ovs liveness/readiness probe

pkg/util/proxyconfig/no_proxy.go, pkg/util/proxyconfig/no_proxy_test.go
External cluster resources such as routes should not be automatically no-proxied. We should provide cluster admins the choice on whether or not to proxy these connections. This PR removes the external api-server hostname from the default noProxy list.
/assign @bparees @deads2k @knobunc
=> Fixes Bug 1757973: Removes external api server from default noProxy

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Upstream defaults to just 'ovn-kubernetes' but we need to use
openshift-ovn-kubernetes.
Fixes: 0ac2cdf16adffca72e385337df95d54d9e97e249
@squeed @JacobTanenbaum @danwinship
=> ovn-kubernetes: fix endpoint namespace

bindata/network/multus-admission-controller/admission-controller.yaml
This ends up causing lots of errors to be logged during cluster start.
Additionally, it does not open any security holes as the Multus binary itself
is capable of performing namespace isolation (if/when that is added to the
admission controller in the future)
=> The Multus admission controller should not have the not-ready toleration

pkg/util/k8s/kubeproxy_test.go
Since rebase to 1.16, conntrack-max is no longer a valid option
of KubeProxyConfig, thus degrade the operator if used.
=> Add test to assert we fail if conntrack-max kubeproxy config option is passed

pkg/network/additional_networks.go
Signed-off-by: Tomofumi Hayashi <tohayash@redhat.com>
=> Bug 1760787: Fix dereference in macvlan IPAM validation function

bindata/network/kuryr/003-config.yaml, bindata/network/kuryr/005-controller.yaml, pkg/platform/openstack/kuryr_bootstrap.go
Kuryr-controller restarts may lead to OpenStack resource leaks.
This PR makes a few adjustments to avoid unneeded restarts by:
- Disable pools pre-population: this has extra stress on neutron
as more ports need to be created for each namespace. Until all the
leaks are fixed, it is better to disable it. The pros is that
namespace creation/deletion will be faster and neutron load will
be lower. The cons is that first allocated pod on a not for a given
namespace will take longer to get to running, as the ports needs to
be created.
- Increase the threshold for considering the kuryr-controller unhealty
- Increase the timeout to wait for OpenStack resources to be ready
(e.g., ports to become active, networks to be created, namespaces to
be annnotated, ...). This, in case of resource creation …
=> Bug 1761344: Tweaking kuryr-controller configuration to avoid restarts

bindata/network/ovn-kubernetes/ovnkube-node.yaml
This is needed on bare metal and clouds that rely on iptables.
=> Add enable-protocol (geneve port) to ovs setup

bindata/network/openshift-sdn/alert-rules.yaml
Change `kube_pod_info_node_count` to `sum(kube_pod_info{namespace="openshift-sdn", pod=~"ovs.*"})`
this more accuratly computes the alert by returning the number of nodes that have an ovs pod running.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1754592
=> Bug 1754606: [release-4.2] Correct the way nodes are computed for alert ClusterIPTablesStale

bindata/network/multus/003-dhcp-daemon.yaml
=> Bug 1754686: The DHCP daemon should mount the directory for the socketfile (backport 4.2)

bindata/network/multus-admission-controller/admission-controller.yaml
This ends up causing lots of errors to be logged during cluster start.
Additionally, it does not open any security holes as the Multus binary itself
is capable of performing namespace isolation (if/when that is added to the
admission controller in the future)
=> Bug 1762921: [4.2] The Multus admission controller should not have the not-ready toleration

pkg/controller/operconfig/configmap_controller.go
controller-runtime change[1] changes to set namespace hence
multus-admission-controller's caBundle is not supplied by CNO.
This change fixes the condition to invoke to reconcile it.
[1] https://github.com/kubernetes-sigs/controller-runtime/commit/6cfbed364aece9fa862ff37c382386630df70bca
=> Bug 1762145: TLS handshake error breaking multus admission controller functionality

bindata/network/ovn-kubernetes/002-rbac.yaml
In commit aa36fc12 of ovn-kubernetes (ovn-org/ovn-kubernetes#767), the ovnkube-node started patching the node resource with an annotation. Currently this is failing with:
```
Failed to set node [...] mgmt port macAddress annotation: map[k8s.ovn.org/node-mgmt-port-mac-address:...]
nodes \"...\" is forbidden: User \"system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-node\" cannot patch resource \"nodes\" in API group \"\" at the cluster scope
```
Add permission to the openshift-ovn-kubernetes-node cluster role to allow this patching.
=> ovnkube: add perms for ovnkube-node to patch node resources

bindata/network/ovn-kubernetes/ovnkube-node.yaml
commit 0ac2cdf1... changes the location of the ovs database. The database was originally in
/etc/origin/openvswitch on the host and after Casey's change got moved to /var/lib/openvswitch. In the upgrade case where a database exists in the old location move the database to the new location so the cluster's networking remains stable.
=> verify if an older version of the ovs database exists

pkg/controller/configmap_ca_injector/controller.go
=> pkg/controller/configmap_ca_injector/controller: Fix {name}/{namespace} log inversion

pkg/util/proxyconfig/no_proxy.go, pkg/util/proxyconfig/no_proxy_test.go
4.2.z backport of https://bugzilla.redhat.com/show_bug.cgi?id=1757973
=> Bug 1758656: Removes external api server from default noProxy

bindata/network/ovn-kubernetes/006-pki.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
This creates a certificate authority and a single certificate. It configures all the OVN processes to use that certificate:
- nbdb and sbdb serve behind that certificate
- nbdb and sbdb authenticate clients against the CA
- ovn-controller and ovnkube-node use the certificate to authenticate
=> ovn-kubernetes: enable TLS

bindata/network/multus/multus.yaml
This ensures OKD-on-FCOS doesn't crash when FCOS is used as a base. Currently RHEL8 binaries are used, proper Fedora support would be added later.
See https://github.com/openshift/installer/pull/2548#issuecomment-548474221
=> multus: copy RHEL8 binaries on FCOS

manifests/0000_70_cluster-network-operator_01_credentialsrequest.yaml, pkg/platform/openstack/kuryr_bootstrap.go
This commit adds OpenStack credentials request and its support in Kuryr.
=> Add OpenStack credentials request

bindata/network/ovn-kubernetes/alert-rules.yaml
- check that every node has a running ovnkube-node pod
- check that none of the pods in openshift-ovn-kubernetes namespace are in CrashLoopBackoff
=> adding initial alert rules to ovnkubernetes

bindata/network/openshift-sdn/sdn-ovs.yaml
OpenShiftSDN is shipped with its own openvswitch service running
as a separate daemonset. However, in some cases we may want to use
an external openvswitch running on the host (e.g. to use it for
host networking). In order to support a mixed environment where some
hosts have this external service and some don't, we introduce
openvswitch anti-selector:
`network.operator.openshift.io/external-openvswitch`
Note that this selector has to be set **before** the operator is started.
Otherwise, the label would not take effect on already scheduled
pods.
TODO: documentation
Signed-off-by: Petr Horacek <phoracek@redhat.com>
=> OpenShiftSDN: introduce OVS anti-selector

bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
Since there is a periodic process that commits to the northbound database (and is mirrored to the southbound), we have a good signal for an e2e test.
(note: this needs an upstream PR to merge, and for that to be pulled downstream)
=> ovn-kubernetes: add basic control plane alerts

bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/multus-admission-controller/monitor.yaml, bindata/network/multus-admission-controller/rules.yaml, bindata/network/multus/000-ns.yaml, pkg/network/multus_admission_controller_test.go
Add Prometheus capability to a multus admission controller.
This PR does not add any metrics but does allow the metrics to be exposed from within a multus-admission-controller to an in cluster Prometheus server.
Along with multus-admission-controller PR which exposes metrics: openshift/multus-admission-controller#11
=> Add Prometheus capability to a multus admission controller

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Bug 1748162
[GCP]Failed to install cluster with OVN network type
https://bugzilla.redhat.com/show_bug.cgi?id=1748162
SDN-637 OVN doesn't work on GCP
https://jira.coreos.com/browse/SDN-637
=> Add "node.kubernetes.io/network-unavailable" toleration to master

pkg/controller/operconfig/operconfig_controller.go
For example, from a recent CI run [1], compare:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.3/1372/artifacts/e2e-aws/must-gather/registry-svc-ci-openshift-org-ocp-4-3-2019-10-30-020950-sha256-dae1257b516a5c177237cfef5a6a3e241962b0d20cf54bcb2b66dc1671c5035e/cluster-scoped-resources/config.openshift.io/clusteroperators/ingress.yaml | yaml2json | jq -cS '.status.relatedObjects[]'
{"group":"","name":"openshift-ingress-operator","resource":"namespaces"}
{"group":"operator.openshift.io","name":"","namespace":"openshift-ingress-operator","resource":"IngressController"}
{"group":"ingress.operator.openshift.io","name":"","namespace":"openshift-ingress-operator","resource":"DNSRecord"} …
```
=> Bug 1769412: pkg/controller/operconfig/operconfig_controller: Add operator namespace to relatedObjects

pkg/util/proxyconfig/no_proxy.go, pkg/util/proxyconfig/no_proxy_test.go
This reverts commit a85860904ef2c95cd92e50ca979dc4563ee71b8e, reversing
changes made to 1eed8132527076b9ffca3dc244001a39855f1545.
We found in BZ https://bugzilla.redhat.com/show_bug.cgi?id=1762618 that at least
some of our code, running on cluster, was accessing the external instead of internal
api.
While it is possible to make it work (by allowing your proxy to talk from internal
to the apiserver) this is a change/regression from GA. Since we hit this with at
least 1 part of our code we have decided to revert and try again with more testing.
=> Bug 1766066: Revert "Merge pull request #334 from danehans/bz_1758656"

bindata/network/openshift-sdn/sdn.yaml
=> Bug 1761609: Remove SDN ds liveness check

bindata/network/multus/multus.yaml
This adds a new flag to `--skip-multus-binary-copy` in the Multus entrypoint
and instead uses an init container to make the copy based on the host OS.
Notably, this retains the atomic opeation of copying the Multus binary
to a temporary filename and then renaming the file, as is used in the Multus
entrypoint.
=> Bug 1725832: The Multus binary should be copied based on the host operating system

pkg/network/additional_networks.go
=> Bug 1760790: Fix dereference in macvlan IPAM validation function (backport 4.2)

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/bootstrap/types.go, pkg/network/bootstrap.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/network/render.go
This adds the raft concensus protocol for the deployment of OVN masters. 
This changes:
* ovn master deployment -> daemonset with a `nodeSelector` on master nodes. 
* A bootstrap on the CNO specifying the master nodes in sorted order that the `ovn-master` pods will run on, this is needed when starting the raft cluster. 
**Discussion:**
This implements OVN raft for Openshift, **not** for upstream ovn-org/ovn-kubernetes. I will file a separate PR for that as to get a discussion going. But the reason we can do it for Openshift, as done in this PR is because we have the CNO which bootstraps the essential information for us before starting. The PR upstreams will contain a more complicated logic based on the leader election mechanism that @numansaddique has done.  
**TODO:**
What remains is to …
=> SDN-551: RAFT implementation for OVN Openshift

pkg/controller/configmap_ca_injector/controller.go
Adjusting one of the log lines from 482ce00a0c (#300) to match another log line from that same commit.  There's nothing inherently proxy-ish about the trusted CA bundle ConfigMap, so we don't need a proxy-specific log line.  And giving the namespace/name is a more actionable error message (admins will know which resource they need to chase down).
=> pkg/controller/configmap_ca_injector: "proxy not found" -> "ConfigMap ... not found"

bindata/network/openshift-sdn/alert-rules.yaml
change from a query that relies on time() to one that uses the more accurate timestamp()
=> more accuratly alert on a single nodes iptable stale

pkg/controller/statusmanager/pod_status.go, pkg/controller/statusmanager/status_manager.go, pkg/controller/statusmanager/status_manager_test.go
If we find ourselves with a DaemonSet or Deployment that hasn't made any progress for the past 10 minutes, then highlight this to the operator as a Degraded state.
This doesn't affect any of the other states (Progressing, Available, etc.).
/cc @danwinship @rcarrillocruz
=> controller/status: set Degraded if rollout is hung.

bindata/network/ovn-kubernetes/ovnkube-node.yaml
getent hosts can return an ipv6 address.
Bug 1748162
[GCP]Failed to install cluster with OVN network type
https://bugzilla.redhat.com/show_bug.cgi?id=1748162
SDN-637 OVN doesn't work on GCP
https://jira.coreos.com/browse/SDN-637
=> Change ovnkube-node.yaml to  getent ahostsv4

bindata/network/ovn-kubernetes/003-rbac-controller.yaml
Bug 1748162
[GCP]Failed to install cluster with OVN network type
https://bugzilla.redhat.com/show_bug.cgi?id=1748162
SDN-637 OVN doesn't work on GCP
https://jira.coreos.com/browse/SDN-637
=> GCP add ClusterRoleBinding to permit changing node/status

pkg/util/proxyconfig/no_proxy.go, pkg/util/proxyconfig/no_proxy_test.go
This PR reverts the changes introduced in PR #388 by removing the external api server from the default `noProxy` generated list.
/cc @wking @mfojtik 
/assign @squeed
=> Bug 1770223: Reverts PR #388

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
Add a PodDisruptionBudget to protect the raft quorum.
Configure a readines probe for the DBs: ovsdb raft only opens its port once it has a raft consensus. Utilize that.
Also, add a TerminationMessagePolicy.
(Closes SDN-662)
/cc @alexanderConstantinescu
=> ovn-kube: add pod disruption budget, readiness check

bindata/network/kuryr/001-rbac.yaml, bindata/network/kuryr/009-admission-controller.yaml
Pass extra information to the kuryr-admission-controller so that it is able to identify the operators that must be restarted in case they don't have the proper dns configuration. The other side of this is handle in kuryr-kubernetes PR: https://github.com/openshift/kuryr-kubernetes/pull/108
=> Bug 1754046: Modif kuryr-admission-controller pod definition

hack/run-locally.sh
This is a common mistake; let's just always re-build.
=> run-locally: rebuild the CNO

bindata/network/openshift-sdn/monitor.yaml, bindata/network/ovn-kubernetes/monitor.yaml
Since these services are just used to configure Prometheus scrape targets, rather than load-balance traffic, we should not remove not-ready addresses from them.
=> osdn, ovnk: add publishNotReadyAddresses to metrics services

bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/sdn.yaml
We pull the apiserver url from the kubelet's kubeconfig. This has changed, and can be found in one of two places. Check them both.
Ultimately we need to generate this in a more sustainable way, but this is a good workaround (and easily backportable).
=> Bug 1781707: openshift-sdn, CNO: handle new kubeconfig path

bindata/network/ovn-kubernetes/monitor.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml
Finish what https://github.com/openshift/cluster-network-operator/pull/419 was trying to do. We need all the master things to use 'app' not 'name' for metrics scraping to work correctly.
@JacobTanenbaum @danwinship @juanluisvaladas @alexanderConstantinescu @rcarrillocruz @pecameron
=> ovn: use app label instead of name for master metrics and quorum guard

bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
It's ovnkube-master not ovn-kubernetes-master.
In conjunction with https://github.com/openshift/cluster-network-operator/pull/435 this should fix the prometheus NoRunningOvnMaster alert issue.
=> ovn: fix master control plane job name

bindata/network/ovn-kubernetes/004-config.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
Configure ovnkube using a config file passed by the ovnkube-config
configMap and mountedinto the container.
SDN-456
https://jira.coreos.com/browse/SDN-456
=> OVN: use config file via ConfigMap rather than environment variables

HACKING.md, README.md, bindata/network/ovn-kubernetes/004-config.yaml, manifests/0000_70_cluster-network-operator_01_crd.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
SDN-494 - ovn custom geneve port number.
https://jira.coreos.com/browse/SDN-494
=> ovn custom geneve port number

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
#333 added logging of the ovn-kube TLS keys to the startup of all of the daemons. I assume @pecameron did this for debugging reasons at one point and then forgot to remove it? If the admin wants to see the key they can just look at the Secret directly... we should not be logging private keys to pod logs.
I'm assuming that for the other fix here (removing "PHIL" from an error message) we actually do want to keep that check.
=> Remove some unwanted logging. Fix an error message

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
@danwinship 
Otherwise:
`2020/01/08 03:54:48 could not apply (apps/v1, Kind=DaemonSet) openshift-ovn-kubernetes/ovnkube-master: could not create (apps/v1, Kind=DaemonSet) openshift-ovn-kubernetes/ovnkube-master: DaemonSet in version "v1" cannot be handled as a DaemonSet: v1.DaemonSet.Spec: v1.DaemonSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.v1.EnvVar.Value: ReadString: expects " or n, but found 4, error found in #10 byte of ...|,"value":4},{"name":|..., bigger context ...|\n"],"env":[{"name":"OVN_KUBE_LOG_LEVEL","value":4},{"name":"K8S_NODE","valueFrom":{"fieldRef":{"fie|...`
Fixes: a5209000b556287a15cef2d6bc1dc78be85e0d17
=> ovn: container env variables need quotes

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
ovn2.12 places the ovn-ctl script in a different directory than earlier
versions. This uses the correct path for the installed version.
SDN-643 - OVN: Bump to ovn v2.12
https://issues.redhat.com/browse/SDN-643
=> Support ovn2.12

bindata/network/multus/003-dhcp-daemon.yaml
Error in logs:
```
could not apply (extensions/v1beta1, Kind=DaemonSet) openshift-multus/dhcp-daemon: could not retrieve existing (extensions/v1beta1, Kind=DaemonSet) openshift-multus/dhcp-daemon: no matches for kind "DaemonSet" in version "extensions/v1beta1"
```
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openshift/cluster-network-operator/442)
=> Fix dhcp daemon api version

bindata/network/ovn-kubernetes/monitor.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Change the port number from 9101 to 9103 to avoid the port conflict during SDN migration.
Per https://github.com/openshift/cluster-network-operator/pull/438#discussion_r364287748
=> Change the metrics port for OVN-Kubernetes

bindata/network/kuryr/004-daemon.yaml, bindata/network/kuryr/005-controller.yaml, pkg/network/kuryr.go, pkg/util/k8s/unstructured.go
This commit makes sure that Kuryr pods are restarted when LogLevel
option is changed in NetworkSpec. This is possible by injecting each
Kuryr pod with a hash representing set of all the options passed to the
templates. If the options change, hash will change and
controller-manager will rollout new DaemonSet/Deployment.
=> Allow changing LogLevel online in Kuryr

bindata/network/kuryr/006-service.yaml, bindata/network/kuryr/007-admission.secret.yaml, bindata/network/kuryr/008-webhook.secret.yaml, bindata/network/kuryr/009-admission-controller.yaml, bindata/network/kuryr/010-webhook.yaml, pkg/bootstrap/types.go, pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go
If octavia amphora provider supports double listeners, i.e.,
exposing the same port but on different protocol (e.g., udp and tcp)
then there is no need for deploying the kuryr-admission-controller
to enforce dns resolution over TCP, as we can create both udp and
tcp listeners on port 53 for the DNS service
=> Bug 1791277: Stop deploying kuryr-admission-controller if double listeners supported

bindata/network/openshift-sdn/sdn.yaml
Fix the socket path for the cni server socket
=> sdn: use the correct socket path

pkg/controller/operconfig/operconfig_controller.go, pkg/names/names.go
Allow users to change the cluster default network type by updating the 'networkType' field of the network.config.openshift.io CR. This not only support the use case of migrating the cluster network from Openshift SDN to OVN-Kubernetes, but also the use case vise Versa.
=> Allow to change the cluster default network type

bindata/network/openshift-sdn/001-crd.yaml
It turns out the bug was failing validation because the implementation of `explain` barfs if the crd schema doesn't have the `preserveUnknownFields` in the spec.
PR https://github.com/openshift/origin/pull/24477 may need some rework after this merges.
=> Bug 1769015: Add preserveUnknownFields to CRDs

bindata/network/additional-networks/crd/001-crd.yaml
To fit requirements for having a structural schema to CRDs.
=> Bug 1796514: Adds openAPIV3Schema to NetworkAttachmentDefinitions

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Rather than connecting to the database TCP socket which just spams the
database logs with failed SSL connection messages.
@danwinship @openshift/networking
=> Bug 1796718: ovn: use ovs-appctl ovsdb-server/sync-status for NB/SB DB readiness

bindata/network/ovn-kubernetes/ovnkube-master.yaml
per https://bugzilla.redhat.com/show_bug.cgi?id=1794923 we're expected to put brackets around IPv6 addresses here even though there are no ports attached to them (at the time we pass them)
=> Bug 1796616: Put brackets around IPv6 addresses passed to ovn-ctl

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/ovn-kubernetes/006-ovs-node.yaml
When terminated gracefully, either via 'ovs-ctl stop' or TERM,
ovs-vswitchd cleans up datapath flows. This prevents any existing
flows from continuing to work, which kinda defeats the purpose of
a seamless upgrade.
@orgcandman @knobunc @danwinship @rcarrillocruz @smarterclayton
=> Bug 1796562: sdn/ovn: don't allow ovs-vswitchd to clean up datapath flows on exit

bindata/network/ovn-kubernetes/006-ovs-node.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
New paths for components
SDN-643
=> Bug 1798191: Bump to ovn2.12

bindata/network/openshift-sdn/alert-rules.yaml
cherry pick of PR https://github.com/openshift/cluster-network-operator/pull/390 to 4.2
Fixes Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1778314
=> Bug 1778314:  False Alarm - SDN pod has gone too long without syncing iptables rule

bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/sdn.yaml
Manual cherry-pick of #420 
There was a conflict because the name of the executable changed from openshift-sdn to openshift-sdn-node.
=> [release-4.2] Bug 1785728: openshift-sdn, CNO: handle new kubeconfig path

bindata/network/kuryr/003-config.yaml, pkg/names/names.go, pkg/platform/openstack/kuryr_bootstrap.go
When bootstrapping OpenStack resources CNO does autodetection of
available Octavia providers and if OVN provider is at hand Kuryr will
get configured to use it.
In order to make sure Kuryr won't get reconfigured when underlying
OpenStack cluster changes, an annotation marking the initial choice will
be saved to the kuryr-config ConfigMap created by CNO and if present CNO
will always choose that Octavia provider.
In order to force CNO to reconfigure Kuryr the annotation needs to be
manually removed by the user to indicate that this is intended and user
had followed upgrade documentation.
=> Bug 1796114: Kuryr: Do not reconfigure if LB providers change

bindata/network/kuryr/010-admission-controller.yaml
The etcd and authentication operators pods might start before the Kuryr admission
controller is running, resulting in no dnsConfig option injected
on the pod spec to allow DNS resolution over TCP, and consequently
failure on DNS resolution.
This commit ensures the pods will have the option in place.
=> Bug 1800633: Ensure etcd and authentication operator resolves dns over TCP

bindata/network/ovn-kubernetes/ovnkube-node.yaml
We were accidentally still passing some command line arguments that we also specified in the config file. Worse, we were passing empty strings for the values on the command line...
/cc @trozet
=> Bug 1802596: Remove erroneous ovnkube node command-line args

bindata/network/ovn-kubernetes/003-rbac-controller.yaml
All e2e-gcp-ovn jobs are failing (at least in part) due to RBAC problems: https://prow.svc.ci.openshift.org/job-history/origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-ovn-4.3
Back-port 1e843cb6ba3d524cb2c84d640206bc9f15788768 to 4.3 to fix this error.
=> Bug 1779863: backport ovn-controller rbac fix to 4.3  

pkg/util/validation/network.go, pkg/util/validation/network_test.go
We were validating agains a subset of RFC-1123, which is invalid.
DNS allows much fancier stuff, this delegates validation to golang and
gets some stuff for free, such as IDNs.
=> Bug 1802606: pkg/util: Fix URI validation to modern standards

hack/run-locally.sh
This PR introduces a `run-remotely.sh` script which allows us to run the CNO against a remotely running cluster. It's based off of `run-locally.sh` and takes only a kubeconfig argument. It strips off some of the logic surrounding manifests, install-config, etc that the `run-locally.sh` script has. 
I am not familiar with the reasons behind having the `PLUGIN_IMAGE` variable. But I kept it, in case someone was using it to modify the `env.sh` using that mechanism.
=> Adding run-remotely.sh script 

pkg/platform/openstack/kuryr_bootstrap.go
Patch making sure Kuryr is not getting a sudden reconfiguration when
underlying Octavia is getting upgraded to version supporting OVN
provider broke the detection of support for multiple listeners. When
OVN provider is used, multiple listeners are not supported.
=> Bug 1804734: Kuryr: Disable multiple listeners for OVN provider

pkg/platform/openstack/kuryr_bootstrap.go
Other implementations of OpenStack cloudprovider CA certs handling print
errors other than NotFound when fetching the CA cert ConfigMap. This
commit makes sure CNO follows the same pattern.
=> Kuryr: Handle unexpected errors fetching CA cert

README.md
the doc was moved into a `v1.0` subdir
`master/v1.0/...`
=> fix multi-net-spec Network CRD std URL

pkg/controller/statusmanager/pod_status.go
The progression message should reflect that the admission controller is reliant on other systems being ready
Previously the CNO would output a message such as 'DaemonSet "openshift-multus/multus-admission-controller" is not available', which would cause users to believe that during a cluster bootstrapping error there was a problem with the multus-admission-controller. However, this is not a dependency of other systems, and therefore should have an error message reflecting that other systems may be involved.
=> Update admission controller progression messaging

bindata/network/kuryr/007-service.yaml, bindata/network/kuryr/008-admission.secret.yaml, bindata/network/kuryr/009-webhook.secret.yaml, bindata/network/kuryr/010-admission-controller.yaml, bindata/network/kuryr/011-webhook.yaml, pkg/bootstrap/types.go, pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go
If octavia amphora provider supports double listeners, i.e.,
exposing the same port but on different protocol (e.g., udp and tcp)
then there is no need for deploying the kuryr-admission-controller
to enforce dns resolution over TCP, as we can create both udp and
tcp listeners on port 53 for the DNS service
cherry-pick of #444
=> Bug 1791278: Stop deploying kuryr-admission-controller if double listeners supported #

README.md, bindata/network/ovn-kubernetes/004-config.yaml, bindata/network/ovn-kubernetes/005-service.yaml, bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/monitor.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Backport of all as-yet-unbackported ovn-kubernetes-related fixes to 4.3
Includes:
- #414 ovn-kube: add pod disruption budget, readiness check
- #427 ovnk: add publishNotReadyAddresses to metrics services
- #419 + #435 Use app label instead of name on ovnkube-master ds, etc
- #436 ovn: fix master control plane job name
- #333 + #437 + #440 + #473 OVN: use config file via ConfigMap rather than environment variables
- #341 ovn custom geneve port number
- #439 + #445 - Support ovn2.12
- #461 ovn: use ovs-appctl ovsdb-server/sync-status for NB/SB DB readiness
- #460 ovn: don't allow ovs-vswitchd to clean up datapath flows on exit
Does not include:
- anything SDN-related (not even the SDN-related parts of #427 and #460)
- anything Kuryr-related
- anything unmanaged-OVS-related
- anything …
=> Bug 1806009: Backport ovn-kubernetes-related changes to 4.3

bindata/network/openshift-sdn/sdn-ovs.yaml
During OVS shutdown and startup, attempt to preserve all existing flows in the kernel while the OVS daemon is offline, and during startup avoid clearing those flows.
While this does not completely mitigate dropped / failed connections while OVS is upgrading, it dramatically reduces the amount of time user applications are impacted both by upgrades or by unexpected disruption (an OOM kill or OVS crash).  Future changes will build on this to try to make OVS upgrade completely transparent to end user applications.
Known gaps:
* ARP flows are potentially still being lost for new connections (workarounds being investigated with OVS team).
=> Bug 1807638: Minimize disruption to pod network while OVS is being upgraded

pkg/util/proxyconfig/no_proxy.go
https://github.com/openshift/cluster-network-operator/pull/490 didn't consider that MachineCIDR might be empty. I will add a test but as this is a regression I want to get this done quickly.
=> Bug 1797894: Don't add empty MachineCIDR to noProxy

bindata/network/multus/multus.yaml, pkg/network/multus.go
This helps to smooth out inconsistencies during an upgrade and helps Multus know openshift-sdn is ready.
This depends on https://github.com/openshift/multus-cni/pull/47 and likely will not pass CI until that is merged.
=> Bug 1805987: Uses the readiness indicator file option for Multus

bindata/network/multus/multus.yaml, pkg/network/multus.go
Backport of #484 to release-4.4. (The PR was originally filed before 4.4 stopped tracking master, so there was a 4.3 backport but not a 4.4 one.)
=> Bug 1805774: Use the readiness indicator file option for Multus

bindata/network/multus/multus.yaml, pkg/network/multus.go
This helps to smooth out inconsistencies during an upgrade and helps Multus know openshift-sdn is ready.
This depends on https://github.com/openshift/multus-cni/pull/48 and will likely not pass CI until that is merged.
=> Bug 1805444: Uses the readiness indicator file option for Multus [backport 4.3]

pkg/platform/openstack/loadbalancer.go
When upgrading Octavia from OSP13 to OSP16 the CNO checks if
tagging is supported and look for an API load balancer with tag.
However, the existent LB was created with OSP13, which does not
support tagging and so the tagging was added on description.
The CNO then tries to create a new LB API and fails due to
address already in use.
This commit fixes the issue by ensuring no LB exists with tags
and description, when tagging is supported, prior to creating
a new one.
=> Bug 1808498: Ensure no API LB recreation happens upon Octavia upgrade

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Tell ovn to not assign hostsubnets to nodes labeled
kubernetes.io/os=windows
when enabeling hybrid networking. This ensures correct operation as the
node deals with it's own hostsubnet
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1789881
=> Bug 1789881: Start ovn correctly with hybrid networking

bindata/network/kuryr/002-crds.yaml, bindata/network/kuryr/011-webhook.yaml
Webhooks and CRDs got out of beta with K8s 1.16. This commit updates
Kuryr resources to use the new v1 versions of them.
=> Update Kuryr K8s resources to latest versions

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Completes the switch from ovn2.11 to ovn2.12 by removing support for the
now obsolete ovn2.11
SDN-643
https://issues.redhat.com/browse/SDN-643
=> Remove support for ovn2.11

pkg/controller/operconfig/cluster.go, pkg/network/cluster_config.go, pkg/network/cluster_config_test.go
Some components depend on some fields of `configv1.NetworkStatus`. Eg, cluster-kubernetes-apiserver-operator needs to know the `ServiceNetwork`.
Previously we weren't setting the status when the default network type was unknown, because we didn't know that the external network plugin would consider them valid. (eg, there might be multiple `ClusterNetwork` values but the plugin only supports one.) But this breaks components that assume they can get their config from there.
Fix this by setting the status fields but allowing them to be overridden by another operator if the network type is unknown.
/assign @dcbw @rcarrillocruz 
/cc @deads2k
=> Bug 1807611: Set network config status even with unknown network plugin

bindata/network/openshift-sdn/sdn-ovs.yaml
This pull request changes the termination grace period to 45s from 10s to allow for saving off flows prior to the pod getting a SIGKILL.
=> Increase termination grace period to 45s to allow for flows to get saved

bindata/network/additional-networks/crd/001-crd.yaml, bindata/network/multus/002-rbac.yaml, bindata/network/multus/multus.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/image-references, pkg/network/additional_networks_test.go, pkg/network/multus.go, pkg/network/multus_test.go
Updates YAML templates for init containers, primarily. Condenses
the binary copy script into a single place to be used across other
CNI plugin binary copies.
Likely dependent on https://github.com/openshift/release/pull/6815
=> Bug 1807072: Adds route-override-cni and whereabouts for secondary network routing and IPAM

pkg/platform/openstack/kuryr_bootstrap.go
We are using a Network client to retrieve the octavia API version,
this results in a wrong api version.
This commit fixes the issue by using the Load Balancer client.
=> Bug 1811022: Ensure correct Octavia API version is retrieved

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Tell ovn to not assign hostsubnets to nodes labeled
Cherry-pick https://github.com/openshift/cluster-network-operator/pull/500 and https://github.com/openshift/cluster-network-operator/pull/515
kubernetes.io/os=windows
when enabeling hybrid networking. This ensures correct operation as the
node deals with it's own hostsubnets
=> Bug 1811077: [4.4] Start ovn correctly with hybrid networking

README.md
How to configure a hybird cluster of Linux an Windows nodes.
https://issues.redhat.com/browse/SDN-842
=> Document Hybird Overlay Config

hack/KIND_CNO.md, hack/kind.yaml, hack/ovn-kind-cno.sh
This patch enables using Kubernetes-in-Docker (KIND) for deploying CNO
with upstream K8S. This is useful for developers who need a quick
environment locally on their laptop. In addition, the script is capable
of building CNO and/or OVN-K8S from a local git workspace to use for
deployment.
=> Enables KIND deployments for CNO

Gopkg.lock, pkg/network/ovn_kubernetes.go
As seen by @pecameron, the CNO might proceed to bootstrapping OVN whilst some control plane nodes are unknown to him/her. 
This PR while make sure we wait until all control plane nodes that should exist, do exist. It does so by reading the `install-config.yaml` which is written as the `cluster-config-v1` configmap in `kube-system`, and proceeds to decoding the user defined amount of control plane nodes. It only proceeds with the OVN bootstrap once the kubeclient return the expected amount of nodes.  
I didn't have any better way of ascertaining this information then doing this, so if anyone has a better idea / knows how to retrieve this information more easily, please raise a hand. 
/assign @pecameron @danwinship
=> Read install-config and wait for the requested amount of control plane nodes

pkg/controller/statusmanager/status_manager.go
If the CNO pod is recreated, the resources that are not rendered
anymore are not deleted. Due to The related objects field of the
cluster operator status being wiped out upon cno recreation.
This commit fixes the issue by ensuring the objects on the status
manager are only updated when the current status is filled.
=> Bug 1811748: Ensure removal of not rendered resources upon CNO recreation

pkg/platform/openstack/loadbalancer.go
In case Octavia is upgraded while the CNO is already running, the admission
controller resources are not deleted due to checking the previous Octavia
API version, as the version is only retrieved once when the CNO is starting.
This commit fixes the issue by ensuring the current API version is always
fetched.
=> Bug 1810137: Delete admission controller if double listeners is supported

bindata/network/additional-networks/crd/001-crd.yaml, bindata/network/multus/002-rbac.yaml, bindata/network/multus/multus.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/image-references, pkg/network/additional_networks_test.go, pkg/network/multus.go, pkg/network/multus_test.go
Was reverted in #519 -- this reintroduces both plugins in 4.3.z after ART has addressed our image backport.
=> Bug 1807062: Reintroduce whereabouts & routeoverride in 4.3.z

bindata/network/openshift-sdn/sdn-ovs.yaml
The ovs container uses approximately 100m of node CPU in a reasonable
medium sized workload. Tune the default to be more realistic for medium
clusters. For large clusters, a dynamic scaling policy would be
necessary.
4.4 bug is 1812709
=> Bug 1812583: Normalize CPU requests on nodes

bindata/network/multus/002-rbac.yaml
It was incorrectly set to ippools.whereabouts.cni.k8s.io and missed when it was
changed upstream/downstream for whereabouts.
=> RBAC for Whereabouts should reference ippools.whereabouts.cni.cncf.io

bindata/network/ovn-kubernetes/006-ovs-node.yaml
There is a race condition in ovn-controller when the
Open_vSwitch external_ids:ovn-monitor-all key is set to "true" after
ovn-controller starts.
Until the bug is fixed in OVS/OVN code, this is a workaround delaying
start up of ovn-controller until OVS is up and ovn-monitor-all is set to
"true".
This commit also ensures that upon an OVS pod reboot that would recreate
the OVS database ovn-controller would not connect to an uninitialized
database (i.e., "ovs-vsctl init" has been called first).
Reported-at: https://bugzilla.redhat.com/1808125
Signed-off-by: Dumitru Ceara <dceara@redhat.com>
=> OVN: Ensure ovn-monitor-all=true before ovn-controller starts.

README.md, bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/sdn.yaml
Casey had added a nice hack to CNO's deployment of ovn-kubernetes to make it easier to enable debugging, but we never did the same thing for openshift-sdn.
=> Add the env-overrides debugging hack to openshift-sdn

bindata/network/kuryr/011-webhook.yaml
The v1beta1 MutatingWebhook version ensured by default
that if an error happened on admission controller endpoint
the failure would be ignored. However, with the new v1 version
the default is to Fail, which can block the installation
to proceed as the API requests would be rejected.
This commit ensures we still default to ignore the error.
=> Ensure admission controller ignores failure

bindata/network/ovn-kubernetes/006-ovs-node.yaml
When 'ovs-ctl start' is called with --db-sock=<value>, ovs-ctl doesn't
properly point its invocation of 'ovs-vsctl' to use the non-default unix
socket passed as argument. The ovsdb-server instance is however started
properly and the error returned can be safely ignored.
Fixes: cae57b4a547d ("OVN: Ensure ovn-monitor-all=true before ovn-controller starts.")
Signed-off-by: Dumitru Ceara <dceara@redhat.com>
=> OVN: Fix initial OVS DB preparation.

bindata/network/kuryr/002-crds.yaml
The remote_ip_prefixes field in KuryrNetPolicy CRD is an object. As it's
not defined with correct schema, it needs
x-kubernetes-preserve-unknown-fields property. This commit fixes that.
I'm not defining the field correctly as we're moving to new CRD anyway.
=> Kuryr: Preserve unknown in remote_ip_prefixes in NP CRD

pkg/controller/statusmanager/pod_status.go, pkg/controller/statusmanager/status_manager_test.go
I was backporting #474 and realized that it solves `DaemonSet "openshift-multus/multus-admission-controller" is not available ...` (ie, "your install failed after the worker nodes were created but before multus-admission-controller could be deployed") but not `DaemonSet "openshift-multus/multus-admission-controller" is not yet scheduled on any nodes` (ie, "your install failed before the worker nodes were created").
(WIP until I see it doing the right thing in a test run)
=> Update Progressing message for non-critical components

hack/ovn-kind-cno.sh
KIND deployments for CNO are failing due to a requirement for existence of
"cluster-config-v1" configMap introduced by merge c594414 on 03/09/2020. This
change adds a minimal "cluster-config-v1" configMap to KIND deployments.
Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>
=> KIND deployments for CNO fails.

pkg/platform/openstack/kuryr_bootstrap.go
We are using a Network client to retrieve the octavia API version,
this results in a wrong api version.
This commit fixes the issue by using the Load Balancer client.
=> Bug 1812037: Ensure correct Octavia API version is retrieved

bindata/network/openshift-sdn/sdn.yaml
https://github.com/openshift/sdn/pull/120 updates openshift-sdn-node to have `--node-name` and `--node-ip` flags; use them. (This won't pass tests until that merges.)
Fixes problems where openshift-sdn-node auto-detects the wrong IP
=> Bug 1802557: Pass --node-name and --node-ip to openshift-sdn-node

hack/ovn-kind-cno.sh
- Added a KIND debugging ENV var that takes an int
which corresponds to the log verbosity level in KIND.
- The default loglevel is set to 0 which aligns with
the default loglevel in upstream KIND.
Signed-off-by: Brent Salisbury <bsalisbu@redhat.com>
=> Enable KIND debugging in ovn-kind-cno

bindata/network/ovn-kubernetes/006-ovs-node.yaml
This reverts commit cae57b4a547d0241d6eef565dc5161f0dcdb7b81 and its
follow up 82d1913cf99564dcbe2a35880b77148f9b47678d. These commits tried
to work around a bug in OVSDB-IDL (https://bugzilla.redhat.com/1808125).
There is no clean and safe way to ensure that ovn-monitor-all=true in
the OVS database so it's better to wait until the proper fix is merged
in OVSDB-IDL instead.
Signed-off-by: Dumitru Ceara <dceara@redhat.com>
=> Revert "OVN: Ensure ovn-monitor-all=true before ovn-controller starts."

bindata/network/multus-admission-controller/002-rbac.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/multus-admission-controller/monitor.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/image-references, pkg/network/multus_admission_controller.go
This reverts commit 76b1e1e4df3a6906d82e0f642a3f92296e11924e.
Apparently causing 80+% failures in OpenShift CI.
=> Revert "Secure metrics endpoint for multus"

bindata/network/openshift-sdn/sdn-ovs.yaml
This PR adds:
a) a timestamp when adding logs for save/restore so they can be correlated with other logs.
b) removes the `hostPID` setting on the daemonset pods
c) removes the `--monitor` option when starting the `ovs-vswitchd` and `ovsdb-server` processes
=> Bug 1807638: Fixes to reliably save/restore flows.

bindata/network/ovn-kubernetes/004-config.yaml
For ovnkube logging we can chose to specify a logfile explicitly by passing the `logfile` parameter in the ovnkube configmap. However, /dev is constrained to 64MB in openshift pods, which means that for long running pods: when logging exceeds that limit we get broken pipes for logging.    
Part of the solution (the one fixed by this patch) is to change the `logfile` location to a unconstrained file system location. 
The other part is to switch from logrus to klog completely as logrus does not provide a feature of logging to a file and to stdout simultaneously, as klog does. This part means that we should back-port the "switch to klog" patch to 4.3.
=> Remove logfile from ovnkube configmap as to avoid log rotation

pkg/platform/openstack/loadbalancer.go
In case of LB which is in error state, don't wait for it, but return
immediately.
=> Bug 1818029: Stop waiting for failed loadbalancer.

bindata/network/ovn-kubernetes/ovnkube-master.yaml
For OVN NB DB interaction with the ovn-nbctl command, we use ovn-nbctl
daemon mode, where we do not need to use SSL arguments to directly
interact with the nbctl socket in the pod. However, SSL arguments are
needed for non-nbctl commands like ovsdb client. This patch adds those
arguments.
In addition, the nbctl-daemon-mode argument was missing as well. This
argument indicates to ovn-kubernetes that it needs to use nbctl daemon
mode. Even though we were previously not setting this, we were exporting
the proper bash env var to allow the process to automatically use daemon
mode. However, we should pass the correct arguments to be consistent.
Due to an OVN bug, we need to temporarily symlink the ovn-nbctl control
socket to /var/run/ovn as it is accidentally placed in
/var/run/openvswitch …
=> Adds missing OVN NB SSL args to ovnkube master

pkg/network/ovn_kubernetes.go
This allows to enable the hybrid overlay without the need to specify
hybridClusterNetwork which is only needed for clusters that connect
to Windows nodes
=> Allow to only enable hybrid overlay and not handle Windows networks

bindata/network/ovn-kubernetes/004-config.yaml
Back-port of: https://github.com/openshift/cluster-network-operator/pull/560 to 4.4
=> Bug 1793108: [Back-port] Remove logfile from ovnkube configmap

pkg/platform/openstack/kuryr_bootstrap.go
Some of the prometheus metrics endpoints we have in the cluster are
running on the host networking. Those endpoints need to be accessible
from the pod subnet. This means that we should add some more security
group rules on the masters and workers SGs to allow prometheus pods to
reach those endpoints.
This commit does so, while doing some refactoring to make increasing
numer of SG rules more manageable in Kuryr bootstrap code.
=> Kuryr: Open metric endpoint ports from pod subnets

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
ovnkube has supported normal syntax for a while, let's use it and clean up some tech debt.
=> ovn: use normal OVN DB address syntax

bindata/network/ovn-kubernetes/ovnkube-master.yaml
If/When OVN gets a backport fix for the wrong nbctl socket location, our
CI will break because the symlink will fail. This adds a failsafe.
=> Adds failsafe for OVN nbctl daemon socket

bindata/network/ovn-kubernetes/ovnkube-master.yaml
For OVN NB DB interaction with the ovn-nbctl command, we use ovn-nbctl
daemon mode, where we do not need to use SSL arguments to directly
interact iwth the nbctl socket in the pod. However, SSL arguments are
needed for non-nbctl commands like ovsdb client. This patch adds those
arguments.
In addition, the nbctl-daemon-mode argument was missing as well. This
argument indicates to ovn-kubernetes that it needs to use nbctl daemon
mode. Even though we were previously not setting this, we were exporting
the proper bash env var to allow the process to automatically use daemon
mode. However, we should pass the correct arguments to be consistent.
Due to an OVN bug, we need to temporarily symlink the ovn-nbctl control
socket to /var/run/ovn as it is accidentally placed in
/var/run/openvswitch …
=> Bug 1822308: Adds missing OVN NB SSL args to ovnkube master

bindata/network/multus/002-rbac.yaml
It was incorrectly set to ippools.whereabouts.cni.k8s.io and missed when it was
changed upstream/downstream for whereabouts.
Backport of #527
=> Bug 1812678: RBAC for Whereabouts should reference ippools.whereabouts.cni.cncf.io [backport 4.4.z]

pkg/network/ovn_kubernetes.go
This allows to have a hybridOverlayConfig empty struct and that will just
enable hybrid overlay but not handle Windows networks.
(cherry picked from commit 4e13142579d27445b4d95dcbb51841a62285d3f7)
=> Bug 1823399: Allow to only enable hybrid overlay and not handle Windows networks

bindata/network/multus-admission-controller/admission-controller.yaml
Multus metrics endpoint was secured in this  PR [#563](https://github.com/openshift/cluster-network-operator/pull/563) , but  the endpoint was listening  to 0.0.0.0 and could have accessible outside the container without tls.  This PR will fix that and make sure metrics endpoint are accessed  only via Kube-Rbac-proxy pod within the  same container.
=> Fix multus metrics endpoint  to listen to localhost only

bindata/network/additional-networks/crd/001-crd.yaml
This enables one to use the 'oc describe' command for the net-attach-def.
=> The NetworkAttachmentDefinition CRD should have description fields

bindata/network/ovn-kubernetes/004-config.yaml
Back-port of https://github.com/openshift/cluster-network-operator/pull/560 to 4.3
=> Bug 1821166: [Back-port 4.3] Remove logfile from ovnkube configmap

bindata/network/ovn-kubernetes/006-ovs-node.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
/hold
While waiting for PR:  https://github.com/openshift/cluster-network-operator/pull/483 to get in 
OVNKubernetes is shipped with its own openvswitch service running
as a separate daemonset. However, in some cases we may want to use
an external openvswitch running on the host (e.g. to use it for
host networking). In order to support a mixed environment where some
hosts have this external service and some don't, we introduce an
openvswitch anti-selector:
network.operator.openshift.io/external-openvswitch
Note that this selector has to be set before the operator is started.
Otherwise, the label would not take effect on already scheduled
pods.
=> Bug 1775838: Back-port, OVNKubernetes: introduce OVS anti-selector

bindata/network/ovn-kubernetes/ovnkube-node.yaml
When trying to transfer cri-o to manage its network namespaces in openshift, we have run into problems with multus. Specifically we see the error:
2020-04-07T17:46:52Z [error] delegateAdd: error invoking DelegateAdd - "ovn-k8s-cni-overlay": error in getting result from AddNetwork: CNI request failed with status 400: '[openshift-dns/dns-default-98tll] failed to configure pod interface: failed to open netns "/var/run/netns/76716600-f7fd-462f-b7df-ae054dbd144e": unknown FS magic on "/var/run/netns/76716600-f7fd-462f-b7df-ae054dbd144e": 1021994
'
through testing, I've found the netns is definitely mounted as an nsfs and not tmpfs, so I suspect we are seeing https://github.com/containernetworking/plugins/issues/69
to fix this, attempt mounting /var/run/netns as HostToContainer in ovnkube …
=> mount /var/run/netns rslave in ovnkube

bindata/network/kuryr/005-daemon.yaml, bindata/network/multus/multus.yaml, bindata/network/openshift-sdn/sdn.yaml, pkg/network/multus.go
Containernetworking binaries are compiled for RHEL7 and RHEL8 [here](https://github.com/openshift/containernetworking-plugins/blob/master/Dockerfile). This was done during the effort last year when fixing this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1725832
That solution was applied to multus only and overlooked the fact that we have initcontainers in SDN and Kuryr that still copy the binaries blindly to the host without checking which OS version we're running on. This means that when we start the network plugin we can still end up in a situation where the binary cannot be executed without SIGSEGV-ing directly. 
Seeing as how Multus always runs, no matter the networking plugin used: just don't do anything and let Multus be the sole responsible, as such we should avoid stepping on …
=> Bug 1802481: Don't override containernetworking binaries in SDN and Kuryr

bindata/network/openshift-sdn/sdn.yaml
Thanks to the magic of bash, this was never caught!
The only effect was that overriding verbosity is not possible.
=> Bug 1826322: sdn: fix typo in openshift-sdn run script

bindata/network/ovn-kubernetes/ovnkube-node.yaml
when starting ovnkube-node in a cluster with hybrid overlay networking it
needs to be started with --no-hostsubnet-nodes=<label> so that it knows
what nodes that use the hybrid overlay network are labeled with.
=> Bug 1827009: correctly tell ovnkube-node containers the label that hybrid overlay nodes have

bindata/kube-proxy/kube-proxy.yaml
This is done as to avoid `QoSClass: BestEffort` status which will fail certain e2e tests. I applied the same requests we have for openshift-sdn. But please advise if someone has an idea on a more scientifically correct way of setting these. 
/assign @danwinship
=> Bug 1825019: Setting resource request for kube-proxy deployment

bindata/network/kuryr/005-daemon.yaml
openshift/machine-config-operator#1568 moved pod namespaces from
/proc into /var/run/crio. As Kuryr needs access to them in order to
manipulate interfaces, we need to mount the new directory and this
commit does that.
Most likely the same change needs to be done for ovn-kubernetes, but
it's a bit out of my expertise.
=> Bug 1831112: Kuryr: Mount /run/netns to ensure netns access

pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Since adding a hybrid network after install time is not a supported
operation throw an error when processesing the config.
=> Bug 1831680: Prevent patching the HybridOverlayConfig after install time

pkg/platform/openstack/kuryr_bootstrap.go, pkg/platform/openstack/loadbalancer.go
During installation a bootstrap node is used as an API node at first,
but then gets removed. In Kuryr's bootstrap we never remove it from API
loadbalancer pool which leads to Octavia stating that LB is in degraded
state.
With those changes we prevent it by making sure on reconciliation we
remove loadbalancer members that we don't need there anymore. This
should help with scaledown of masters too.
=> Bug 1829824: Remove dead member from LB pool.

pkg/network/kube_proxy.go
since the clusterCIDR is user configurable determine if the
given cluster is IPv4 or IPv6 single stack based on that value
for network plugins. this will allow third party plugins that
do support single stack to function
=> bug 1831006: For third party plugins enable testing of IPv6 single stack

hack/verify-style.sh
ci/prow/verify is failing in #616 because of weird interactions between "go get" and "migrating to go modules", but we can't fix either side without breaking the other unless we do this first
@squeed @dcbw @rcarrillocruz 
(cc @vishnoianil )
=> Bug 1833372: Drop 'dep verify' from verify-style

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Multiple northds run for HA in active/passive mode where the active
northd holds a lock. If that northd loses connectivity to the database
or is killed without releasing the lock, ovsdb-server will clear
the lock after twice the inactivity probe. But if that probe is set
to 0 (disabled) that will never happen, and a new northd will never
grab the lock and continue reconciling NB->SB.
Set the DB inactivity probe to something greater than 0 to ensure
that a northd will always eventually become active. The value of 60 was
chosen as a reasonable middle-ground between the lock being cleared
and another northd grabbing it (~120s) and the possibility that a loaded
ovsdb-server (many ovn-controller clients) would take more than 30-40
seconds to send/reply to all inactivity probes from clients. …
=> Bug 1834473: ovnkube: set NB/SB database inactivity probes to 60 seconds

pkg/platform/openstack/kuryr_bootstrap.go
In order to support updates in the SG rules added on Kuryr bootstrap we
need to make sure the security groups that got replaced by others are
removed. This commit, by maintaing list of "decommissioned" SG rules,
will make sure we delete them on upgrade.
=> Bug 1834858: Kuryr: Remove old SG rules on upgrade

bindata/network/openshift-sdn/alert-rules.yaml
Now that we have both sync-queued and sync-applied timestamps, we can write more accurate alerts. This change includes alerts that:
1. find nodes with queued changes for too long
2. find pods that are not ready for too long.
=> Bug 1826339: openshift-sdn: rethink kube-proxy rules, fix spurious alerts

bindata/network/ovn-kubernetes/ovnkube-master.yaml
inactivty_probe is in milliseconds, not seconds.
Fixes: d70c0c67b322936fa83750323c38c583a8e09f51
=> Bug 1834473: ovnkube: really set NB/SB database inactivity probes to 60 seconds

bindata/network/kuryr/005-daemon.yaml, bindata/network/multus/multus.yaml, bindata/network/openshift-sdn/sdn.yaml, pkg/network/multus.go
Release 4.3 Back-port for https://github.com/openshift/cluster-network-operator/pull/602
/hold 
Until MCO PR is in: https://github.com/openshift/machine-config-operator/pull/1722
And since he's been in the loop of this since the very beginning: 
/assign @danwinship 
And just so that I don't forgot:
/cherry-pick release-4.2
=> Bug 1834247: Don't override containernetworking binaries in SDN and Kuryr

bindata/network/openshift-sdn/sdn-ovs.yaml
This PR adds:
a) a timestamp when adding logs for save/restore so they can be correlated with other logs.
b) removes the hostPID setting on the daemonset pods
c) removes the --monitor option when starting the ovs-vswitchd and ovsdb-server processes
=> Bug 1807648: Fixes to reliably save/restore flows

pkg/controller/statusmanager/status_manager.go
Namespace deletion cannot be done while openshift-apiserver is down. It will be stuck in 'Terminating' state forever, and that can block the sdn restore. So we choose not to delete the namespace by the cleanup function but leave it to the user to manually remove the namespace after the cluster is back to a normal state.
=> Bug 1820472: Not delete namespace object when cleanup not rended objects

bindata/network/multus/003-dhcp-daemon.yaml
Otherwise, it can fail with out being able to locate the netns paths under OCP 4.5
=> Bug 1838251: The DHCP CNI daemonset should mount the netns paths

bindata/network/kuryr/003-config.yaml, pkg/bootstrap/types.go, pkg/names/names.go, pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go
When Octavia is upgraded from OSP13 to OSP16 double listeners becomes
supported and the load balancers that requires TCP and UDP on same
port should be recreated.
This commit ensure the DNS service is recreated upon Octavia upgrade.
=> Bug 1829233: Recreate DNS service upon Octavia upgrade

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Multiple northds run for HA in active/passive mode where the active
northd holds a lock. If that northd loses connectivity to the database
or is killed without releasing the lock, ovsdb-server will clear
the lock after twice the inactivity probe. But if that probe is set
to 0 (disabled) that will never happen, and a new northd will never
grab the lock and continue reconciling NB->SB.
Set the DB inactivity probe to something greater than 0 to ensure
that a northd will always eventually become active.
=> Bug 1834474: ovnkube: set NB/SB database inactivity probes to 60 seconds

bindata/network/openshift-sdn/sdn-ovs.yaml
This PR adds:
a) a timestamp when adding logs for save/restore so they can be correlated with other logs.
b) removes the hostPID setting on the daemonset pods
c) removes the --monitor option when starting the ovs-vswitchd and ovsdb-server processes
=> Bug 1807670: Fixes to reliably save/restore flows

README.md
It should be 'complete', not 'coplete' :)
=> Fix 'complete' typo in README

README.md
Markdown language allows the specification of relative links, which can
be used to write more interactive documents.  This change implements a
relative link in README.md for the reference to HACKING.md in an
attempt to promote UX.
Signed-off-by: Ryan Goulding <rgouldin@redhat.com>
=> Use markdown relative link in README.md for HACKING.md reference

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Current implementation of sb/nb db containers readiness probe uses
exec to call the ovn-appctl to check the status of the sb/nb db raft
cluster. This exec call will be executed by another exec call that is
used to execute the probe. If sb/nb db raft cluster is busy and readiness
probe is fired, it will be stuck till the raft cluster respond with
success or failure. It might take time in seconds (even more than
`periodSeconds` time). Next readiness probe executes and kills the parent
that makes the child processes zombie and they never reap. With single
readiness probe failure it creates 3 zombie threads.
With higher scale, raft cluster can be busy for long duration
(10 to 100s depending on the load) and readiness probe will fail
more frequently and that can increase the zombie threads and …
=> Bug 1835497 : Prevent sb/nb db readiness probe from being zombie

pkg/apply/merge.go, pkg/apply/merge_test.go
We should not attempt to overwrite Service.Spec.IPFamily, if it's set (in a dual-stack cluster)
=> fix up dual-stack Service reconciling

bindata/network/openshift-sdn/004-multitenant.yaml
=> Bug 1841507: Allow connection between authentication net namespaces

bindata/network/network-metrics/000-rbac.yaml, bindata/network/network-metrics/001-daemonset.yaml, bindata/network/network-metrics/002-prometheus.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/image-references, pkg/network/multus.go, pkg/network/network_metrics_test.go
This PR is to build the [network metrics daemon](https://github.com/openshift/network-metrics-daemon/) as part of CNO
=> Deploy the network metrics daemon as part of the CNO.

pkg/network/kube_proxy_test.go, pkg/util/k8s/kubeproxy.go
Aggregated several commits in the PR because I was finding several issues.
It was reported that the cluster-network-operator wasn't configuring correctly kube-proxy bind-address if it was "::", so I added some unit tests to check that it works correctly.
The other fixes are explained in the commit messages.
=> Improve IPv6 testing and minor fixes

bindata/network/openshift-sdn/sdn-ovs.yaml
saw this error message in the logs
Terminated:&ContainerStateTerminated{ExitCode:1,Signal:0,Reason:Error,Message:ovsdb-server: /var/run/openvswitch/ovsdb-server.pid: pidfile check failed (No such process)
when it looked like ovs was restarting causing the sdn pods to spin. explicitly delete
/var/run/openvswitch/ovs-vswitchd.pid and
/var/run/openvswitch/ovsdb-server.pid:
on ovs pod exit
=> Bug 1824983: explicitly delete pidfiles when exiting

bindata/network/kuryr/003-config.yaml, pkg/bootstrap/types.go, pkg/names/names.go, pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go
When Octavia is upgraded from OSP13 to OSP16 double listeners becomes
supported and the load balancers that requires TCP and UDP on same
port should be recreated.
This commit ensure the DNS service is recreated upon Octavia upgrade.
=> Bug 1841029: Recreate DNS service upon Octavia upgrade

pkg/platform/openstack/kuryr_bootstrap.go, pkg/platform/openstack/loadbalancer.go
During installation a bootstrap node is used as an API node at first,
but then gets removed. In Kuryr's bootstrap we never remove it from API
loadbalancer pool which leads to Octavia stating that LB is in degraded
state.
With those changes we prevent it by making sure on reconciliation we
remove loadbalancer members that we don't need there anymore. This
should help with scaledown of masters too.
(cherry picked from commit 0ccf62b3f058ebc1e9d8ddfa7a661098b37b1a21)
=> Bug 1832872: Remove dead member from LB pool.

bindata/network/ovn-kubernetes/006-ovs-node.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
This modifies the CNO daemonse yaml to add a timestamp in the same format
as the logfile generated by the container. This permits including them in
trace output
SDN-971 - Logging: Modify CNO .yaml files to prefix logged lines with the std prefix
https://issues.redhat.com/browse/SDN-971
=> Logging: add time stamp to echo in cno yaml

pkg/platform/openstack/kuryr_bootstrap.go
The ovn-octavia limitation of having several listener protocols
on the same port has been fixed, so the exception made for it
is not needed anymore.
=> Bug 1846396: Drop ovn-octavia provider limitation for multiprotocol listeners

bindata/network/ovn-kubernetes/004-config.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, vendor/k8s.io/utils/net/ipnet.go, vendor/k8s.io/utils/net/net.go, vendor/modules.txt
CNO is enforcing that ovn-kubernetes only accepts a single service CIDR, which is no longer true
=> ovn-kubernetes: allow dual-stack configs

pkg/platform/openstack/kuryr_bootstrap.go
Depending on the workload running on the cluster,
the etcd leader elections can happen more frequently due to
timing out to connect to etcd port 2380. This commit can
workaround the issue by splitting the etcd port ranges into
different security group rules.
=> Bug 1847313: Split etcd sg rule ports range into different sg rules

pkg/controller/statusmanager/pod_status.go, pkg/controller/statusmanager/status_manager_test.go
This patch checks for the statuses of pods of those deployments and daemonsets
which are in a "hung" state. If any of the pods are in CrashLoopBackOff state
the operator will be marked as degraded.
=> Mark operator as degraded if there are any pods in CrashLoopBackOff State

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/ovn-kubernetes/006-ovs-node.yaml
Needed to remove some of the readiness probes because they don't work, but this doesn't actually lose much coverage.
And liveness probes are not useful in this context.
This contains a hack to pass a strange case that an artifact of CI upgrade tests. It won't be in the wild, and could be removed.
Note to reviewers: hide whitespace changes :-)
=> openshift-sdn, ovn-kubernetes: adopt systemd-managed openvswitch if present

bindata/network/ovn-kubernetes/ovnkube-node.yaml
When trying to transfer cri-o to manage its network namespaces in openshift, we have run into problems with multus. Specifically we see the error:
2020-04-07T17:46:52Z [error] delegateAdd: error invoking DelegateAdd - "ovn-k8s-cni-overlay": error in getting result from AddNetwork: CNI request failed with status 400: '[openshift-dns/dns-default-98tll] failed to configure pod interface: failed to open netns "/var/run/netns/76716600-f7fd-462f-b7df-ae054dbd144e": unknown FS magic on "/var/run/netns/76716600-f7fd-462f-b7df-ae054dbd144e": 1021994
'
through testing, I've found the netns is definitely mounted as an nsfs and not tmpfs, so I suspect we are seeing https://github.com/containernetworking/plugins/issues/69
to fix this, attempt mounting /var/run/netns as HostToContainer in ovnkube …
=> Bug 1847675: [4.4] mount /var/run/netns rslave in ovnkube

bindata/network/kuryr/003-config.yaml, pkg/bootstrap/types.go, pkg/names/names.go, pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go
When Octavia is upgraded from OSP13 to OSP16 double listeners becomes
supported and the load balancers that requires TCP and UDP on same
port should be recreated.
This commit ensure the DNS service is recreated upon Octavia upgrade.
=> Bug 1846459: Recreate DNS service upon Octavia upgrade

.gitignore, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, pkg/network/ovn_kubernetes.go
These timers are currently set to fixed value based on my current observation
from scale tests. We might have to increase these values in future based on
the scale we will be supporting for upcoming release. Currently election-timer
values are limited by the raft jsonrpc inactivity-probe time of 5 seconds as well.
To further increase the election-timer value, we need to disable jsonrpc
inactivity-probe.
Signed-off-by: Anil Vishnoi avishnoi@redhat.com
=> Bug 1851518: Expose raft (nb-db/sb-db) election-timer and ovn-controller inactivity probe.

pkg/platform/openstack/kuryr_bootstrap.go
Depending on the workload running on the cluster,
the etcd leader elections can happen more frequently due to
timing out to connect to etcd port 2380. This commit can
workaround the issue by splitting the etcd port ranges into
different security group rules.
=> Bug 1851338: Split etcd sg rule ports range into different sg rules

bindata/network/ovn-kubernetes/ovnkube-master.yaml
If this does not happen, the master pod might fail with `ovsdb-server: ovsdb error: server does not belong to cluster`
and never recover. We make sure the current serverid is in the file by checking its presence in the prev_servers set.
As discussed in https://bugzilla.redhat.com/show_bug.cgi?id=1837953, this is a workaround to recover from inconsistent local db state that may cause the master pod to CrashLoopBackOff.
=> Bug 1837953: Check if the db file has been correctly initialized with raft.

bindata/network/openshift-sdn/sdn-ovs.yaml
This commit deletes /var/run/openvswitch/flows.sh after being done with
restoring. This avoids appending old flows to such file and
misconfiguring OVSDB.
Closes-Bug 1848374: Killing ovs-vswitchd cause some ovs openflows lost
=> Bug 1848374: Delete flows.sh after restore.

pkg/network/ovn_kubernetes.go
Today we wait for 1 minute for all nodes to be up before booting OVN. With "OVS on the system" there is additional configuration done by NetworkManager / MCO networking startup scripts and the likes, which might require longer timeouts than what we currently support. So, let's bump the time.
Reconciliation happens every 5 min, so I am setting the timeout to 280 seconds to not block reconciliation during bring up. 
/assign @trozet
=> Bump OVN Bootstrap timeout

bindata/network/kuryr/alert-rules.yaml
Alerting when running with kuryr and:
- There is no kuryr-controller
- There are nodes without kuryr-cnis
- Pods on openshift-kuryr namespace are  crashLooping
- There is not enough quota
- There are subnets with no IPs left
- Slow time for creating pods
- Kuryr CNI actions are slow
=> Add support for Kuryr alerts

bindata/network/ovn-kubernetes/ovnkube-node.yaml
The TargetDown alert was always getting fired for all the ovnkube-nodes
because the metrics-bind-address flag was not getting passed in the exec
command for the ovnkube-node container. This regression was introduced
in  PR #615. Promethues was hence not able to scrape the up metrics.
=> Bug 1851928: [metrics] TargetDown alert is always fired in ovnkube-node job

bindata/network/openshift-sdn/sdn.yaml
1852593 - EgressRouter: error in getting result from AddNetwork: CNI request failed with status 400
https://bugzilla.redhat.com/show_bug.cgi?id=1852593
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_egress-redirect-pod_test_d22d4544-18ec-43bf-95c4-70f21e5246fe_0(4d0cbd2631875f117df10c0a8501b385919b1162f40382e75b8c87b8bb3cf7ca): Multus: [test/egress-redirect-pod]: error adding container to network "openshift-sdn": delegateAdd: error invoking confAdd - "openshift-sdn": error in getting result from AddNetwork: CNI request failed with status 400: 'could not open netns "/var/run/netns/11cb808b-c141-40e9-86fe-c74643b481aa": unknown FS magic on "/var/run/netns/11cb808b-c141-40e9-86fe-c74643b481aa": 1021994
Fix by mounting /run/netns in …
=> Bug 1852593: Add netns mount

bindata/network/kuryr/005-daemon.yaml
This commit adds an init container to kuryr-daemon pods that will
execute iptables commands to block access to machine-config-server and
metadata server for pods that run on host networking. Both should not be
required after ignition.
=> Bug 1856289: Block MCS and metadata for host-networking pods

bindata/network/network-metrics/001-daemonset.yaml
The network metrics daemon is not supposed to run on windows nodes.
=> Bug 1856271: Make sure the network metrics pod runs only on linux nodes.

bindata/network/ovn-kubernetes/ovnkube-master.yaml
New upstream metrics require this, so ovn-appctl can find northd
=> ovn-kubernetes: record ovn-northd pid

bindata/network/ovn-kubernetes/ovnkube-master.yaml
The daemonset file currently doesn't enable multicast support by default. This change is to pass that as an argument during starting of the ovnkube-master pod.
=> Enable multicast support by default on the master

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/ovn-kubernetes/006-ovs-node.yaml
Seen on a distant and heavily loaded CI cluster: if the cluster is heavily loaded we can expect `ovs-vsctl` to be slow. The commands executed by our `livenessProbe`/`readinessProbe` already take this into account, however the probes themselves do not. We thus restart OVS many more times than what we should, as those probes default to 1 second. This is not a real problem, but an optimization. The real problem is that we flush our DB when restarting, which is something which will need to be fixed later on.  
PS: I decided to set `timeoutSeconds` to whatever timeout the command has + a 1 second buffer
I will file a separate PR for release-4.5....but I will wait with filing that until tomorrow, once we, possibly, find and define a fix for the DB flush. As such there are less back-ports, CI …
=> Set timeoutSeconds to reflect expected timeout for OVS commands

hack/KIND_CNO.md, hack/ovn-kind-cno.sh, hack/webhook-create-signed-cert.sh
for networking development and testing, using single node
environments mask a big part of the problems.
We should use multinode by default if possible.
Another improvements:
* the apiserver autodiscovers the API address, so we don't
need to pass the kubeconfig
* fix multus webook problem
* bump KIND version to 0.8.1
* allow to configure IPv6 environments
* use kubectl wait instead of bash loops
=> use KIND multinode cluster , add IPv6 support, fix multus webook problem

bindata/kube-proxy/kube-proxy.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
which allows umount events that happen on the host to be propegated to the container.
This prevents situations where the networking pods hold onto a mount that was umounted on the host,
which causes attempts to remove the mountpoint to fail
Signed-off-by: Peter Hunt <pehunt@redhat.com>
=> Bug 1855121: mount host-slash HostToContainer

bindata/network/ovn-kubernetes/ovnkube-master.yaml
We need to search the whole line for the server_id.
Current regex is too aggressive.
The original example indicates that the prev_server line is a list of servers
```bash
$ ovsdb-tool show-log /etc/ovn/ovnnb_db.db | grep "server_id\|prev_servers"
server_id: d5db
prev_servers: 33b4("ssl:10.19.138.37:9643"), 720d("ssl:10.19.138.33:9643"), 7e4f("ssl:10.19.138.32:9643"
```
The above DB is inconsistent because d5db is not part of prev_servers.
A consistent DB looks like this:
```bash
$ ovsdb-tool show-log /etc/ovn/ovnnb_db.db | grep "server_id\|prev_servers"
server_id: 33b4
prev_servers: 33b4("ssl:10.19.138.37:9643"), 720d("ssl:10.19.138.33:9643")
```
=> Bug 1837953: fixup server_id regex

bindata/network/openshift-sdn/sdn-ovs.yaml
This is the release-4.5 back-port of https://github.com/openshift/cluster-network-operator/pull/701
Unlike https://github.com/openshift/cluster-network-operator/pull/701 we need to set the values in different places as the code varies a lot between these versions, so no cherry-pick involved here, however same logic applies to the value definition.
=> Bug 1857738: [release-4.5] Set timeoutSeconds to reflect expected timeout for OVS commands

bindata/network/openshift-sdn/002-rbac.yaml, bindata/network/openshift-sdn/monitor.yaml, bindata/network/openshift-sdn/sdn.yaml, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go
We use port 29101 for plain HTTP metrics which is firewalled and expose 29102 over HTTPS.
---
Uses RBAC proxy just like https://github.com/openshift/cluster-network-operator/pull/563
Because  the pod uses `hostNetwork: true` and I don't want to add additional ports, the regular http metrics endpoint is exposed in `127.0.01:9101` and the https one on `0.0.0.0:9101`
=> Bug 1809205: Configure TLS for OpenShift SDN metrics endpoint

bindata/network/ovn-kubernetes/ovnkube-master.yaml
It turned out the prev_servers list contains only the leader, so it can't be used to understand if the db is consistent or not. This leads in always deleting the db file when restarting a ovn-master pod that is not the leader.
More details in https://bugzilla.redhat.com/show_bug.cgi?id=1837953#c36
Revert "Merge pull request #694 from rbbratta/fix-server_id_regex"
This reverts commit 3ff3b90bffdce72cdf3fe9c95115374f2242c54d, reversing
changes made to a8ababe5dd02dedfa0ed451504140b8d0f60aa15.
Revert "Merge pull request #688 from fedepaol/dbhealthy"
This reverts commit a0aaca735a240cc6cdf8cd3517fc71c2efc5e043, reversing
changes made to 2f04083382a5a824aeca0adfc2b5a58bd34cbb80.
=> Bug 1858834: Revert ovn db consistency check.

bindata/network/additional-networks/crd/001-crd.yaml, bindata/network/multus/002-rbac.yaml, pkg/network/additional_networks_test.go, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
This change applies a new CRD and the appropriate RBAC permission to enable
functionality in Whereabouts IPAM CNI which enables the use of overlapping
ranges without re-assigning IP addresses across ranges.
=> Multus whereabouts IPAM CNI should support overlapping ranges

bindata/network/ovn-kubernetes/003-rbac-controller.yaml, bindata/network/ovn-kubernetes/monitor.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
This is a quick workaround for getting OVN metrics using TLS to unblock us...
I will modify OVN kubernetes to be capable to expose HTTPS directly in the near future.
https://issues.redhat.com/browse/SDN-912
=> Bug 1822720: Configure TLS for OVN metrics endpoints

bindata/network/ovn-kubernetes/006-pki.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
This change renders the daemonsets for ovnkube-master and ovnkube-node
using the same parameter that is used for the hostname parameter of
the PKI cert generated.
=> Support using common name as hostname for TLS server cert verification

bindata/network/kuryr/001-rbac.yaml, bindata/network/kuryr/002-crds.yaml, bindata/network/kuryr/003-config.yaml
With 4.6 Kuryr uses KuryrPort custom resources to save Neutron port
information instead of annotating them on the pod. Also the
KuryrNetPolicy is replaced by updated format of KuryrNetworkPolicy CR.
This commit makes sure new CRDs are added, RBAC extended and Kuryr
configuration updated to support this.
=> Kuryr: Add new Custom Resource Definitions

bindata/network/ovn-kubernetes/001-crd.yaml, bindata/network/ovn-kubernetes/003-rbac-controller.yaml
grant ovn-kubernetes the ability to get,list, watch, and update egressfirewall and egressIP objects; add get, list, and watch to CustomResourceDefinitions in order to dynamically enable/disable egressfirewall based on the presence of its defining CRD
Also add the CRD for egressFirewall to the bindata for ovn-kubernetes
=> Add required setup for egressFirewall and egressIP

bindata/network/additional-networks/crd/001-crd.yaml
This adds the apiversion, kind and metadata fields for explain to properly function.
@s1061123 can you check and see if this look OK? If it does, we can move forward with backports. Thanks!
=> Bug 1819571: NetworkAttachmentDefinitions should have output for "oc explain" 

bindata/network/ovn-kubernetes/ovnkube-master.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, pkg/network/ovn_kubernetes.go
This commit adds support for configuring the ovn northd probe interval
in the start-up script for the nbdb container.
=> Configure northd probe interval during startup

bindata/network/ovn-kubernetes/002-rbac.yaml
Nodes do watch for CRDs and EgressIP objects.
```
I0731 22:36:03.045463    2191 reflector.go:175] Starting reflector *v1beta1.CustomResourceDefinition (12h0m0s) from k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go:117
I0731 22:36:03.045480    2191 reflector.go:211] Listing and watching *v1beta1.CustomResourceDefinition from k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go:117
E0731 22:36:03.058470    2191 reflector.go:178] k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1beta1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-node" cannot list resource …
```
=> ovnkube: add RBAC for egressip and crd resources for nodes

bindata/network/network-metrics/001-daemonset.yaml
It makes sense to have the daemon running on masters too, because users may end up using the composed metric to monitor the networks.
The query we are going to document looks like:
(container_network_receive_bytes_total) + on(namespace,pod,interface) group_left(network_name) ( pod_network_name_info )
Which results in the same metric exposed by cAdvisor, but with the network name added to it.
If the daemon does not run on masters, the composed metric won't be available for pods running on masters.
=> Bug 1857222: Run the network metrics daemon on masters too.

bindata/network/ovn-kubernetes/alert-rules.yaml
This PR ensures that console dashboard do not fire`NodeWithoutOVNKubeNodePodRunning` alert for Windows
worker nodes, as we would not be running OVN pods on Windows.
=> Update NodeWithoutOVNKubeNodePodRunning alert to ignore Windows Nodes

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
This patch migrates from using Local gateway mode to Shared gateway mode
with ovn-kubernetes. With shared gateway mode, the external network NIC
is now directly configured as part of an OVS bridge, which has a Layer 2
connection to OVN, effectively allowing OVN to share the NIC with the
host as a Layer 2 network.
Unlike Local gateway mode, this eliminates the need to route through the
kernel for certain OVN traffic to egress the host.
=> Enable shared gateway mode for OVN

README.md, manifests/0000_70_cluster-network-operator_01_crd.yaml, pkg/network/cluster_config.go, pkg/network/cluster_config_test.go
For plugins like Calico which don't use the hostPrefix for anything,
it does not make sense to validate this field and force customers
to set specific values just to pass validation considering the
field is not even used in these plugins. This patch ensures that
we perform the validation only for OpenShiftSDN and OVNKubernetes.
=> Bug 1852112: Ignore hostPrefix validation for non-(sdn/ovn) plugins

bindata/network/additional-networks/crd/001-crd.yaml
Similar to https://github.com/openshift/cluster-network-operator/pull/745
After the change
```
$ oc explain ippools
KIND:     IPPool
VERSION:  whereabouts.cni.cncf.io/v1alpha1
DESCRIPTION:
IPPool is the Schema for Whereabouts for IP address allocation
FIELDS:
apiVersion	<string>
APIVersion defines the versioned schema of this representation of an
object. Servers should convert recognized schemas to the latest internal
value, and may reject unrecognized values. More info:
https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
kind	<string>
Kind is a string value representing the REST resource this object
represents. Servers may infer this from the endpoint the client submits
requests to. Cannot be updated. In CamelCase. More info: …
```
=> Bug 1866792: Fix oc explain ippools

bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
Following the change in PR #581 the job name should be renamed to
"ovnkube-master-metrics"
=> OVN: Fix control plane metrics alert job name

bindata/network/ovn-kubernetes/ovnkube-master.yaml
If user manually configure the election-timer, restarting the pods
can reset the value to default value (5 second). This can be an issue
if pods are restarted at large scale -- resetting to 5 second might
disrupt the cluster at that scale and it might not converge.
Signed-off-by: Anil Vishnoi <avishnoi@redhat.com>
=> Bug 1857387: Do not reset the election-timer value

bindata/network/additional-networks/crd/001-crd.yaml
This fix changes CRD to show output for 'oc explain' correctly.
=> Bug 1819571: NetworkAttachmentDefinitions should have output for "oc explain"

bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
Add a new rule that will alert when there is no OVN master
leader present for more than 10minutes.
=> OVN: Add the NoOvnMasterLeader alert-rule

bindata/network/kuryr/alert-rules.yaml, bindata/network/openshift-sdn/alert-rules.yaml, bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/alert-rules.yaml
The `general.rules` group name conflicts with others, causing them to be merged with other rules in OpenShift console via Thanos Querier.
This fixes it.
/cc @openshift/openshift-team-monitoring
=> Bug 1866200: fix recording rules group name

Dockerfile, Dockerfile.rhel7, go.mod, vendor/modules.txt
We noticed in https://github.com/openshift/release/pull/10862 that `Dockerfile` and `Dockerfile.rhel7` used different versions of golang. This updates everything to use 1.14.
Changing `go.mod` to specify 1.14 required re-running `go mod vendor` to update `vendor/modules.txt` to include the `## explicit` lines
=> build: require golang 1.14

bindata/network/kuryr/002-crds.yaml
The vifs field totally belongs to the status part of the KuryrPort CR
and this commit moves it there. This is handled in kuryr-kubernetes too.
Should be safe as version with previous CRD wasn't yet released.
=> Bug 1867538: Kuryr: Update KuryrPort CRD to move vifs to status

pkg/network/ovn_kubernetes.go
In order to deploy without using HybridClusterNetwork with
OVN-Kubernetes, the user is required to specify:
ovnKubernetesConfig:
hybridOverlayConfig:
hybridClusterNetwork: []
The code was assuming the slice always had values.
=> Bug 1868078: Fixes providing empty slice for HybridClusterNetwork

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
With OCP upgrade today, CNO happens before MCO. When upgrading from 4.5
to 4.6, 4.6 OVN expects system OVS to be there and configured which will
not happen until MCO upgrade finishes. Therefore upon initial CNO
upgrade, we will run in local gateway mode until the node is rebooted
via MCO with a machine-os-content change to include system OVS and run
the ovs-configuration service.
We also need to temporarily use local gateway when converting from
openshift-sdn to ovn-kubernetes, so use the enabled system service path
for checking.
=> Bug 1868259: Fixes OVN upgrade with shared gateway mode

bindata/network/kuryr/002-crds.yaml
This commit formats the KuryrLoadBalancer CRD to include
the structure of EndpointSlice.
Depends-on Kuryr-Kubernetes [PR](https://github.com/openshift/kuryr-kubernetes/pull/329)
=> Bug 1873058: Convert KuryrLoadBalancer subsets CRD to EndpointSlice

bindata/network/ovn-kubernetes/ovnkube-master.yaml
This adds a preStop hook to call ovs-appctl exit for both nbdb and sbdb. Hopefully this reduces instances of database corruption.
/cc @trozet @dceara
=> Bug 1872750: ovn-k: add prestop actions for nbdb and sbdb

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Reverts openshift/cluster-network-operator#748
This PR stops election leader timers from being set to the default value of 5 seconds, because 5 is never less than 1.
=> Bug 1874242: Revert "Bug 1857387: Do not reset the election-timer value"

cmd/cluster-network-operator/log.go, cmd/cluster-network-operator/main.go
While trying to figure out how we ended up with three simultaneous copies of CNO running in an IPv6 cluster, I found that we're currently dropping all logs from code in `sigs.k8s.io/controller-runtime`.
This is hacky but we should eventually stop using controller-runtime anyway, so...
=> Bug 1874647: Initialize controller-runtime logging

bindata/network/openshift-sdn/002-rbac.yaml, bindata/network/openshift-sdn/monitor.yaml, bindata/network/openshift-sdn/sdn.yaml
The SDN metrics pod needs a service serving certificate which depends on
the SDN. However during the upgrade we've seen that sometimes during the
upgrade tis causes problems because the metrics daemonset is deployed
before rolling out the old daemonset.
=> Bug 1870711: Move metrics to SDN DS

bindata/network/additional-networks/crd/001-crd.yaml
This adds the apiversion, kind and metadata fields for explain to properly function.
Backport of #729
=> Bug 1861412: NetworkAttachmentDefinitions should have output for "oc explain"

bindata/network/ovn-kubernetes/004-config.yaml
Egress IP has been disabled for OpenShift due to critical bugs rendering the functionality "un-testable". 
Now that PR https://github.com/openshift/ovn-kubernetes/pull/243 merged, we got a bunch of fixes in OVN-Kubernetes. Hopefully once PR: https://github.com/openshift/ovn-kubernetes/pull/240 merges we'll get the essential OVN fix to make egress IP work.
This enablement is independent of any of that though. 
/assign @dcbw
=> Enable EgressIP for OpenShift

bindata/network/ovn-kubernetes/ovnkube-master.yaml
The ovnkube master daemonset starts the ovsdb-servers using ovn-ctl commands - run_nb_ovsdb
and run_sb_ovsdb. These versions of the command don't daemonize the ovsdb-servers and hence
the code to handle the DB upragdes in these functions never gets run.
This results in the OVN dbs in the old schema. Upgraded ovn-controllers will not see
any new columns because of this resulting in datapath disruptions.
This patch adds the code to handle the db upgrade in the 'postStart' stage.
Bug 1868392: [FDP 20.F] OVN 2.13 breaks pod-pod networking across the projects on OCP
Signed-off-by: Numan Siddique <nusiddiq@redhat.com>
=> Bug 1874385: OVN: Handle OVN db upgrades.

bindata/network/additional-networks/crd/001-crd.yaml
This adds the apiversion, kind and metadata fields for explain to properly function.
Backport of #729
=> Bug 1823709: [backport 4.4] NetworkAttachmentDefinitions should have output for "oc explain"

pkg/network/mtu.go, pkg/network/render.go
The code was taking into account IPv4 routes only.
It consider IPv6 routes now
Signed-off-by: Antonio Ojea <aojea@redhat.com>
=> Bug 1874591: autodect mtu support for ipv6

bindata/network/openshift-sdn/sdn.yaml
When creating an egress-router pod, openshift-sdn fails during the CNI_ADD with the error message:
```
'could not open netns "/var/run/netns/11cb808b-c141-40e9-86fe-c74643b481aa": unknown FS magic on "/var/run/netns/11cb808b-c141-40e9-86fe-c74643b481aa": 1021994
```
PR: https://github.com/openshift/cluster-network-operator/pull/696 already made an attempt months ago at fixing this, but didn't.  
Now, this is going to sound strange to say: but I am not entirely sure why this fixes the issue...but it does (tested on AWS). So needless to say, I am open to any suggestion / complaint detailing why this should not be done. 
I inspired myself off of: https://github.com/openshift/cluster-network-operator/pull/648/files 
/assign @danwinship
=> Bug 1852593: SDN mount host's /var/run/netns

pkg/platform/openstack/kuryr_bootstrap.go, pkg/platform/openstack/networking.go
Kuryr requires a router to be present on the cluster
to allow communication between Pod and Services. However,
during a FIP less no router is created by the installer.
This commit makes sure a router is created if not already
present.
=> Bug 1874457: Ensure router is present when Kuryr is used

bindata/network/kuryr/005-daemon.yaml
This commit makes iptables commands available on the
container by relying on the host.
=> Bug 1878725: Ensure iptables commands are available on cni init container

pkg/network/ovn_kubernetes.go
In order to deploy without using HybridClusterNetwork with
OVN-Kubernetes, the user is required to specify:
ovnKubernetesConfig:
hybridOverlayConfig:
hybridClusterNetwork: []
The code was assuming the slice always had values.
(cherry picked from commit 3df57bbb27a05b0165fe1a11f6d331441a97387b)
=> Bug 1868444: Fixes providing empty slice for HybridClusterNetwork

bindata/network/ovn-kubernetes/ovnkube-master.yaml
4.5 back-port of https://github.com/openshift/cluster-network-operator/pull/755 needed to unpin ovn-kubernetes 4.5 and revert https://github.com/openshift/ovn-kubernetes/pull/248
/assign @knobunc
=> Bug 1874737: [release-4.5] OVN: Handle OVN db upgrades

bindata/network/ovn-kubernetes/004-config.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
move the enabling of hybrid overlay into the ConfigMap for ovnkube like
all new arguments should be
Signed-off-by: Jacob Tanenbaum <jtanenba@redhat.com>
=> Bug 1880490: change the hybrid overlay config to use the ConfigMap instead of cli

manifests/0000_70_cluster-network-operator_01_pki_crd.yaml
Because the CRD's preserveUnknownFields was set to false, oc explain wouldn't work. This PR Fixes it.
Before the PR:
```
$ oc explain operatorpkis
KIND:     OperatorPKI
VERSION:  network.operator.openshift.io/v1
DESCRIPTION:
<empty>
```
With this PR:
```
$ oc explain operatorpkis
KIND:     OperatorPKI
VERSION:  network.operator.openshift.io/v1
DESCRIPTION:
OperatorPKI is a simple certificate authority. It is not intended for
external use - rather, it is internal to the network operator. The CNO
creates a CA and a certificate signed by that CA. The certificate has both
ClientAuth and ServerAuth extended usages enabled. More specifically, given
an OperatorPKI with <name>, the CNO will manage: - A Secret called
<name>-ca with two data keys: - tls.key - the private key - tls.crt - the
CA …
```
=> Bug 1880853: Fix oc explain for operatorPKI

bindata/network/openshift-sdn/001-crd.yaml
The max items per EgressNetworkPolicy was always completely arbitrary; the code blindly assumes that there won't be more items there than there are possible `priority` values in an OpenFlow rule, but it doesn't really care beyond that. We picked 50 arbitrarily because it should have been more than enough _given the way that we intended for people to use the feature_, but people have always been using the feature to do things we didn't really originally intend.
Anyway, this bumps it to 1000.
@abhat there is no `maxItems` in openshift/api's version of this CRD... are those CRDs supposed to be in sync with these ones? Should we be validating that somewhere?
=> Bug 1879910: openshift-sdn: bump EgressNetworkPolicy maxItems to 1000

OWNERS
=> Add trozet to owners

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
ovs-configuration.service is enabled for both ovn-kube and openshift-sdn. So using the parameter of configure-ovs.sh as the condition to tell whether ovnkube shall be in a shared gw or local gw mode. In 4.5, this parameter is not added yet.
=> Bug 1854306: Run ovn in shared gw mode when configure-ovs.sh run with parameter OVNKubernetes

bindata/network/ovn-kubernetes/ovnkube-node.yaml
By default the timeout of 'kubectl get' is infinity. If apiserver don't response,
This command can take ~15min to fail(socket timeout). It's too long. This patch
set a 30s timeout to 'kubectl get'.
=> Bug 1854306: Set a 30s timeout for kubectl command in ovnkube-node

bindata/network/ovn-kubernetes/ovnkube-master.yaml
This PR adds the following:
a) ovn-dbchecker to the daemonset.
b) ability to detect an existing raft cluster and join
the cluster when the raft leader db pods restart.
=> Bug 1882569: Add support for OVN DB Management

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/ovn-kubernetes/006-ovs-node.yaml
/assign @pliurh 
When systemctl is run in a separate PID namespace where PID 1 isn't systemd, it doesn't behave the normal way: https://github.com/systemd/systemd/issues/11300
The solution for this is to entirely remove calls to systemctl calls.
=> Bug 1874696: Remove systemctl calls

manifests/0000_70_cluster-network-operator_03_deployment.yaml
At current scale test (100 nodes, 3000+ services, 15K+ pods), sb-db
cluster is partitioning very frequently with the current default
election time of 5 seconds. This makes the cluster
stable and once it goes to unstable state, it takes longer to recover.
Given the huge number of flows being installed, using any utility tool to
dump the logical flows from sb-db causes the cluster partition with the
current election timer.
Signed-off-by: Anil Vishnoi <avishnoi@redhat.com>
=> Bug 1883662: Tune sb-db raft cluster election-timer

bindata/network/openshift-sdn/sdn.yaml
Because kube-proxy may not be initialized by the time the RBAC proxy
starts it may crashloop for a while. Doesn't have any actual impact but
the restarts show in oc get pod and people may worry about that.
=> Bug 1883903:Add retries to SDN's RBAC proxy

bindata/network/ovn-kubernetes/ovnkube-master.yaml
We always bracketify init_ip when we set it, so no need to do it again
when we start ovsdb-server.
=> Bug 1884272: Fixes double bracketify on init_ips

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/ovn-kubernetes/006-ovs-node.yaml
There is a period of time where MCO will lay down the files for 4.6
before it reboots the node into the new OS. If the ovs pods are coming
up at this time they could accidentally think systemd ovs is running,
which it is not. This patch modifies the check to look in systemd, where
the ovs-configuration service will be enabled only when 4.6 is booted.
=> Bug 1884101: Fixes systemd ovs check for ovn/sdn

bindata/network/ovn-kubernetes/monitor.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Follow up of this PR: https://github.com/openshift/cluster-network-operator/pull/751
Basically it's fixing same issue as for SDN. To avoid deploying metric's DeamonSet before OVN, metrics was moved to OVN DeamonSet.
=> Bug 1884430: Move kube-rbac-proxy to general ovnkube DeamonSet

bindata/network/ovn-kubernetes/002-rbac.yaml, bindata/network/ovn-kubernetes/003-rbac-controller.yaml, bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/monitor.yaml
With PR #778 (commit 518118b) we changed the service monitor definition,
and the daemonset serviceaccount.
With this PR we fix the serverName in the serviceMonitors, the
serviceAccount permissions and the prometheusRule alert expression.
=> Bug 1885165: Fix ovnkube metrics

bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
When the cert wasn't available yet the script would crash with a python json-parsing error rather than looping like it was supposed to.
It is possible there are further problems here...
/assign @juanluisvaladas
=> Bug 1885002: Fix kube-rbac-proxy startup scripts

bindata/kube-proxy/kube-proxy.yaml, bindata/kube-proxy/monitor.yaml, cmd/cluster-network-renderer/main.go, pkg/apply/merge.go, pkg/controller/operconfig/operconfig_controller.go, pkg/network/dhcp_daemon.go, pkg/network/dhcp_daemon_test.go, pkg/network/kube_proxy.go, pkg/network/kube_proxy_test.go, pkg/network/mtu.go, pkg/network/mtu_unsupported.go, pkg/network/multus.go, pkg/network/multus_admission_controller_test.go, pkg/network/multus_test.go, pkg/network/network_metrics_test.go, pkg/network/openshift_sdn.go, pkg/network/previous_test.go, pkg/network/render.go, pkg/util/k8s/kubeproxy_test.go
Spinoff of #819. Along with https://github.com/openshift/sdn/pull/198 this will allow us to run openshift-sdn with a standalone kube-proxy for testing.
The first two commits are drive-by cleanups, with the second (`render: clarify that config "canonicalization" is deprecated`) being inspired by https://bugzilla.redhat.com/show_bug.cgi?id=1877984.
I've tested that a cluster installed with this comes up. Next step is to add a CI job using it
=> Allow running openshift-sdn with standalone kube-proxy

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/ovn-kubernetes/006-ovs-node.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Checking files or symlinks on disks seems to be flaky and there are time
windows where files are laid down on the disk but the running version is
still 4.5. This changes the logic to determine if OVS is running on the
host by checking the for a file generated when ovs-configuration is
executed.
=> Bug 1880591: 4.6 Use ovs-configuration file to determine if OVS is running in systemd

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Add ovn-db-pod label on the master pods
The problem we are seeing is that when the master gets replaced, the new master starts off with a config that has itself in the list of masters, but the old masters don't see the updated config till the new master pod starts up fully. That results in the ovn-dbchecker container on the existing masters to kick the newly joined master out of the raft cluster. So we have a bit of chicken-and-egg problem. In order to handle stale config on the existing masters, Tim and I decided to make a `list all db pods` call to check for the presence of a pod with the IP of the raft member prior to kicking the member out. The `ovn-db-pod: "true"` label lets us select all the pods that are running db containers in a consistent manner for upstream and downstream. …
=> Add ovn-db-pod label on the master pods

bindata/network/openshift-sdn/sdn-ovs.yaml
In 4.6, openvswitch is executed as a systemd service. This is not the case
for 4.5. However, changes are always rolled out to the SDN first, including
on rollback. This means we need to handle, even if sub-optimally, the case
where we're running the 4.5 daemonset on a 4.6 MCO-configured node.
In other words, openvswitch is running as a systemd service.
Fixes: 1885848
Replaces: #830 
Co-authored-by: Casey Callendrello <cdc@redhat.com>
=> Bug 1886127: Handle downgrades from 4.6 to 4.5

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
With commit 518118bb9 we accidentlly made ovn-cert secret mount
optional, this secret is never optional.
=> Bug 1886834: Make ovn-cert secret mandatory for both master and node

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
With commit 518118bb9 we accidentlly made ovn-cert secret mount
optional, this secret is never optional.
=> Bug 1886855: Make ovn-cert secret mandatory for both master and node

pkg/network/kube_proxy.go
master PR: https://github.com/openshift/cluster-network-operator/pull/620
since the clusterCIDR is user configurable determine if the
given cluster is IPv4 or IPv6 single stack based on that value
for network plugins. this will allow third party plugins that
do support single stack to function
=> [release-4.4] bug 1833048: For third party plugins enable testing of IPv6 single stack

README.md
We never actually documented explicitly how to enable sdn verbosity.
=> README: document verbosity overrides

bindata/network/openshift-sdn/sdn-ovs.yaml
ovs-appctl doesn't like running in a different pid namespace, so the liveness probe fails when downgrading from 4.6 (which runs it in systemd).
=> Bug 1886127: [4.5] sdn-ovs: fix liveness probe for downgrade case

Dockerfile.rhel7
Updating cluster-network-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/cluster-network-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating cluster-network-operator builder & base images to be consistent with ART

manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/image-references
This doesn't affect production deploys nor CI runs, as those
versions are replaced to sane ones.
However when using hack/run_locally we need this otherwise
there is a mismatch between 4.3/4.4 code and master (which is what
we usually use for developing)
=> Set image versions of CNO deployment to latest

bindata/kube-proxy/kube-proxy.yaml, bindata/kube-proxy/monitor.yaml, pkg/network/kube_proxy.go, pkg/network/kube_proxy_test.go, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go
As with openshift-sdn and ovn-kubernetes, we should run the standalone kube-proxy metrics behind an authenticated proxy.
To avoid possible problems with upgrading old clusters, I made it conditional on using the new metrics port.
=> Use kube-rbac-proxy for standalone kube-proxy metrics

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
We were pointing to both wrong service name and namespace.
=> Bug 1891023: Fix ovn rbac proxy init script secret name

bindata/network/openshift-sdn/004-multitenant.yaml
It needs to be able to reach etcd, so it needs to be in netns 1.
Fixes: bz 1890130
=> Bug 1890130: openshift-sdn: multitenant: join openshift-etcd-operator to etcd

bindata/network/ovn-kubernetes/ovnkube-master.yaml
=> Bug 1880591: Adds missing check for ovs-config-executed

manifests/0000_70_cluster-network-operator_00_namespace.yaml, manifests/0000_70_cluster-network-operator_01_crd.yaml, manifests/0000_70_cluster-network-operator_01_credentialsrequest.yaml, manifests/0000_70_cluster-network-operator_01_pki_crd.yaml, manifests/0000_70_cluster-network-operator_02_rbac.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/0000_70_cluster-network-operator_04_clusteroperator.yaml
This is matches openshift/enhancements#414 and doesn't change existing behavior
=> add current profile annotations to CVO manifests

bindata/network/openshift-sdn/sdn-ovs.yaml
Turns out we were shooting ourselves in the foot, because nodes and containers can have different numeric ids for openvswitch.
Fixes: RHBZ 1886127
=> Bug 1886127: [release-4.5] sdn-ovs: don't step on directory permissions.

bindata/network/ovn-kubernetes/ovnkube-master.yaml
=> Bug 1874638: Fixes missing nbctl daemon logging

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/ovn-kubernetes/006-ovs-node.yaml
There's a great Linux-specific feature that allows sending a signal
to a child process when its parent dies.  This allows strongly
"lifecycle binding" two processes together and avoiding the default
Unix behavior where the child process will just be reparented.
I think this will help avoid problems like
https://bugzilla.redhat.com/show_bug.cgi?id=1893362
where when the bash process exits, the tail process sticks around.
Perhaps something isn't removing the pid file?  In any case when
this pod is requested to terminate, the tail processes should die too.
=> Bug 1893362: Ensure tail processes exit with parent

bindata/network/kuryr/003-config.yaml, pkg/bootstrap/types.go, pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go, pkg/platform/openstack/networking.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/results.go, vendor/modules.txt
This commit adds the support to detect the Nodes
Network MTU so that the Namespace Networks use the
same MTU as the host.
=> Detect Nodes Network MTU on Installations with Kuryr

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Remove the ovn-db-pod=true label from matchLabels since the daemonset
pod selector doesn't need to select on that label.
=> Bug 1891716: Remove spurious label in the pod selector of the master daemonset.

bindata/network/multus/multus.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, manifests/image-references, pkg/network/multus.go
This commit adds a new init container for the deployment of the
egress-router-cni plugin to the hosts.
=> Add egress-router-cni init container

bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
CNO tries to create the objects defined in bindata's files in
lexicographic order, so we can rely on the secret being created when
this starts.
I don't know what happens if during an upgrade the CNO
fails to create the services, so it's probably a good idea not to
backport this to 4.6.
/assign @tssurya
=> Simplify kube-rbac-proxy startup script

pkg/network/kuryr.go
With the fact that change in the kuryr-config ConfigMap will trigger
recreation of all Kuryr pods, we can allow changing Kuryr options on the
running cluster. This commit implements that making sure that only
options directly affecting only kuryr.conf are considered safe to
apply.
=> Kuryr: Allow changes to KuryrConfig

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Add ovn-db-pod label on the master pods
Backport of #828 and #867 for 4.6.
=> Bug 1887462: Add ovn-db-pod label on the master pods

bindata/network/ovn-kubernetes/002-rbac.yaml, bindata/network/ovn-kubernetes/003-rbac-controller.yaml
OVN needs permission to list and watch slices, needed for dual stack.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
=> ovn rbac for endpoint slices

pkg/network/bootstrap.go, pkg/network/ovn_kubernetes.go
Waiting 280 seconds for the bootstrap to fail without any timeout is too
long and does not reflect to the user what is going on appropriatly.
adding a log that prints out every 15 seconds while waiting for the
master nodes to become avalible telling the user how many have been seen
and how many are expected.
Also changed a typo boostrapOVN() -> bootstrapOVN() and changed the
timeouts to a const so that they can be changted and be reflected in the
new logging without additional changes
Signed-off-by: Jacob Tanenbaum <jtanenba@redhat.com>
=> increasing logging when waiting for Masters during bootstrap for OVN

bindata/network/kuryr/alert-rules.yaml
When the number of available Ports on a Network is 0 the
InsuficientPortsOnNetwork and LimitedPortsOnNetwork alerts
are raised which could lead to different conclusions.
This commit fixes the issue by ensuring only the
InsuficientPortsOnNetwork is raised for this scenario.
=> Bug 1890630: Ensure LimitedPortsOnNetwork is only triggered when needed

pkg/network/ovn_kubernetes.go
IPsec CI is unable to start pods due to lack of openshift-ovn-kubernetes namespace.
=> Fix IPsec CI

bindata/network/ovn-kubernetes/001-crd.yaml
with the addition of egressfirewall in ovn-kubernetes the crd deployed
by the CNO needs to be updated.
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1905792
=> Bug 1905792: changes to egressfirewall CRD to accommodate DNS names

Dockerfile, Dockerfile.rhel7
PodNetworkConnectivityCheck resources were introduced in 4.6. Due to their highly experimental status at the time, the CRD was not installed by default, but instead managed by various controllers.
With the PR the PodNetworkConnectivityCheck CRD will be installed via the installation manifests. It is done in the network operator, as to better match the owner of the CRD.
=> Bug 1907454: install podnetworkconnectivitycheck crd

bindata/kube-proxy/001-rbac.yaml
`EndpointSliceProxying` is on by default in 1.20, so standalone kube-proxy now needs permission to list EndpointSlices
=> Bug 1909791: Standlone kube-proxy needs to list EndpointSlices now

pkg/controller/operconfig/operconfig_controller.go
This PR adds the  NetworkPolicy, EgressIP, and EgressFirewall to the CNO's related object list so they are collected across the entire cluster when a must-gather is run. 
The Egress IPs are collected under `cluster-scoped-resources` 
The NetworyPolicies and EgressFirewall's are collected on a per `namespace` basis
=> Bug 1906650: Add NetworkPolicy, EgressIP, and EgressFirewall to related-objects

bindata/network-diagnostics/network-check-source.yaml, docs/operands.md, pkg/controller/statusmanager/pod_status.go, pkg/controller/statusmanager/status_manager.go
Fixes three problems:
1. network-check-source cannot be scheduled to masters, but it was not marked as "non-critical", so if a cluster install fails before the worker nodes are created, you would see:
`level=error msg=Cluster operator network Degraded is True with RolloutHung: Deployment "openshift-network-diagnostics/network-check-source" rollout is not making progress - last change 2020-12-10T14:03:43Z `
in the logs
2. We didn't have a special-case "waiting for other operators" message for non-critical Deployments (as opposed to for non-critical DaemonSets) so even after fixing the above, you'd still see CNO as Progressing with
`Deployment "openshift-network-diagnostics/network-check-source" is not available (awaiting 1 nodes)`
which makes it sound like _we're_ doing something wrong, as …
=> Bug 1907644: fix up non-critical / Progressing status handling

bindata/network/ovn-kubernetes-ipsec/ovn-ipsec.yaml
Fix test case in e2e-ovn-ipsec-step-registry:
"Managed cluster should ensure control plane pods do not run in
best-effort QoS" by requesting cpu and memory resources.
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
=> Bug 1910097: ovn-ipsec: Add resource limits

bindata/kube-proxy/001-rbac.yaml
#926 was supposed to fix this but I actually added support for watching "v1.EndpointSlice", not "discoveryv1.EndpointSlice".
/hold
until I test it
=> Bug 1909791: Fix EndpointSlice addition to standalone kube-proxy RBAC role

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/ovn-kubernetes/006-ovs-node.yaml
#876 ("remove OVS daemonsets") has been postponed, but we should still at least get rid of the now-dead code for running OVS in a container since (a) in 4.7 we should *never ever* do that, and (b) apparently sometimes we can still get tricked into doing it.
We could get rid of a lot more dead code here but, eh, it's late in the release cycle.
=> Bug 1912577: get rid of support for running OVS in a container

pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
OVN IPsec currently uses esp=aes_gcm256 for phase2 algorithm.
The following RFCs describe the packet format for AEC-GCM ESP:
https://tools.ietf.org/html/rfc4106
https://tools.ietf.org/html/rfc2406
ESP Transport packets using AES-GCM should add the following
additional overhead to packets:
* ESP Header -  SPI:             4B
* ESP Header -  Sequence Number: 4B/8B
* ESP Header -  IV:              8B
* ESP Header -  Salt:            4B
* ESP Trailer - Pad:             <4B
* ESP Trailer - Pad Length:      1B
* ESP Trailer - Next Header:     1B
* ESP Trailer - ICV:             8B/12B/16B
This gives a worst-case of 46B of packet overhead.
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
=> Bug 1908775: ovn-ipsec: Adjust MTU to account for additional ESP overhead

pkg/controller/operconfig/operconfig_controller.go, pkg/controller/statusmanager/status_manager.go
PR: https://github.com/openshift/cluster-network-operator/pull/873 was missing a correct resource name for `networks.operator.openshift.io` to be exported properly to a must-gather. PR: https://github.com/openshift/cluster-network-operator/pull/877 tried fixing this, but was missing a piece to be able to pass the CI upgrade jobs, which this PR now adds. 
Essentially upgrade jobs upgrade from HEAD to HEAD + patch. So with #873: HEAD now has a resource name which is incorrect, if we now want to fix this we will incorrectly delete `networks.operator.openshift.io` on such upgrades. This is not yet a problem for any OpenShift release, since #873 is only on master. The only fix I could think of was to explicitly skip the deletion of the CRD for now. Once this PR has merged we can then delete …
=> Bug 1914932: Put correct resource name in relatedObjects

pkg/util/proxyconfig/no_proxy.go, pkg/util/proxyconfig/no_proxy_test.go
Since 4.4 etcd no longer has a DNS dependency. Currently, we are still passing etcd records to the proxy config which should be removed.
This PR removes the unused etcd records from NoProxy which can result in sync issues with MCD.
depends on: https://github.com/openshift/machine-config-operator/pull/2315
related to: https://github.com/openshift/installer/pull/4518
=> Bug 1909502: pkg/util/proxyconfig: remove unused etcd records from proxy config

bindata/network/ovn-kubernetes/ipsec.yaml
In the case of failure of ipsec daemons, add liveness
probe to detect so that the kubelet can restart the
container.
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
=> Bug 1914402: ipsec: Add liveness probe

docs/operands.md
(mostly because I noticed that the indentation was wrong in the sections that were supposed to be `<pre>`)
=> Minor fixups to docs/operands.md

bindata/network/ovn-kubernetes/ovnkube-master.yaml, pkg/bootstrap/types.go, pkg/controller/operconfig/cluster.go, pkg/controller/operconfig/operconfig_controller.go, pkg/names/names.go, pkg/network/bootstrap.go, pkg/network/ovn_kubernetes.go
PR #896 tried to unblock the assisted installer team by reverting commit a14003d from #421. However the level entropy introduced by removing that commit can in some situations bring the OVN cluster down. Essentially, if the amount of master nodes are not met during the initial cluster deployment: we risk rolling out successive versions of the OVN DB cluster in a very short time span. Since the NB / SB DB raft clusters does not have the time to stabilize before the new version rolls out, we risk doing bad things in some cases. 
This PR does things as before, except we don't block the cluster deployment if the master node replica count is not met. Thus we will still wait for all master nodes that should be up, are up. However if they are not, we proceed with the deployment of the initial …
=> Bug 1903660: Don't error when expected master node amount is not met 

bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/ovn-kubernetes/006-ovs-node.yaml
Now that OVS has moved to the node in 4.7, the daemonset pods have
less to do. Looking at some production systems data, the OVS pod
uses about 5 millicores on 4.6 and less than 1 millicore on 4.7.
Reduce the request from 100m to 15m to retain some headroom for users
upgrading from 4.6 and running the new pod on the old nodes. In a
future release the daemonset will be fully removed.
/hold
Testing with other PRs
=> Bug 1920159: Reduce CPU requests of ovs daemonset

bindata/network-diagnostics/000-ns.yaml
If the default node selector is not overridden then during upgrade the
network never comes up because the network diagnostics assumes the
network-checker pods are on all nodes and if the default node selector
is present and not overridden they could be restricted.
=> Bug 1920769: override the default node-selector for network-connectivity check

bindata/network/ovn-kubernetes/ipsec.yaml
ovn-ipsec pods have the following benign error messages on startup. This PR removes these error messages.
+ /usr/sbin/ipsec --checknflog
**chroot: cannot change root directory to '/host': No such file or directory**
nflog ipsec capture disabled
+ /usr/libexec/ipsec/pluto --leak-detective --config /etc/openvswitch/ipsec.conf --logfile /var/log/openvswitch/libreswan.log
+ OVS_LOGDIR=/var/log/openvswitch
+ OVS_RUNDIR=/var/run/openvswitch
+ OVS_PKGDATADIR=/usr/share/openvswitch
+ /usr/share/openvswitch/scripts/ovs-ctl --ike-daemon=libreswan start-ovs-ipsec
**2020-12-08T15:41:54Z |  1  | ovs-monitor-ipsec | INFO | Restarting LibreSwan
Redirecting to: systemctl restart ipsec.service
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is …
=> Bug 1905730: ipsec: Suppress benign error messages on startup of ovs-monitor-ipsec

bindata/network-diagnostics/000-ns.yaml
commit cc38b9510e828462ab740bbffe5ed834c8a442d0 adds an annotation
section to the namespace definition for openshift-network-diagnostics.
The spacing was wrong so the override is ignored. Correctly add the
annotation as part of the metadata field so the correct propogation will
happen
=> Bug 1920769: Fix the spacing for the node-selector override annotation

bindata/network-diagnostics/network-check-source.yaml, bindata/network-diagnostics/network-check-target.yaml
The resource requests made by pods in the openshift-network-diagnostics
namespace is way too high, this can cause the kube-scheduler to
needlessly error in deploying these pods as the documentation states
"The scheduler ensures that, for each resource type, the sum of the
resource requests of the scheduled Containers is less than the capacity
of the node."
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits
this is the memory usage I see on a running cluster
```
$ kubectl top pod  -n
openshift-network-diagnostics
NAME                                    CPU(cores)   MEMORY(bytes)
network-check-source-744c4f7fbf-djmbl   3m           36Mi
network-check-target-28zd8              0m           10Mi
network-check-target-5c8dd              0m …
```
=> Bug 1924383: update the resource requests made by pods in openshift-network-diagnostics namespace

bindata/kube-proxy/001-rbac.yaml
I am not sure what minimum required permissions apply for this resource by kube-proxy, so I've applied `create` / `patch` / `update` , though one or multiple might be superfluous. 
Do you have any input on this @aojea / @danwinship ?
=> Bug 1918375: Add tokenreviews permissions for kube-proxy

bindata/network/ovn-kubernetes/006-ovs-node.yaml
In cases where we run ovs in a container, sometimes ovs-vswitchd
will take a bit longer to come up as a daemon. In this case liveness
probes will start failing if the initial delay is too small and this
will prevent ovs-daemons container from coming up. This fixes the
initial delay parameter to make sure liveness and readiness probes
start after giving ovs a chance to start.
=> Bug 1924137: Increase the initialDelaySeconds for liveness and readiness probes

bindata/network/kuryr/003-config.yaml
Kuryr has a mechanism in place that attempts to autodetect the primary
trunk interface that the kuryr-cni should bind the subports to. The
mechanism checks if the interface that's configured as link_iface exists
and if not attempts to do autodetection by looking where kubelet's
bound.
We hardcoded `link_iface=ens3` in the config anyway, assuming that if in
some configurations interface is named differently we'll just do the
autodetection.
The problem with that approach is when there are multiple interfaces and
they're swapped, we'll just keep using the wrong one never attempting
autodetection. And we were told that this sometimes happens.
This patch removes the [binding]link_iface from the kuryr.conf in order
to always force the autodetection and make sure kuryr-cni will bind fine
even if …
=> Bug 1921184: Kuryr: Let Kuryr autodetect primary CNI interface

bindata/network/ovn-kubernetes/ipsec.yaml
Sleep messages are useless but printed in ovn-ipsec log every minute
=> Suppress sleep message in ovn-ipsec container

pkg/controller/operconfig/operconfig_controller.go, pkg/controller/statusmanager/status_manager.go
4.6 backport of #945 
Given that 4.6 supports egress IP, egress firewall, etc, and that those objects have been added to "related objects" in 4.7, we need to add them in 4.6 too, since: on a downgrade those CRDs would be deleted. This is not bad since we'll have them in the must-gathers on 4.6. 
I am also removing the skip in `status_manager.go` (see: https://github.com/openshift/cluster-network-operator/blob/master/pkg/controller/statusmanager/status_manager.go#L99-L102) on the CRD `network.operator.openshift.io`, since on a 4.6 -> 4.5 - once we have the 4.5 backport in - it should not get deleted anymore since that CRD will be in the "related objects" in both versions.
/assign @squeed @juanluisvaladas @danwinship
=> Bug 1916601: guard against the deletion of the network CRD: `network.operator.openshift.io`

bindata/network/kuryr/003-config.yaml, pkg/bootstrap/types.go, pkg/network/kuryr.go, pkg/platform/openstack/kuryr_bootstrap.go
Turns out in UPI there are no Machine objects so we still need to
manually tell Kuryr the ID of the Neutron subnet the masters and workers
are running in. This commit makes sure that's done.
=> Bug 1927244: Kuryr: Always set worker_nodes_subnets

bindata/network/multus/multus.yaml
Without setting the gracePeriodSeconds lower, a pod in the Multus daemonset can take ~35 seconds to exit.
When setting to 10 seconds, the pods will exit in approximately 17 seconds.
~Additionally, this sets the maxUnavailable to 10%, which allows for a larger amount of pods to be upgraded at once
in larger deployments.~
=> Bug 1920209: The pods in the Multus daemonset should exit in a reasonable time during an upgrade.

go.mod, go.sum, vendor/github.com/gogo/protobuf/proto/text_parser.go, vendor/golang.org/x/sync/singleflight/singleflight.go, vendor/golang.org/x/tools/go/ast/astutil/util.go, vendor/golang.org/x/tools/imports/forward.go, vendor/golang.org/x/tools/internal/event/core/event.go, vendor/golang.org/x/tools/internal/gocommand/invoke.go, vendor/golang.org/x/tools/internal/gocommand/version.go, vendor/golang.org/x/tools/internal/imports/mod.go, vendor/golang.org/x/tools/internal/imports/mod_cache.go, vendor/modules.txt
This commit udpates the protobuf version used in CNO to 1.3.2
to address the CVE-2021-3121
=> Bug 1924425: Update protobuf version to address CVE-2021-3121

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Column diffs only work when the entire cluster is upgraded to ovsdb 2.15, so for now, ensure they're always disabled.
/cc @dcbw
/cc @numansiddique
=> Bug 1908916: disable ovsdb column diffs if supported

manifests/0000_70_cluster-network-operator_03_deployment.yaml
Previously, we used to parse the kubelet's kubeconfig to get the URL to the apiserver. But this is a strange coupling.
In openshift/machine-config-operator#2232 we added a special environment file that emulates the in-cluster config environment variables. So now we can just source that if it exists.
Fallback to the old mode for now, mostly out of paranoia for upgrade / downgrade.
=> cmd: stop using URL_ONLY_KUBECONFIG

pkg/platform/openstack/kuryr_bootstrap.go
The ports created for master VMs created on day-2 operation
have a different name pattern than the ones created on a
regular installation making it impossible for the CNO to
identify it and create a new member. This commit fixes the
issue by takeing into account the extra name pattern.
=> Bug 1933269: Include LB members for Machines created on day-2 operation

bindata/network-diagnostics/network-check-target.yaml
rolling update default is 1 and can be inefficient with
larger clusters
=> Bug 1933179: Use 10% for nw-check-target maxUnavailable

bindata/network/openshift-sdn/sdn.yaml
default is 1 and can be inefficient with larger clusters
=> Bug 1933173: Use 10% for sdn maxUnavailable for rolling update

bindata/network/ovn-kubernetes/ovnkube-node.yaml
rolling update default is 1 and can be inefficient with
larger clusters
=> Bug 1934711: Use 10% for ovnkube-node for maxUnavailable

bindata/network/network-metrics/001-daemonset.yaml
This PR configures the network-metrics DS to use the system-node-critical
priorityClass. This is a result of layered products on OSD/OCP like
RHOAM whom have resource hungry components and have a policyClass set at
1000000. There have been cases where RHOAM component scheduling is being
prioritized against openshift core components like network-metrics.
This PR resolves this issue and protects core.
=> OSD-6600 network-metrics missing priorityClass

pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go, pkg/util/k8s/kubeproxy.go
Turn it on default (protected by RBAC).  Allows a user to configure this post deployment.
Verified we RBAC protect this.  Because it's rbac protected (like kubelet and apiserver) on by default is acceptable.
```
curl https://localhost:9101/debug/pprof -k -H "Authorization: bearer $( oc sa get-token -n openshift-sdn default )"
Handling connection for 9101
Forbidden (user=system:serviceaccount:openshift-sdn:default, verb=get, resource=, subresource=)
```
=> config: Set enable-profiling true by default and allow `enable-profiling` as a proxy argument

bindata/network/openshift-sdn/sdn-ovs.yaml
default is 1 and can be inefficient with larger clusters
=> Bug 1933174: Use 10% for ovs maxUnavailable for rolling update

bindata/network/kuryr/alert-rules.yaml
In OpenStack world, a quota count of -1 means unlimited.
Therefore we need to change the rule that says "Running out of quota",
and add a condition "kuryr_quota_free_count > 0" so we raise the alert
when the resource is positive and inferior to 10.
BZ#1937005
Signed-off-by: Emilien Macchi <emilien@redhat.com>
=> Bug 1937005: kuryr/alerts: change the rule for free count

bindata/network/ovn-kubernetes/ipsec.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go
OVN-Kubernetes IPsec was originally designed to not allow
runtime enable of IPsec as per the enhancment proposal. This
commit removes this restriction.
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
=> SDN-1571 ipsec: Allow enablement/disablement at runtime

pkg/platform/openstack/kuryr_bootstrap.go
Due to wrong place of usage of '+' the current regex that
handles Ports names allows the following name of ports:
'ostest-7g27t-bootstrap-porttt' and not
'ostest-7g27t-master-port-10', which is wrong as the
installer supports the latter, but not the former.
This commit fixes the issue by including '+' in the
correct place.
=> Fix possible name patterns on regex

pkg/platform/openstack/kuryr_bootstrap.go
The ports created for master VMs created on day-2 operation
have a different name pattern than the ones created on a
regular installation making it impossible for the CNO to
identify it and create a new member. This commit fixes the
issue by takeing into account the extra name pattern.
=> Bug 1935473: Include LB members for Machines created on day-2 operation

bindata/network/openshift-sdn/002-rbac.yaml
The SDN pod will need to read these, like ovn already does.
Prereq for testing https://github.com/openshift/sdn/pull/271
=> sdn: Add list/watch RBAC for endpointslices to openshift-sdn

pkg/network/cluster_config.go, pkg/network/cluster_config_test.go, pkg/network/render.go, pkg/network/render_test.go
Not sure what's happening with this wrt 4.7, and it needs a bunch of additional testing, but...
This fixes CNO to let you flip a single-stack configuration to dual-stack, and vice versa.
=> Allow dual stack migration

pkg/controller/statusmanager/status_manager_test.go
This PR fixed golangci-lint violations in status_manager_test.go which
would make all PR fail on the current CI. I'm ignoring staticcheck on
that file rather than ignoring only the specific SA1019 as per this [1]
issue on golangci-lint.
[1] https://github.com/golangci/golangci-lint/issues/741
=> Bug 1937452: Fix golangci-lint violations

bindata/network/ovn-kubernetes/006-ovs-node.yaml
Default settings are inefficient on larger clusters. This PR changes
~~* `ovnkube-master` maxUnavailable to 33% (one node at a time, third of control plane masters)~~
* `ovs-node` - 10% (as it runs on workers as well)
=> Bug 1938920: Set maxUnavailable for ovs-node daemonset

bindata/network/multus/multus.yaml, bindata/network/network-metrics/001-daemonset.yaml
Being that we have on-host OVS, this shouldn't cause connectivity issues for the nodes to go not ready while Multus upgrades on 10% of the nodes.
=> Bug 1933159: The Multus daemonset should handle 10% maxUnavailable 

bindata/network/ovn-kubernetes/ipsec.yaml
Fixes issues with:
```
:  [sig-arch] Managed cluster should only include cluster daemonsets that  have maxUnavailable update of 10 or 33 percent  [Suite:openshift/conformance/parallel] expand_less
fail [github.com/onsi/ginkgo@v4.7.0-origin.0+incompatible/internal/leafnodes/runner.go:113]: Mar 16 14:14:30.850: Daemonsets found that do not meet platform requirements for update strategy:
expected daemonset openshift-ovn-kubernetes/ovn-ipsec to have maxUnavailable 10% or 33% (see comment) instead of 1
```
eg https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1023/pull-ci-openshift-cluster-network-operator-master-e2e-ovn-ipsec-step-registry/1371816352179818496
@markdgray @trozet @abhat
=> ovn/ipsec: set maxUnavailable to 10%

pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
The current logic attempts to restore the old version of the daemonset if shouldUpdateOVNK returns false, but the replacement is done against a list that does not contain the ovnk rendered objects yet.
=> Bug 1939060: OVN Upgrade: fix upgrade order of node and master

pkg/network/ovn_kubernetes.go, pkg/network/semver.go, pkg/network/semver_test.go
=> ovnkube: better logging for upgrades/downgrades

bindata/network/additional-networks/crd/001-crd.yaml, bindata/network/multus-admission-controller/003-webhook.yaml, bindata/network/openshift-sdn/001-crd.yaml
We were still using the v1beta1 versions of the APIs for the SDN and Multus CRDs and multus-admission-webhook.
CRD diffs are best viewed with `-w`
Relevant changes:
- the CRD for `OverlappingRangeIPReservation` had claimed `preserveUnknownFields: true` before, but based on https://github.com/openshift/whereabouts-cni/blob/master/pkg/api/v1alpha1/overlappingrangeipreservation_types.go that does actually seem to be needed.
- multus-admission-webhook now has to explicitly specify some things that were previously defaulted/guessed in v1beta1
=> Update remaining CRDs and webhooks to v1

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Now that the OpenFlow flows in the shared bridge are fixed and we have
also fixed the transport is closing bug, move back to shared gw mode.
=> Re-enable shared gateway mode

bindata/network/ovn-kubernetes/ovnkube-node.yaml
Description
modify openvswitch mount volume so it will mount ovsdb inside ovn-kube container so it can be consumed by multi-gather tool
Type of change
Enhance debugging of openshift cluster.
How Has This Been Tested?
created Openshift cluster then run
drop in ovnkube node and check the mount is done correctly
[root@ci-ln-kzbqhr2-f76d1-mw92h-worker-d-hnqqd ~]# ls -l /etc/openvswitch/
total 200
-rw-r-----. 1 800 801 129157 Mar 23 14:49 conf.db
-rw-r--r--. 1 800 801    163 Mar 12 23:22 default.conf
-rw-r--r--. 1 800 801     37 Mar 23 12:49 system-id.conf
=> Bug 1916809: mount node ovs db for multi-gather gather_network_logs

bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/multus/multus.yaml
All containers should make reasonable cpu and memory requests.
Correct a few places where they were still missing.
Supercedes #925 (some of which merged elsewhere)
=> Bug 1905331: Set requests on multus components

bindata/network/openshift-sdn/host-network/ns.yaml, bindata/network/openshift-sdn/host-network/resourcequota.yaml, bindata/network/ovn-kubernetes/host-network/ns.yaml, bindata/network/ovn-kubernetes/host-network/resourcequota.yaml, pkg/controller/add_networkconfig.go, pkg/controller/ingressconfig/ingressconfig_controller.go, pkg/names/names.go
This PR adds support for 
- creating the host network namespace via bindata manifests
- watching the ingress controller objects and updating the labels on host network namespace.
=> Allow from router support in CNO

bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/network/ovn_kubernetes.go
This change allows to export network flows metadata by using
NetFlow/SFlow/IPFIX in OVN-Kubernetes clusters.
In order to use it:
* oc edit networks.operator.openshift.io
* Add exportNetworkFlows options as depicted in
https://github.com/openshift/api/pull/846.
=> Add support for exporting network flows

bindata/network/kuryr/002-crds.yaml
This includes CRD changes regarding a new upstream feature - being able
to set Octavia listeners timeouts for LBs created to support Services.
=> Kuryr: Update CRDs from upstream

README.md, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, go.sum, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Changes for [SDN-1364](https://issues.redhat.com/browse/SDN-1364)
See [Enhancement](https://github.com/openshift/enhancements/pull/617) for
details on the changes
1. Allows `ovn-kubernetes.go` to digest the new API changes 
2. Adds a new sidecar container to the `ocnkube-node` daemonset named acl-audit-logging
It does the following 
- Pipes the audit logs(which are persisted to the node at `var/log/ovn/` ) to stdout so they can be consumed by the logging 
stack if desired 
- Handles log rotation since COREOS doesn't include logrotate modules
=> [SDN-1364] Update CNO for OVN acl audit logging

pkg/network/cluster_config.go, pkg/network/cluster_config_test.go
I really don't know if this is a real problem, but it is always better to copy this values instead of passing the references
Signed-off-by: Antonio Ojea <aojea@redhat.com>
=> copy the service network slice

pkg/names/names.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
OVN kubernetes dual-stack conversion
Add a new annotation to the OVN kubernetes daemonsets, ovnkube-master
and ovnkube-node, indicating the IP family mode configured:
- single-stack
- dual-stack
This annotations allow to automate the conversion of the cluster from
single-stack to dual-stack and viceversa, since the change in the
annotation triggers a rollout of the daemonset.
Because the conversion requires to update the master daemonsets first,
we add the same logic used to manage the versions upgrades to this
process. The dual-stack conversion also blocks the upgrade, so both
are exclusive.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
=> automatic dual-stack conversion

README.md, pkg/network/additional_networks.go, pkg/network/additional_networks_test.go
This change sets 'ips' in 'capabilities' in static IPAM CNI
config if no ip address in staticIPAM config because user will
supply ip address through pod annotation.
=> Add capabilities in simpleMacvlan's staticIPAM config

.gitignore, bindata/network-diagnostics/network-check-target.yaml, cmd/cluster-network-check-target/main.go
#1046 imported hello-openshift as cluster-network-check-target, but if we're going to have our own copy we should customize it a little...
(the gitignore change fixes spurious error messages where it thinks it's supposed to be ignoring `cmd/cluster-network-check-target/` rather than just the top-level `cluster-network-check-target` binary)
=> Bug 1949099: Fix up network-check-target

bindata/egress-router/000-nad.yaml, bindata/egress-router/001-deployment.yaml, pkg/client/client.go, pkg/controller/add_networkconfig.go, pkg/controller/egress_router/egress_router_controller.go, pkg/controller/statusmanager/status_manager.go
This PR adds the egress router controller for managing such objects.
It'll be cherry-picking #852, which adds CRD/Types for egress routers
objects. It's taking PKI Controller as a model to be built upon.
Signed-off-by: Daniel Mellado <dmellado@redhat.com>
=> Bug 1948592: Add Egress Router Controller

bindata/kube-proxy/000-ns.yaml, bindata/kube-proxy/kube-proxy.yaml, bindata/network-diagnostics/000-ns.yaml, bindata/network-diagnostics/network-check-source.yaml, bindata/network-diagnostics/network-check-target.yaml, bindata/network/kuryr/000-ns.yaml, bindata/network/kuryr/005-daemon.yaml, bindata/network/kuryr/006-controller.yaml, bindata/network/kuryr/010-admission-controller.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/multus-networkpolicy/multus-networkpolicy.yaml, bindata/network/multus/000-ns.yaml, bindata/network/multus/003-dhcp-daemon.yaml, bindata/network/multus/multus.yaml, bindata/network/network-metrics/001-daemonset.yaml, bindata/network/openshift-sdn/000-ns.yaml, bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/openshift-host-network-ns.yaml, bindata/network/openshift-sdn/sdn-ovs.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/000-ns.yaml, bindata/network/ovn-kubernetes/006-ovs-node.yaml, bindata/network/ovn-kubernetes/ipsec.yaml, bindata/network/ovn-kubernetes/openshift-host-network-ns.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, manifests/0000_70_cluster-network-operator_00_namespace.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
=> Add management workload annotations

pkg/controller/operconfig/operconfig_controller.go, pkg/network/cluster_config.go, pkg/network/render.go, pkg/network/render_test.go
Phase1, Users add the spec.migration feild in network.operator
CR. The only changes the migration field under the status of
Network.config. It will trigger MCO to provision ovs-configuration
service on every node and reboot. After rebooting, openshift-sdn
will use br-ex as L3 gateway.
Phase2, Users update the spec.networkType in network.config.
CNO starts to swap the network provider for the cluster to ovnkube.
Users need to manually reboot all nodes to make all pods attach to
the new cluster network.
=> Bug 1937594: Split SDN migration into 2 phase

pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go
`EndpointSlice` is no longer optional in 1.21. However, the only feature gate we need to disable is `EndpointSliceProxying` anyway.
blocks https://github.com/openshift/sdn/pull/267
=> Bug 1952079: Don't try to disable the EndpointSlice feature gate

pkg/controller/ingressconfig/ingressconfig_controller.go
The default ingress config controller on certain platforms such as
vsphere and baremetal implicitly has HostNetwork as endpoint
publishing strategy. So the spec for the default controller on these
platforms will not have an endpointPublishingStrategy object. But
the reconciled object's status fields show the right value for the
type. This change is to rely on status field than the spec field
for setting the host-network traffic related labels.
=> Bug 1942555: Rely on status for ingress controller for endpointPublishingStrategy

Makefile, go.mod, go.sum, manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, profile-patches/ibm-cloud-managed/0000_70_cluster-network-operator_03_deployment.yaml-patch, vendor/github.com/openshift/build-machinery-go/README.md, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk, vendor/modules.txt
Part 2 of cluster profiles support for IBM Cloud:
- Bumps github.com/openshift/build-machinery-go to latest version
- Adds targets to Makefile for updating/verifying profile patches
- Adds profile patch for ibm-cloud-managed
On IBM Cloud the network operator needs to run on worker nodes, thus the
master node selector needs to be removed from the operator deployment
manifest.
=> Bug 1948718: IBM Cloud manifest profile patch

bindata/egress-router/001-deployment.yaml, bindata/kube-proxy/kube-proxy.yaml, bindata/network-diagnostics/network-check-source.yaml, bindata/network-diagnostics/network-check-target.yaml, bindata/network/kuryr/005-daemon.yaml, bindata/network/kuryr/006-controller.yaml, bindata/network/kuryr/010-admission-controller.yaml, bindata/network/multus-admission-controller/admission-controller.yaml, bindata/network/multus-networkpolicy/multus-networkpolicy.yaml, bindata/network/multus/003-dhcp-daemon.yaml, bindata/network/multus/multus.yaml, bindata/network/network-metrics/001-daemonset.yaml, bindata/network/openshift-sdn/controller.yaml, bindata/network/openshift-sdn/sdn.yaml, bindata/network/ovn-kubernetes/ipsec.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml
As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged please
=> Rename workload annotations

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, hack/KIND_CNO.md, hack/gateway-mode.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go
- if a configMap openshift-ovn-kubernetes/gateway-mode-config
has a value of "local" or "shared", it will be honored. Otherwise
the default (currently "shared") is used.
=> Bug 1948582: Allow for local gateway mode to be configured

manifests/0000_70_cluster-network-operator_02_rbac.yaml
Removing the reference to v1beta1 clusterrolebindings.
=> Bug 1947795: Remove reference to v1beta1 API

pkg/apply/apply.go
This prevents the operator to flip flop on Degraded state
if there is a concurrent update by other external actor.
=> Bug 1939726: Enclose ApplyObject on RetryOnConflict

pkg/names/names.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/1034
We backported the ovnkube bits to 4.7 as part of https://github.com/openshift/ovn-kubernetes/pull/460
Add a new annotation to the OVN kubernetes daemonsets, ovnkube-master
and ovnkube-node, indicating the IP family mode configured:
- single-stack
- dual-stack
This annotations allow to automate the conversion of one cluster from
single-stack to dual-stack and viceversa, since the change in the
annotation triggers a rollout of the daemonset.
Because the conversion requires to update the master daemonsets first,
we add the same logic used to manage the versions upgrades to this
process. The dual-stack conversion also blocks the upgrade, so both
are exclusive.
=> Bug 1956352: [4.7] OVN kubernetes dual-stack conversion

bindata/network/multus/multus.yaml
In OpenShift, we have a feature for Multus known as "namespace isolation" this allows pods to only
have annotations for additional networks that refer to the same namespace as a given pod. The expection
is the default namespace, where net-attach-defs in the default namespace can be referred to by pods
in any namespace.
Sometimes, operators need to manage their own net-attach-defs, and dumping them all into the default
namespace is not ideal. This extends the CNO to use the Multus "--global-namespaces" option, and sets
for the openshift-multus, as well as the SRIOV network operator namespace to be used.
=> Bug 1954755: Multus configuration should allow for net-attach-defs in certain namespaces to be used across namespaces

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
This parameter was added in https://github.com/openshift/cluster-network-operator/commit/14a5e41bb9b8fedaec0037b8551be4888e0ac821
and scrambles the egress IP feature for OVN-Kubernetes. The reason is
that egress IP for OVN-Kubernetes relies on SNAT-ing pod traffic to the
egress IP on the cluster's GW router when traffic exists the nodes (so
that the server sees the egress IP addresses as source IP addresses). This
flag is used for ICNI traffic where the goal is to SNAT egress traffic
to the pod's IP (so that the server sees the pod IP addresses as source
IP addresses). Naturally, these two features don't go very well
together.
The reason was that we were thinking that customer ** would be moving to
shared GW mode in 4.8 and that we would need to enable ICNI pod SNAT-ing.
This is not the …
=> Bug 1958126: Remove OVN "--disable-snat-multiple-gws" parameter

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
This is 100% safe; the metrics endpoint is behind kube-rbac-proxy.
/cc @dcbw
=> Bug 1959406: ovn-kube: enable pprof on the metrics endpoint

bindata/network/multus/multus.yaml, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
This separates into two daemonsets, one for Multus itself, and one for all other CNI binary and configuration installation.
The goal is to improve the time it takes a node to become ready, as images are pulled serially.
=> Bug 1949677: The Multus daemonset should be separate other CNI binary installation

bindata/network/ovn-kubernetes/ipsec.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go
Due to https://bugzilla.redhat.com/1960711, IPsec cannot be enabled
at runtime. IPsec requires an additional 46B overhead for packet headers,
therefore we will need to be able to dynamically adjust the MTU at
runtime before enabling this feature.
This reverts commit 59a50f93ea671564412334ee181c0404588f2cb5.
=> Bug 1960711: Revert "ipsec: Allow enablement/disablement at runtime"

bindata/network/ovn-kubernetes/004-config.yaml, pkg/network/ovn_kubernetes_test.go
ovn-kubernetes has changed to use a flag to enable egressFirewall, the cno needs to use that flag
=> Bug 1954773: update the cno to use the egressfirewall flag

manifests/0000_70_cluster-network-operator_01_egr_crd.yaml
Copy vendored file to manifests, this was missing in: https://github.com/openshift/cluster-network-operator/pull/1094
/assign @squeed @msherif1234
=> Bug 1951158: Update egress router CRD from vendor to manifests

pkg/network/openshift_sdn.go
Follow-up to #1059.
* `pkg/network/openshift_sdn.go` (`bootstrapSDN`): Delete an unnecessary check for nil `infraConfig`.  Check if `infraConfig.Status.PlatformStatus` is nil, which is possible if the cluster was originally installed using OpenShift 4.1 and then upgraded.
=> Bug 1825219: Fix nil checks in bootstrapSDN

bindata/egress-router/000-nad.yaml
there was JSON format issue leading to this error
```
0602 19:44:10.396859 1 egress_router_controller.go:228] could not apply egress router object: ApplyObject of (k8s.cni.cncf.io/v1, Kind=NetworkAttachmentDefinition) test2/egress-router-cni-nad was unsuccessful: admission webhook "multus-validating-config.k8s.io" denied the request: configuration string is not in JSON format
E0602 19:44:10.396873 1 egress_router_controller.go:131] ApplyObject of (k8s.cni.cncf.io/v1, Kind=NetworkAttachmentDefinition) test2/egress-router-cni-nad was unsuccessful: admission webhook "multus-validating-config.k8s.io" denied the request: configuration string is not in JSON format
```
used Json linter to find the format issue and confirm the fix
```
{ …
```
=> Bug  1951158: Fix generated JSON format

bindata/network-diagnostics/network-check-source.yaml, bindata/network-diagnostics/network-check-target.yaml
Priority classes for all components in openshift namespaces have been mandated and the network-check-source and network-check-target were missing it. This sets the priority to allow these components to be preempted by user workload and OOMKilled.
Signed-off-by: Ben Pickard <bpickard@redhat.com>
=> Bug 1954870: Add priorityClass to allow user load to preempt tests

bindata/egress-router/001-deployment.yaml
egress CNI pod command is missing 
Unit-test
```
oc new-project test
```
```
oc create -f test.yaml 
egressrouter.network.operator.openshift.io/egress-router-test created
```
```
oc get all
NAME                                                READY   STATUS    RESTARTS   AGE
pod/egress-router-cni-deployment-5b9f59477d-96t76   1/1     Running   0          13s
NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/egress-router-cni-deployment   1/1     1            1           13s
NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/egress-router-cni-deployment-5b9f59477d   1         1         1       13s
```
```
oc describe network-attachment-definition egress-router-cni-nad 
Name: …
```
=> Bug 1968567: egress router CNI command is missing

bindata/network/openshift-sdn/006-flowschema.yaml, bindata/network/ovn-kubernetes/007-flowschema.yaml
PR https://github.com/openshift/cluster-network-operator/pull/920 added flowcontrol to 4.7 with `v1alpha1` and PR https://github.com/openshift/cluster-network-operator/pull/937 bumped flowcontrol on 4.8 to `v1beta1`. Given the kube-apiserver bump between these version, and the fact that a 4.8 kube-apiserver does not support `flowcontrol.apiserver.k8s.io/v1alpha1` at all: all upgrades from 4.7 -> 4.8 result in a degraded network operator (because the network operator upgrades after the kube-apiserver, so we'll have a 4.7 network operator talking to a 4.8 kube-apiserver) - and subsequently a failed upgrade job. 
The original concern with bumping 4.7 flowcontrol to `v1beta1` was: https://bugzilla.redhat.com/show_bug.cgi?id=1913399#c1, but that concerns itself only with 4.7 -> 4.6 downgrades, …
=> [release-4.7] Bug 1967388: annotate flowcontrol with `networkoperator.openshift.io/ignore-errors`

manifests/image-references
We need to reference the network-tools imagestream from an
operator for it to be a part of the payload.
=> Bug 1967933: Add network-tools to image-stream

bindata/network/openshift-sdn/sdn.yaml, pkg/bootstrap/types.go, pkg/network/bootstrap.go, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go, pkg/network/render.go
Add daemonset to drop icmp frag needed packets received from other nodes in the cluster
Add logic to SDN to determine what platform we are running on.
(cherry picked from commit 401ea0cff5c967151e101bd97b4ac63cc46ac3e7)
Bug 1825219: Fix nil checks in bootstrapSDN
(cherry picked from commit 89cf5ffdbb34c0f43b86515e133becf2b92a8c45)
=> Bug 1967994: Backport daemonset to drop icmp frag needed packets received from other nodes in the cluster to Rel 4.7

bindata/network/openshift-sdn/sdn-ovs.yaml
The ovs-save script restoring flows when running OVS in a container on 4.6 defaults to OpenFlow14, which is not supported by openshift-sdn. This leads to flow restore errors on upgrades from 4.5 and hence a larger downtime window. See: https://github.com/openshift/sdn/pull/306#issuecomment-849773314
Force the script to use OpenFlow13, which is the only version of OpenFlow openshift-sdn supports.
=> Bug 1970453: Replace to correct OpenFlow version when replacing flows

pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go, pkg/util/k8s/kubeproxy.go
Cherry pick of #988 (#1129 was for 4.7 release)
=> [release-4.6] Bug 1972587: config: Allow enable-profiling to be used to set profiling

bindata/network/openshift-sdn/sdn.yaml, pkg/bootstrap/types.go, pkg/controller/operconfig/operconfig_controller.go, pkg/network/bootstrap.go, pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go, pkg/network/render.go
Add daemonset to drop icmp frag needed packets received from other nodes in the cluster
Add logic to SDN to determine what platform we are running on.
(cherry picked from commit 401ea0cff5c967151e101bd97b4ac63cc46ac3e7)
Bug 1825219: Fix nil checks in bootstrapSDN
(cherry picked from commit 89cf5ffdbb34c0f43b86515e133becf2b92a8c45)
=> Bug 1851549: Backport daemonset to drop icmp frag needed packets received from other nodes in the cluster to Rel 4.6

bindata/network/kuryr/003-config.yaml, bindata/network/kuryr/003-credentials.yaml, bindata/network/kuryr/006-controller.yaml
This commit moves options filled with OpenStack credentials from a
ConfigMap to a Secret and makes sure kuryr-controller gets it mounted.
=> Bug 1975016: Kuryr: Store OpenStack credentials in a secret

bindata/network/ovn-kubernetes/ovnkube-master.yaml
enable ovs column diffs feature for release 4.9
Note: after this commit is merged we no longer can downgrade to older releases.
New ovsdb-server will be able to read old database format, but older ovsdb-server will fail to read database created by this new OVS version.
changes in ovs2.15: https://github.com/openvswitch/ovs/blob/0b3ff31d35f56c9401d868613581b4d35bb42724/NEWS#L17
package details : https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1584628
=> Bug 1962951: enable ovs column diffs feature

bindata/network/kuryr/alert-rules.yaml
Adds critical alerts for load balancers without
members or with error for more than 5 minutes. Also,
includes warning alerts for load balancers with only
one member.
=> Include alerts for critical lbs

bindata/network/kuryr/alert-rules.yaml
Sometimes, we could experience issues regarding unrecoverable state for
either Neutron ports and/or Octavia load balancers being stuck forever.
Currently there is nothing we could do from Kuryr-Kubernetes side except
alerting.
=> Add alerts for issues with load balancers/ports.

README.md, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Since OVS is run on host, OVS logs are collected from systemd journal. Default value for ovs syslog level is err, set it to info to collect info level logs with must-gather.
How to test:
Run `ovs-appctl vlog/list` on a node, assure syslog level is set to requested level.
Run must-gather, check `host_service_logs/<node_name>/ovs-vswitchs_service.log` file. Previously it only contained ERR messages like this:
> Jun 28 07:35:19.248737 ci-ln-hxbr65t-f76d1-zw5kl-master-0 ovs-vswitchd[1234]: ovs|00040|stream_ssl|ERR|SSL_use_PrivateKey_file: error:20074002:BIO routines:file_ctrl:system lib
Jun 28 07:35:19.248780 ci-ln-hxbr65t-f76d1-zw5kl-master-0 ovs-vswitchd[1234]: ovs|00041|stream_ssl|ERR|failed to load client certificates from /ovn-ca/ca-bundle.crt: error:140AD002:SSL …
=> Bug 1970129: Add env variable OVS_SYS_LOG_LEVEL for ovn nodes to setup ovs syslog level

bindata/network/ovn-kubernetes/004-config.yaml, bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
OVN-Kubernetes cannot support having egress IP and `--disable-snat-multiple-gws` (used for ICNI traffic) defined at the same time. The reason is how both features SNAT on the GW router. Egress IP SNATs to the egress IP, whereas with `--disable-snat-multiple-gws` we will force all pod IPs to SNAT individually to the node IP. Having both configured at the same time will scramble the egress IP configuration. Many OCP customers want the egress IP feature, one OCP customer wants the ICNI feature...hence, have that one customer use a dedicated field in the config map they are already using, to specify this.
/assign @trozet
=> Make egress IP and ICNI mutually exclusive when bootstrapping OVN-kube

bindata/network/ovn-kubernetes/ovnkube-node.yaml
If br-ex1 is available on the host, it means that the user wants to use
it as the ovs bridge for external gateway traffic, so we set the related
parameter in ovnkube-node
=> OVNKube: check if br-ex1 is available and pass it as a parameter

pkg/controller/proxyconfig/controller.go
Without the PR:
```
RJPkcV9aF5Oc08hytpBfeU/H8v+e2DQK258=
-----END CERTIFICATE-----# Red Hat IT Root CA
-----BEGIN CERTIFICATE-----
```
With the PR:
```
RJPkcV9aF5Oc08hytpBfeU/H8v+e2DQK258=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
```
=> Bug 1961811: Add a newline between user CAs and system CAs

bindata/network/ovn-kubernetes/pre-puller.yaml, pkg/bootstrap/types.go, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go, pkg/util/k8s/unstructured.go
According to https://bugzilla.redhat.com/show_bug.cgi?id=1943334#c0 it takes roughly a minute during upgrades for old pods to get killed and new pods to get created.
It is predicted that a major chunk of this time is spent in pulling the new image into the node. (@squeed : do we have data to back up this claim that I can point to?)
This PR adds a new prepuller daemonset that is basically a no-op which simply assists in pulling the new image onto the nodes before the new pods get created so that it cuts down on the downtime.
Idea, Co-Authored By: https://github.com/squeed/openshift-cluster-network-operator/commit/42c0d1db5576a2e4e6b16b115e657477dbc33073
=> Bug 1970985: SDN-1955: Add pre-puller ds to reduce upgrade downtime

README.md, bindata/network/ovn-kubernetes/ovnkube-node.yaml
Move setting ovs log level to machine-config-operator because:
- it should be set in the same place where ovs start to capture all the logs between ovs startup and CNO startup
- we don't need to reset this log level, therefore no need for ConfigMap variable
- log level settings should be alive after service restart, cluster upgrades
New PR for the same feature: https://github.com/openshift/machine-config-operator/pull/2690
=> Revert: Add env variable OVS_SYS_LOG_LEVEL for ovn nodes to setup ovs syslog level

bindata/network/ovn-kubernetes/004-config.yaml, pkg/network/ovn_kubernetes_test.go
By default the lflow cache is unlimited, but at scale this
makes ovn-controller consume large amounts of RSS and cause OOM
situations. Limit the cache size to prevent unbounded memory
usage while still providing enough for most setups.
The lflow cache is a tradeoff between CPU and memory, but we'd
rather use a bit more CPU than OOM a box.
Pick a 1GB limit based on data gathered from various scale runs,
which seems to be the upper-limit (for now) for 120-node
density runs.
@trozet @jcaamano
=> Bug 1961757: ovnkube: set ovn-controller lflow cache limit to 1GB

bindata/network/ovn-kubernetes/ovnkube-master.yaml, manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml, manifests/0000_70_cluster-network-operator_03_deployment.yaml, pkg/network/ovn_kubernetes.go
@numansiddique  @trozet : Please take a look and advice what the 'default' values should be.
It is possible we may want them to be '0' ?!?
=> Bug 1985033: Make inactivity_probe configurable

bindata/network/ovn-kubernetes/004-config.yaml, pkg/network/ovn_kubernetes.go, pkg/network/ovn_kubernetes_test.go
Currently ovnkube-master leader election has the following timers [(ovn-org/ovn-kubernetes config.go)](https://github.com/ovn-org/ovn-kubernetes/blob/f5ddbe324fc561c58629db649524cd4b44075255/go-controller/pkg/config/config.go#L119-L123):
* lease duration: 60 seconds
* renew deadline: 30 seconds
* retry period: 20 seconds
This causes it to go through leader election and restart during an kube-apiserver rollout in a SNO (as this currently takes longer than 60 seconds).
This PR increases the ovnkube-master leader election timers for SNO clusters to its [recommended](https://github.com/openshift/enhancements/pull/832/files#diff-2e28754e69aa417e5b6d89e99e42f05bfb6330800fa823753383db1d170fbc2fR183) values to handle a apiserver disruption:
* lease duration: 137 seconds
* renew deadline: 107 …
=> Bug 1981055: ovnkube-master handle 60 seconds downtime of API server gracefully in SNO

pkg/network/openshift_sdn.go, pkg/network/openshift_sdn_test.go
https://github.com/openshift/sdn/pull/296 added support for `EndpointSliceProxying` to openshift-sdn, so we no longer have to forcibly disable it.
Then once we rebase sdn to kube 1.22 we can use the endpoint termination stuff
/cc @abhat @Miciah
=> Bug 1989122: let openshift-sdn use EndpointSliceProxying

bindata/network/ovn-kubernetes/ovnkube-master.yaml
Adding template OVN_DB_PROBE_INITIAL_DELAY parameter, which will set to 0 when there is only one master node.
=> Bug 1984049: Slow OVN Recovery on SNO

bindata/network/openshift-sdn/sdn.yaml
Change iptables chain names to not conflict with existing workaround(s)
(cherry picked from commit 32d72e5794ecd5e5f742c8708a2e4a6c183b0e4b)
=> Bug 1988425: Change to use mountPath: /host

bindata/network/multus/002-rbac.yaml, pkg/network/multus_test.go, pkg/network/network_metrics_test.go
Newer feature in Whereabouts uses leases for coordination of leaders as to not cause a race condition in ip allocations.
=> Bug 1989734: Whereabouts should have RBAC for leases

bindata/network/kuryr/alert-rules.yaml, bindata/network/openshift-sdn/alert-rules.yaml, bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml, bindata/network/ovn-kubernetes/alert-rules.yaml
This PR switches to the OpenShift comply annotations for PrometheusRules:
The guidelines can be found at https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#documentation-required
**How to validate:**
* start a cluster with this patch
* check the prometheus rules (e.g. for openshift-sdn): `k -n openshift-sdn get prometheusrules -o yaml`. e.g.:
```
$ k -n openshift-sdn get prometheusrules -o yaml
apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
annotations:
networkoperator.openshift.io/ignore-errors: ""
creationTimestamp: "2021-08-12T09:05:57Z"
generation: 1
labels:
prometheus: k8s
role: alert-rules
name: networking-rules
namespace: openshift-sdn
ownerReferences:
- apiVersion: …
```
=> Bug 1992507: Use prometheus rule annotations comply with the OpenShift alerting guidelines

bindata/kube-proxy/001-rbac.yaml, bindata/network-diagnostics/001-rbac.yaml, bindata/network/multus/002-rbac.yaml, bindata/network/openshift-sdn/002-rbac.yaml, bindata/network/openshift-sdn/003-rbac-controller.yaml, bindata/network/ovn-kubernetes/002-rbac.yaml, bindata/network/ovn-kubernetes/003-rbac-controller.yaml
Events are slowly being moved from `core/v1` to `events.k8s.io/v1`, so update everything to be able to use both namespaces for now.
Also, while we're here, drop the rules for the old `extensions/v1beta1` NetworkPolicy API.
/hold
need to test manually as the bug is not currently caught by CI
=> Bug 1991551: allow sdn (and others) to use new events.k8s.io API

bindata/network/ovn-kubernetes/ovnkube-master.yaml, bindata/network/ovn-kubernetes/ovnkube-node.yaml
When upgrading from 4.5 to 4.6 the more recent openssl defaults to
stricter security requirements and rejects the use of 1024 bit dh params
when ovn-controller 4.6 tries to connect to sbdb 4.5, blocking the
upgrade.
This patch softens the security requirement back to allow 1024 bit dh
params.
Note that this should not affect once the upgrade is completed and these
connections are among 4.6 components with a recent openssl version on
both sides as this will cause to negotiate a cipher that does not use
fixed dh params.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1973770
=> Bug 1973770: Reduce SSL sec level for ovsdb connections 
